### ISSUE TITLE
Play controls not visible with Breeze Dark theme

### ISSUE THREAD

**Issue by sureloc** [owncloud/music#1011]
As the title says, all play controls aren't visible when using the Breeze Dark theme. The only thing showing is the play/pause button and volume control

![Screenshot 2022-09-17 151604](https://user-images.githubusercontent.com/69294325/190856326-1079fd8a-47eb-45b9-9dd8-4b356c943dbd.jpg)

**Comment by paulijar** [comment]
This issue has been already fixed and the fix will be included in the next release. The issue has been originally discussed on the PR https://github.com/owncloud/music/pull/1002 although the proper fix was different from the one proposed by that PR.

**Comment by JoshuaPettus** [comment]
So you know the breeze theme author usually handles these incompatibilities.  He already pushed an update.  I just hope you two arn't treading on each other's toes here

https://github.com/mwalbeck/nextcloud-breeze-dark/pull/316

**Comment by paulijar** [comment]
@JoshuaPettus I believe that the changes made to the Music app are not in conflict with those made on the Breeze theme, although those changes will become unnecessary and redundant with the Music app update. The changes made on the Music app should make the life a bit easier for any other Nextcloud 3rd party theme, too.

**Comment by paulijar** [comment]
The fix for this has now been released in Music v1.7.0.
