### ISSUE TITLE
Add support for Cyrillic / Alphabet in app / Albums / Songs - Add search song / artist

### ISSUE THREAD

**Issue by webagroprom** [owncloud/music#1018]
1. It is necessary to add the cleric alphabet so that you can find the artist by alphabet
2. You need to add a search by artist and music tracks

![1665682382371](https://user-images.githubusercontent.com/30408997/195666714-7561b1f8-a6e6-41b3-abb1-9ed70239eea4.jpg)

**Comment by paulijar** [comment]
For the searching, just click the search icon in the upper right corner of the screen or press ctrl+f; you can filter the contents of any of the views of the Music app using any combination of the artist/album/track information visible in the view in question.
![image](https://user-images.githubusercontent.com/8565946/195703395-34986813-329a-4d6d-bc32-50648e7336c2.png)

For the alphabet navigation, yes, this is a known shortcoming of the current system that it only has the Latin alphabet. Similar problem is present for users having predominantly Greece or Arabic or Hebrew songs, just to name a few. And actually, this has been requested nearly a decade ago in https://github.com/owncloud/music/issues/108. One option could be to add some user setting to select the set of alphabet shown on the alphabet navigation bar. But that would still be sub-optimal if the user happens to have both songs written in Cyrillic alphabet and songs written in Latin alphabet. Probably a perfect solution does not exist.

**Comment by webagroprom** [comment]
> For the searching, just click the search icon in the upper right corner of the screen or press ctrl+f; you can filter the contents of any of the views of the Music app using any combination of the artist/album/track information visible in the view in question. ![image](https://user-images.githubusercontent.com/8565946/195703395-34986813-329a-4d6d-bc32-50648e7336c2.png)
> 
> For the alphabet navigation, yes, this is a known shortcoming of the current system that it only has the Latin alphabet. Similar problem is present for users having predominantly Greece or Arabic or Hebrew songs, just to name a few. And actually, this has been requested nearly a decade ago in #108. One option could be to add some user setting to select the set of alphabet shown on the alphabet navigation bar. But that would still be sub-optimal if the user happens to have both songs written in Cyrillic alphabet and songs written in Latin alphabet. Probably a perfect solution does not exist.


**Thanks for the hint about the search.**

1. It would be convenient if there was a separate search in the application only for music, artist, album and not a global search.

2. It would be nice if there was an opportunity to select languages ​​for navigating music / artists (2-3 options to choose from)

**Comment by paulijar** [comment]
> It would be convenient if there was a separate search in the application only for music, artist, album and not a global search.

Well, it basically is a separate search for the app, it just uses the same input field as the global search.

**Comment by webagroprom** [comment]
> > It would be convenient if there was a separate search in the application only for music, artist, album and not a global search.
> 
> Well, it basically is a separate search for the app, it just uses the same input field as the global search.

This is global search in app music 

![1666116672054](https://user-images.githubusercontent.com/30408997/196510955-bae69279-be28-4099-893a-7b2738205b28.jpg)

It would be nice if the Search was separate only for the application.

Is it planned to add the function of selecting an additional language for navigation through the music collection or is it not worth waiting for?

**Comment by paulijar** [comment]
> This is global search in app music

That's right. And on the left (no pun intended), you can see your local search results.
![image](https://user-images.githubusercontent.com/8565946/196605535-36c4b4e7-fecc-4c7a-84c7-162f54508b07.png)

> Is it planned to add the function of selecting an additional language for navigation through the music collection or is it not worth waiting for?

Maybe one day but not in the immediate future. There are many nice features requested, and if I had infinite amount of time, I would implement them all. But in the real life, I'm able to pick only a small fraction of all the requests. This multi-script support for the alphabet navigation would probably require more effort than you would expect although not an insane amount. But if anyone is willing to contribute a pull request implementing this, I'm ready to consider merging it.

**Comment by paulijar** [comment]
For the record, the implementation of the application-local search functionality was changed in Music v1.10.0 so that it nowadays works with its own dedicated input on the navigation pane. This was made because of design changes in the global search input by Nextcloud.

As the second part of this issue is a duplicate to the older issue https://github.com/owncloud/music/issues/108, I'm now closing this one.
