### ISSUE TITLE
Changes needed due to Nextcloud 25 design changes

### ISSUE THREAD

**Issue by PVince81** [owncloud/music#1019]
There were some changes in the scroll container and many apps needed adjustments.
Currently with Nextcloud 25.0.0 RC5 only the left sidebar panel is visible.
See https://github.com/nextcloud/server/issues/32060 for details.

**Comment by paulijar** [comment]
Yep, noted, but thanks for the link. This is basically duplicate to https://github.com/owncloud/music/issues/1017.

**Comment by paulijar** [comment]
Closing as duplicate. Also, the required changes have now been implemented, so this will be fine in the forthcoming 1.7.0 release.
