### ISSUE TITLE
Controls are not visible on Nextcloud 25.x shared public folder

### ISSUE THREAD

**Issue by moonman** [owncloud/music#1028]
![image](https://user-images.githubusercontent.com/674485/202646371-3e5c1990-bf5a-4b9b-b0ad-4f281368ecd3.png)

**Comment by paulijar** [comment]
Thanks for the report. I can confirm that there is a problem although it doesn't look quite the same on my system. First of all, the generic Nextcloud advertisement pane in the bottom seems to be on top of the Music controls, hiding them totally:
![image](https://user-images.githubusercontent.com/8565946/202716427-d38d1328-de02-4a87-afc0-71798ef63471.png)

If I modify the style sheet to hide this Nextcloud banner, then the Music controls pane appears but it's not correctly adjusted to the dark theme. Furthermore, the bottom left corner of the pane is not properly rounded.
![image](https://user-images.githubusercontent.com/8565946/202716283-585ae587-fdbe-4336-b10d-b8e9c8b49319.png)

**Comment by moonman** [comment]
Thank you for looking into this so quickly. It is possible that because I have an empty string under "Name", "Slogan" etc. under "Theming" in the settings that the footer is completely empty on mine.

**Comment by paulijar** [comment]
> It is possible that because I have an empty string under "Name", "Slogan" etc. under "Theming" in the settings that the footer is completely empty on mine.

Okay, that explains it then.

**Comment by moonman** [comment]
I build the plugin from git and can confirm that music controls now show up. The buttons are still too dark to see with the dark theme (different from when a user actually logs in - which works just fine with grey buttons), but at least music can now be controlled. I'm closing this. Thanks again.

**Comment by paulijar** [comment]
Yeah, I'm in the process of refactoring the dark theme handling bit-by-bit. In the end of this, I believe I can make it work correctly also in the public share page on NC25.

**Comment by paulijar** [comment]
Music v1.8.0 is now out, fixing both the controls visibility issue and the dark theme handling on public shares.
