### ISSUE TITLE
Album View not orgainized in several columns

### ISSUE THREAD

**Issue by Stonerocker** [owncloud/music#1029]
When I click on Album view my albums of a specific artist are not organized in several columns. 

![Screenshot_20221123_204747](https://user-images.githubusercontent.com/17471557/203634878-41285811-db75-42ad-83c6-861f5adfbdd4.png)

However, choosing the option "Normal Layout" within Album view the layout changes adequately filling free space of the frame with more columns. 

![Screenshot_20221123_204705](https://user-images.githubusercontent.com/17471557/203634924-417e7774-77d6-4189-93aa-f49f95264d43.png)

This can be reverted again by changing to another view and back to album view.

(Musik v1.7.0 on Nextcloud 25.0.1)

**Comment by paulijar** [comment]
Thanks for the report. Which browser are you using? It might be that your browser doesn't trigger all the same resize events as those which I have tested. It also seems to me that the alphabet navigation on the right is placed slightly too far right on your screenshots, not leaving the proper space for the scroll bar. This might be another symptom of the same underlying issue.

If you resize the browser window, does the UI reflect correctly the new size? Does this update the layout between 1-column and multi-column modes when the window size become narrow or wide enough?

**Comment by Stonerocker** [comment]
My browser is a Mozilla Firefox for Ubuntu 107.0 (64-bit)
You are right! A resize of the Window also triggers the change to multi-column mode.

**Comment by paulijar** [comment]
Okay, I'm using the same Firefox version but on Windows. Are you able to test this on your cloud using any other browser?

**Comment by Stonerocker** [comment]
For me too, Firefox on Windows 107.0 (64-bit) and Microsoft Edge 107.0. 1518.56 (64-bit) show multi-columns and adapt on resize. 
Seems Firefox on Linux really behaves differently here.

**Comment by paulijar** [comment]
Okay, good to know. At some point, I'll try to find some time to install Linux on VirtualBox as it's pretty difficult to try to fix this without being able to reproduce the issue.

**Comment by Stonerocker** [comment]
Sure. Thank you for looking into this so quickly!

**Comment by paulijar** [comment]
This is now fixed in Music v1.8.0.
