### ISSUE TITLE
Is lossless support present for Subsonic API?

### ISSUE THREAD

**Issue by proninyaroslav** [owncloud/music#1031]
I have a collection of FLAC files on my Nextcloud server. And for Android streaming, I use Ultrasonic with Subsonic API and Clementine for PC. Is any lossy compression used for Subsonic API, or is streaming lossless if FLAC/ALAC is played?

**Comment by paulijar** [comment]
The Music app doesn't support any kind of transcoding although it has been requested ages ago (https://github.com/owncloud/music/issues/428). This means that any music file is streamed just like it is found from the disk. It's then up to the Subsonic client used if it supports playing FLAC and or ALAC files.

**Comment by proninyaroslav** [comment]
Thank you
