### ISSUE TITLE
Add Subtracks to list of known working Subsonic clients

### ISSUE THREAD

**Issue by tliebig** [owncloud/music#1032]
Hi Pauli,

I've just added my nextcloud Server via the Subsonic URL to https://play.google.com/store/apps/details?id=com.subtracks and it works perfectly (had to enable the 'force clear text password option though).

There's other users in Austin GitHub Project talking about Nextcloud as well, so I consider it safe to add it to the verified clients.

Thanks alot for taking the time and developing the app & server. Muuuuuch appreciated 🙏👍❤️

Yours,
Torsten.

**Comment by paulijar** [comment]
Thanks for the info, I'm always interested to hear about new Subsonic or Ampache clients; especially ones which are still maintained. I now tested Subtracks and added it to https://github.com/owncloud/music/wiki/Subsonic. I added there also SonicLair and sonixd.

**Comment by Christopher-Hayes** [comment]
@paulijar Subtracks works great with Music, super clean app. Might want to add a wiki note that "Force plaintext password" needs to be checked for Subtracks to work.

**Comment by paulijar** [comment]
@Christopher-Hayes Yeah, I was a bit lazy when adding Subtracks to wiki, but now I added also the note about "Force plaintext password".

**Comment by Christopher-Hayes** [comment]
@paulijar thanks!
