### ISSUE TITLE
Unusable in mobile view on NC 25.0.2

### ISSUE THREAD

**Issue by StreetyYEET** [owncloud/music#1036]
On Nextcloud 25.0.2 the music plugin is unusable in mobile view: 
![EF974099-F1C7-4114-9052-CA123270B004](https://user-images.githubusercontent.com/44947977/209439433-e5fb17b6-2601-4d90-849e-dbd653f560d9.jpeg)

**Comment by paulijar** [comment]
Thanks for the report. I can't see such problem on NC 25.0.1 so apparently something has changed in the 25.0.2 patch. It's kind of frustrating when the cloud behavior changes between the patch releases.

**Comment by strokeMD** [comment]
I can confirm this started after 25.0.2. Chrome, Safari, and Brave all rendered incorrectly as shown by OP

**Comment by paulijar** [comment]
This is now fixed in Music v1.8.0.
