### ISSUE TITLE
Neither Podcast nor Internet Radio work

### ISSUE THREAD

**Issue by dln949** [owncloud/music#1037]
Nextcloud 25, Music 1.7.0, Ultrasonic 4.2.0 on Android 13.  

Within Nextcloud, Music works great:  I can access all my music, I can obtain and listen to podcasts, I have set up internet radio stations and I can listen to them.  Within Nextcloud.  

I successfully linked the Music app in my Nextcloud server to my android phone using the Ultrasonic app.  I got the URL and username and the generated password from the Music app, and as a result on my android device using Ultrasonic I can listen to my music collection from Nextcloud.  However....  

I am unable to access my Nextcloud  podcasts and the internet radio stations from within Ultrasonic on my android device.  For podcats all I get is the word "null".  And I can't even figure out how to attempt to listen to the internet radio stations.  (Maybe Ultrasonic is the wrong app for podcasts and radio stations?????)  

I don't know if something is wrong, or if I'm doing things incorrectly.  

I did see what is shown in the attached screenshot, but I didn't understand any of it, didn't even know if those are things I need to do.  But seeing that makes me think there's a "secret handshake" set of steps that are assumed I would know to do but sadly in fact I don't know about or understand.  

![Screenshot from 2022-12-25 22-24-53](https://user-images.githubusercontent.com/8601150/209603086-d6881352-bce8-4c61-8a79-2cf6d56fd914.png)

**Comment by paulijar** [comment]
Hello. None of those Admin settings have any effect on how the radio and podcast features work on the Subsonic API so you don't have to worry about them here.

It seems to me that Ultrasonic has no view for the radio stations so probably it doesn't support this feature. And for the podcast channels, it shows the title of the channel as "null" for each channel. If you click that null, then you would probably see the episodes of that channel. The same thing happens with the official Subsonic demo server (demo.subsonic.org, user: guest, password: guest), so this seems to be a bug in the Ultrasonic client.

Both internet radio and podcasts should work fine on the DSub client.

**Comment by dln949** [comment]
Thanks paulijar.  You were right about tapping on the word "null", it shows the podcast episodes.  

I would very much like to try out Dsub.  However, using the _exact same URL and login credentials___ on Dsub that I successfully use for Ultrasonic, Dsub always reports that my "resource cannot be found".  :(

**Comment by paulijar** [comment]
On DSub, did you disable "Authorization Basic headers" in the server settings? The connection to Nextcloud doesn't work if you leave it enabled.

**Comment by dln949** [comment]
Ha!  That fixed it, thanks.  

Well, one more Dsub question, just in case you know an easy answer:  When I tap on "Stream Video" for a video or movie, nothing happens.  And, when I tap on "Play Video", it says I first have to download the video, but there is no option that I see to download it.

**Comment by paulijar** [comment]
Well, the ownCloud/Nextcloud Music app doesn't support videos at all, at least for now. On the Subsonic demo server, I can see there is a single video available but it cannot be played or streamed on DSub. I assume that the video is in such a format that DSub doesn't support it but I don't know any details.

**Comment by paulijar** [comment]
Closing as out-of-scope of the Music app.
