### ISSUE TITLE
[Feature Request] + and - Buttons for easier Volume

### ISSUE THREAD

**Issue by DarkSide1305** [owncloud/music#1039]
With the Setup I currently have I have the Player at roughly 3-4% Volume (Nextcloud is really loud compared to YouTube etc.), so usually when I want to make it a bit louder and I try to make it slightly louder, it goes too loud or too quiet. Using Up + Down Arrow works for 1% changes, but that only works if you clicked the volume slider ALREADY and already changed the volume, so 2 buttons for simple +-1% volume would be appreciated for much easier volume control

**Comment by paulijar** [comment]
Hello. The keypad + and - keys should already work for this since Music v1.7.0.

**Comment by paulijar** [comment]
I just released Music v1.8.1 and included there also this requested feature: The numpad `+` and `-` keys adjust the volume by only +-1% while the ALT key is held down. Symmetrically to this, the seeking with arrow keys now seeks only +-1 s at a time while ALT held down.
