### ISSUE TITLE
Tracks with non-English characters rejected when importing playlists

### ISSUE THREAD

**Issue by Valoiro** [owncloud/music#1047]
From a desktop web browser create a new playlist then "Import from file" - all tracks with non-English characters are rejected -
e.g. Blue Öyster Cult - (Don't Fear) The Reaper.mp3, Urban släke - Så jävla svensk.mp3

**Comment by paulijar** [comment]
If your playlist file has the extension .m3u, then it's assumed to be encoded as Latin-1, unless another encoding is given in the tags of the file. If the extension is .m3u8, then the encoding is assumed to be utf-8 by default. Most likely you now have utf-8 within .m3u file without defining the encoding and that combination doesn't work.

**Comment by Valoiro** [comment]
Might it not be better to assume UTF-8, even if it is an .m3u file?
Or is it something that's controlled by (for instance) a library?
Very useful app, by the way!
------- Original Message -------

**Comment by paulijar** [comment]
This interpretation is in our own hands.

As I have understood it, the .m3u format originally used the Latin-1 encoding. Later, the .m3u8 format was introduced to be its UTF-8 equivalent. But as years go by, it's probably becoming more and more common to use UTF-8 also in .m3u files. As there's no actual standard available, there's strictly speaking no right or wrong way to do this. 

So yes, it might make sense to interpret the file as UTF-8 if it seems to be valid UTF-8, regardless of the file extension. As you may know, all valid UTF-8 can be interpreted as some valid characters in Latin-1 but all valid Latin-1 cannot be interpreted as valid UTF-8. But still, this logic would be only heuristic: there are cases where the same stream of bytes is both valid Latin-1 and valid UTF-8 but the interpretation is different.

**Comment by numerfolt** [comment]
> Might it not be better to assume UTF-8, even if it is an .m3u file?

A fix was already added but to manually fix this for one playlist, one can:

1. Add the line `#EXTENC: UTF-8` between the first line (saying #EXTM3U) and the first entry of the playlist.
2. Or rename the file from .m3u to .m3u8

And I agree, this app is great!

**Comment by Valoiro** [comment]
👍

-------- Original Message --------

**Comment by paulijar** [comment]
Also .m3u files are now assumed to be in UTF-8 by default in the newly released Music v1.8.4.
