### ISSUE TITLE
Playlist sort not respecting ignored artist prefixes

### ISSUE THREAD

**Issue by Valoiro** [owncloud/music#1048]
Playlist... Sort... by artist does not apply the rule set in Settings... Articles to ignore on artist names.
e.g. "The Ark" appear amongst the artists beginning with T, not with A.

**Comment by paulijar** [comment]
Good point, ignoring the articles also here would make sense.

**Comment by paulijar** [comment]
This improvement has now been released in Music v1.8.2.

**Comment by Valoiro** [comment]
Excellent!

-------- Original Message --------
