### ISSUE TITLE
how to install on docker for windows?

### ISSUE THREAD

**Issue by IveMalfunctioned** [owncloud/music#1049]

**Comment by paulijar** [comment]
I have no experience on docker but if anyone has done this, then feel free to comment. Or if you @IveMalfunctioned figure it out on your own, then please share your experiences. Or if you run into some more specific problem while trying to do that, then I might be able to help just based on the general knowledge about the app (or not).

**Comment by IveMalfunctioned** [comment]
I just installed it through the store.
