### ISSUE TITLE
The player above PDF viewer #Enchacement

### ISSUE THREAD

**Issue by 4volodin** [owncloud/music#1057]
Hello
I think it will be very useful to have the player above the PDF viewer.
You can press play/pause an audiobook at the moment while reading the same text pdf book
Could you make the player above PDF viewer? 
Thanks

**Comment by paulijar** [comment]
Actually, on ownCloud (tested v10.11), the music player bar in Files gets drawn on top of the pdf viewer. But on Nextcloud, the pdf viewer is implemented differently and this does not happen. I don't see any easy way to make this happen on NC, either.

To me, also the use case sounds like very unordinary: how often one wants to simultaneously read and listen to a book? Is that maybe to learn a foreign language or what's the point?

Note also, that if you have the media control keys on your keyboard, then you can use those to control the playback even when the music player UI is not on the top. And if you don't have the keys, then there are software alternatives like https://github.com/evilpro/Taskplay or the media control popup on Chrome: https://user-images.githubusercontent.com/16665512/96973502-4373e800-1518-11eb-9f99-9446d3dbf19a.jpg

**Comment by 4volodin** [comment]
Yes, you are right. It's useful for learning foreign languages.
There is the same functionality in [Oxford Books](https://www.oxfordlearnersbookshelf.com)

**Comment by paulijar** [comment]
I don't think it's feasible to try to draw the Music UI on top of the PDF viewer on Nextcloud, given that the PDF viewer has been specifically designed to be drawn on top of all other UI components. But if the feature https://github.com/owncloud/music/issues/932 gets ever implemented, then it would serve also this use case.
