### ISSUE TITLE
Automated music organizing?

### ISSUE THREAD

**Issue by IngwiePhoenix** [owncloud/music#1063]
Hello!

This is a relatively quick question - and since I didn't see a Discussions tab, I decided to just put it here. Sorry if I missed the supposed way to do that :)

I attempted to use Beet a while ago but it broke on numerous occasions and I have been trying to find another tool to automate my music organizing needs. Sadly, Picard does not seem to have a CLI to do so.

Whilst the README didn't specify and thus I assume this feature is not implemented, I still would like to know if this app actually has the capabilities of organizing my music - or, if you are aware of one that does.

My entire main storage is accessible via NFS and mounted as root on my user account via external storage - so, perfectly accessible.

Device's a FriendlyElec NanoPi R6s (arm64 8 cores at about 2.8GHz).

Thank you in advance and sorry again if I misplaced this question.

Kind regards,
Ingwie

**Comment by paulijar** [comment]
Hi. Organizing the collections (e.g. modifying metadata tags and/or altering the directory structures, renaming files) is outside of the scope of this app. I have used [Mp3Tag](https://www.mp3tag.de/en/index.html) for all such needs for years. But that's not an answer for you if you need something running on NanoPi and need to control it via a CLI.

**Comment by IngwiePhoenix** [comment]
Ahh, gotcha. Thank you for the pointer though! :)
