### ISSUE TITLE
ArgumentCountError: Too few arguments to function OCA\Music\BackgroundJob\PodcastUpdateCheck

### ISSUE THREAD

**Issue by SockenSalat** [owncloud/music#1064]
OwnCloud-Version: 10.11.0.6
Music-Version: 1.8.3

After update to latest version cron spams me with the following failure:

```
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Music\BackgroundJob\PodcastUpdateCheck::run(), 0 passed in {omitted}/lib/private/BackgroundJob/Legacy/RegularJob.php on line 31 and exactly 1 expected in {omitted}/apps/music/lib/BackgroundJob/PodcastUpdateCheck.php:28
Stack trace:
#0 {omitted}/lib/private/BackgroundJob/Legacy/RegularJob.php(31): OCA\Music\BackgroundJob\PodcastUpdateCheck::run()
#1 {omitted}/lib/private/BackgroundJob/Job.php(81): OC\BackgroundJob\Legacy\RegularJob->run()
#2 {omitted}/core/Command/System/Cron.php(127): OC\BackgroundJob\Job->execute()
#3 {omitted}/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\System\Cron->execute()
#4 {omitted}/lib/composer/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#5 {omitted}/lib/composer/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#6 {omitted}/lib/composer/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#7 {omitted}/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#8 {omitted}/console.php(116): OC\Console\Application->run()
#9 {omitted}/occ(11): require_once('/var/www/vhosts...')
#10 {main}
```

Since no user has any Podcast subscribed I'd guess this is a bug :thinking:

**Comment by paulijar** [comment]
The v1.8.3 updates the background jobs away from the legacy API to a more modern alternative. Because of this, the migration steps during the app installation of the new version are supposed to unregister the old background jobs and then register the new ones. But I guess that in your case, these steps have not been run as intended.

You could verify this by running the `occ` command `background:queue:status` which lists all the registered background jobs. If you do that, then please post the result here and I can check if it is as I suspect.

Next, you should be able to fix the situation by running these `occ` commands:
`maintenance:mode --on`
`maintenance:repair`
`maintenance:mode --off`.
This will rerun the migration steps of all intalled apps.

**Comment by SockenSalat** [comment]
@paulijar 

Look's like you where guessing right: 

![grafik](https://user-images.githubusercontent.com/50449195/234784428-f40181b5-5ce9-471f-a9c9-e1e2c870b8da.png)

After executing the _workaround_ the two jobs have an entry in the `Reserved At` Column, what ever that means :thinking: 

As result I do not receive any error messages from the cron run anymore :+1: Thnx a lot!

**Comment by paulijar** [comment]
Okay, great. Another interesting thing about that list of background jobs would have been if these two jobs were available before you ran `maintenance:report`:
```
| 22     | OCA\Music\BackgroundJob\Cleanup                    |               | 2023-04-23T18:58:05+00:00 | 2023-04-23T18:58:05+00:00 | N/A         | 0                      |
| 23     | OCA\Music\BackgroundJob\PodcastUpdateCheck         |               | 2023-04-23T18:58:16+00:00 | 2023-04-23T18:58:16+00:00 | N/A         | 1                      |
```
Most likely they were not which would indicate that the migration steps had not run at all while you updated the Music app. But if they were and simultaneously there were *also* the legacy jobs, then that would tell us that somehow the migration ran only partially. But that would be highly unexpected.

Btw, did you update the Music app using the ownCloud Apps Management on the admin settings UI or via some other method?

**Comment by SockenSalat** [comment]
@paulijar they where after I ran your workaround with your App deactivated. After I repeated the step with activated App they where gone.

And yes, I updated the App using the UI.
