### ISSUE TITLE
Playing individual files

### ISSUE THREAD

**Issue by johnwry** [owncloud/music#1065]
Hello, 
Is there a way to play individual files within a page. I am using the PICO CMS and would like to include the files there....thanks!

**Comment by paulijar** [comment]
I have no knowledge of any kind about PICO CMS. This sounds more like a question for [Pico CMS for Nextcloud](https://github.com/nextcloud/cms_pico.).

**Comment by paulijar** [comment]
As far as I understood, this request is out of the scope of the Music app. Hence, closing.
