### ISSUE TITLE
no sync on nextcloud 26 anymore

### ISSUE THREAD

**Issue by LooOOooM** [owncloud/music#1069]
Hello,
I just upgraded my nextcloud to 26. Since than I cannot snyc any more  my Garmin 6X Pro solar ending always in a ERROR 500

`65.0.95.201 - - [01/Jun/2023:13:24:45 +0200] "GET /apps/music/subsonic/rest/getPlaylist?v=1.10.2&c=SubMusic-v0.2.9-tyndareos&p=qv3xxrngn3ct&f=json&u=has%40nxus.eu&id=4 HTTP/1.1" 200 611 "-" "Garmin fenix 6X Pro Solar/25.10"
65.0.95.201 - - [01/Jun/2023:13:24:46 +0200] "GET /apps/music/subsonic/rest/getPlaylist?v=1.10.2&c=SubMusic-v0.2.9-tyndareos&p=qv3xxrngn3ct&f=json&u=has%40nxus.eu&id=5 HTTP/1.1" 200 1056 "-" "Garmin fenix 6X Pro Solar/25.10"
65.0.95.201 - - [01/Jun/2023:13:24:46 +0200] "GET /apps/music/subsonic/rest/getPlaylist?v=1.10.2&c=SubMusic-v0.2.9-tyndareos&p=qv3xxrngn3ct&f=json&u=has%40nxus.eu&id=5 HTTP/1.1" 200 1056 "-" "Garmin fenix 6X Pro Solar/25.10"
65.0.95.201 - - [01/Jun/2023:13:24:46 +0200] "GET /apps/music/subsonic/rest/getPlaylist?v=1.10.2&c=SubMusic-v0.2.9-tyndareos&p=qv3xxrngn3ct&f=json&u=has%40nxus.eu&id=6 HTTP/1.1" 500 3561 "-" "Garmin fenix 6X Pro Solar/25.10"
`

can anybody help me? with that?

**Comment by LooOOooM** [comment]
Thx for you quick answer and the hint about the api key. I already changed with my logs the relevant stuff. The message you see are from the file :
/var/log/nginx/nextcloud.access

No errors within nextcloud.log.
I meanwhile reset some thing regarding my music:

  992  sudo -u nginx php occ music:cleanup
  993  sudo -u nginx php occ music:podcast-reset
  994  sudo -u nginx php occ music:podcast-reset --all
  995  sudo -u nginx php occ music:reset-cache
  996  sudo -u nginx php occ music:reset-database
  997  sudo -u nginx php occ music:reset-cache --all
  998  sudo -u nginx php occ music:reset-database --all
  999  sudo -u nginx php occ music:scan
 1000  sudo -u nginx php occ music:scan --all


Since that I dont have any more any errors - So this issue is closed

within

**Comment by paulijar** [comment]
It's somewhat surprising if there was nothing in nextcloud.log; usually there's always some kind of error shown if the HTTP response code is 500. What we can tell from the log shown in the OP, is that the problem happened when reading the playlist with ID=6. Playlists with IDs 4 and 5 were read successfully before it. When you ran `music:reset-database --all`, you removed also all the playlists. Hence, the sync obviously cannot fail on the same item where it previously failed. But it would have been interesting to know, what was so special on that one playlist.

**Comment by LooOOooM** [comment]
I thing my issue is related to https://help.nextcloud.com/t/error-deleting-folders-or-moving-folders/162994/4, as I had also issues deleting things , pointning me there. After deactivating "music" I could delete again my other files, being not related to music at all:

"OC\Files\Cache\QuerySearchHelper::getCachesAndMountPointsForSearch(): Argument #1 ($root) must be of type OC\Files\Node\Root, OC\Files\Node\LazyRoot given, called in /usr/share/nginx/nextcloud/lib/private/Files/Node/Folder.php on line 237
