### ISSUE TITLE
Subsonic Android Client not able to play music

### ISSUE THREAD

**Issue by M1scer** [owncloud/music#1070]
Hi,

i am trying to make a subsonic android client running.
Both apps i tried (Ultrasonic and Subtracks) are not able to play music or download album covers.
Ultrasonic and Subtracks are both able to login and show my music collection.

Playing music via browser is possible and there the covers are showen.

My Setup (installed on a raspberry pi 4):
Nextcloud: 26.0.2
Music: V1.8.4
PHP: 8.1.18

Clients i tried:
Ultrasonic: 4.4.1
Substracks: 1.3.0

**Comment by paulijar** [comment]
What is the format of your audio files? All clients should be able to play MP3 but support for other formats may vary. When you attempt to play the music on the Subsonic client, is there any errors in nextcloud.log? If you paste any errors here, then note that your generated API password may be visible there as part of the URL, as the argument `p=XXXXXXXX`.

**Comment by M1scer** [comment]
The audio files are in .mp3 format.
Attached the [nextcloud.log](https://github.com/owncloud/music/files/11674335/nextcloud.log) file. But i dont see any errors.
I cleaned the log file and then tried again with Subtracks.

Thanks for the hint with the password.

**Comment by paulijar** [comment]
Are your music files located on an external storage? This might be the same issue as https://github.com/owncloud/music/issues/1040.

**Comment by M1scer** [comment]
My music is stored in the "regular" nextcloud data.

I run into this the [Fix file delete, moved and copy](https://help.nextcloud.com/t/fix-file-delete-moved-and-copy/162750) nextcloud issue. So i had to disable the music app. After reactivating i am able to play music.

Unfortunately i also sorting my music collection and for the lastest test i only added 1 song into the nextcloud storage.

So i can not tell if deactivate and reactivate solved it, or if the 3000 songs i had before coused the problem.

I will finish sorting my music collection and will add all the songs again, we will see if the error occurs again.

**Comment by M1scer** [comment]
It looks like the reactivaten of this app resolved the problem for me. I am using it again with 3000+ songs without issue since i have done the reactivation.
