### ISSUE TITLE
Show shortcuts/hotkeys in app

### ISSUE THREAD

**Issue by kimsin98** [owncloud/music#1086]
The app has several keyboard shortcuts that are not obvious and hidden in CHANGELOG. I suggest showing them in app through hover tooltips and/or a list (tucked in playback UI or settings).

**Comment by paulijar** [comment]
Yes, makes sense. This was actually brought up in the discussion when v1.7.0 added a larger number of new keyboard shortcuts but the best place to put these hints was not decided at that time. But the combination of showing the shortcuts in tooltips and listing them all under Settings sounds like a good idea.

**Comment by paulijar** [comment]
The new Music app release v1.10.0 now has a section about shortcuts in the Settings view, as well as tooltips with shortcut hints on the playback control buttons.
