### ISSUE TITLE
Invalid track id in playlist, but it isn't in the interface

### ISSUE THREAD

**Issue by phirestalker** [owncloud/music#1087]
I am getting an invalid track id error. I have an old copy of the database and know what song it referred to. It is indeed invalid now, but I do not see the song when viewing the playlist in the interface. How can I remove the song if it is not in the interface?

Nextcloud docker: 26.0.5
Nextcloud Music: 1.8.4

Error
```
{"reqId":"Fg0DKI92kqdRgpII9Xo7","level":0,"time":"2023-09-08T15:00:47+00:00","remoteAddr":"10.254.0.9","user":"--","app":"music","method":"GET","url":"/apps/music/subsonic/rest/getPlaylist.view?u=user&p=enc:__redacted__&v=1.2.0&c=DSub&id=23","message":"Invalid track ID 17840 found on playlist 23","userAgent":"DSub","version":"26.0.5.1","data":{"app":"music"}}
```

**Comment by paulijar** [comment]
You are right, I tested it and can confirm that the invalid tracks are not shown on the web UI. I think they have been shown in some earlier version as an empty row which could be removed through the web UI. I'm not sure about when and why has this changed.

As a workaround, you should get rid of the invalid track ID if you export the playlist to a file and then import it again as a new playlist.

**Comment by phirestalker** [comment]
Thanks, I figured that out. I was worried that it would export the bad track, but then I remembered that playlists are a text file. I was also unsure the paths would line up. It uses relative paths, so all worked out well.

Also, is there any way to kind of reverse the import ui flow? Something like, I select import playlist and it creates a new playlist with the file name to import the tracks to.

**Comment by paulijar** [comment]
> Also, is there any way to kind of reverse the import ui flow? Something like, I select import playlist and it creates a new playlist with the file name to import the tracks to.

This can be achieved by opening the playlist file within the Files view. There, select the three dots next to the list name in the player pane and "Import list to Music"
![image](https://github.com/owncloud/music/assets/8565946/42f30ae7-c49a-4932-be32-42a58529d3b4)

I haven't created such feature within the Music app proper since I couldn't figure out any natural location on the UI for this feature.

**Comment by phirestalker** [comment]
@paulijar. That works just fine. Thanks.
Since I found a workaround, do I close the issue?

**Comment by paulijar** [comment]
Maybe we could leave this open for now. I'd like to improve the handling of this case at some point so that no work-around would be needed.

**Comment by paulijar** [comment]
The Music v1.9.1 is now out with two related fixes:
1. The playlist can now be loaded via the Subsonic API even if the list contains some broken track references.
2. The broken track references are now visible on the web UI as "ERROR" lines. This makes it possible to remove them manually.
