### ISSUE TITLE
Nextcloud 25.0.11

### ISSUE THREAD

**Issue by typusmensch** [owncloud/music#1088]
Hi. Plugins doesn't work with Nextcloud 25.0.11. Just an empty sidebar there. :(

**Comment by paulijar** [comment]
Thanks for the report. I just installed Nextcloud 25.0.11, downloaded Music 1.8.4 from the app store, and uploaded two mp3 files to the cloud instance. For me, this configuration works fine without any issues. I presume that your installation is now somehow corrupted.

Do you see anything in the developer console of the browser when the Music app fails to load?

**Comment by paulijar** [comment]
You could try to uninstall Music, then make sure that all the app files have been really removed (e.g. check that there's no longer folder `nextcloud/apps/music`), and then reinstall the app from the app store.

**Comment by typusmensch** [comment]
Reinstall works. Thank you. :)
