### ISSUE TITLE
track is often getting stuck since upgrade from 0.x version

### ISSUE THREAD

**Issue by benapetr** [owncloud/music#1090]
Hello, I didn't update my nextcloud for a long time, I did that recently which pushed the Music version to 1.8.4 and ever since there are 2 annoying bugs, one of which is happening very often: the played track just get stuck somewhere in the middle, basically that dark gray representing part of song that is being pre-loaded no longer keeps increasing and the blue bar eventually reaches the edge and playback stops.

I have to move song back and forth to get it unstuck. It would be far more convenient if the app tried to fetch the piece of song again if it fails previously for whatever reason (I don't even know the reason - I tried debug console, but other than some notification errors, I don't see anything), here is excerpt from debug console:

```
HTTP "Content-Type" of "text/html" is not supported. Load of media resource https://cloud.xxx/apps/music/ failed. [music](https://cloud.xxx/apps/music/#/playlist/1)
Using html5 for type audio/mpeg URL /index.php/apps/music/api/file/85341/download [webpack.app.0f58fac36199389b782a.js:2:674317](https://cloud.xxx/apps/music/dist/webpack.app.0f58fac36199389b782a.js?v=05b20db1-3)
HTTP "Content-Type" of "text/html" is not supported. Load of media resource https://cloud.xxx/apps/music/ failed. [music](https://cloud.xxx/apps/music/#/playlist/1)
Using html5 for type audio/mpeg URL /index.php/apps/music/api/file/9330/download [webpack.app.0f58fac36199389b782a.js:2:674317](https://cloud.xxx/apps/music/dist/webpack.app.0f58fac36199389b782a.js?v=05b20db1-3)
Slowing down notifications: Status 500 [notifications-main.js:2:1244572](https://cloud.xxx/apps/notifications/js/notifications-main.js?v=05b20db1-3)
Polling interval updated to 300000 [notifications-main.js:2:1244994](https://cloud.xxx/apps/notifications/js/notifications-main.js?v=05b20db1-3)
Using html5 for type audio/mpeg URL /index.php/apps/music/api/file/12969/download [webpack.app.0f58fac36199389b782a.js:2:674317](https://cloud.xxx/apps/music/dist/webpack.app.0f58fac36199389b782a.js?v=05b20db1-3)
OC.requestToken changed XZpjQ5UjOrJFSVZrmEqb3DDW4UENy8RGTgU3yXsVoeE=:O80PctRSaJ0xODBfrSb3jgTvrhN6n7ZpK05loS5+6Ic= [main.js:160:89](https://cloud.xxx/core/js/dist/main.js?v=05b20db1-3)
Slowing down notifications: Status 500 [notifications-main.js:2:1244572](https://cloud.xxx/apps/notifications/js/notifications-main.js?v=05b20db1-3)
Polling interval updated to 300000 [notifications-main.js:2:1244994](https://cloud.xxx/apps/notifications/js/notifications-main.js?v=05b20db1-3)
HTTP "Content-Type" of "text/html" is not supported. Load of media resource https://cloud.xxx/apps/music/ failed. [music](https://cloud.xxx/apps/music/#/playlist/1)
Using html5 for type audio/mpeg URL /index.php/apps/music/api/file/23937/download [webpack.app.0f58fac36199389b782a.js:2:674317](https://cloud.xxx/apps/music/dist/webpack.app.0f58fac36199389b782a.js?v=05b20db1-3)
Using html5 for type audio/mpeg URL /index.php/apps/music/api/file/14778/download [webpack.app.0f58fac36199389b782a.js:2:674317](https://cloud.xxx/apps/music/dist/webpack.app.0f58fac36199389b782a.js?v=05b20db1-3)
Using html5 for type audio/mpeg URL /index.php/apps/music/api/file/83292/download [webpack.app.0f58fac36199389b782a.js:2:674317](https://cloud.xxx/apps/music/dist/webpack.app.0f58fac36199389b782a.js?v=05b20db1-3)
Slowing down notifications: Status 500 [notifications-main.js:2:1244572](https://cloud.xxx/apps/notifications/js/notifications-main.js?v=05b20db1-3)
Polling interval updated to 300000 [notifications-main.js:2:1244994](https://cloud.xxx/apps/notifications/js/notifications-main.js?v=05b20db1-3)
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://cloud.xxx/apps/notifications/js/notifications-main.js?v=05b20db1-3
Source Map URL: notifications-main.js.map?v=951083631ec28abaabd6

Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://cloud.xxx/apps/music/dist/webpack.app.0f58fac36199389b782a.js?v=05b20db1-3
Source Map URL: webpack.app.0f58fac36199389b782a.js.map

Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://cloud.xxx/core/js/dist/main.js?v=05b20db1-3
Source Map URL: main.js.map

Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

second bug is that sometimes next track starts before the previous one finishes, resulting in both mp3 playing simultaneously, but that's much more rare and doesn't bother me so much

**Comment by benapetr** [comment]
some more observation:

first track always loads full (all dark gray) and works fine. Subsequent track is almost always interrupted somewhere in the middle. It starts with tiny dark part which grows as blue part approaches it, but after about 2 - 3 increases it stops working and no longer increases. When this happen "move back" button is defunct. Clicking it does nothing. Move forward button works and after next track is loaded move back starts working again.

**Comment by benapetr** [comment]
btw where are user settings stored? I unchecked "notify on song change" and in different browser I am now trying it out in had it checked again, is it stored in cookies instead of database?

**Comment by paulijar** [comment]
> btw where are user settings stored? I unchecked "notify on song change" and in different browser I am now trying it out in had it checked again, is it stored in cookies instead of database?

I'll answer this one first as this is an easy one. I shall return to the actual issue later when I have time.

This particular setting is stored on the browser, using the browser local storage. This functions the same way as cookies, expect that cookies are sent back and forth between the client and the server while the local storage items are never sent to the server. The sound volume and the status of the shuffle and repeat buttons is stored the same way while most of the settings visible in the Settings view are stored in the DB on the back-end.
![image](https://github.com/owncloud/music/assets/8565946/301d993d-9090-4aba-b117-7319bcf92330)

The rationale behind this is that, for myself, I wanted to have the notifications enabled on the desktop browsers but disabled on the mobile browsers.

**Comment by paulijar** [comment]
For the actual issue, this is not something which I would have seen. Also, as the version 1.8.4 has been downloaded more than 20'000 times during the past three months and such problem has not been reported before, it seems likely that this is not a common thing but something very specific to your setup. Can you tell anything more about your system? Like, are you maybe using some reverse proxy there? Are your files locally on the same server running Nextcloud or do you use some external storage?

Looking at your console log, this line seems like it could be relevant here:
```
HTTP "Content-Type" of "text/html" is not supported. Load of media resource https://cloud.xxx/apps/music/ failed. [music](https://cloud.xxx/apps/music/#/playlist/1)
```
To me, it looks like the front-end player had tried to stream music from the URL of a playlist which makes absolutely no sense. If you look at the Network tab of your browser developer tools, do you see there the attempts to load the playlist URL when the problem happens? Or maybe something else of interest?

**Comment by benapetr** [comment]
It seems that problem is related to browser cache (it's firefox on MacOS), running another instance of same firefox with a fresh profile seems to work. Probably some old JS is cached somewhere. I tried clearing cache, but didn't help. I will just keep running music app from another firefox profile for now...

**Comment by paulijar** [comment]
Okay, cool. Would it help to do the forced refresh by holding the shift key pressed and clicking the reload button? If not, then you could also try to discard the site data through the "Privacy & Security" settings of Firefox (there's such view on Firefox for Windows, I assume that on MacOS it is the same).
