### ISSUE TITLE
Unable to set the folder path

### ISSUE THREAD

**Issue by morceaudebois** [owncloud/music#1091]
Hi! I'm trying to configure the Music app but I can't seem to set the library's path. It's lacking a button to confirm the selection and there's no way to save the page when I type it in manually.

Not sure if it's a real bug or if I'm just being an idiot, but some help would be appreciated!
Thank you 😊

https://github.com/owncloud/music/assets/50768582/5cd4be2f-f674-4ae7-9778-436c836ee9bd

**Comment by paulijar** [comment]
Thanks for the report. Which version of Nextcloud is this? The folder selection dialog seems slightly different than any of the versions which I have tested.

**Comment by morceaudebois** [comment]
Thanks for the quick reply! It's version 27.0.1. I tried to reinstall it but it didn't change anything.

I have some errors in the console but I'm not sure if they're related or not:

<img width="1128" alt="Screenshot 2023-09-21 at 08 25 56" src="https://github.com/owncloud/music/assets/50768582/15b8527d-807f-45ec-a8c7-054202985e90">

**Comment by paulijar** [comment]
Thanks, I need to install that version and check. The logging in the console doesn't look like it would be relevant here.

**Comment by pm-pm** [comment]
Same here with NC 27.1.1 (not tested/used on 27.0.0 nor 27.1.0)

**Comment by Rob-Geebivi** [comment]
Same problem here with NC 27.1.0. Please fix soon or post if there is a workaround. Thank you!

**Comment by paulijar** [comment]
I'm not able to investigate this during the next few days, but I will as
soon as I can.

-Pauli

pe 22. syysk. 2023 klo 21.52 Robbie ***@***.***> kirjoitti:

**Comment by paulijar** [comment]
The workaround is to set the path from the command line using the `occ` tool. The command to use is like
```sudo -u www-data php occ user:setting <user_name> music path <path_relative_to_home>```
e.g.
```sudo -u www-data php occ user:setting pauli music path /Music/MP3/```.

When done like this, any previously scanned files outside the new path are not removed automatically. To remove them, you may use the command
```sudo -u www-data php occ music:scan --clean-obsolete <user_name>```.

**Comment by paulijar** [comment]
It seems that this happens because Nextcloud has accidentally broken their API compatibility and it has been fixed here: https://github.com/nextcloud/server/pull/40557. Hence, the issue should be gone in the NC version 27.1.2, which is scheduled to be released on 2023-10-19. I may be able to release a Music-app-side workaround before that but this remains to be seen.

**Comment by paulijar** [comment]
The app-side workaround has now been released in Music v1.9.1.
