### ISSUE TITLE
Error playing URL

### ISSUE THREAD

**Issue by sureloc** [owncloud/music#1096]
After the latest update, i get the above error when trying to play a music file, and then Nextcloud gives a 503 Service Unavailable error for a while. I tried to view the logs but it keeps updating with the same error so i can't even copy any text, but here's a screenshot
![image](https://github.com/owncloud/music/assets/69294325/aaed9272-afd1-44e6-a27d-23e0758f8623)

**Comment by paulijar** [comment]
So have you been able to reduce the logging level @sureloc, and did this reveal any more relevant errors? It might be worthwhile to check also if there's any logging in the console of the web browser.

**Comment by sureloc** [comment]
Sorry forgot to report back, but yes i reduced the log level. Looks like the problem wasn't the Music app but NC in general and duckdns, but everything seems to work now

**Comment by paulijar** [comment]
Okay, great, closing then.
