### ISSUE TITLE
New version 1.9.1/1.9.0 not working on NC27.1.2 

### ISSUE THREAD

**Issue by Ho551** [owncloud/music#1100]
When I try to update the app music in my NC 27.1.2, the whole NC stops working.
Log Info:

> [PHP] Error: file_get_contents(/var/www/html/nextcloud/apps/music/lib/../dist/manifest.json): Failed to open stream: No such file or directory at /var/www/html/nextcloud/apps/music/lib/Utility/HtmlUtil.php#108
> 
> GET /settings/apps/installed/music
> from 217.7.114.170 by admin at 2023-10-10T07:31:07+02:00
> 
> [index] Error: TypeError: json_decode(): Argument #1 ($json) must be of type string, bool given at <<closure>>
> 
>  0. /var/www/html/nextcloud/apps/music/lib/Utility/HtmlUtil.php line 109
>     json_decode()
>  1. /var/www/html/nextcloud/apps/music/lib/Utility/HtmlUtil.php line 41
>     OCA\Music\Utility\HtmlUtil::getManifest()
>  2. /var/www/html/nextcloud/apps/music/appinfo/app.php line 33
>     OCA\Music\Utility\HtmlUtil::getSvgPath()
>  3. /var/www/html/nextcloud/lib/private/NavigationManager.php line 115
>     OC\App\AppManager::OCA\Music\App\{closure}("*** sensitive parameters replaced ***")
>  4. /var/www/html/nextcloud/lib/private/TemplateLayout.php line 108
>     OC\NavigationManager->getAll()
>  5. /var/www/html/nextcloud/lib/private/legacy/OC_Template.php line 182
>     OC\TemplateLayout->__construct()
>  6. /var/www/html/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php line 213
>     OC_Template->fetchPage()
>  7. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 182
>     OCP\AppFramework\Http\TemplateResponse->render()
>  8. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 183
>     OC\AppFramework\Http\Dispatcher->dispatch()
>  9. /var/www/html/nextcloud/lib/private/Route/Router.php line 315
>     OC\AppFramework\App::main()
> 10. /var/www/html/nextcloud/lib/base.php line 1068
>     OC\Route\Router->match()
> 11. /var/www/html/nextcloud/index.php line 36
>     OC::handleRequest()
> 
> GET /settings/apps/installed/music
> from 217.7.114.170 by admin at 2023-10-10T07:31:07+02:00
> 
> [PHP] Error: file_get_contents(/var/www/html/nextcloud/apps/music/lib/../dist/manifest.json): Failed to open stream: No such file or directory at /var/www/html/nextcloud/apps/music/lib/Utility/HtmlUtil.php#108
> 
> GET /settings/apps/installed/music
> from 217.7.114.170 by admin at 2023-10-10T07:31:08+02:00
> 
> [PHP] Error: TypeError: json_decode(): Argument #1 ($json) must be of type string, bool given at /var/www/html/nextcloud/apps/music/lib/Utility/HtmlUtil.php#109
> 
> GET /settings/apps/installed/music
> from 217.7.114.170 by admin at 2023-10-10T07:31:08+02:00

**Comment by paulijar** [comment]
That might be some kind of PHP caching issue, or then your installation has somehow got only partially updated. It seems like the HtmlUtil.php file being used is still of the old version as it tries to open the file `manifest.json`. But in the new version, the corresponding file is named `assets-manifest.json`.

**Comment by Ho551** [comment]
Thanks! After the update I restarted php-fpm and it worked.
