### ISSUE TITLE
WavPack support

### ISSUE THREAD

**Issue by greenvorbisfan** [owncloud/music#1101]
Hello.
I have a large collection of audio in WavPack format (including DSD). Is it possible to add support for it in the player? If necessary, I can provide access to the content.
Thank you.

**Comment by paulijar** [comment]
Sorry but I don't see any plausible way to make this happen.

The thing is, we mostly support playing files which have a native support in the web browsers. And WavPack is supported neither in Chrome, Firefox, nor Edge. We do have a javascript-based fallback solution for a few file types with no native support in most browsers (like M4A-ALAC and AIFF), but I couldn't find any javascript libraries for WavPack with a bit of googling.

So I would say that this will not happen in the foreseeable future. But if the web browsers ever get the native support for this type, then it will be trivial to support it in the Music app, too.

**Comment by greenvorbisfan** [comment]
Thanks for the answer. I found [this](https://www.wavpack.com/flash/WavPackJSFirefox.html) — it's probably not quite what you need. Thanks again, sorry.

**Comment by paulijar** [comment]
Flash is basically dead nowadays, with support removed from all the major browsers. The webassebly solution, on the other hand, wouldn't be totally out of question. I downloaded five sample files from https://filesamples.com/formats/wv and out of those, the webassembly player could play three correctly (or at least with no obvious faults) while two played as badly distorted. VLC on my PC played all five files just fine. So this webassembly is definitely not a perfect solution but at least it's something.

I believe that this is the project creating that webassembly package: https://github.com/soiaf/WebAssembly-WavPack. That doesn't look like very actively maintained project, with overall 9 commits and the last commit having happened one year ago. Also, there's no issues nor pull requests, suggesting that next to no-one uses it.

Add to that that the package doesn't look very finalized nor that it would be simple to plug it to any host project and you might guess that I'm not terribly enthusiastic to dive deeper into this package. But if anyone else is willing to invest the time and try to integrate this to the Music app, then I'm ready to consider merging the related pull request.
