### ISSUE TITLE
Time and bitrate in supersonic and other apps 

### ISSUE THREAD

**Issue by starmanager01** [owncloud/music#1102]
Hi, thanks for the nice music app in Nextcloud. I am using it with supersonic on Windows. It works like a charme. I got just something missing. It does not show any time or bitrate in the album list. If I am using the original subsonic Server it shows this infos.

Thanks a lot

Greetings.

Klaus

**Comment by paulijar** [comment]
Thanks for the report. Are you talking about this app and this view:
![image](https://github.com/owncloud/music/assets/8565946/9aa1432d-ebae-44cf-bea6-8b63d00ae5d8)
There has been also at least one other Subsonic client called Supersonic but that one has not been maintained for years and is no longer publicly available anywhere, as far as I know.

If this is the correct view, then I don't see any times or bitrates even when using the official Subsonic demo server demo.subsonic.org (as shown in the picture above). That server seems to be running Subsonic 6.1.6 which should be the latest version.

**Comment by starmanager01** [comment]
It lookes like there is somebody still active on this project. I did download the latest version a view weeks ago. 
Here are 2 screenshots. The one with the yellow marked zeros is when I am connect to the nextcloud and the other is with the latest subsonic server 6.1.6
 
https://github.com/dweymouth/supersonic

Thanks. 
![2023-10-14 09_10_27-Supersonic](https://github.com/owncloud/music/assets/140885188/07da2489-9e18-4e50-9934-3c827d9771b3)
![2023-10-14 09_28_29-Supersonic](https://github.com/owncloud/music/assets/140885188/d779e2c9-d22a-461e-ad82-ad04dd96609b)

**Comment by paulijar** [comment]
The Music app does show the "Time" and "Bitrate" on my system. The "Plays" are not shown though, this is something I could fix:
![image](https://github.com/owncloud/music/assets/8565946/49d19814-ee3a-40c4-87d5-f89e0f98e468)

You didn't disable the metadata scanning in your Music app settings, did you?
![image](https://github.com/owncloud/music/assets/8565946/e8a68939-b177-4082-8c6e-dd8947351277)

**Comment by starmanager01** [comment]
I am sorry. This was the problem. I did turn it of because it did show me so many albums with just one song in the recently added List. Now it works like a charme. 

Thanks a lot for your help. 

Greetings. 

Klaus

**Comment by paulijar** [comment]
Okay, great, one more mystery solved.
