### ISSUE TITLE
smart playlist with lastest added songs

### ISSUE THREAD

**Issue by tigermick** [owncloud/music#1110]
Hi,
first of all, thank you for your great app !
Recently, you implemented quick shuffle playlist with "smart playlist" feature, can you add "lastest added songs" as filter to create a playlist with only recently added new songs ?

**Comment by paulijar** [comment]
Yes, this is a feasible idea for further development. Basically the same feature has been requested already in the issue https://github.com/owncloud/music/issues/1098 although the intention is not quite clear from its title.

**Comment by tigermick** [comment]
Oh yes, I hadn't seen that topic ... Sorry.

**Comment by paulijar** [comment]
Closing as duplicate
