### ISSUE TITLE
Compatibility with Nextcloud 28

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#1112]
There are many changes in the Nextcloud version 28 which make it incompatible with the current Music app version 1.9.1. A few notable problems include (and there may be others):
- The navigation pane layout is broken, making it difficult or impossible to use
- The embedded "lite" player is absent in the Files app because of architectural changes
- The Music app local search doesn't work with the new "Unified search" input. Even if it would technically work, the new UI concept is still a bad fit for the Music app's local search and we probably need to add our own search input field.

I'm working on fixing these but it may take some time.

**Comment by paulijar** [comment]
In addition, all the file/folder selection dialogs are broken at least on NC28 RC4. I believe that this is a bug in Nextcloud and not something which should be fixed on the application side.

**Comment by JoshuaPettus** [comment]
Not a bug, it's an enhancement!  You didn't break it, they did :)
Thank you sir for all that you do!

**Comment by groms** [comment]
Thank you for your work @paulijar. I really like your plugin!

**Comment by sanfx** [comment]
Enable it if you want to be able to use music app via phone from a third party app like subsonic on android.
Works fine for me, only UI is messed up. 

`sudo -u www-data nextcloud/occ app:enable music -f`

**Comment by paulijar** [comment]
The (slow) progress on this topic can now be followed on the PR https://github.com/owncloud/music/pull/1116.

**Comment by john-2000** [comment]
@paulijar  firstly massive thank you for all the work - do you feel that you an alpha or beta of your improvements could be pushed into the system?

**Comment by paulijar** [comment]
I'll try to publish a pre-release in GitHub during this weekend. Then I will be pre-occupied for the next week, but I hope I can make the actual release v1.10.0 by the end of January.

**Comment by paulijar** [comment]
The pre-release can now be loaded from https://github.com/owncloud/music/releases/tag/v1.10.0-PR1. I actually forgot to mark it as compatible with NC28 in the metadata but don't let that bother; it can still be used. Feel free to give your feedback here although I will not be able to respond to any questions during the next week.

**Comment by john-2000** [comment]
@paulijar thank you am using the PR1 and have so far not had any problems, will update if I find something

**Comment by paulijar** [comment]
The official Music release v1.10.0 is now out! Be sure to use Nextcloud version 28.0.2 (RC4) or newer with the Music app to have fix for the issue https://github.com/nextcloud/server/issues/42291.
