### ISSUE TITLE
Garbage shown in the title of some AIFF files

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#1115]
But I have seen another Problem. And I think there is still a Problem with AIFF files:

![Screenshot_20231220_091137](https://github.com/owncloud/music/assets/1506204/d0d8badf-9b71-4aab-84ed-da9573f3e832)

The title of the AIFF tag looks a bit faulty. When I open it with an ID3 editor, everything looks correct.

_Originally posted by @djtulan in https://github.com/owncloud/music/issues/767#issuecomment-1864046341_

**Comment by paulijar** [comment]
_From https://github.com/owncloud/music/issues/767#issuecomment-1864046341 by @djtulan:_

@paulijar , I sent you a DL link for the file.
Hex Editor shows that bytes, if this is helpful?

![Screenshot_20231220_114120](https://github.com/owncloud/music/assets/1506204/09869275-f85d-4bc2-97b7-c20e73929960)

**Comment by paulijar** [comment]
I have reported this upstream for the library we use to extract the file metadata: https://github.com/JamesHeinrich/getID3/issues/430

**Comment by paulijar** [comment]
A fixed GetID3 library version has now been merged to the master branch with b1050122. Hence, this issue should be gone in the next release of Music. Note that you still need to rescan your library to see the correct titles in the albums view; the details pane, on the other hand, shows the correct titles without rescan.

**Comment by paulijar** [comment]
The release v1.10.0 is now out, including also this fix.

**Comment by djtulan** [comment]
Thank you very much, I will see if it works now!
