### ISSUE TITLE
Three Dots to add Radio or Podcast not shown

### ISSUE THREAD

**Issue by cswertz** [owncloud/music#1117]
When I called "Podcasts" the first time, it was possible to add one first rss feed in a form in the main window. But now this form  is not longer avaiable. I assume that three dots to call this form should be visible behind "Podcasts". But there are no dots. Same for Radio stations. In the case of Radio stations, the instructions suggest to click on three dots - but there are none. Tried this with Firefox and Chromium (Ubuntu 22.04). Same Result. Music Version is 1.9.1 and nextcloud version is 28.0.0. Thus I can't add a second podcast and no radio stations.

![grafik](https://github.com/owncloud/music/assets/15083008/d8d1e5d9-1040-41a6-bdf2-2113386c4954)

BTW: Great piece of software - works like a charm. Just what I've bee looking for...

**Comment by paulijar** [comment]
This is just one part of the Music app not being yet compatible with Nextcloud 28. This is already reported here: #1112
