### ISSUE TITLE
No option to scan library

### ISSUE THREAD

**Issue by Spurge420** [owncloud/music#1119]
Hi,
Music doesn't have a prompt or option to scan music library. 
I click on the music tab, it whirls for some time then nothing.  

Any way to force a scan? 

Using NextcloudPI   28.0.2 RC3

Update:  Apparently it just takes a long time with a large library. Please close this one. Thank you.

**Comment by paulijar** [comment]
Yeah, checking the existence of unscanned audio files may take a while if you have e.g. hundreds of thousands of files within the selected music library path. Another case, where the app might not prompt about unscanned files, is when your files reside on an external storage and Nextcloud hasn't indexed those yet. It's possible that Nextcloud indexes the external storage only once you navigate to those folders in Files or run `occ files:scan` manually.
