### ISSUE TITLE
search broken with 1.10

### ISSUE THREAD

**Issue by paroj** [owncloud/music#1121]
searching in the "Albums" view used to filter it. After upgrading this does not work any more.

**Comment by paulijar** [comment]
Did you notice, that Music now has its own input field for Search, just above Settings on the navigation pane? It's no longer integrated to the global search input of Nextcloud because the new design of global search in NC 28 wasn't really suitable for this.

**Comment by paroj** [comment]
doh! thanks for the hint. I indeed did not discover the input field yet..
