### ISSUE TITLE
After upgrading from NC 27 to 28 white side

### ISSUE THREAD

**Issue by zeroblue2005** [owncloud/music#1129]
Hello everyone,
After the upgrade to version 28 with PHP 8.2, only an empty white side is displayed on the Music app. I removed the app and reinstalled. All OCC Music commands executed! All other app deactivated. But it stays with the white side, no change! What can I do?

The Versison is:  1.10.00

Thanks Mike

**Comment by paulijar** [comment]
Are you using the latest version of Music? Is there any errors shown in the browser console (in the developer tools, opened with the F12 key on most browsers)?

**Comment by zeroblue2005** [comment]
Hello Paulijar,

The Version is: 1.10.00. In the browser console stand the following Problems:

`GET https://domain.eu:446/nextcloud/apps/music/%7B%7B%20repeat%20===%20'one'%20?%20%27/nextcloud/apps/music/img/../dist/img/342890d62ca1ea24d1a8.svg%27%20:%20%27/nextcloud/apps/music/img/../dist/img/2860aa2d47464d113666.svg%27%20}} 404 (Not Found)`

`ypeError: Cannot read properties of undefined (reading 'aliases')
    at Object.getIconUrl (merged-template-prepend.js?v=5dafc643-100:77:38)
    at Object.<anonymous> (webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:303745)
    at Object.invoke (webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:60133)
    at webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:94084
    at se (webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:85003)
    at webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:78457
    at se (webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:85649)
    at webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:78457
    at webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:77772
    at webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2:44174
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
$apply @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
invoke @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
i @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
Ie @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
h @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
f @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
setTimeout (async)
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
h @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
fireWith @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
fire @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
h @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
fireWith @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
ready @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
setTimeout (async)
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
85703 @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
n @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
4002 @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
n @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
74426 @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
n @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
66695 @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
n @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
(anonymous) @ webpack.app.ed7a3d4fa79d10ae7b4c.js?v=5dafc643-100:2
`
![2024-02-28_070451](https://github.com/owncloud/music/assets/123501472/a4b4953a-4854-46c9-b1db-41d506e2ed3c)

the following OCC Comand have i executed:

sudo -u www-data php occ music:register-mime-types
sudo -u www-data php occ music:reset-cachenc. username
sudo -u www-data php occ music:reset-database nc.username
sudo -u www-data php occ music:scan nc.username

**Comment by paulijar** [comment]
If you browse on your server to the folder `<server_public_dir>/nextcloud/apps/music/dist/img`, then can you find the file named `342890d62ca1ea24d1a8.svg`? If not, then the installation has somehow failed.

You could try to first remove Music using the Nextcloud web UI, then ensure manually that the directory `nextcloud/apps/music` is really gone, and then reinstall Music.

**Comment by zeroblue2005** [comment]
I solved the problem. After the update to NC 28, I have: PHP OCC Integrity: Check-Core
   - Invalid_hash:
     - Core/JS/Mimetypelist.js:

Sudo rm /var/www/nextcloud/core/js/mimetypelist.js and replace the Music app for recent from NC 28 now, thank you

**Comment by paulijar** [comment]
Okay, great that you could solve the problem. But I don't really see, how the invalid hash on Mimetypelist.js could be related, especially if the problem was present only in the Music app and nowhere else in your Nextcloud.

**Comment by zeroblue2005** [comment]
But other apps were also affected. But I noticed that at Music.
