### ISSUE TITLE
Php cron job fails on Nextcloud 29.0.0 Beta

### ISSUE THREAD

**Issue by ksaro1** [owncloud/music#1132]
Since upgrading I now notice that the cron job fails with the following:

Error: Class “OC\BackgroundJob\TimedJob” not found in /var/www/html/nextcloud/apps/music/lib/BackgroundJob/Cleanup.php:24

Nextcloud support inform me that the music app should move from OC to OCP in order to prevent this failure under Nextcloud 29.0.0.

**Comment by paulijar** [comment]
Thanks for the report. This change isn't quite trivial because `OCP\BackgroundJob\TimedJob` is available on Nextcloud 15+ but not any any version of ownCloud. So it will require some coding magic but should be doable. Shall be fixed before releasing a version of Music with the claimed support for NC29.

**Comment by kmorber** [comment]
Error: Class "OC\BackgroundJob\TimedJob" not found in /var/www/html/nextcloud/apps/music/lib/BackgroundJob/Cleanup.php:24
Stack trace:
#0 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(576): include()
#1 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/html/n...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\Music\\Backg...')
#3 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): ReflectionClass->__construct('OCA\\Music\\Backg...')
#4 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Music\\Backg...')
#5 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(469): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Music\\Backg...')
#6 /var/www/html/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Music\\Backg...')
#7 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query('OCA\\Music\\Backg...')
#8 /var/www/html/nextcloud/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Music\\Backg...')
#9 /var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php(326): OCP\Server::get('OCA\\Music\\Backg...')
#10 /var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php(235): OC\BackgroundJob\JobList->buildJob(Array)
#11 /var/www/html/nextcloud/cron.php(163): OC\BackgroundJob\JobList->getNext(true)
#12 {main}

same for me

**Comment by paulijar** [comment]
Music v1.11.0 is now released with support for NC29.
