### ISSUE TITLE
Benign error in nc log - Cannot set response code - headers already sent

### ISSUE THREAD

**Issue by JoshuaPettus** [owncloud/music#1133]
Hi I have: Music 1.10.0
nextcloud 28.0.3
php 8.3.3
pgsql 15.6
nginx 1.25.4

This error keeps repeatedly flooding the nextcloud log.  It doesn't seem to effect anything but I was wondering if you might have any idea:

  http_response_code(): Cannot set response code - headers already sent  (output started at  /var/www/nextcloud/apps/music/lib/Http/FileStreamResponse.php:99) at  /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#77

**Comment by paulijar** [comment]
Thanks for the report. What is the logging level where this is shown? I haven't seen this on NC 28.0.2 but maybe this is something new in 28.0.3. It's possible that I'm using the NC `ICallbackResponse` API a bit incorrectly in a way which doesn't cause any actual problem.

**Comment by JoshuaPettus** [comment]
It shows up at the error level.

**Comment by paulijar** [comment]
Now I managed to reproduce and fix this. The key was to use PHP 8.3, this error didn't appear with PHP 8.2 regardless of the cloud version.

**Comment by JoshuaPettus** [comment]
Thank you!  I just tested the fix on my install and its working fine (Isn't PHP a neat thing?).  Guess just to go show how much I use the app that it was triggered by every new song I listened to :)

**Comment by paulijar** [comment]
The fix is now released in Music v1.11.0.
