### ISSUE TITLE
Configurable session timeout for the Ampache API

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#1134]
Currently, the session timeout for the Ampache API has been hard-coded to 6000 seconds (1 hour 40 minutes). This value could be made configurable. As this is a rather technical detail with some security implications, I would allow only the cloud admins to configure it via `config.php` and not add any user-setting.

This was first requested at https://github.com/mitchray/ample/issues/44#issuecomment-1996768069.

**Comment by rstefko** [comment]
Thank you. Btw. the API tokens can only be used with ownCloud Music APIs right?

**Comment by paulijar** [comment]
Yes, the API tokens only allow access to the Ampache and Subsonic APIs of the Music app if that was what you meant. So if those keys are leaked, then the damage made is limited.

**Comment by paulijar** [comment]
This feature is now released in Music v1.11.0.
