### ISSUE TITLE
Ampache error due to interface mismatch

### ISSUE THREAD

**Issue by boynux** [owncloud/music#1138]
Hi

I tried to use Ampache API on a self hosted owncloud, however, I'm getting the following error:

`PHP Fatal error:  Declaration of OCA\\Music\\Controller\\AmpacheController_AllTracksPlaylist::__construct(string $userId, OCA\\Music\\BusinessLayer\\TrackBusinessLayer $trackBusinessLayer, OCP\\IL10N $l10n) must be compatible with OCP\\AppFramework\\Db\\EntityInterface::__construct() in /mnt/data/apps/music/lib/Controller/AmpacheController.php on line 2179`

Thank you!

**Comment by boynux** [comment]
This commit https://github.com/owncloud/core/commit/825364e0860b6cdc1e9a189bb609ffe55e0bbf3b seems to be the culprit

**Comment by paulijar** [comment]
Thanks for the report. So apparently classes inheriting the `Entity` class from the framework are no longer allowed define a constructor taking any arguments. I guess I need to refactor my code a bit.

**Comment by paulijar** [comment]
This is now fixed in Music v1.11.0.
