### ISSUE TITLE
Activity integration

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#114]
cc @karlitschek 
- Played song
- provide path to mp3 for cover art

**Comment by benediktg** [comment]
What does activity integration mean?

**Comment by MorrisJobke** [comment]
> Played song
> provide path to mp3 for cover art

Show this in the activity app.

**Comment by paulijar** [comment]
IMHO, this is a bad idea as showing the played songs would create an awful amount of noise to the Activity feed. There are loads of enhancements I would like to implement for the Music app if I had the time but this isn't one of them. Closing.
