### ISSUE TITLE
Chinese garbled characters

### ISSUE THREAD

**Issue by 18937062462** [owncloud/music#1146]
my Music version is 1.11.0, Chinese music file names displayed as garbled characters.

**Comment by paulijar** [comment]
Thanks for the record. Most likely, your files have some inconsistency in how they define the character set used for the metadata. But it's also possible that there is some problem in the library which we use to extract the metadata. Could you share one sample file with me? You can find my email from my github profile.

**Comment by 18937062462** [comment]
I had send one sample file to your email[pauli.jarvinen@gmail.com]. Please check it carefully. Thank you .

**Comment by paulijar** [comment]
Thanks for the sample. Your file claims to use the ISO-8859-1 character set (aka Latin-1). Obviously, that character set contains no Chinese characters. In reality, the metadata in the ID3v2.3 tags of the file seem to be using the GB2312 encoding but I believe that this is not actually a valid encoding for ID3v2.x, as per the specification. To use non-Latin characters in the ID3v2.x tags, the encoding should be either UTF16 or UTF8.

For comparison, this is how Windows shows your file details:
![image](https://github.com/owncloud/music/assets/8565946/e19a9b52-85a9-4802-a923-31489901d59d)

And this is foobar2000:
![image](https://github.com/owncloud/music/assets/8565946/e0e7873f-4027-4406-a9a3-1bce31b0fb19)

And this is is MP3Diags:
![image](https://github.com/owncloud/music/assets/8565946/166a19dd-44e0-4d18-8075-a409037a97b3)

**Comment by paulijar** [comment]
If you don't care to fix the metadata of your files, then the alternative is to disable the metadata scanning from the Music app settings. With this, only the file and and folder names are used as the source of song and album and artist names.
![image](https://github.com/owncloud/music/assets/8565946/e8b9a9c8-5d20-4044-bc62-dce560436e36)

**Comment by 18937062462** [comment]
Due to the large number of files.I have decided to disable metadata scanning solution to solve this problem, which has reduced the workload.Thank you very much.

**Comment by paulijar** [comment]
Okay, cool. If you ever change your mind and want to fix the metadata, then [MP3Tag](https://www.mp3tag.de/en/download.html) is one option. It's an application which I have used on all my own mass-tagging needs. Most likely, there are also other similar utilities.
