### ISSUE TITLE
Internal server error after update to Music 2.0.0

### ISSUE THREAD

**Issue by ssarna1** [owncloud/music#1154]
Nextcloud version 27.1.10. After disabling Music app the instance is working again. Here is what is in the log:

[no app in context] Error: OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\Music\App\Music! Class "OCA\Music\App\Music" does not exist at <<closure>>

0. /mnt/repozytorium/nextcloud/data/lib/private/AppFramework/Utility/SimpleContainer.php line 142
   OC\AppFramework\Utility\SimpleContainer->resolve()
1. /mnt/repozytorium/nextcloud/data/lib/private/ServerContainer.php line 171
   OC\AppFramework\Utility\SimpleContainer->query()
2. /mnt/repozytorium/nextcloud/data/apps/music/appinfo/routes.php line 19
   OC\ServerContainer->query()
3. /mnt/repozytorium/nextcloud/data/lib/private/Route/Router.php line 422
   include_once("/mnt/repozytori ... p")
4. /mnt/repozytorium/nextcloud/data/lib/private/Route/Router.php line 163
   OC\Route\Router->requireRouteFile()
5. /mnt/repozytorium/nextcloud/data/lib/private/Route/Router.php line 273
   OC\Route\Router->loadRoutes()
6. /mnt/repozytorium/nextcloud/data/lib/private/Route/Router.php line 307
   OC\Route\Router->findMatchingRoute()
7. /mnt/repozytorium/nextcloud/data/ocs/v1.php line 65
   OC\Route\Router->match()
8. /mnt/repozytorium/nextcloud/data/ocs/v2.php line 23
   require_once("/mnt/repozytori ... p")

GET /ocs/v2.php/core/navigation/apps?format=json
from <IP> by <username> at 2024-07-03T07:27:12+00:00

**Comment by paulijar** [comment]
This seems like the same issue as https://github.com/owncloud/music/issues/1152. Your instance is running only partially updated version of the Music app, probably due to PHP caching. The first thing to try is to restart the PHP-FPM.

**Comment by paulijar** [comment]
I don't know if it would be technically possible for the NC updater (being PHP application itself) to restart the PHP-FPM, or at least flush its cache. Also, I don't know why this problem affects some users some times but apparently not all users all the time.

**Comment by ssarna1** [comment]
Perhaps it depends on cache settings, if it happens that the Music app is not cached then there is no problem.
