### ISSUE TITLE
Folders not showing up

### ISSUE THREAD

**Issue by sgt-droord** [owncloud/music#1155]
Hello there,

automatic scan finds all audio files. BUT I can't neither exclude directories nor import playlists. After hitting the button, the selection screen appears ... without any directories. Is this an already known issue? Is there any workaround/fix? 
![import](https://github.com/owncloud/music/assets/174649334/7a580ef5-49f1-4374-8a70-df122087497d)
As mentioned before, the automatic scan works perfectly, but I can't choose any folders.

**Comment by paulijar** [comment]
Which version of Nextcloud are you using? There has been this kind of bug in Nextcloud more than once, which has been fixed and then reappeared in some later version and the got fixed again.

**Comment by sgt-droord** [comment]
Dear Paulli Järvinen, thank you for your help. It is Nextcloud Hub 7 (28.0.7) and Music 2.0.0

**Comment by paulijar** [comment]
I just installed NC 28.0.7, but for me, this problem doesn't occur there. When this happens, do you see any errors in the browser console screen?

**Comment by sgt-droord** [comment]
Ok, maybe there is a hint. The moment I open the folder-selection, appears the following in the console of firefox:

Error: Invalid response: 404 Not Found
    pt https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    mt https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    Xt https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
[core-common.js:2:1870255](https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1)
Error: Invalid response: 404 Not Found
    pt https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    mt https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    Xt https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
[core-common.js:2:1870255](https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1)
Uncaught (in promise) Error: FilePicker: No nodes selected
    pick https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    close https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    Tn https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    n https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    Tn https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    $emit https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    handleClose https://10.8.0.1/nextcloud/dist/8321-8321.js?v=1e9a8023ef8296a459a5:2
    Tn https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    n https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    Tn https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    $emit https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    u https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    Tn https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    n https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    Tn https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    $emit https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
    close https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1:2
[core-common.js:2:2216626](https://10.8.0.1/nextcloud/dist/core-common.js?v=b77b8767-1)

1. The same error appears when I connect to my nextcloud-instance without vpn, but with full address instead of 10.8.0.1, so vpn is not the issue
2. core-common,js is in the mentioned directory, so why the 404 error?

So it is more a Nextcloud than a Music error? And why doesn't he appear on your installation?

**Comment by paulijar** [comment]
This means that while executing `core-common.js`, the cloud internally makes some HTTP request which fails with 404, in such an occasion where it is not expected. If you check the Network tab of the developer tools, can you see the URL which failed with the 404?

The latter error "Uncaught (in promise) Error: FilePicker: No nodes selected" is something I can see too, when I close the file picker dialog without selecting anything. I believe it's just because this Nextcloud dialog doesn't handle the cancel case gracefully. However, this apparently doesn't cause any real problem.

Anyway, most likely this problem is more a Nextcloud bug than a Music bug. Maybe it also has something to do with your web server configuration as I don't see it now, although I have seen very similar problem in some older NC versions (as reported here: https://github.com/nextcloud/server/issues/42291).

**Comment by sgt-droord** [comment]
Thank you Pauli for your great work. After updating to newest version of Nextcloud, the error had disappeard magically, everything works as intended. Possibly, the upgrade-process fixes/cleans some minor db issues? Idk, but upgrading NC made everything work well again.

**Comment by heibertelf** [comment]
Hello, my fresh installation of Nextcloud Hub 8 (29.0.4) and same errors
![image](https://github.com/user-attachments/assets/c157e6de-6339-4b45-81b3-eab328cebed0)

**Comment by paulijar** [comment]
@heibertelf The error messages on your console seem a bit different although functionally the problem is similar as in the OP. Can you see from the Network tab, what is actually the URL which failed to load? It seems to be truncated on the console tab.

**Comment by paulijar** [comment]
> Same problem with Audio Player app, so agree it's a common Nextcloud bug

I believe that Audio Player uses this dialog very similarly as the Music app, so it's expected that both will always be affected by the same bugs. The Files app, on the other hand, uses the same dialog with a different API (to copy or move files), so that's another use case to test.
