### ISSUE TITLE
Error playing URL: /nextcloud/index.php/apps/music/api/file/16162/download

### ISSUE THREAD

**Issue by Schoebi** [owncloud/music#1162]
Running a local i386 with yunohost.org OS machine. 
Since some days the music doesn't play anymore with errors like: "Error playing URL: /nextcloud/index.php/apps/music/api/file/16162/download"

Podcasts and Radio Stations run properly.

I've made no updates myself, though I'm not sure if the yunohost OS made some.

Anyone an idea about this?

**Comment by paulijar** [comment]
Thanks for the report. Can you find anything from nextcloud.log after the failed attempt to play the file? Does the same file play and download correctly from the Files app?

**Comment by paulijar** [comment]
And also, can you see any more details on the console tab of the web browser development tools?

**Comment by paulijar** [comment]
With no additional info, it's impossible to investigate this any further. Closing.
