### ISSUE TITLE
Scanner only scans the rootfolder and not the subfolders

### ISSUE THREAD

**Issue by lpaauw** [owncloud/music#1170]
I have a large collection of flac files with a root folder and then artist folders and then album folders
If i try to put the rootfolder and scan it only finds 1 album

If i scan one album it goes ok but as soon as i try to scan more it can not

How can i make it possible to scan the root and all of its subfolders so it finds all my albums and not just one

**Comment by paulijar** [comment]
Are your files on some kind of external storage? In that case, ownCloud or Nextcloud may not notice automatically the existence of the files. And if the host cloud hasn't indexed the files, then the Music app can't see them.

If this is the case, then you have two alternatives to make the cloud find the files:
1. Access each folder at time in the Files app
2. Use the command line tool `occ files:scan` with appropriate parameters.
