### ISSUE TITLE
[question] which phone app for podcast ? 

### ISSUE THREAD

**Issue by potagerGit** [owncloud/music#1171]
congrats for the great NextcloudMusic App.
I use powerampache2 on my android phone to stream my songs, but unfortunatly it doesnt handle podcasts configured on NCmusic.

if possible, which Android App would you suggest to stream my NCMusic podcast on my phone ? 

thank you.

**Comment by paulijar** [comment]
At least DSub and Ultrasonic support playing podcasts. DSub has not been maintained for some years now, it looks somewhat outdated, but it still is the most feature-complete Subsonic client which I know. Ultrasonic is a bit more modern alternative but its development hasn't been very active lately, either.
