### ISSUE TITLE
Playing on speakers attached on server

### ISSUE THREAD

**Issue by dudeofx** [owncloud/music#1175]
Any chance on playing the radio on the speakers that are attached to the server. The server has speakers attached to it and would love it if I could play the radio on the server.

**Comment by paulijar** [comment]
There's no such feature in the Music app if that's what you meant. I also did a quick online search of what would it require to add such support but it looked like a can of worms which I rather wouldn't want to touch. Any anyway, it would be quite different from the current feature set of this app.

On my search, I found this project which does something similar but I didn't test it though: https://www.musicpd.org/. I don't know if it can play external (radio) streams, but maybe it could with the proper plugins.

**Comment by dudeofx** [comment]
Thanks for listening
I was thinking it required a daemon, I was curious if the engine behind NextCloud had it in it. Thus far I use cron jobs for audio reminders and ssh some scripts to play my favorite radio stations. I should look into this MusicPD 👍

**Comment by paulijar** [comment]
Closing as out-of-scope for the project
