### ISSUE TITLE
使用版本1.9.23音频amr无法获取时长

### ISSUE THREAD

**Issue by genghaifeng** [owncloud/music#1180]
![QQ20241129-094727](https://github.com/user-attachments/assets/154304af-531f-402e-8b75-41f4245d50ad)
![QQ20241129-094747](https://github.com/user-attachments/assets/ebe6f3fe-bce8-42eb-b197-f1c5c6c694c1)

**Comment by paulijar** [comment]
With no further info available, I assume this is something outside of the scope of the Music app and reported to wrong project.
