### ISSUE TITLE
No Order Albums by Artists

### ISSUE THREAD

**Issue by luishidalgoa** [owncloud/music#1185]
When we have albums that are composed by different artists or songs with different collaborators, it becomes uncomfortable to see a very extensive list of songs without being grouped together. 

It would be much better if we directly see all the songs that belong to the same album as if it were a playlist

BEFORE:
![image](https://github.com/user-attachments/assets/08dd2c36-b9f1-4610-af36-9b1f69ae53fb)

AFTER:
![image](https://github.com/user-attachments/assets/0b315ac1-0437-40b2-88b1-50faff158300)

**Comment by paulijar** [comment]
What you need to do is to add the *Album artist* tag to your songs. On compilations, you can set it e.g. as "Various artists". At the moment, you presumably have only the *Song artist* tag set, and that gets used as a fallback also for the *Album artist*. Then, the app assumes that each of the songs belong to a different album which just happens to have the same name as some other album. The album identity is defined by the pair of *Album artist* and *Album title*.

**Comment by paulijar** [comment]
Can be fixed with proper tagging and "works as specified" => closing
