### ISSUE TITLE
value too long for type character varying(64) when importing a file with multiple genres

### ISSUE THREAD

**Issue by edocod1** [owncloud/music#1186]
### Steps to reproduce
1. Import the attached file
2. Run a "Scan" task with "occ music:scan" or from the web interface

### Expected behaviour
The song is imported succesfully

### Actual behaviour

```
In ExceptionConverter.php line 87:
                                                                                        
  An exception occurred while executing a query: SQLSTATE[22001]: String data, right t  
  runcated: 7 ERROR:  value too long for type character varying(64)                     
                                                                                        

In Exception.php line 28:
                                                                                        
  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type cha  
  racter varying(64)                                                                    
                                                                                        

In Statement.php line 130:
                                                                                        
  SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type cha  
  racter varying(64)                                                                    
                                                                                        
```

### Server configuration
**Operating system**:
Debian 12

**Web server:**
Nginx

**Database:**
Postgresql 17.1

**PHP version:**
8.2

**owncloud version:**
Nextcloud 30.0.0.4

**Updated from an older ownCloud or fresh install:**
App has been just installed so i assume the tables are fresh.

**Where did you install ownCloud from:**
PHP install

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxxxxxxxxxxx"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "apc.enable_cli": 1,
        "default_phone_region": "it",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "30.0.4.1",
        "overwrite.cli.url": "https:\/\/xxxxxxxxxxxx",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance_window_start": 2,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "defaultapp": "dashboard,files"
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 4.0.3
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.8
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - collectives: 2.15.1
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - cospend: 2.0.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.2
  - external: 5.5.2
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - forms: 4.3.4
  - group_everyone: 0.1.16
  - groupfolders: 18.0.8
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - music: 2.0.1
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - registration: 2.5.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - social: 0.7.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - unroundedcorners: 1.1.4
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflow_script: 1.15.0
  - workflowengine: 2.12.0
Disabled:
  - encryption: 2.18.0
  - files_external: 1.22.0
  - suspicious_login: 8.0.0 (installed 7.0.0)
  - user_ldap: 1.21.0
```

**Are you using external storage, if yes which one:** No
**Are you using encryption:** No
**Are you using an external user-backend, if yes which one:** No

#### ownCloud log (data/owncloud.log)
```
Above
```

Download a truncated (half a second for copyright reasons) snippet of the file i use to trigger this error:
[01. Shadow Dancers.zip](https://github.com/user-attachments/files/18188693/01.Shadow.Dancers.zip)

Metadata extracted from ffmpeg:

```
Input #0, mp3, from 'Downloads/01. Shadow Dancers.mp3':
  Metadata:
    album           : The New Boss Guitar Of George Benson
    artist          : George Benson
    album_artist    : George Benson
    genre           : Jazz | Contemporary Jazz | Crossover Jazz | Smooth Jazz | Hard Bop | Fusion | Jazz Pop | Funk | Soul
    title           : Shadow Dancers
    track           : 01
    date            : 1964
  Duration: 00:04:49.20, start: 0.025056, bitrate: 3 kb/s
  Stream #0:0: Audio: mp3 (mp3float), 44100 Hz, stereo, fltp, 320 kb/s
      Metadata:
        encoder         : LAME3.99r
  Stream #0:1: Video: mjpeg (Progressive), yuvj420p(pc, bt470bg/unknown/unknown), 500x489 [SAR 1:1 DAR 500:489], 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)

```

**Comment by paulijar** [comment]
Thanks for the report. We do have a logic in place to truncate overly long fields before the DB insertion but somehow it now doesn't work as expected in this case. However, on my test setup this doesn't happen neither with MariaDB nor with PostgreSQL using the provided sample file.

I suspect that it is now something in the database configuration which explains the difference. What kind of character encoding your DB uses? You should see this with a command like
```
psql -l -U <db_user_name>
```

**Comment by edocod1** [comment]
Hello!
The server encoding is "SQL_ASCII".

**Comment by paulijar** [comment]
Okay, that explains it then, my DB uses UTF8 encoding. What happens here is that we truncate the genre to 63 characters and then append the Unicode ellipses character U+2026. When this Unicode character is added to the ASCII table, it becomes two or three characters, and the total length will exceed the column max size of 64 characters. The same problem could happen also without this special character if the genre would happen to contain any non-ASCII characters.

Now, I suspect that I might not have any easy way to detect at run time, what is the encoding configured for the DB. Hence, it would be difficult to adapt to such configuration in the application logic.

**Comment by paulijar** [comment]
That might work. However, it's quite awkward and hacky because that would need to be checked within the DB system and not in PHP. And the SQL query needed would need to be different depending on the DB management system used:
- On MariaDB, this should work `select char_length('…');`
- On SQLite, this should work `select length('…');`
- On PostgreSQL, both of the above probably work the same, or at least both return "1" on my system

**Comment by paulijar** [comment]
Btw, do you have some good reason to use ASCII encoding in your DB? UTF8 has been quite universally regarded as the "best practice" for the last decade or so.

**Comment by edocod1** [comment]
I honestly never cared about the database encoding despite always using clients that used UTF8. For some reason, SQL_ASCII is still the default in postgresql. After checking that my db contained only UTF-8 encoded special characters, i have changed the encoding to UTF8 and now everything is working fine.

The best would be to just use TEXT everywhere which is the suggested type, but I assume this will cause compatibility problems with Mysql and this is why it hasn't been used.

I'll close this since i now believe the bug was bogus in first place.
