### ISSUE TITLE
Wildcards support in Smart Playlist filter

### ISSUE THREAD

**Issue by palto42** [owncloud/music#1187]
I would like to use wildcard matches in the Smart Playlist filters for the Gerne and Artist fields.
Currently the Music app doesn't properly support multiple Genre tags so that they appear as combined strings. In my collection multiple tags are separated by different characters, e.g. `/`, `;`, `,`,  `\\`.
The iss with some artists is that they are playing with various other artists and the Music app creates different entries for each combination, so that I would need to select a lot of entries for some artists at the moment.

**Comment by paulijar** [comment]
Adding this to the Smart Playlist feature would be somewhat difficult as the UI component used for genre and artist filter supports selecting multiple pre-defined values but it doesn't allow entering any free-form text. And on the other hand, I'd like to keep this feature as streamlined and easy-to-use as possible.

For the more specialized needs, we have the Advanced search feature although I suspect that many users may not find it:
![kuva](https://github.com/user-attachments/assets/d1aef0b7-7426-4471-8df9-2b01292781ba)

There, among many other possibilities, you could make for example this kind of search:
![kuva](https://github.com/user-attachments/assets/500843c2-229e-4da2-ac2c-7fd458c8712b)

And if you are familiar with regular expressions (RegEx), you can use also them to make even more versatile queries.

And once you have your search results, you can drag the title "XX results" to "+ New Playlist" to save the results as a list.

**Comment by palto42** [comment]
Thanks for pointing me to the Advanced Search option, for now this is sufficient for me.

Would be nice if such advanced settings could be saved as a dynamic smart playlist, similar to the request in #1097, but this is a different topic, so closing here.
