### ISSUE TITLE
sorting by album artist 

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#130]
http://apps.owncloud.com/content/show.php?content=160485&forumpage=2 by cjtech

**Comment by protist** [comment]
I just installed the Music app, and was disappointed that you couldn't sort by album artist. This is my preferred way of browsing, and prevents me from using this app.

If a program can only sort by artist, it will get confused with albums by Artist A… except one track by "Artist A featuring Artist B". Or the John Lennon/Yoko Ono album "Double Fantasy", which alternates artists for each track. Or any kind of compilation.

**Comment by paulijar** [comment]
@gnarula This is another issue which is already resolved (the link in the OP is dead but I guess the title and the follow-up posts explain what this is about)
