### ISSUE TITLE
Ampache postponed queries

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#160]
Unimplemented Ampache API stuff
- [ ] url_to_song
  - url (Full Ampache URL from server, translates back into a song XML)
#### Tags
- [x] tags
  - filter (Value is Alpha Match for returned results, may be more then one letter/number)
  - exact (Boolean, if true filter is exact rather then fuzzy)
- [x] tag
  - filter (UID of tag, returns tag XML)
- [x] tag_artists
  - filter (UID of tag, returns artist XML)
- [x] tag_albums
  - filter (UID of tag, returns album XML)
- [x] tag_songs
  - filter (UID of tag, returns song XML)
#### Playlists
- [x] playlists
  - filter (Value is Alpha Match for returned results, may be more then one letter/number)
  - exact (Boolean, if true filter is exact rather then fuzzy)
- [x] playlist
  - filter (UID of playlist, returns playlist XML)
- [x] playlist_songs
  - filter (UID of Playlist, returns song XML)
#### Videos
- [ ] videos
  - filter (Value is Alpha Match for returned results, may be more then one letter/number)
  - exact (Boolean, if true filter is exact rather then fuzzy)
- [ ] video
  - filter (UID of video, returns video XML)
### Control Methods
- [ ] localplay
  - command
    - next (Advance to Next Localplay Item)
    - prev (Return to Previous Localplay Item)
    - stop (Stop Localplay Instance)
    - play (Play Localplay Instance)
- [ ] democratic
  - method
    - vote
    - oid (Unique ID of the element you want to vote on)
    - type (Type of object, only song is currently accepted so this is optional)
    - devote
    - oid (Unique ID of the element you want to vote on)
    - type (Type of object, only song is currently accepted so this is optional)
    - playlist (Returns an array of song items with an additional <vote>[VOTE COUNT]</vote> element)
    - play (Returns the URL for playing democratic play)

**Comment by paulijar** [comment]
I think it's time to close this issue. Many/most of the API features still left unticked will probably never be implemented. On the other hand, the API spec nowadays contains several unimplemented features which may be eventually implemented. But this is a moving target as the API spec is constantly being expanded.
