### ISSUE TITLE
music 0.1.9.1-rc for ownCloud 6 does not create tables on activate

### ISSUE THREAD

**Issue by burnersk** [owncloud/music#193]
Database tables will not be creates when activating music 0.1.9.1-rc on ownCloud 6.0.2 (stable). No (error) message occur on activation.

Error message after click on "music" icon in menu:

```
Fatal   index   Exception: Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT `artist`.`name`, `artist`.`image`, `artist`.`id` FROM `oc_music_artists` `artist` WHERE `artist`.`user_id` = ? ': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_music_artists' doesn't exist 
```

**Comment by paulijar** [comment]
It's unlikely that this issue is anymore valid after 3 years of inactivity. There have been almost 20 Music app releases and several ownCloud major releases since this was reported. The lowest OC version supported by Music app is nowadays 8.2 so OC 6 is way out of bounds.
