### ISSUE TITLE
Doesn't play / toolbar disappears in Chromium 33

### ISSUE THREAD

**Issue by PVince81** [owncloud/music#195]
### Steps to reproduce
1. Upload a song into a subdirectory
2. Enable music app
3. Click play

### Expected result
Toolbar appears on top and song is played

### Actual result
Tool bar appears shortly then suddenly disappears.
Song is not played

### Versions
ownCloud 7 pre-alpha (git master ab696edba685cd6d2a64c2e48907f03197aae53f)
Music app git master 504c7014871441543415ed0ed29f85522f13b6b6
Chromium  33.0.1750.117 (252094)
OS (server and client): openSUSE 13.1

### More information
This seems to be a Chrome thing, because Firefox runs fine.
Maybe the audio API isn't supported yet ?
Would be good to have an error message.

**Comment by jancborchardt** [comment]
Closing cause of inactivity.
