### ISSUE TITLE
Shuffle and repeat button issues

### ISSUE THREAD

**Issue by vgezer** [owncloud/music#204]
1. They overlap the song name
2. Cannot see if they are deactivated if one taps on them (the image remains black).

![screenshot_2014-04-08-23-02-35](https://cloud.githubusercontent.com/assets/231068/2649355/15592506-bf62-11e3-86aa-c7d64556b348.png)

**Comment by paulijar** [comment]
This age-old issue is now finally fixed in Music v1.7.0 by using two-line layout for the controls bar on narrow screens.
