### ISSUE TITLE
Can't connect with ampache client

### ISSUE THREAD

**Issue by RokPapez** [owncloud/music#213]
Configuration:
- php: 5.4
- postgresql: 9.3.4
- owncloud: 6.0.2
- music: from HEAD (also tried 0.1.9 and 0.1.9-1 )
- client: virdian

When trying to connect with ampache client i get: [Error] Authentication Failed -- Retry = 1. 
In owncloud log i get: Exception: Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT lastval()': SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR: lastval is not yet defined in this session.
In postgresql logs i get:  ,ERROR,55000,"lastval is not yet defined in this session",,,,,,"SELECT lastval()",,,""

I guess there is problem with function lastval().

Regards.

**Comment by NiklasRosenstein** [comment]
I can't get it to work at all. Got ownCloud 9.0.0 (stable), PostgreSQL and the Music App in Version 0.3.10. When I got to

    https://cloud.mydomain.com/index.php/apps/music/ampache/server/xml.server.php

I get

```xml
<root>
    <error code="401">Invalid Login</error>
</root>
```

Tomahawk shows

![screen shot 2016-03-24 at 11 16 21](https://cloud.githubusercontent.com/assets/1318438/14014274/df7a4fda-f1b1-11e5-89fe-58ef6ae5396c.png)

The URL without `server/xml.server.php` redirects to the files app.

**Comment by NiklasRosenstein** [comment]
I just found out I need to install the Ampache Plugin in Tomahawk. Though that doesn't either. Looking at the URL suggested by the plugin, I get 500 Bad Gateway. That might be related to my server configuration, but I'm unsure how to resolve it.

    https://cloud.mydomain.com/remote.php/ampache

**Comment by paulijar** [comment]
It seems that many separate issues have been discussed and solved within this github issue. Apparently, some reported problems have not been addressed but it's well possible that these have got solved during the past 4.5 years after the latest update here. If there are still Ampache problems with the latest version of the Music app, then a new issue should be raised.
