### ISSUE TITLE
Music streaming (or playlist sharing)

### ISSUE THREAD

**Issue by vgezer** [owncloud/music#216]
Another nice feature could be letting users share their playlists and use them to stream songs from their clouds to their favourite music players.

**Comment by paulijar** [comment]
I thinks this old feature request is already fulfilled by the Ampache and Subsonic APIs, both of which have support for playlists. That of course requires that your "favourite music player" has support for one of these APIs, but that's kind of inevitable: there has to be some well defined API which is supported both by the Music app and the client player.
