### ISSUE TITLE
The delete hook takes very long with increasing number of files because the album covers are regenerated on a delete

### ISSUE THREAD

**Issue by butonic** [owncloud/music#217]
Line https://github.com/owncloud/music/blob/master/businesslayer/albumbusinesslayer.php#L137 tries to find covers for an album on a _delete_. not only when A music file has been deleted but on ALL file deletes, delaying execution time.

![delete cachgrind](https://cloud.githubusercontent.com/assets/956847/2776639/703187ea-cad7-11e3-91fa-f9bc7ac10229.jpg)

@MorrisJobke this will have a very noticable impact on the sync performance. We stumbled over it because deletes took >20sec in the web ui. I assume because there is an index missing for the `getAlbumsWithoutCover()` and `findAlbumCover()` operations.

``` sql
SELECT DISTINCT `albums`.`id`, `files`.`parent`
FROM `*PREFIX*music_albums` `albums`
JOIN `*PREFIX*music_tracks` `tracks` ON `albums`.`id` = `tracks`.`album_id`
JOIN `*PREFIX*filecache` `files` ON `tracks`.`file_id` = `files`.`fileid`
WHERE `albums`.`cover_file_id` IS NULL

SELECT `fileid`, `name`
FROM `*PREFIX*filecache`
JOIN `*PREFIX*mimetypes` ON `*PREFIX*mimetypes`.`id` = `*PREFIX*filecache`.`mimetype`
WHERE `parent` = ? AND `*PREFIX*mimetypes`.`mimetype` LIKE 'image%'
```

these queries are not using indexes

cc @DeepDiver1975

**Comment by paulijar** [comment]
The issue was solved a long time ago by removing the logic to find new covers from the delete hook, and doing it in the maintenance task instead. It seems to me that also all the related indexes are nowadays in place in the DB tables of the Music app. Hence, I see no reason to keep this report open.
