### ISSUE TITLE
Follow Up BUG on PR #182

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#220]
Based on https://github.com/owncloud/music/pull/182
After upgrading to this fix based on a empty system (empty db, no local external mounts) and adding the necessary local external mounts (as described in my comment at https://github.com/owncloud/music/issues/144#), letting them scan, enabling music, letting music finished scanning, I get a new behavior:
- a new message appears in music, but nothing more happens
  ![image](https://cloud.githubusercontent.com/assets/3321281/2803807/63e29170-cca1-11e3-85d8-d674aea434e1.png)
- and a error is raised each time music is accessed: Fatal Index: Symfony\Component\Routing\Exception\MissingMandatoryParametersException: The "music_file_download" route has some missing mandatory parameters ("fileId").

(BTW: scanning music is very slow. About 10s for 50 songs)

**Comment by paulijar** [comment]
I believe that after six years of inactivity, it's safe to close this issue. A new issue should be reported if problems still persist.
