### ISSUE TITLE
Limit file size of transferred music files

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#224]
From apps.owncloud.com:

---

Hello!

Can the cache size of music files be limited?

I use the music app to listen to dumped radio streams, and the whole 100 MB is transferred...

**Comment by paulijar** [comment]
Fetching only sub-range of the played file has been supported for long time on modern browsers. It's up to the browser to decide, how large part of the file it wants to download at a time.

Another solution for the problem could be transcoding (#428).
