### ISSUE TITLE
Scanner->delete() assumes fielid to always be a file and does not handle directories

### ISSUE THREAD

**Issue by butonic** [owncloud/music#235]
https://github.com/owncloud/music/blob/master/utility/scanner.php#L270
https://github.com/owncloud/music/blob/master/businesslayer/trackbusinesslayer.php#L124 and finally https://github.com/owncloud/music/blob/master/db/trackmapper.php#L66
 assume the fileid is a single file and does not traverse directories, leaving all tracks in place when a whole folder has been deleted.

**Comment by paulijar** [comment]
I think this was fixed already last year by f0171d8863691e3. The hooks and the scanner were further improved by PR #566 and now all scenarios should be covered quite nicely with decent performance.
