### ISSUE TITLE
Scanning collection fails on umlauts/spaces in file names

### ISSUE THREAD

**Issue by Jay2k1** [owncloud/music#237]
I just installed the music app and it started scanning. However, it got stuck on scanning 153/1936. Looking at the logs, it says:

<pre>
Info    music   Rescan finished (153/1936)  2014-05-13T12:12:11+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Far/Hörsturz (CD2)/14 Bury White.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127   2014-05-13T12:12:11+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/08 Zu spät.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:11+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/05 Monsterparty.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/11 Komm zurück.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/10 1_2 Lovesong.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/07 Kopfhaut.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/01 Schrei nach liebe.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127   2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/18 Manchmal haben Frauen....mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/04 Gestern Nacht ist meine Freundin explodiert.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127 2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/09 Westerland.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127  2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/06 Hipp hipp hurra.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127 2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Unplugged_ Rock'n'Roll Realschule/19 Nie wieder.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127  2014-05-13T12:12:13+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Ab 18/06 Sweet Sweet Gwendoline.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127  2014-05-13T12:12:15+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Junge/02 Das schönste Lied der Welt.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127 2014-05-13T12:12:15+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Junge/03 Tut mir leid.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:15+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Junge/01 Junge.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127   2014-05-13T12:12:15+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Die Ärzte/Runter mit den Spendierhosen, Unbekannter!/01 Wie es geht.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:15+00:00
Error   PHP filemtime(): stat failed for /var/lib/owncloud/data/Jay2k1/files/Music/Tomte/Hörsturz (CD2)/02 Schreit Den Namen Meiner Mutter.mp3 at /var/www/owncloud/lib/private/files/storage/local.php#127    2014-05-13T12:12:15+00:00
Info    music   Rescan triggered </pre>

This block repeats every one or two seconds. This causes some load on the server. Also, hovering the mouse over an album's play button makes that button flicker every one or two seconds, maybe that has the same cause. This "refresh mechanism" also makes me unable to scroll down in the music list because I'm constantly being thrown back to the top.

**Comment by paulijar** [comment]
@Jay2k1 @bence8810 This report is very old and it seems likely that the issue has got fixed at one point or another, taking into account how much has changed since this report was filed. Do you still see the issue on recent Music app and ownCloud (or Nextcloud) versions?

**Comment by paulijar** [comment]
Umlauts and spaces in file names have always worked fine for me. As there has been no replies for 5 months either, I thinks it's safe to close this issue.
