### ISSUE TITLE
Library scanning and Browser related issue

### ISSUE THREAD

**Issue by ApolloLV** [owncloud/music#240]
Scanning a Library of several thousand songs takes a giant amount of time (several hours, possibly days for my 25.000 song library). Also, the scan process causes my Firefox 27 to become unresponsive about every 30 seconds. (I don't know if those two issues are related). There really is no reason why scanning should be so slow on that hardware (still at 1825 songs after about an hour of indexing, and right now, it is advancing at about 1 song per minute). This is a major usability issue and needs to be adressed as soon as possible.
Background info: 
Client: Firefox 27 on Ubuntu 14.04 LTS
Server: Dedicated Server, 8 cores, 32 GB RAM, Ubuntu 14.04 , Apache 2.4.7, PHP 5.5.9-1ubuntu4, MySQL 5.5.37-0ubuntu0.14.04.1, Owncloud 6, Music 0.2 (right from apps.owncloud.com)

**Comment by paulijar** [comment]
The PR #564 improving the performance especially with large collections was merged yesterday. If you are willing to test with development version, I would be interested to hear how it works now with large real-life music collections and what is the practical collection size limit for usability. I would recommend using Chrome browser with large music collections.

I assume that after the PR, 10k songs should be still usable. 25k and 40k libraries mentioned in this report may still be more than the app can handle.

**Comment by paulijar** [comment]
The Music app version 0.4.1 containing #564 has been released to ownCloud marketplace and Nextcloud app store. There's always room for improvement on performance, but IMHO, the app is now quite usable at least with several thousands of tracks. I believe that scanning no longer takes days or causes browser unresponsiveness even for tens of thousands of tracks like the OP reported. Feel free to reopen if this is still the case.
