### ISSUE TITLE
ID3v2 tags are ignored

### ISSUE THREAD

**Issue by GitHubGeek** [owncloud/music#251]
If a music file contains both v1 and v2 tags, the scanner should prefer v2 tags.

**Comment by paulijar** [comment]
We use the getID3 library to extract the tags from audio files. If the track has both ID3v1 and ID3v2 tags, the library tries to select the one with more complete data. IMHO this heuristics works nowadays quite well (and definitely better than in 2014 when this issue was reported). Closing.
