### ISSUE TITLE
the music app slows down file deletion

### ISSUE THREAD

**Issue by sezuan** [owncloud/music#252]
I noticed that the music app slows down file deletion. Without the music app it needs few milliseconds, with the music app it needs more than 8 seconds.

It seems to happen during the post delete hook in:

```
    public function findCovers(){
            $albums = $this->mapper->getAlbumsWithoutCover();
            foreach ($albums as $album) {
                    $this->mapper->findAlbumCover($album['albumId'], $album['parentFolderId']);
            }
    }
```

The search for new album cover is, at least with my owncloud setup, pretty slow.

A quick and dirty solution might be to check the path in the *_hooks against the configured music path of the affected account, bu maybe this can cause some issues with shared files?

**Comment by paulijar** [comment]
This seems to have been fixed a long time ago.
