### ISSUE TITLE
Owncloud stops playing after the first song

### ISSUE THREAD

**Issue by tsikerdekis** [owncloud/music#255]
### Steps to reproduce
1. Install tomahawk or amarok on Windows 8
2. install owncloud on ubuntu 13.10
3. Add some song on the playlist and hit play
4. Let the first song end and once it ends all other songs dont play even if clicked.
### Expected behaviour

Songs should play.
### Actual behaviour

Subsequent songs don't play.
### Server configuration

**Operating system**:  Ubuntu 13.10

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.3

**ownCloud version:** (see ownCloud admin page) ownCloud 5.0.12+dfsg-1ubuntu1~saucy1 (Debian)

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Music, calendar

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '53a9f616e28fb',
  'passwordsalt' => '*** Removed for security reasons',
  'datadirectory' => '/media/michael/fd258dca-71c2-4c82-89fe-c6634b3c0dd3/owncloud',
  'dbtype' => 'mysql',
  'version' => '5.0.22',
  'appstoreenabled' => false,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dsadad',
  'dbpassword' => '*** Removed for security reasons',
  'installed' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
);

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes/no
don't know
### Client configuration

**Browser:** Chrome

**Operating system:** Windows 8
#### Web server error log

```
25.191.160.155 - - [27/Jul/2014:18:29:01 -0400] "GET /owncloud/remote.php/ampache//server/xml.server.php?filter=Serpents%20In%20Paradise&limit=10&action=search_songs&auth=a55ebbd8c3cfe33425c605a22990994cbf8b4275ae8a11c3cbedb08c8ca4f2d1& HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/534.34 (KHTML, like Gecko)  Safari/534.34"
[Sun Jul 27 18:24:10.321098 2014] [:error] [pid 12067] [client 25.191.160.155:53434] PHP Fatal error:  Class 'Zend_Search_Lucene_Document' not found in /usr/share/owncloud/apps/search_lucene/lib/indexer.php on line 68, referer: http://25.154.83.39/owncloud/
[Sun Jul 27 18:24:14.511831 2014] [:error] [pid 12267] [client 25.191.160.155:53433] PHP Fatal error:  Class 'Zend_Search_Lucene_Document' not found in /usr/share/owncloud/apps/search_lucene/lib/indexer.php on line 68, referer: http://25.154.83.39/owncloud/index.php/apps/files
[Sun Jul 27 18:24:17.826836 2014] [access_compat:error] [pid 12067] [client 25.154.83.39:38193] AH01797: client denied by server configuration: /usr/share/owncloud/data/htaccesstest.txt
[Sun Jul 27 18:24:18.861794 2014] [:error] [pid 12070] [client 25.191.160.155:53431] PHP Fatal error:  Class 'Zend_Search_Lucene_Document' not found in /usr/share/owncloud/apps/search_lucene/lib/indexer.php on line 68, referer: http://25.154.83.39/owncloud/index.php/settings/admin



#### ownCloud log (data/owncloud.log)
empty log
```

**Comment by paulijar** [comment]
Not reproduced with Tomahawk 0.8.4 on Windows 10 and Music 0.4.1 on Nextcloud 12. I assume this has got fixed at some point.
