### ISSUE TITLE
Album Covers not displaying in OC7 / Header Error

### ISSUE THREAD

**Issue by mediakontor** [owncloud/music#257]
Hello!
I Know this topic is well discussed but is there a solution for this right now?
I installed Music app from latest git-repo but no album covers are shown. Owncloud is installed on ubuntu 12.04 as version 7.0.0
Can anyone give a advice?

![bildschirmfoto 2014-07-31 um 17 27 51](https://cloud.githubusercontent.com/assets/8321542/3766703/4849139a-18c7-11e4-971d-ae10a30c4b37.png)

I also recognize that the log file turns over with the following error while using music app:

Error    PHP     Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#65     2014-07-31T15:19:01+00:00
Error    PHP     Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#61     2014-07-31T15:19:01+00:00
Error    PHP     Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#61     2014-07-31T15:19:01+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#57 2014-07-31T15:19:01+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#65 2014-07-31T15:18:14+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#61 2014-07-31T15:18:14+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#61 2014-07-31T15:18:14+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#57 2014-07-31T15:18:14+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#65 2014-07-31T15:16:47+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#61 2014-07-31T15:16:47+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#61 2014-07-31T15:16:47+00:00
Error   PHP Cannot modify header information - headers already sent at /var/www/owncloud/apps/music/appframework/app.php#57 2014-07-31T15:16:47+00:00

Any help is very appreciated!

Regards
Andreas

**Comment by jancborchardt** [comment]
Doesn’t work for me either. Doesn’t pick up any jpg in the folders, not even the `cover.jpg`. @MorrisJobke ?

**Comment by sorglos** [comment]
It works with cover.jpg and cover.png within the folders, but not with pictures in the tags.

**Comment by paulijar** [comment]
The embedded cover art support was added in PR #512 and has worked properly since #550. The Music app can also use an image file from the folder of the audio file as cover art if there is no embedded art available. Closing.
