### ISSUE TITLE
Unable to use Ampache with Tomahawk

### ISSUE THREAD

**Issue by Fly0s** [owncloud/music#265]
Hi !

I posted on https://github.com/owncloud/music/pull/91 , but since the bug is closed, I'm afraid nobody read that ! ;)

Using my login and a generated password for the ampache API, I can't use the Ampache Resolver in Tomahawk. The log says :
"Failed to do GET request: to: https://my.server.net/owncloud/index.php/apps/music/ampache/server/xml.server.php?timestamp=1399496300&version=350001&user=XXX&action=handshake&auth=0e1cad6824fb90bf84278a08a0dff5103e499196f41526424cd2a3d017901bfb&"
"Status Code was: 0"
(I blurred out the login and changed the server name...)

Any idea why ? Tested with Owncloud 7.0.1 and Music app 0.3. It works with Ampache.NET on Android.

Cheers !

**Comment by rseek** [comment]
Hi!
same problem with:
- tomahawk 0.8.4-0ubuntu5~ppa13~ubuntu14.04.1
- Music 0.3.8

**Comment by paulijar** [comment]
Tomahawk has been abandoned by its developers. For me, Tomahawk has always been able to connect the Music app, but its Ampache-plugin seems to be rather bugged. Hence, it can't be recommended for anyone as an Ampache client, and there's little hope for the situation to ever get better. I see no reason to keep this 6-year old issue open any more.
