### ISSUE TITLE
Spinner never stops spinning

### ISSUE THREAD

**Issue by enoch85** [owncloud/music#267]
### Video

http://youtu.be/wJJmeBD4DEg
### Expected Behavior

Spinner should only be visable when it loads
### Actual Behavior

Spinner never stops spinning
### Steps to reproduce

Just open the music app.
### Server information

Ubuntu 12.04
Owncloud 7.0.1
Music app v 0.3
### Browser

Chrome (latest)

@MorrisJobke

**Comment by paulijar** [comment]
This has most likely got fixed at latest by the scalability fixes released in v0.4.0. At least I haven't seen this even when testing with a test library of 58k tracks. Hence, closing.
