### ISSUE TITLE
Artist and Album set to unknown

### ISSUE THREAD

**Issue by rheylens** [owncloud/music#273]
Hello i try the database reset in my sql database but it didn't work

**Comment by paulijar** [comment]
@rheylens @Stef3478 @nerdy-sam @cirriform This issue is very old and I assume it has probably got fixed by now. Is anyone of you still facing the problem on recent Music app versions (latest is currently v0.5.5)?

**Comment by paulijar** [comment]
After 5 months with no replies, I think it's safe to close this issue.
