### ISSUE TITLE
Ampache on iOS - AmpacheX

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#274]
https://github.com/owncloud/music/issues/60#issuecomment-52874804

**Comment by RyanCopley** [comment]
Odd, I never got emails for this. Fortunately a google search brought it up. @MorrisJobke - I just released version 3.0.0, as long as your mimic'd API keeps the same API key authentication everything should work fine. I believe there was a discrepancy between how the API key is managed between OwnCloud and Ampache.

**Comment by bence8810** [comment]
@RyanCopley do you still have access to my server? Just tried and it didn't work for me but it was such a long time ago that I might have forgotten how to go about it.

Ben

**Comment by RyanCopley** [comment]
Nope

**Comment by bence8810** [comment]
@RyanCopley please check your email. Just given you access.

Thanks,
Ben
