### ISSUE TITLE
How am I supposed to use OC music?

### ISSUE THREAD

**Issue by tanuva** [owncloud/music#288]
_What I expected_: "Owncloud Music" (OCM) is a music addon that does similar things as the "music"-portion of older Owncloud versions with additional Ampache API support. Therefore, I can use an Ampache compatible client to listen to music stored in my OC instance.

_What I found_: After installing OCM, the music tab was there as expected, it even plays _some_ of the mp3s I threw into OC. Don't know why some are played and some aren't, there are no error messages in OC's own log on the settings page.

Then I had a look at the README.md and found this:

```
In the settings the URL you need form Ampache is listed and looks like this:

https://cloud.domain.org/index.php/apps/music/ampache/

This is the common path. Some clients append the last part (`server/xml.server.php`) automatically. If you have connection problems try the longer version of the URL with the `server/xml.server.php` appended.
```

First, I ignored the ambigous "form" describing the URL and just dropped it into various Ampache clients as the second paragraph suggests, expecting OCM to mimic the Ampache API. That didn't work - clients just tell me they cannot connect. Manually requesting that `xml.server.php` in a browser led to an XML error message about missing login credentials. So there is something responding, just the clients don't seem to speak the same language.

Second, I disambiguated the "form" to "from" or "for" and guessed I might additionally need an Ampache instance that uses OCM as storage backend and provides the API for clients. Dropping the same URL (with and without the "last part" in both cases) into Ampache as a "remote collection" just made Ampache tell me it couldn't connect.

Now I found some people here in the issues talk about "generated Ampache API credentials" they used to connect. That also suggests a separate Ampache instance really is required. So my questions are:
1. How is OCM supposed to fit in between Owncloud, Ampache and my Ampache client?
2. Depending on the first answer, what might I be missing here?
3. Where/how could I retrieve useful error messages? Apache log and OC log weren't that informative yet.
4. Probably a separate issue: Why are some mp3s not played?

Owncloud 7.0.2 (from official repository, fresh installation, no external storage, no encryption)
Music 0.3.4 - no other apps except defaults
MySQL database
PHP 5.5.9+dfsg-1ubuntu4.4
on a fresh installation of Ubuntu 14.04

Clients: Safari 7.0.6 / Chrome 37.0.2062.122

**Comment by paulijar** [comment]
As I see it, the only real issue in this report is that some MP3 files do not play. This is reported also in #404 and is no longer a problem in Chrome, Firefox, IE, or Edge. The problem persists in browsers with no built-in mp3 codec like Chromium. Anyway, I think it is enough to have one open issue for the mp3-playback problem.
