### ISSUE TITLE
CD number tag is ignored

### ISSUE THREAD

**Issue by tanuva** [owncloud/music#291]
I have an album that consists of three discs and each of them starts track numbers at 1. Now I get the following order in the music app:
1. 1-01
2. 2-01
3. 3-01
4. 1-02
5. 2-02

instead of
1. 1-01
2. 1-02
3. 2-01
4. 2-02
5. 3-01

**Comment by paulijar** [comment]
The disc number issue has been addressed some 6 months ago in #508 and #521. The UI now shows each disc of a multi-disc album as a separate album entry. This is far from perfect but at least the disc tag is no longer ignored. Closing.
