### ISSUE TITLE
0.3.4 not playing mp3's in web interface

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/music#297]
0.3.3 used to play my music in the web interface but now 0.3.4 just says 'Loading...' for all my songs.
I'm using OC 7.0.2 and there are no error's logged in my admin panel.
Connecting with Tomahawk works and plays my music.

What happened between these versions?
I've tried using Chrome and IE 11.

Some settings in my config:

```
  'appstoreenabled' => false,
  'updatechecker' => false,
  'check_for_working_webdav' => false,
  'check_for_working_htaccess' => false,
  'xframe_restriction' => true,
  'enable_previews' => true,
  'filesystem_check_changes' => 1,
  'loglevel' => '1',
```

**Comment by nodiscc** [comment]
@MorrisJobke ping, any update on this? I've just hit this bug on Firefox. What needs to be done?

**Comment by FoxGit** [comment]
Similar Problem here: the music is not playing but I don't get any error :?
Last thing I see in the web debugger is the HEAD request for the mp3 file. The URL is correct as the file is played just fine when I enter the URL directly in the browser. Why is the request a HEAD request? I mean, I am missing the actual GET to well get the data ;) I am more than happy to helpo debugging but don't really know where to start. :( Can't find anything interesting in the owncloud log :/

**Comment by nodiscc** [comment]
https://github.com/Sonerezh/sonerezh is a nice workaround

**Comment by MU7L3Y** [comment]
@MorrisJobke I've tried 0.3.5 in 7.0.4 and still not playing... :(

**Comment by MU7L3Y** [comment]
not working in 7.0.5 either..

**Comment by MU7L3Y** [comment]
0.3.5 not working in 8.0.3 either. It tries to load but the bar never loads fully and just says "Loading....."

**Comment by MU7L3Y** [comment]
@MorrisJobke I still haven't been able to get this working. I've was using 0.3.7 and owncloud 8.2.0 and I had this error when upgrading to 8.2.1. It also disabled the music app.
```
Error   core    Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"music.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/route\/router.php(314): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('music.page.inde...', Array, false)\n#1 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/route\/cachingrouter.php(53): OC\\Route\\Router->generate('music.page.inde...', Array, false)\n#2 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/urlgenerator.php(65): OC\\Route\\CachingRouter->generate('music.page.inde...', Array)\n#3 \/home\/REMOVED\/public_html\/cloud\/apps\/music\/appinfo\/app.php(26): OC\\URLGenerator->linkToRoute('music.page.inde...')\n#4 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/app.php(160): require_once('\/home\/REMOVED\/...')\n#5 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/app.php(141): OC_App::requireAppFile('music')\n#6 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/app.php(1171): OC_App::loadApp('music', false)\n#7 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/installer.php(219): OC_App::updateApp('music')\n#8 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/installer.php(249): OC_Installer::updateApp(Array)\n#9 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/updater.php(509): OC_Installer::updateAppByOCSId('164319')\n#10 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/updater.php(323): OC\\Updater->upgradeAppStoreApps(Array)\n#11 \/home\/REMOVED\/public_html\/cloud\/lib\/private\/updater.php(205): OC\\Updater->doUpgrade('8.2.1.4', '8.2.0.12')\n#12 \/home\/REMOVED\/public_html\/cloud\/core\/ajax\/update.php(111): OC\\Updater->upgrade()\n#13 {main}","File":"\/home\/REMOVED\/public_html\/cloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}
```
I then upgraded to 0.3.8 and manually enabled the app in the database since the UI doesn't load any apps for me (another problem). I then try to play some music and it tries to load but the loading bar doesn't complete. In the admin panel I get this error repeatedly:
```
Error	PHP	Cannot modify header information - headers already sent by (output started at /home/REMOVED/public_html/cloud/3rdparty/sabre/http/lib/Sapi.php:70) at /home/REMOVED/public_html/cloud/3rdparty/sabre/http/lib/Sapi.php#63
Error	PHP	Cannot modify header information - headers already sent by (output started at /home/REMOVED/public_html/cloud/3rdparty/sabre/http/lib/Sapi.php:70) at /home/REMOVED/public_html/cloud/3rdparty/sabre/http/lib/Sapi.php#58
```

**Comment by MU7L3Y** [comment]
@MorrisJobke I am still having trouble playing music in a browser. I just upgraded to 9.0.2 and installed music 0.3.11 and the play bar at the top just says loading as it only loads maybe 90-95% of the bar. I get no logs in owncloud.

I do however get this when inspecting the page:
```aurora.js?v=a536897…:890Uncaught UnderflowError
Failed to parse SourceMap: http://mutleyproductions.com/cloud/apps/music/js/vendor/angular-route/angular-route.min.js.map
Failed to parse SourceMap: http://mutleyproductions.com/cloud/apps/music/js/vendor/aurora/aurora.js.map
Failed to parse SourceMap: http://mutleyproductions.com/cloud/apps/music/js/vendor/angular/angular.min.js.map
Failed to parse SourceMap: http://mutleyproductions.com/cloud/apps/music/js/vendor/aurora/mp3.js.map
Failed to parse SourceMap: http://mutleyproductions.com/cloud/apps/music/js/vendor/aurora/flac.js.map
```

**Comment by gnarula** [comment]
I managed to reproduced this for one file in my collection and I think this is related to Aurora.js failing to decode files if the chunk size is small. Unfortunately there is no fix available for it yet upstream.

#535 was merged recently and it defaults to using SoundManager2 for mp3 files on all browsers except Chromium. I think that's the only way to avoid this bug for now. @MU7L3Y could you please check the music app on `master`, on a browser like say, Chrome or Firefox and comment if it still persists? The file I managed to reproduce the issue against works with SoundManager2.

**Comment by MU7L3Y** [comment]
@gnarula I just uploaded the master and I am playing songs successfully in Chrome. Finally!

**Comment by paulijar** [comment]
Using SoundManager2 fixes the issue for most browsers. The problem with Aurora.js remains to be an issue on Chromium (at least), but it is reported also in #404. Hence, I'm closing this issue.
