### ISSUE TITLE
WebDAV fails to load filename with URL encoded strings

### ISSUE THREAD

**Issue by pellaeon** [owncloud/music#299]
For example, a file named `Sample_of_%22Another_Day_in_Paradise%22.ogg` on disk, when trying to load the file via WebDAV, the actual request sent is
`HEAD /remote.php/webdav/Music/Sample_of_%22Another_Day_in_Paradise%22.ogg`, but I think the WebDAV module will just decode the `%22` to `"`, mismatching the actual filename on disk, causing a `404`.

Filename with URL encoded strings often comes from the "add from link" feature in Files app.

@MorrisJobke by the way, I think this problem might also exist in other apps which use WebDAV to retrieve files, do you know what other apps that do so?

**Comment by pellaeon** [comment]
@paulijar Thanks 😄

**Comment by paulijar** [comment]
The fix has now been released in the v0.5.5.
