### ISSUE TITLE
Rescan music files from web interface

### ISSUE THREAD

**Issue by 5punk** [owncloud/music#302]
I have a shared web hosting, so I do not get access to the system terminal to run ./occ commands.
After adding new music files, is there a way to refresh or rescan for new music files?

**Comment by paulijar** [comment]
Button to clear the music collection has been added to the Settings view of the app. This enables rescanning via web UI as originally requested. If the problem of scanning gettings stuck is still valid, then that should be reported as a new issue.

**Comment by paulijar** [comment]
Music app version 0.7.0 including this enhancement has been released today.
