### ISSUE TITLE
Bar at the slider on the right side "vanishes" when moving to top

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#303]
Ubuntu 14.04, mysql, oc 8 beta, git pull from today

When you have your music library listed, you have the slider on the right to scroll up and down.
The bad thing is, that the bar does not start at the hight of "A" but at the top end, which is unfortunately under the level of the 3/4 circle. To get the bar visible, you must click more often on a empty space in the slider below so it will move down and can be used to grab it with the mouse.

bar full visible but not on top
![image](https://cloud.githubusercontent.com/assets/3321281/4679872/e8dc8488-5605-11e4-8737-85597c4325f3.png) 

bar starts to "vanish" whan moving up
![image](https://cloud.githubusercontent.com/assets/3321281/4680069/9e30df0e-5607-11e4-9d05-a124371aa7ee.png)

**Comment by paulijar** [comment]
This is duplicated by #360.
