### ISSUE TITLE
getID3 error message: $frame_size (154000) > strlen($framedata)

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#304]
Ubuntu 14.04, mysql, git 8 pre alpha, external storage (local mount), no encryption

Music started to scan the list, when finished (whhoooaa, >5000 titles, boring slow) I saw many of the following debug messages in the log:

Debug	music	getID3 error message: error parsing "PIC" (510 bytes into the ID3v2.2 tag). (ERROR: $frame_size (154000) > strlen($framedata) (null)).

**Comment by paulijar** [comment]
This is most definitely caused by the issue explained in #518.
