### ISSUE TITLE
GET (...)/owncloud/index.php/apps/music/api/collection 500 (Internal Server Error)

### ISSUE THREAD

**Issue by GerardGarcia** [owncloud/music#306]
Music app just stopped working. Chrome developer tools says:

GET (...)/owncloud/index.php/apps/music/api/collection 500 (Internal Server Error)

If I access directly to the URL /owncloud/index.php/apps/music/api/collection it seems to work (it just shows one file but I don't know if this is normal)

Using owncloud 7.0.2 and latest music from git repo.

**Comment by paulijar** [comment]
I believe the significant part of the commit 49b166d mentioned above are the changes to method Track.toCollection. After those changes, loading the collection.json fails with 500 if the collection contains even single dangling track reference to a file which is no longer available for the user. Such references could occur e.g. in scenario described in #567. The toCollection method was changed again as part of #564 and now the dangling references no longer break the loading of collection.json. Hence, this issue should be fixed for the latest release and can be closed.
