### ISSUE TITLE
Don't use the year as a separator for albums

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/music#307]
### Steps to reproduce

I have albums where the songs have been made in different years.
### Expected behaviour

I don't think it's relevant to use the year as a important data for album separation (and it's the first time I see a music software doing it actually).
A solution for album with songs with different years might be to display the year range (e.g. 2004-2013).
### Actual behaviour

I have 3 albums with the same name just because the year is different.
### Server configuration

**Operating system**: Debian 7.5 (GNU/Linux)

**Web server:** Nginx 1.2

**Database:** MySQL 5.5

**PHP version:** PHP 5.4

**ownCloud version:** 7.0.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Default apps, Music 0.3.4

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains =>
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword => 'xxx',
  'installed' => true,
  'loglevel' => '0',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
### Client configuration

**Browser:** Firefox 33

**Operating system:** GNU/Linux (Archlinux), Windows 7
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by paulijar** [comment]
This is a duplicate for issue #279.

**Comment by radoeka** [comment]
Thanks.
