### ISSUE TITLE
UI problems with the "href" links

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/music#308]
### Steps to reproduce

I think there are a few problem with the links to play songs:
- On big screens, the whole clickable line is very confusing. You often get to click somewhere it seems empty but it starts to play all the musics from the random artist you clicked on.
- If you put your cursor on the album's name, the cursor doesn't change (but on the blank part after, it changes). Nonetheless if you click, it'll start the playing.
- Same goes for "Show all ## songs ..." / "Show less ...", the cursor doesn't change, but around the text does change, and in any cases it expands/collapses the songs list.
### Expected behaviour

Prevent whole blank lines to trigger songs playback.
Have the proper cursor icon on everything that triggers something.
### Actual behaviour

I often click somewhere I think it won't do anything, but instead it starts to play a song.
### Server configuration

**Operating system**: Debian 7.5 (GNU/Linux)

**Web server:** Nginx 1.2

**Database:** MySQL 5.5

**PHP version:** PHP 5.4

**ownCloud version:** 7.0.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Default apps, Music 0.3.4

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains =>
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword => 'xxx',
  'installed' => true,
  'loglevel' => '0',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
### Client configuration

**Browser:** Firefox 33

**Operating system:** GNU/Linux (Archlinux), Windows 7
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by paulijar** [comment]
The issues mentioned in the second and third bullet of the OP were fixed in #522.
