### ISSUE TITLE
Bug: trying to allocate too much memory when reading flac tags.

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/music#309]
### Steps to reproduce

Having this FLAC file I have. I can share it for the test if needed.
### Expected behaviour

No error. ID3 tag recognized fine.
### Actual behaviour

Error trying to allocate more than 3GB of memory, just for the ID3 tags. Here is the log:

```
Error   PHP     Allowed memory size of 134217728 bytes exhausted (tried to allocate 3073586277 bytes)   2014-11-11T15:45:27+00:00
                at /var/www/owncloud/3rdparty/james-heinrich/getid3/getid3/getid3.php#1671
Debug   music   update - mimetype audio/flac                                                            2014-11-11T15:45:27+00:00
Debug   music   update - /creak/files/music/Die Antwoord/Ten$ion/07 - So What_.flac                     2014-11-11T15:45:27+00:00
Info    music   Rescan triggered                                                                        2014-11-11T15:45:26+00:00
```

Infinite scanning message: "Scanning ... 263/264".
### Server configuration

**Operating system**: Debian 7.5 (GNU/Linux)

**Web server:** Nginx 1.2

**Database:** MySQL 5.5

**PHP version:** PHP 5.4

**ownCloud version:** 7.0.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Default apps, Music 0.3.4

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains =>
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword => 'xxx',
  'installed' => true,
  'loglevel' => '0',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
### Client configuration

**Browser:** Firefox 33

**Operating system:** GNU/Linux (Archlinux), Windows 7
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by paulijar** [comment]
@MightyCreak This issue is nearly 3 years old. Are you still facing the problem with recent versions of the Music app or could this be closed?

**Comment by MightyCreak** [comment]
It can be closed, I don't use this app anymore :/
