### ISSUE TITLE
Bug: ID3 tags failed on OGG and FLAC songs

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/music#310]
### Steps to reproduce
1. Add albums in OGG and/or FLAC formats.
### Expected behaviour

Artists and albums tags should be recognized.
### Actual behaviour

All my FLAC and OGG songs are referenced under "Unknown artist", "Unknown album". But the songs names are correct.
### Server configuration

**Operating system**: Debian 7.5 (GNU/Linux)

**Web server:** Nginx 1.2

**Database:** MySQL 5.5

**PHP version:** PHP 5.4

**ownCloud version:** 7.0.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Default apps, Music 0.3.4

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'trusted_domains =>
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword => 'xxx',
  'installed' => true,
  'loglevel' => '0',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
### Client configuration

**Browser:** Firefox 33

**Operating system:** GNU/Linux (Archlinux), Windows 7
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by paulijar** [comment]
Tested on Music 0.4.3. Artist name, album name, and track title tags were extracted correctly from both OGG and FLAC files. I assume that this has got fixed at some point.
