### ISSUE TITLE
Picture in Tags

### ISSUE THREAD

**Issue by hitam4450** [owncloud/music#312]
I tagged all my Mp3's incl. a picture of the album associated. However, starting the apps, the picture does not show up. In case i copy the associated jpeg file  to EACH directory, only in this case I see the picture of the album. I do have a huge MP3 library and I do not want to copa ALL album pictures to each subdirectory.

Please fix the issue!

Many, many thanks in advance

regqrds, hitam4450!

**Comment by luckydonald** [comment]
Maybe just use OC8's Preview? I noticed, in fileview there is the image already displayed.

**Comment by MorrisJobke** [comment]
@luckydonald This could be the way to go. Back in time, when I implemented this, the preview wasn't available yet.

**Comment by paulijar** [comment]
This was implemented in #512 and improved with #547 and #550.
