### ISSUE TITLE
Music path setting not used

### ISSUE THREAD

**Issue by morsik** [owncloud/music#323]
1. Go to "<username>" → "Personal" (user settings).
2. Change Music path to something else (labeled: "This setting specifies the folder which will be scanned for music.")
3. Rescan library.
4. ...
5. Scanned everything again.

**Comment by paulijar** [comment]
I don't believe this 2 years old bug is any longer reproducible, at least I haven't ever seen it although I have changed the path setting several times. Please reopen if still valid.
