### ISSUE TITLE
Music app fatal error

### ISSUE THREAD

**Issue by vgezer** [owncloud/music#327]
I cannot make music app run due to md5.js

```
Fatal error: Uncaught exception 'Exception' with message 'js file not found: script:js/md5/md5.min serverroot:/var/www/owncloud' in /var/www/owncloud/lib/private/template/resourcelocator.php:46 Stack trace: #0 /var/www/owncloud/lib/private/templatelayout.php(152): OC\Template\ResourceLocator->find(Array) #1 /var/www/owncloud/lib/private/templatelayout.php(103): OC_TemplateLayout::findJavascriptFiles(Array) #2 /var/www/owncloud/lib/private/template.php(118): OC_TemplateLayout->__construct('error', '') #3 /var/www/owncloud/lib/private/template/base.php(103): OC_Template->fetchPage() #4 /var/www/owncloud/lib/private/template.php(227): OC\Template\Base->printPage() #5 [internal function]: OC_Template::printExceptionErrorPage(Object(Exception)) #6 {main} thrown in /var/www/owncloud/lib/private/template/resourcelocator.php on line 46
```

@MorrisJobke can you guide me so that I can fix it?

Thanks.

**Comment by HeisSpiter** [comment]
I'm sorry to revive this issue, but it appears that this issue still happens. I've just updated my local ownCloud instance to 8.0.1-1 from 8.0.0-9. It's installed using the owncloud packages for Debian provided by owncloud.org.
The music app is now failing with such error. When attempting to access it, I only get a blank page, while log displays:
> Error 	PHP 	js file not found: script:js/md5/md5.min serverroot:/var/www/owncloud at /var/www/owncloud/lib/private/template/resourcelocator.php#46 	2015-03-05T09:21:13+00:00

> Fatal 	index 	Exception: {"Message":"js file not found: script:js\/md5\/md5.min serverroot:\/var\/www\/owncloud","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/templatelayout.php(156): OC\\Template\\ResourceLocator->find(Array)\n#1 \/var\/www\/owncloud\/lib\/private\/templatelayout.php(107): OC_TemplateLayout::findJavascriptFiles(Array)\n#2 \/var\/www\/owncloud\/lib\/private\/template.php(118): OC_TemplateLayout->__construct('user', 'music')\n#3 \/var\/www\/owncloud\/apps\/music\/appframework\/http\/templateresponse.php(124): OC_Template->fetchPage()\n#4 \/var\/www\/owncloud\/apps\/music\/appframework\/http\/dispatcher.php(85): OCA\\Music\\AppFramework\\Http\\TemplateResponse->render()\n#5 \/var\/www\/owncloud\/apps\/music\/appframework\/app.php(54): OCA\\Music\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\PageController), 'index')\n#6 \/var\/www\/owncloud\/apps\/music\/appinfo\/routes.php(36): OCA\\Music\\AppFramework\\App::main('PageController', 'index', Array, Object(OCA\\Music\\DependencyInjection\\DIContainer))\n#7 [internal function]: OC\\Route\\Router->OCA\\Music\\{closure}(Array)\n#8 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(Closure), Array)\n#9 \/var\/www\/owncloud\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/music\/')\n#10 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#11 {main}","File":"\/var\/www\/owncloud\/lib\/private\/template\/resourcelocator.php","Line":46} 	2015-03-05T09:21:13+00:00

> Error 	PHP 	Only variables should be passed by reference at /var/www/owncloud/lib/private/cache/fileglobalgc.php#50

**Comment by MorrisJobke** [comment]
@HeisSpiter Which version of the music app do you use? The lastest version should fix that. (0.3.5)

**Comment by HeisSpiter** [comment]
Yes, indeed. I updated it and it fixed the issue. I thought the music app was included in the Debian packages.
I'm sorry for the noise.
