### ISSUE TITLE
Error "Class 'OC_Filesystem' not found" when importing files

### ISSUE THREAD

**Issue by qirtaiba** [owncloud/music#328]
I am importing a large directory of music files, and the import script chokes at a certain point with this error:

`PHP Fatal error:  Class 'OC_Filesystem' not found in /var/www/owncloud/apps/music/appframework/core/api.php on line 400`

I then move the offending file out and start the script again and it then chokes on another file.  I uploaded some of the files on which ownCloud choked at https://www.malcolm.id.au/files/music/oc-failed-mp3.zip.

**Comment by qirtaiba** [comment]
I've worked around this bug by rewriting the ID3 tags of the offending files. (At least I think that was what fixed it. I also noticed that cron hadn't been running, in case that made a difference.)

**Comment by RealRancor** [comment]
@qirtaiba @synappsis 
Seems you're using the old and outdated version 0.2 of the music app:

https://github.com/owncloud/music/tree/v0.2/appframework/core

Newer versions like 0.3.4 (for OC6) and 0.3.5 (for OC7+) don't have this file:

https://github.com/owncloud/music/tree/v0.3.4/appframework/core
https://github.com/owncloud/music/tree/v0.3.5/appframework/core

**Comment by blizzz** [comment]
Closing as fixed based on @RealRancor 's input https://github.com/owncloud/music/issues/328#issuecomment-85194464 (and no further activity)
