### ISSUE TITLE
Add subsonic API

### ISSUE THREAD

**Issue by vinilox** [owncloud/music#329]
Supporting this API will allow more users to use more apps with ownCloud music  == more potential users.
Here is an old owncloud app supporting this API https://github.com/akiraohgaki/owncloud-submedia-app

Ampache support the subsonic API see https://github.com/ampache/ampache/wiki/API
Subsonic API http://www.subsonic.org/pages/api.jsp

**Comment by dhharris** [comment]
Looking at the documentation, it is clear how we would add it to an existing ampache server, but how would that work in the owncloud app? I'd like to work on this feature but I am unsure where to begin. https://github.com/ampache/ampache/wiki/API#subsonic-api

**Comment by paulijar** [comment]
First, you should probably familiarize yourself with how the Ampache XML API support has been integrated to the Music app. Here's a rough overall explanation about it as I wrote elsewhere some time earlier (I'm not the original author of this module, but I've been working with it enough to know it somewhat well):

1. File `appinfo/routes.php` directs HTTP requests with certain path to `ampachecontroller.php` and its function `ampache`. Note that `routes.php` defines this with the name `ampache#ampache` where the first part refers to the controller and the second part to the function name.
2. The function `AmpacheController.ampache()` gets the URL parameters and dispatches the request according the parameter called `action`. Each action has its own handler function.
3. The handler functions fetch the requested data from `BusinessLayer` and build the responses using templates which can be found under `templates/ampache`.
4. As final related component, all HTTP requests to the Music app go through the module `middleware/ampachemiddleware.php`. It checks if the request is in fact an Ampache request and, if so, checks the Ampache session token. Requests with invalid token are blocked.

I guess that adding the Subsonic API support would require more or less similar modules to be added.

Next, you should get a good grasp of the internals of the Subsonic API as documented at http://www.subsonic.org/pages/api.jsp. The documentation contains some ~75 REST endpoints but probably we don't have to implement all of them.

Also, studying the "old owncloud app supporting this API" mentioned in the opening post might be educative. The link in OP is dead by now, but I guess that this is a working link for the same app: https://github.com/eskerda/owncloud-submedia-app

**Comment by dhharris** [comment]
Thank you very much! I will start working on this when I have the time :)

**Comment by soeren-b-c** [comment]
FYI there is now a bounty for this bug here:
https://bounty.cash/#/categories/1/apps-features/bounty/12/add-subsonic-api

It is for payment in Bitcoin Cash (but for a USD amount), and technically you only have the persons word that they will pay, but I have a strong hunch that they will :)

**Comment by paulijar** [comment]
The Subsonic API has now been released in the version 0.11.0.
