### ISSUE TITLE
Partial Scan after install

### ISSUE THREAD

**Issue by giovanisp** [owncloud/music#333]
I have just installed 0.3.4 on owncloud  7.0.4. And I get this, for hours:
![image](https://cloud.githubusercontent.com/assets/180794/5514956/31ee2066-8854-11e4-9822-2f5ba1dda7b1.png)

Scan finishes at 194/4154. the debug says "re-scan is done" !:
![image](https://cloud.githubusercontent.com/assets/180794/5514964/71ce3d4c-8854-11e4-8ef5-ab45ea638337.png)

**Comment by paulijar** [comment]
Major changes were introduced on the scanning logic as part of #564. If there are still scanning-related bugs, they are probably not the same as before #564. Hence, I assume that this report is obsolete.
