### ISSUE TITLE
Cannot play Ogg files

### ISSUE THREAD

**Issue by rettenbs** [owncloud/music#334]
I just updated my OwnCloud installation to 7.0.4 and also updated the music app to the lastest version. Now I doesn't play Ogg files any more. MP3 still working fine.

I always get the error message: "Einige nicht abspielbare Titel wurden übersprungen." (Not sure about the English translation but it should be something like: Some non playable titles were ignored).

Any ideas? According to the changelog, the apps should be able to play Ogg and MP3 files.

**Comment by MorrisJobke** [comment]
@rettenbs Which browser do you use?

**Comment by rettenbs** [comment]
I am using firefox.

**Comment by AMD1212** [comment]
Hi,

I also have this problem. I am using owncloud version 8.2 and the Music App version 0.3.7 installed.
A could play mp3 files without problem, but not Ogg/Vorbis files. I see them in the list, the Metadata is extracted fine. When i try to play them there is the message mentioned from @rettenbs above.

I find nothing in the owncloud.log
File of an unplayable ogg file: 08_Lunas_Reel.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~256000 bps, created by: Xiph.Org libVorbis I

**Comment by paulijar** [comment]
In Music app version 0.3.7 mentioned above, all audio files were played using the Aurora.js backend. As the Music app did not (and does not) contain ogg and vorbis plugins for Aurora, it couldn't play Ogg/Vorbis files. Nowadays, Ogg/Vorbis files play fine on Firefox and Chrome using the SoundManager2 backend. Case closed.
