### ISSUE TITLE
Length of all music tracks is 0:00

### ISSUE THREAD

**Issue by qirtaiba** [owncloud/music#335]
Finally I scanned all my music successfully after patching for the bug in owncloud/music#328. But all of the files scanned with a length of NULL (confirmed by looking in the MySQL table oc_music_tracks). This doesn't actually stop the files playing using the Web interface, but they won't play with a third-party client AmpacheX.
### Steps to reproduce
1. php occ music:scan terminus
### Expected behaviour

Music is scanned and imported with correct track lengths.
### Actual behaviour

Track lengths are 0:00. 
### Server configuration

**Operating system**: Debian GNU/Linux 7

**Web server:** Apache/2.2.22 

**Database:** mysql  Ver 14.14

**PHP version:** PHP 5.4.4-14+deb7u11

**ownCloud version:** ownCloud 7.0.3

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** activity,                files,             files_versions,     search_lucene,
admin_dependencies_chk,  files_encryption,  files_videoviewer,  templateeditor,
bookmarks,               files_external,    firstrunwizard,     updater,
calendar,                files_pdfviewer,   gallery,            user_external,
contacts,                files_sharing,     grauphel,           user_ldap,
documents,               files_texteditor,  mozilla_sync,       user_webdavauth,
external,                files_trashbin,    music

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc1e0d67c158',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'www.malcolm.id.au',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_terminus',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'php',
  'mail_domain' => 'malcolm.id.au',
  'mail_from_address' => 'owncloud',
  'preview_libreoffice_path' => '/usr/bin/soffice',
  'theme' => '',
  'maintenance' => false,
  'overwritewebroot' => '/owncloud',
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no
### Client configuration

AmpacheX.
#### Web server error log

Nothing unusual.
#### ownCloud log (data/owncloud.log)

While AmpacheX is connecting for the first time I get errors like this:

```
{"app":"PHP","message":"Undefined offset: 462 at \/var\/www\/owncloud\/apps\/music\/controller\/ampachecontroller.php#421","level":3,"time":"2015-01-06T17:50:47+00:00"}
{"app":"PHP","message":"Undefined offset: 872 at \/var\/www\/owncloud\/apps\/music\/controller\/ampachecontroller.php#421","level":3,"time":"2015-01-06T17:50:47+00:00"}
{"app":"PHP","message":"Undefined offset: 1488 at \/var\/www\/owncloud\/apps\/music\/controller\/ampachecontroller.php#421","level":3,"time":"2015-01-06T17:50:47+00:00"}
{"app":"index","message":"OCA\\Music\\AppFramework\\Db\\DoesNotExistException: No matching entry found","level":4,"time":"2015-01-06T17:51:01+00:00"}
{"app":"index","message":"OCA\\Music\\AppFramework\\Db\\DoesNotExistException: No matching entry found","level":4,"time":"2015-01-06T17:51:01+00:00"}
```
#### Browser log

Not applicable.

**Comment by RealRancor** [comment]
@qirtaiba 
As it seems you're using an outdated version of the music app (based on your posting in https://github.com/owncloud/music/issues/328) consider to upgrade to the latest version 0.3.5.

**Comment by qirtaiba** [comment]
On Mar 24, 2015, at 5:01 AM, RealRancor <notifications@github.com> wrote:
> 
> @qirtaiba <https://github.com/qirtaiba> 
> As it seems you're using an outdated version of the music app (based on your posting in #328 <https://github.com/owncloud/music/issues/328>) consider to upgrade to the latest version 0.3.5.
> 


Thanks, I had since done so but didn’t update this thread since the upgrade raised another problem in core that prevented me from using music at all (https://github.com/owncloud/core/issues/13096). Anyhow, I don’t doubt that this particular problem is indeed fixed.

-- 
Jeremy Malcolm PhD LLB (Hons) B Com
Internet lawyer, ICT policy advocate, geek
echo "9EEAi^^;6C6]>J^=^>6"|tr '\!-~' 'P-~\!-O'|wget -q -i - -O -

**Comment by paulijar** [comment]
Based on the comments above, and the last comment being nearly two years old, I assume this bug is already fixed. Please reopen if still reproducible.
