### ISSUE TITLE
[feature request] to be able to seek audio time positions

### ISSUE THREAD

**Issue by dhsc19** [owncloud/music#340]
Is there a way to make this so that you can jump time positions during playback?  I have audio files that can go up to 15-30 minutes in length and I would like to be able to jump time positions, but the interface doesn't seem to allow it.  Thanks.

**Comment by MorrisJobke** [comment]
Hi @dhsc19 

this is already possible, but just in Chrome/Chromium.

**Comment by euneuber** [comment]
Hi Morris,
I'm sorry using chrome 41 (linux x64) I can confirm selection of playback position (jumping) is not possible.

**Comment by MorrisJobke** [comment]
@euneuber Thanks for the feedback. I will check it again.

**Comment by paulijar** [comment]
After #536, seeking is possible for mp3 and ogg files on many browsers (but not on Chromium unless additional codecs are installed).

**Comment by paulijar** [comment]
After 72a893be64, also .flac files can be seeked in Chrome and Firefox. This means that those two browsers can now seek all the supported audio file types. Other browsers have more limited support for playing different file types and may not be able to seek some formats they can play.

I think this issue can be closed now.
