### ISSUE TITLE
Stuck at "Loading..." when playing songs from one album, "UnderflowError"

### ISSUE THREAD

**Issue by devurandom** [owncloud/music#341]
When I try to play songs from one specific album, the Music app is stuck at "Loading..." instead of displaying the current time and duration of the song. In the JS console I see "UnderflowError:", without any further details. The JS debugger shows no stack trace, either. The webserver shows no errors. In the access log I see ``, so the file is actually being served.

Please assist me in acquiring more information to debug the cause of this.

The album consists of MP3 tracks with a year set, and few without. The ones without play without any issues, while all of the ones with a year do not play. The album is "Rodriguez - Cold Fact", which you can get from Light In The Attic Records: http://lightintheattic.net/releases/1-cold-fact (that's the version I have).
### Steps to reproduce
1. Try to play a song from a specific album (details below).
### Expected behaviour

The song should play and the current time and total duration of the song should be displayed.
### Actual behaviour

The app is stuck at displaying "Loading..." and no music is being played.
### Server configuration

**Operating system**: Gentoo/Linux

**Web server:** Lighttpd 1.4.35

**Database:** MariaDB 10.0.15

**PHP version:** 5.5.21

**ownCloud version:** 7.0.4.2

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:**
- Music 0.3.4

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'XXX',
  ),
  'datadirectory' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'XXX',
  'dbhost' => 'XXX',
  'dbtableprefix' => 'XXX',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'XXX',
  'mail_smtpport' => 'XXX',
  'mail_domain' => 'XXX',
  'mail_from_address' => 'no-reply',
  'loglevel' => '0',
  'secret' => 'XXX',
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No
### Client configuration

**Browser:** 35.0.1

**Operating system:** Ubuntu 14.04
#### Web server error log

```
… "GET /remote.php/webdav/music/Rodriguez/Cold%20Fact/01%20Sugar%20Man.mp3 HTTP/1.1" 206 …
```
#### ownCloud log (data/owncloud.log)

```
…
```
#### Browser log

```
UnderflowError:
```

**Comment by devurandom** [comment]
While encryption is enabled, this error does not occur (see #342).

**Comment by devurandom** [comment]
Can someone please remove the Needs-Info label. I think I provided all the necessary information.

**Comment by paulijar** [comment]
This report appears to be about the same problem in the Aurora.js library as #404 and #297. Most browsers nowadays play mp3 tracks using the SoundManager2 library instead of aurora, making this a less severe issue. The problem still remains on Chromium which is stuck with aurora.

I'm closing this report since having one open report (#404) for the issue should be enough.
