### ISSUE TITLE
White screen on music app page on ownCloud 8

### ISSUE THREAD

**Issue by rakekniven** [owncloud/music#343]
### Steps to reproduce
1. Fresh install of ownCloud 8.0.0
2. Installed music app 0.3.4
3. Enabled app in admin app menu
4. Called up music app from app selection

### Expected behaviour
Music app should open

### Actual behaviour
I just get a white page with no content

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.12

**ownCloud version:** (see ownCloud admin page) 8.0.0

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:**
Core
Contacts
Calendar
Notes
News
Pictures

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx.l.0wjNnH',
  'trusted_domains' => 
  array (
    0 => 'xxx.rakekniven.de',
  ),
  'datadirectory' => '/usr/www/users/xxx/data',
  'overwrite.cli.url' => 'http://xxx.rakekniven.de',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.7',
  'installed' => true,
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox 35.0.1

**Operating system:**
OS X

#### Web server error log
nothing in

#### ownCloud log (data/owncloud.log)
Error 	PHP 	js file not found: script:js/md5/md5.min serverroot:/usr/www/users/xxx at /usr/www/users/xxx/lib/private/template/resourcelocator.php#46 	2015-02-11T15:34:30+00:00
Fatal 	index 	Exception: {"Message":"js file not found: script:js\/md5\/md5.min serverroot:\/usr\/www\/users\/xxx","Code":0,"Trace":"#0 \/usr\/www\/users\/xxx\/lib\/private\/templatelayout.php(155): OC\\Template\\ResourceLocator->find(Array)\n#1 \/usr\/www\/users\/xxx\/lib\/private\/templatelayout.php(106): OC_TemplateLayout::findJavascriptFiles(Array)\n#2 \/usr\/www\/users\/xxx\/lib\/private\/template.php(118): OC_TemplateLayout->__construct('user', 'music')\n#3 \/usr\/www\/users\/xxx\/lib\/public\/appframework\/http\/templateresponse.php(146): OC_Template->fetchPage()\n#4 \/usr\/www\/users\/xxx\/lib\/private\/appframework\/http\/dispatcher.php(105): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#5 \/usr\/www\/users\/xxx\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\PageController), 'index')\n#6 \/usr\/www\/users\/xxx\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('PageController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#8 \/usr\/www\/users\/xxx\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#9 \/usr\/www\/users\/xxx\/lib\/base.php(763): OC\\Route\\Router->match('\/apps\/music\/')\n#10 \/usr\/www\/users\/xxx\/index.php(36): OC::handleRequest()\n#11 {main}","File":"\/usr\/www\/users\/xxx\/lib\/private\/template\/resourcelocator.php","Line":46} 	2015-02-11T15:34:30+00:00

**Comment by rakekniven** [comment]
Update: Just tried master and it works fine for me.

**Comment by rakekniven** [comment]
Maybe related to #327

**Comment by rakekniven** [comment]
Please release app for supporting ownCloud 8.
Lot of users have been asking on our forums.

**Comment by MorrisJobke** [comment]
I will have a look at this on monday. I'm not at home over the weekend.

**Comment by MorrisJobke** [comment]
Done https://github.com/owncloud/music/releases/tag/v0.3.5

**Comment by MorrisJobke** [comment]
I also updated the music app in the appstore

**Comment by Akhenaton** [comment]
.... and we still get the old 0.3.4 on the appstore....

**Comment by MorrisJobke** [comment]
Sorry ... I uploaded the old archive. I updated the appstore and github one. Sorry for the trouble.
