### ISSUE TITLE
API error with ownCloud 8

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/music#345]
I updated recently to ownCloud 8, uninstall and reinstall Music 0.3.4, I applied the fix 7a41981a80c11f4d86609a6e57709aec15231f37 so that Music works again (and it does), but my log is spammed by this debug line (around one per second):

    Debug 	no app in context 	Accessing the API class is deprecated! Use the appropriate services instead! 	2015-02-16T14:18:44+00:00
    Debug 	no app in context 	Accessing the API class is deprecated! Use the appropriate services instead! 	2015-02-16T14:18:42+00:00
    Debug 	no app in context 	Accessing the API class is deprecated! Use the appropriate services instead! 	2015-02-16T14:18:42+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:19:05+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:19:04+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:19:04+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:19:00+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:18:57+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:18:52+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:18:52+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:18:52+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:18:51+00:00
    Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!	2015-02-16T14:18:51+00:00

I deactivated the Music app and the spam was gone. Reactivated the Music app again, and the spam was back again. Is there another patch to apply to fix this?

Thanks!

**Comment by MorrisJobke** [comment]
Thanks I will look into this, once I finished my thesis. ETA ~1-2 weeks

**Comment by MightyCreak** [comment]
:+1: 

Good luck with your thesis ;)

**Comment by pierre-alain-b** [comment]
Hello,
Same issue here, as reported in owncloud/core#15412 (now closed as not related to the core). Only visible in debug, but still annoying.

**Comment by MorrisJobke** [comment]
Ah ... I will try to remove the output by using proper API calls.

**Comment by pierre-alain-b** [comment]
Great, this was quick!
