### ISSUE TITLE
Occ scan doesn't work

### ISSUE THREAD

**Issue by nholz** [owncloud/music#349]
Hi, 
when I do 
./occ music:scan username or ./occ music:reset-database username I get this error:
PHP Fatal error:  Class 'OCA\Music\Utility\Scanner' not found in */apps/music/app/music.php on line 272

Any suggestions?

**Comment by MorrisJobke** [comment]
@nholz Which version of the music app do you use?

**Comment by paulijar** [comment]
This seems like some kind of installation problem. As there has been answer from the reporter for 2.5 years and apparently no-one else has ever ran into this, there's really no way to investigate any further. Closing.
