### ISSUE TITLE
optional: display the file name of *.mp3

### ISSUE THREAD

**Issue by euneuber** [owncloud/music#352]
Hi,
I have many, many podcasts which are poorly describing themself in metadata. Sometimes several of them tell the same text. Please make it possible to display the file name (in which they differ as in content). This would make finding the right podcast easier...
Thanks, Eugen

**Comment by paulijar** [comment]
This feature is now implemented as part of #656.

**Comment by paulijar** [comment]
The feature is now released in v0.8.0.
