### ISSUE TITLE
0.3.5 is not compatible with OC 8.0.2 ?

### ISSUE THREAD

**Issue by zeblair** [owncloud/music#355]
HI
it seems that music 0.3.5 is not compatible whith OC 8.0.2 .
Don't play music when clicking a mp3 file and directories on "music page" not appears". Searching all time .

**Comment by MorrisJobke** [comment]
I will test this, but recently I had no problems. Can you have a look at the owncloud log if there is something written?

**Comment by zeblair** [comment]
Le 19/03/2015 09:56, Morris Jobke a écrit :
>
> I will test this, but recently I had no problems. Can you have a look 
> at the owncloud log if there is something written?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/music/issues/355#issuecomment-83427320>.
>
i've just got this message in the log file when i lauch  Music app .
> Debug 	no app in context 	Accessing the API class is deprecated! Use 
> the appropriate services instead!
>

**Comment by zeblair** [comment]
Le 19/03/2015 09:56, Morris Jobke a écrit :
>
> I will test this, but recently I had no problems. Can you have a look 
> at the owncloud log if there is something written?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/music/issues/355#issuecomment-83427320>.
>
when i attempt to read a mp3 file i've got this message too:


	
	


Fatal 	index 	Exception: {"Message":"","Code":0,"Trace":"#0 
\/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(107): 
OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), 
Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: 
OCA\\Music\\Controller\\ApiController->collection()\n#2 
\/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): 
call_user_func_array(Array, Array)\n#3 
\/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): 
OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 
'collection')\n#4 
\/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97): 
OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 
'collection')\n#5 
\/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): 
OC\\AppFramework\\App::main('ApiController', 'collection', 
Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 
[internal function]: 
OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 
\/var\/www\/owncloud\/lib\/private\/route\/router.php(250): 
call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), 
Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(767): 
OC\\Route\\Router->match('\/apps\/music\/api...')\n#9 
\/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#10 
{main}","File":"\/var\/www\/owncloud\/apps\/music\/db\/track.php","Line":97}

**Comment by MorrisJobke** [comment]
```
Fatal 	index 	Exception: {"Message":"","Code":0,"Trace":"#0 apps/music/controller/apicontroller.php(107): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))
#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()
#2 lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)
#3 lib/private/appframework/http/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')
#4 lib/private/appframework/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')
#5 lib/private/appframework/routing/routeactionhandler.php(44): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)
#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)
#7 lib/private/route/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)
#8 lib/base.php(767): OC\\Route\\Router->match('/apps/music/api...')
#9 index.php(36): OC::handleRequest()
#10 {main}","File":"apps/music/db/track.php","Line":97} 
```

**Comment by zeblair** [comment]
sorry but I'm not a hacker.What can i do with this log ?

Best regards

**Comment by MorrisJobke** [comment]
@zeblair Nothing it was just for readability. When I come back later it's easier for me to have a look at this ;)

**Comment by zeblair** [comment]
thanks a lot for your time !!

**Comment by sorglos** [comment]
#345 ?

**Comment by ravermeister** [comment]
hope thats the correct place, I'm having similar issues:
1. When I try to set the Music Path in my Preferences, The Dialog which openes after clicking on the Text Field for the Directory
![Screenshot](http://www.rimkus.it/devel/owncloud/music_1.png)
is "read only" means I can't select any path

2. when you set it to a path
which represents an external (local!) share,
no music is loaded at all!. (means I get the Message: Nothing in here. Upload your music!)
note: the mp3 files are in subdirectories of the specified local share.
structure is as follows (*external_local_share_dir* is the specified music dir) :
**external_local_share_dir**/musik1/song.mp3
**external_local_share_dir**/musik1/song.mp3

**Comment by dcanali** [comment]
I'm experiencing the same issue as @zeblair

**Comment by gianluca-saba** [comment]
Same for me. I was trying to set a music directory which is a local share and the error is:

Exception: {"Message":"","Code":0,"Trace":"#0 /var/www/owncloud/lib/private/app.php(77): OC_App::loadApp('music')
#1 /var/www/owncloud/lib/private/util.php(75): OC_App::loadApps(Array)
#2 /var/www/owncloud/lib/base.php(766): OC_Util::setupFS()
#3 /var/www/owncloud/index.php(36): OC::handleRequest()
#4 {main}","File":"/var/www/owncloud/lib/private/app.php","Line":96}

**Comment by daftu** [comment]
Same problem here. Any solution?

**Comment by paulijar** [comment]
Considering that the latest Music app release is 0.3.13 and it no longer supports ownCloud 8.0.x, I think that this report is obsolete. If someone finds similar problems with newer Music app and ownCloud versions, those should be reported as new issues.
