### ISSUE TITLE
Music app doesn't read MP3 tags (ownCloud 7.0.2)

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#356]
Music app: 0.3.5

Web server: Apache 2.2.15, PHP 5.5.21

OS: CentOS 6.5 x86_64

allow_url_fopen is True in php.ini, magic quotas are turned off

In music/ app files tree, in 3rdparty/getID3/getid3/getid3.php, on line 96, 

public $option_max_2gb_check = false

Rescan:

./occ music:scan --all

performs and reports scan are done, nothing written to owncloud.log, yet all music files are still by Unknwon Artist within Unknown Album.

I would appreciate pieces of advise on how to handle that.

From https://github.com/owncloud/apps/issues/2034 by @temmokan

**Comment by MorrisJobke** [comment]
@temmokan can you provide me a file that doesn't extract the artist? My email address is listed here: https://github.com/MorrisJobke

**Comment by temmokan** [comment]
@MorrisJobke I have sent you email with sample track attached. Thanks in advance.

**Comment by viki53** [comment]
Hi, same problem here with `flac` files too.

All the music I uploaded is listed as *Unkwown artist* / *Unknow album*.

**Comment by paulijar** [comment]
@stayen @viki53 Is this issue still present with the latest Music app version (currently 0.5.4)?

**Comment by viki53** [comment]
@paulijar No idea, I've basically stopped using ownCloud, the music app has been uninstalled a long time ago. Sorry…

**Comment by paulijar** [comment]
I assume that this old issue is no longer present. If anyone still faces problems like this, they should file a new report.
