### ISSUE TITLE
Error loading music app landing page

### ISSUE THREAD

**Issue by oviney** [owncloud/music#357]
After clean install of the latest version, I get the following error when navigating to the Music app landing page:

{"reqId":"c8c1c5b30edb0f789e259dc242dff65e","remoteAddr":"192.168.2.81","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/apps\\/music\\/controller\\/apicontroller.php(107): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(158): call_user_func_array(Array, Array)\n#3 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#5 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/routing\\/routeactionhandler.php(44): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \\/var\\/www\\/owncloud\\/lib\\/private\\/route\\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \\/var\\/www\\/owncloud\\/lib\\/base.php(767): OC\\Route\\Router->match('\\/apps\\/music\\/api...')\n#9 \\/var\\/www\\/owncloud\\/index.php(36): OC::handleRequest()\n#10 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/apps\\/music\\/db\\/track.php\",\"Line\":97}","level":4,"time":"2015-03-24T23:42:29+00:00"}

**Comment by LukeOwncloud** [comment]
I am having exactly the same problem. Here are my server details.
Note worthy: At first it worked (even though it was really slow -> https://github.com/owncloud/music/issues/359) now this error. It come from  https://[myOcServer]/index.php/apps/music/api/collection which returns error code 500:

    Technical details

        Remote Address: MYIP
        Request ID: 2e180a06e9e9d547fc7a9ff1614d49c3
        Code: 0
        Message:
        File: /var/www/owncloud/apps/music/db/track.php
        Line: 97


    Trace

    #0 /var/www/owncloud/apps/music/controller/apicontroller.php(107): OCA\Music\Db\Track->toCollection(Object(OC\URLGenerator), Object(OC\Files\Node\Folder))
    #1 [internal function]: OCA\Music\Controller\ApiController->collection()
    #2 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)
    #3 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(86): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Music\Controller\ApiController), 'collection')
    #4 /var/www/owncloud/lib/private/appframework/app.php(97): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Music\Controller\ApiController), 'collection')
    #5 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('ApiController', 'collection', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    #6 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
    #7 /var/www/owncloud/lib/private/route/router.php(250): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
    #8 /var/www/owncloud/lib/base.php(767): OC\Route\Router->match('/apps/music/api...')
    #9 /var/www/owncloud/index.php(36): OC::handleRequest()
    #10 {main}

    

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.x

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** Updated from 7.

**List of activated apps:** Default apps + Calendar, Contacts, Deleted Files + Music 0.3.5

**Are you using external storage, if yes which one:** Internal HDD

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no


### Client configuration
**Browser:** Firefox 36.0.1 and Chromium 36.0.1950.0

**Operating system:** Win7, 32bit

**Comment by tibirou** [comment]
You just need to rebuild the music DB . From owncloud root dir run : sudo -u www-data php occ music:reset-database USERNAME  . Then to rebuild the DB run :  sudo -u www-data php occ music:scan USERNAME    .Note : update www-data with the correct user under your web server is running

**Comment by paulijar** [comment]
This has almost certainly happened because the music database has contained a file ID which is no longer available to the user. This could happen at least in the scenario described in #567. Two years ago when this was reported, there might have been also other use cases where such thing could have happened.

After #564, the obsolete tracks no longer prevent loading the collection.json. Hence, the issue reported here should no longer happen.
