### ISSUE TITLE
SQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause

### ISSUE THREAD

**Issue by hmuus** [owncloud/music#358]
### Steps to reproduce
1. install music 0.3.5

### Expected behaviour
cron cycle should not deliver errors

### Actual behaviour
each cron cycle throws error

### Server configuration
**Operating system**: Debian 7 latest, all updates

**Web server:** apache

**Database:** mysql

**PHP version:** 5 latest

**ownCloud version:** 8 latest

**Updated from an older ownCloud or fresh install:** updated from 7 latest

**List of activated apps:** standard plus music

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'instance id here',
  'passwordsalt' => 'salt here',
  'secret' => 'secret here',
  'trusted_domains' => 
  array (
    0 => 'full domain hostname here',
  ),
  'datadirectory' => '/var/www/path here/data',
  'overwrite.cli.url' => 'https://full domain hostname here/path here',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'sender name here',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'domain name here',
  'theme' => '',
  'maintenance' => false,
  'dbname' => 'dbname here',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'user with root access here',
  'dbpassword' => 'password here',
  'mail_smtphost' => 'ip here',
  'ldapIgnoreNamingRules' => false,
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** various

**Operating system:** various

#### ownCloud log (data/owncloud.log)
```
snip start SQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause snip end
```

### Reason

apps/music/utility/helper.php sql statements throw errors each cron cycle:

SQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause

due to contained SQL commands
'UPDATE `*PREFIX*music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `*PREFIX*music_albums` LEFT JOIN `*PREFIX*filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);'
and
'DELETE FROM `*PREFIX*music_tracks` WHERE `file_id` IN (SELECT `file_id` FROM `*PREFIX*music_tracks` LEFT JOIN `*PREFIX*filecache` ON `file_id`=`fileid` WHERE `fileid` IS NULL);'

### Proposal

 replace by

```
<?php

/**
 * ownCloud - Music app
 *
 * This file is licensed under the Affero General Public License version 3 or
 * later. See the COPYING file.
 *
 * @author Morris Jobke <hey@morrisjobke.de>
 * @copyright Morris Jobke 2014
 *
 * update 25.March 2015
 * hmuus
 */

namespace OCA\Music\Utility;

use \OCA\Music\AppFramework\Core\Db;


class Helper {

	private $db;

	public function __construct(Db $db){
		$this->db = $db;
	}

	/**
	 * Removes orphaned data from the database
	 */
	public function cleanUp() {
		$sqls = array(
/*SQLSTATE[HY000]: General error: 1093 You can't specify target table for update in FROM clause
			'UPDATE `*PREFIX*music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `*PREFIX*music_albums` LEFT JOIN `*PREFIX*filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);',
*/			'CREATE TABLE IF NOT EXISTS `*PREFIX*music_albums_cleanup` AS 
SELECT `cover_file_id` FROM `*PREFIX*music_albums` LEFT JOIN `*PREFIX*filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL;',
			'UPDATE `*PREFIX*music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `*PREFIX*music_albums_cleanup`);',
			'DROP TABLE `*PREFIX*music_albums_cleanup`;',
/*SQLSTATE[HY000]: General error: 1093 You can't specify target table for update in FROM clause
			'DELETE FROM `*PREFIX*music_tracks` WHERE `file_id` IN (SELECT `file_id` FROM `*PREFIX*music_tracks` LEFT JOIN `*PREFIX*filecache` ON `file_id`=`fileid` WHERE `fileid` IS NULL);',
*/			'CREATE TABLE IF NOT EXISTS `*PREFIX*music_tracks_cleanup` AS 
SELECT `file_id` FROM `*PREFIX*music_tracks` LEFT JOIN `*PREFIX*filecache` ON `file_id`=`fileid` WHERE `fileid` IS NULL;',
			'DELETE FROM `*PREFIX*music_tracks` WHERE `file_id` IN (SELECT `file_id` FROM `*PREFIX*music_tracks_cleanup`);',
			'DROP TABLE `*PREFIX*music_tracks_cleanup`;',
			'DELETE FROM `*PREFIX*music_albums` WHERE `id` NOT IN (SELECT `album_id` FROM `*PREFIX*music_tracks` GROUP BY `album_id`);',
			'DELETE FROM `*PREFIX*music_album_artists` WHERE `album_id` NOT IN (SELECT `id` FROM `*PREFIX*music_albums` GROUP BY `id`);',
			'DELETE FROM `*PREFIX*music_artists` WHERE `id` NOT IN (SELECT `artist_id` FROM `*PREFIX*music_album_artists` GROUP BY `artist_id`);'
		);

		foreach ($sqls as $sql) {
			$query = $this->db->prepareQuery($sql);
			$query->execute();
		}
	}
}
```

### Afterwards behaviour
No more likely errors in log

**Comment by stefarossi** [comment]
I can confirm this bug. It's happening to me too.



### Steps to reproduce
1. Install Music.
2. Scan your folders.

### Expected behaviour
The library with all the covers should appear.

### Actual behaviour
The library appears with no cover.

### Server configuration
**Operating system**: Debian 7 x64

**Web server:** nginx

**Database:** mysql 5.6

**PHP version:** 5.5.23

**ownCloud version:** ownCloud 8.0.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** SMS, Notes, Conversations, News, Passwords, Music, Bookmark, Activities

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '-----------',
  'passwordsalt' => '-----------',
  'secret' => '-----------',
  'trusted_domains' => 
  array (
    0 => '-----------',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '-----------',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => '-----------',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => '-----------',
  'dbpassword' => '-----------',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'no-reply',
  'mail_domain' => '-----------',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '-----------',
  'mail_smtpname' => '-----------',
  'mail_smtppassword' => '-----------',
  'ldapIgnoreNamingRules' => false,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
  'forceSSLforSubdomains' => true,
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
I get this error, probably because I'm not using sqlite.
```
sqlite> select * from oc_appconfig where appid='user_ldap';
Error: no such table: oc_appconfig
```
Anyway, is LDAP information really needed for this?

### Client configuration
**Browser:** Google Chrome 41

**Operating system:** OS X 10.8.5

### Logs
#### Web server error log
No error messages are produced by the web server.

#### ownCloud log (data/owncloud.log)
```
[...]
{"reqId":"fce32d2cb9a1f4be76e41d4b210e7e9d","remoteAddr":"","app":"no app in context","message":"Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause","level":3,"time":"2015-03-26T21:30:04+00:00"}
[...]
```

#### Browser log
I don't think this is relevant to the problem, but I can provide it if needed.

**Comment by hmuus** [comment]
@stefarossi Have you tried my proposed solution? Let me know, if that works out.

**Comment by stefarossi** [comment]
@hmuus Yes, and it stopped the error from appearing in the log. However, my covers still don't show up. I know my music files have correctly embedded covers, because I can see them in the Files app.

**Comment by hmuus** [comment]
@owncloud-bot to find the requested info and delete the need info tag
