### ISSUE TITLE
Scrollbar hidden by music player controls

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/music#360]
### Steps to reproduce
1. Load many songs into owncloud.
2. Browse to music app, stay at top of list, and play some song.

### Expected behaviour
I want to be able to grab the scroll bar slider with the cursor to quickly scroll down.

### Actual behaviour
The music controls - to be specific the repeat button - is covering the scroll bar slider. I have to scroll down by clicking the scroll bar. For long lists it takes some time until the slider becomes visible.

Here the slider is covered and barely visible:
![image1](https://cloud.githubusercontent.com/assets/2737900/6993924/f1cfc002-db05-11e4-909a-8ae06620c97a.jpg)

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.x

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** Updated from 7.

**List of activated apps:** Default apps + Calendar, Contacts, Deleted Files + Music 0.3.5

**Are you using external storage, if yes which one:** Internal HDD

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 36.0.1 and Chromium 36.0.1950.0

**Operating system:** Win7, 32bit

#### Browser log
n/a

**Comment by jancborchardt** [comment]
Yes, same issue as we have in Mail: https://github.com/owncloud/mail/issues/328

I solved it in the Files app with some crazy Javascript: https://github.com/owncloud/core/pull/15260 – we could make that into a reusable function.
