### ISSUE TITLE
Clicking on music file in main OwnCloud 8.0 "Files" page does not automatically load and play file

### ISSUE THREAD

**Issue by dhsc19** [owncloud/music#362]
It used to be that when I click on a music file in the main OwnCloud "Files" page, the "Music" page would load and start playing the file I clicked on.  Now, the "Music" page loads but doesn't load the file that I selected.

**Comment by paulijar** [comment]
This has been fixed by #529.
#492 is a duplicate for this issue.
cc @gnarula
