### ISSUE TITLE
First run experience: scan automatically

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#363]
Currently when you start up the Music app for the first time you are faced with this:
![capture du 2015-04-13 23 48 34](https://cloud.githubusercontent.com/assets/925062/7126214/c698db1a-e237-11e4-9c9c-9ea077551fcd.png)
Instead, the scan should just start automatically, and the music should get displayed already.

Then for some reason there’s a »refresh« icon shown in the bottom left. Only when you click that, all the music is shown. This should all be more automatic. :) cc @MorrisJobke

**Comment by paulijar** [comment]
IMHO, the first run experience is good enough after  dcd5c44. I wouldn't want the app to start scanning completely without user intervention. Closing.
