### ISSUE TITLE
When playing a song/artist/album, the view jumps to the top

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#364]
1. Scroll down to your desired artist
2. Click the play icon
3. Music starts, but the list also jumps all the way to the beginning again …

cc @MorrisJobke :)

**Comment by jancborchardt** [comment]
This is in Chrome. Doesn’t occur in Firefox.

**Comment by autious** [comment]
This does indeed occur on Mozilla Firefox 45.0.2 aswell as Chrome

**Comment by benediktg** [comment]
It occurs on Firefox (v45.0), too, but only one time when I refresh the page. After that it doesn't happen again until I refresh the page. In addition to that it does not jump all the way up – there are some "centimetres" left.

**Comment by paulijar** [comment]
I believe that this, too, gets fixed with the PR #517.

**Comment by paulijar** [comment]
@gnarula Proposing to close this issue.
