### ISSUE TITLE
Clicking on the song/artist/cover in the play bar should scroll the view to that album

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#365]
Currently it’s a bit cumbersome to get back to the currently playing artist. Simple fix: When clicking on song/artist/cover in the play bar, scroll the main view to that album.

Yes, clicking anywhere there should just scroll to the album. We don’t need to differentiate between clicking on album or artist for now. cc @MorrisJobke

**Comment by paulijar** [comment]
I have a working implementation for this feature but it would be easier to make a pull request if #523 is merged first.

**Comment by paulijar** [comment]
@gnarula This feature is implemented and could be closed
