### ISSUE TITLE
Ability to search through music

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#367]
Similar to how it is in the Files app, Apps management etc, it should be possible to use the top bar search field to filter music.

As you type, the music list should be reduced. Everything should be searched over, including artist / album / song title / year / genre / etc. If that will result in performance hits, first just search by artist/album/songname.

**Comment by boardfish** [comment]
Ctrl+F seems alright in the meantime, given things aren't lazy-loaded, but I'd appreciate this feature.

**Comment by paulijar** [comment]
Search/filtering feature in included in the Music v0.13.0 which was just released.
