### ISSUE TITLE
Music doesn’t play in Firefox

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#369]
In Chrome it works fine, but in Firefox the music doesn’t play. No errors in the log and the play bar also moves.

It’s all mp3s, couldn’t test with .ogg yet because of https://github.com/owncloud/music/issues/368

**Comment by paulijar** [comment]
This issue probably hasn't been valid for long time. At latest, #535 should have fixed all MP3 playback problems on Firefox.
