### ISSUE TITLE
OC 8.0.3: Owncloud crashes with music app. 

### ISSUE THREAD

**Issue by jmp9292** [owncloud/music#379]
### Steps to reproduce

1.anything only have the music app on
### Expected behaviour

a good perfomance of music app
### Actual behaviour

when I try to acces to owncloud it seems down and i need to reboot the server
### Server configuration

**Operating system**: 
ubuntu xfce

**Web server:**apache2

**Database:** mysql/phpmyadmin 

**PHP version:**
 PHP Version 5.5.9-1ubuntu4.9

**ownCloud version:**
 8.0.3

**Updated from an older ownCloud or fresh install:** 
an older owncloud

**List of activated apps:**
only music app

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:** chrome normally

**Operating system:**
windows 8.1
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
Exception: {"Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(107): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/music\/api...')\n#9 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/apps\/music\/db\/track.php","Line":97}
```

**Comment by paulijar** [comment]
Based on the owncloud.log above, this is probably duplicate to #357, and should no longer happen.
