### ISSUE TITLE
OCP\Files\NotFoundException on file with accented character over NFS

### ISSUE THREAD

**Issue by qirtaiba** [owncloud/music#383]
When I scan my files I get an error when it comes to a file called "10 Berimbáu.mp3". On the console it loos like this:
   [OCP\Files\NotFoundException]

The file that it is choking on is on an NFS mounted filesystem, if that makes a difference.

_Steps to reproduce_
su -c 'php occ music:scan --all' www-data

_Expected behaviour_
Scanning completes

_Actual behaviour_
Scanning fails

_Server configuration_

Operating system: Debian Wheezy

Web server: Apache2

Database: MySQL

PHP version: 5.6.7

ownCloud version: 8.0.3

Updated from an older ownCloud or fresh install: An older owncloud

List of activated apps: Music

The content of config/config.php:

<?php
$CONFIG = array (
  'instanceid' => 'oc1e0d67c158',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'www.malcolm.id.au',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_terminus',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'php',
  'mail_domain' => 'malcolm.id.au',
  'mail_from_address' => 'owncloud',
  'preview_libreoffice_path' => '/usr/bin/soffice',
  'theme' => '',
 'maintenance' => false,
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'logfile' => '/var/log/owncloud.log',
  'loglevel' => '0',
);

Are you using external storage, if yes which one: NFS

Are you using encryption: No

Are you using an external user-backend, if yes which one: No

_Client configuration_

Browser: Firefox

Operating system: Mac 10.6

_Logs_
Web server error log

Not relevant

ownCloud log (data/owncloud.log)
   {"reqId":"b7915c28155399cabf0cd98654a9a439","remoteAddr":"","app":"OC\Files\Cache\Scanner","message":"!!! Path 'Compilations\/Diggin' Deeper 2 - The Roots Of Acid Jazz\/10 Berimb\u00e1u.mp3' is not accessible or present !!!","level":0,"time":"2015-05-31T04:14:14+00:00","method":"--","url":"--"}

**Comment by adevx** [comment]
Confirmed bug using Owncloud 8.2 and Music 0.3.8 - interprets Küss as K\u00fcss which causes a break, and essentially breaks the app (continuous scanning without ever loading files). Using locally attached sata disk storage. 

Error logged:
Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"\/files\/K\u00fcss.mp3","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/node\/folder.php(117):

**Comment by paulijar** [comment]
@qirtaiba @adevx Is this issue still present with the latest Music app version (currently 0.5.4)?

**Comment by qirtaiba** [comment]
It seems not. I still have that file, but the command now completes without errors.

**Comment by paulijar** [comment]
Okay, great. Thanks for the info!
