### ISSUE TITLE
Error in OC 8.1 beta 2

### ISSUE THREAD

**Issue by tflidd** [owncloud/music#385]
### Steps to reproduce
1. Install OC 8.1 beta 2 on debian (via opensuse repo)
2. Put music files
3. Activate music app, scan music files
4. Open Music App

### Expected behaviour
show music files

### Actual behaviour
Music app shows empty page ("nothing in here, put files...")

### Server configuration
**Operating system**: Debian Wheezy

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.4

**ownCloud version:** 8.1 beta2

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
 - activity: 2.0.0
 - bookmarks: 0.4
 - calendar: 0.6.4
 - contacts: 0.3.0.18
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - music: 0.3.5
 - news: 5.3.5
 - provisioning_api: 0.2
 - templateeditor: 0.1

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Pob0Mi6klQzo1l57kYTJ","remoteAddr":"","app":"no app in context","message":"Error while running background job: An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL WHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (SELECT `cover_file_id` FROM `oc_music_albums` LEFT JOIN `oc_filecache` ON `cover_file_id`=`fileid` WHERE `fileid` IS NULL);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause","level":3,"time":"2015-06-04T09:19:35+00:00","method":"--","url":"--"}
```

**Comment by MorrisJobke** [comment]
Fixed with #372
