### ISSUE TITLE
Music  app breaks anonymous upload

### ISSUE THREAD

**Issue by gschwepp** [owncloud/music#387]
Hi, 

I run OC 8.0.3 on a hosted server (linux, apache, PHP 5.6.8 (CGI)). With enabled music app (0.3.5) remote users are not able to upload multiple files to a shared folder (via link and password protection). When multiple files (more than 2) are uploaded the upload-progress bar freezes and nothing happens. After cancelling the upload only one file is uploaded. The timespan waiting for the upload and filesize have no effect on this behaviour.  There is no difference if the files are dragged into the cloud or uploaded over the "upload button".

The log shows: 
"Debug	no app in context	Accessing the API class is deprecated! Use the appropriate services instead!"

With disabled music app the upload works normal and the debug message does not appear. As logged in user everthing works fine with enabled music app. 

Cheers
gschwepp

**Comment by gschwepp** [comment]
### Steps to reproduce
1. Activate music app
2. Share folder via liink and allow editing
3. Upload multiple files as remote user

### Expected behaviour
All files should be uploaded.

### Actual behaviour
Only one file is uploaded and the upload progress stops. 

### Server configuration
**Operating system**: Linux 3.2.0-85-generic #122-Ubuntu SMP Tue May 26 16:14:57 UTC 2015 x86_64 

**Web server:** Apache

**Database:**  Mysql 5.5.43

**PHP version:** PHP 5.6.8

**ownCloud version:** (see ownCloud admin page)
8.0.3 
**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
- Activity 1.2.0
- Calendar 0.6.4
- Contacts 0.3.0.18
- Deleted files 0.6.2
- Documents 0.9.0
- File Locking 
- First Run Wizard 1.1
- Full Text Search 0.6.0
- Mail Template Editor 0.1
- OwnNote 0.0.8
- PDF Viewer 0.7
- Pictures 0.6.0
- Provisioning API 0.2
- Share Files 0.6.1
- Text Editor 0.4
- Updater 0.4
- Versions 1.0.5
- Video Viewer 0.1.3

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Firefox 38.0.5 + (other unknown versions)

**Operating system:** Windows 7 + Linux

### Logs
#### Web server error log
None

#### ownCloud log (data/owncloud.log)
Debug no app in context Accessing the API class is deprecated! Use the appropriate services instead!

#### Browser log
None

**Comment by MorrisJobke** [comment]
Fix for this is in #436
