### ISSUE TITLE
Doesn't play music with metadata in asian characters

### ISSUE THREAD

**Issue by antoniosv** [owncloud/music#388]
I tried to play japanese music, obviously the metadata and file are both written with the japanese letters, and it refused to play.
Later I added another song that had the metadata in roman letters, and it played properly... So I can only assume that it's because of the encoding.

**Comment by paulijar** [comment]
Tested on Music 0.4.3 + Nextcloud 12 with a MP3 track with file name and metadata containing Japanese Hiragana, Katakana, and Kanji characters. The file played back fine. I assume that this has either got fixed at some point or then this is another duplicate to #404 and the Japanese characters were irrelevant to begin with. Either way, case closed.
