### ISSUE TITLE
Viridian no artists, amarok conn fail

### ISSUE THREAD

**Issue by nolash** [owncloud/music#389]
Viridian (v1.2) reports no artists, no albums from my owncloud, although there is lots there. Amarok (v2.8.0 / KDE 4.14.2) says connection failure. I've tried with and without https, and with and without the /server/xml.server.php part of the URL. Using OC v7.0.2, music app v0.3.5

**Comment by paulijar** [comment]
So much has changed in the Music app and its Ampache support during the past 6 years that I doubt that this old bug is relevant any more. If similar problems still occur, then a new issue should be opened.
