### ISSUE TITLE
Music 0.3.6: Class 'OCA\\Music\\AppFramework\\Db\\Mapper' not found

### ISSUE THREAD

**Issue by burnersk** [owncloud/music#397]
Configuration
- Debian 8 (stable)
- ownCloud 8.1.0 (stable)
- Music 0.3.6
- PHP-FPM 5.6.9 (debian)
- APCu 4.0.7
- Zend OPcache 7.0.4
- PHP memcached 2.2.0

Installing Music 0.3.5 will work correctly. Switching to "Music" tab or to "Personal Settings" will cause errors in the logs and plain white websites.

Related error logs:

```
{"reqId":"hiosF\/1Al90Utu\/U7Arf","remoteAddr":"192.0.2.20","app":"PHP","message":"Class 'OCA\\Music\\AppFramework\\Db\\Mapper' not found at \/var\/www\/owncloud\/apps\/music\/db\/artistmapper.php#19","level":3,"time":"2015-07-10T13:25:08+00:00"}
```

Switching back to Music 0.3.6 will work when changes to database will be reverted.

**Comment by MorrisJobke** [comment]
> Switching back to Music 0.3.6 will work when changes to database will be reverted.

You mean 0.3.5?

Weird. Looks like some OpCache caching behave wrong, because this Class isn't used anymore. Can you restart php-fpm and test again?

**Comment by burnersk** [comment]
@MorrisJobke yes, I meant 0.3.5 as the working replacement. Sorry for the typo - fixed it.

Procedure for the final 0.3.6 test:

1. disable Music 0.3.5
2. "App uninstall" via ownCloud web interface
3. purge Music folder/files
4. delete Music related settings in database
5. drop Music related tables in database
6. restart php-fpm
7. install/activate Music 0.3.6 via ownCloud web interface
10. restart php-fpm
11. working Music interface - "Uncanned files available"
12. scanning files...: OK
13. playing some music: OK
14. "Personal Settings" page: OK

Seems that it is realy somehow related to OpCache.

This issue is fixed (at least for "fresh" installs of Music).

**Comment by MorrisJobke** [comment]
Okay. I will have a look at making the DB more robust against some orphaned entries.

**Comment by paulijar** [comment]
Based on the comments above and the fact that this error is related to a version update ~10 release versions ago, I don't think there's anymore reason to keep this issue open.
