### ISSUE TITLE
doesn't recognize ogg vorbis

### ISSUE THREAD

**Issue by BigButt** [owncloud/music#399]
Same issue like #161 - doesn't recognize ogg vorbis as well.
Version: 0.3.6

**Comment by christi9n** [comment]
Hi,
Also same pb, I can see my OggVorbis file but no recognition !
OC 8.1 and galleryplus-13-stable8.1

**Comment by MorrisJobke** [comment]
Thanks. I will test this.

**Comment by BigButt** [comment]
Now I have all my collection. My bad, didn't scan - sorry for the confusion.
Right now I'm at the office, without any speakers but it seems to work. At least it's buffering and playing.
Gotta at home.

**Comment by BigButt** [comment]
Nope, forget the last post. Issue's still valid.
ogg vorbis is recognized but it doesn't play.

**Comment by MorrisJobke** [comment]
> ogg vorbis is recognized but it doesn't play.

Then it's definetely a problem of the player, which currently only supports mp3 and flac https://github.com/owncloud/music/tree/master/js/vendor/aurora

**Comment by paulijar** [comment]
Playing .ogg files has been possible for quite some time now, but only if the browser used contains the suitable codec. This includes Firefox and Chrome, at least, but not Chromium, IE, or Edge.

**Comment by paulijar** [comment]
The current status of file formats supported per browser is documented in README. I don't see any plausible way to extend the ogg/vorbis support to browsers which do not have the built-in codecs for it. There are aurora.js plugins ogg.js and vorbis.js which could do the trick, but in my tests they performed poorly both on Chromium and Edge. Furthermore, those plugins haven't got any commits for 3 years now.

As there is probably no way to improve the current situation, I see no reason to keep this issue open.
