### ISSUE TITLE
Version 0.3.7 doesn't play (some) MP3 files

### ISSUE THREAD

**Issue by africanforest** [owncloud/music#404]
Some MP3 files get loaded completely, but do not play (Firefox 39, Windows & Mac). 

In Safari for Windows no files at all are displayed in "Music", the spinner is turning forever and nothing happens.

These are the errors related to the issue above, found in my log file:

```
Error PHP Cannot modify header information - headers already sent by (output started at /home/.sites/web/cloud/3rdparty/sabre/http/lib/Sapi.php:70) at /home/.sites/web/cloud/3rdparty/sabre/http/lib/Sapi.php#58 2015-07-21T11:35:36+02:00
```

```
Fatal index Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"music.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/home\/.sites\/web\/cloud\/lib\/private\/route\/router.php(306): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('music.page.inde...', Array, false)\n#1 \/home\/.sites\/web\/cloud\/lib\/private\/urlgenerator.php(65): OC\\Route\\Router->generate('music.page.inde...', Array)\n#2 \/home\/.sites\/web\/cloud\/apps\/music\/appinfo\/app.php(26): OC\\URLGenerator->linkToRoute('music.page.inde...')\n#3 \/home\/.sites\/web\/cloud\/lib\/private\/app.php(389): require('\/home\/.sites\/95...')\n#4 \/home\/.sites\/web\/cloud\/settings\/ajax\/navigationdetect.php(29): OC_App::getAppNavigationEntries('music')\n#5 \/home\/.sites\/web\/cloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/home\/.sites\/95...')\n#6 [internal function]: __lambda_func(Array)\n#7 \/home\/.sites\/web\/cloud\/lib\/private\/route\/router.php(274): call_user_func('\\x00lambda_60', Array)\n#8 \/home\/.sites\/web\/cloud\/lib\/base.php(867): OC\\Route\\Router->match('\/settings\/ajax\/...')\n#9 \/home\/.sites\/web\/cloud\/index.php(40): OC::handleRequest()\n#10 {main}","File":"\/home\/.sites\/web\/cloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134}
```

**Comment by MorrisJobke** [comment]
> Safari for Windows

But other browsers work?



> Some MP3 files get loaded completely, but do not play (Firefox 39, Windows & Mac).

I have also some of such files here. I need to investigate what is wrong with them.

**Comment by africanforest** [comment]
Yes other browsers - Firefox for example - at least do show the light-gray progress bar indicating that the file is getting loaded, but what's missing is the dark progress bar that is displayed when a music file is played.

**Comment by MorrisJobke** [comment]
Not really :(

**Comment by tx7** [comment]
I don't have any problem play mp3 songs on my computer via Firefox or Chrome.
However, I can't play them on my iPhone 5S safari.

**Comment by paulijar** [comment]
For the record, Aurora.js engine cannot play some perfectly fine MP3 files which play well in every other player. After #535, Aurora.js is used for MP3 playing only on Chromium. Hence, this issue should now be fixed for all browsers except Chromium.

**Comment by paulijar** [comment]
Aurora.js has an open issue reported about this problem here: https://github.com/audiocogs/aurora.js/issues/174.

**Comment by paulijar** [comment]
The Music app version 0.4.4 has an updated version of aurora.js which seems to be able to play some mp3 files which were previously unplayable. I still could find a file which did not play, though.
