### ISSUE TITLE
upgrading gets stuck

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/music#408]
my ownCloud 8.1.1 is currently stuck on an upgrade of the Music app:
![8 1 2](https://cloud.githubusercontent.com/assets/551757/9193557/96f84216-4014-11e5-8767-d4a982236665.png)
I upgraded most likely from 0.3.5 to the latest, 0.3.7.

Running openSUSE 13.2 (latest stable)/Apache 2.4.16/PHP 5.6.9/mariadb 10.0.20

**Comment by MorrisJobke** [comment]
The only version that could trigger this was 0.1.5 and before (from September 2013) :(

Can you remove the first `if` statement in `apps/music/app/update.php` and try the upgrade again?

**Comment by MorrisJobke** [comment]
You can also apply 1246243 which should fix the issue ;)
