### ISSUE TITLE
Continue streaming while browsing OC

### ISSUE THREAD

**Issue by awikatchikaen** [owncloud/music#409]
I think it could be difficult be having control bar on the OC header bar and having my music playing while I use Owncloud file, calendar or news would be an awesome usability.

Thank

**Comment by paulijar** [comment]
Although the idea is nice, I don't see it as realistically possible. This would require a total overhaul of the architecture of ownCloud/Nextcloud and that's totally out of scope of the Music app. Also, you can always pin the Music app tab in your browser and let it play there while doing other things (within your cloud or on any other web site) on the other browser tabs.
