### ISSUE TITLE
Ampache streaming broken for shared folders not owned by user

### ISSUE THREAD

**Issue by bgouhier** [owncloud/music#412]
I am playing with the integrated ampache server in the new music app, and I think there is an issue with streaming music from shared folders.

I have 2 folders, say 'Music' and 'MusicShared'. I own 'Music' while 'MusicShared' is owned by a different user ('user2') who has shared it with me.

Now, when setting the music folder in Personal/Music to 'Music', I can listen to all files from the web interface (music app), as well as in a 3rd party client (e.g Tomahawk). However, if I change the folder to 'MusicShared', I can only play it in the web interface (after a rescan). Upon restarting Tomahawk to force a refresh of the music list, I can see the list of albums and titles but it refuses to play anything. Note that it doesn't throw any error nor warning, but the playing time stays at 0:00 and seems to wait forever for the server.

The two folders contain exactly the same files, just the owner is different.

I have the following 'fatal / index' error message in the admin tab from owncloud when trying to open a title from the 'MusicShared' folder with Tomahawk:

`Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"\/user2\/files\/Music\/Justin Hurwitz & Tim Simonec\/2014-09-26 - Whiplash\/02 - Overture.mp3","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/files\/node\/folder.php(341): OC\\Files\\Node\\Root->get('\/user2\/files\/M...')\n#1 \/var\/www\/owncloud\/apps\/music\/controller\/ampachecontroller.php(470): OC\\Files\\Node\\Folder->getById(11454)\n#2 \/var\/www\/owncloud\/apps\/music\/controller\/ampachecontroller.php(109): OCA\\Music\\Controller\\AmpacheController->play()\n#3 [internal function]: OCA\\Music\\Controller\\AmpacheController->ampache()\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\AmpacheController), 'ampache')\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\AmpacheController), 'ampache')\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('AmpacheControll...', 'ampache', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/music\/amp...')\n#11 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/node\/root.php","Line":181}`

This is with owncloud server 8.1.1 and music app 0.3.7

**Comment by paulijar** [comment]
Tested on Music 0.4.3, Nextcloud 12, and Tomahawk 0.8.4 (on Windows 10), and the problem did not reproduce. I assume that the issue has got fixed at some point.
