### ISSUE TITLE
White screen, spinning circle and unending scan running in Music app

### ISSUE THREAD

**Issue by djmcd89** [owncloud/music#414]
Hi,
I was using the OC Music app under OC7 but since I've upgraded to OC8 it is no longer working.
I can trigger a scan at the bottom of the screen but that won't complete it just hangs at 1778/1805
I've tried older versions of the music app and under 0.2 I am able to see and play music that I have but I am also unable to see recently added music or scan any new tracks.
I've attached a screenshot of my error log. Any ideas ? Sorry am a bit of a noob when it comes to programming/scripting.
Thanks 

Dan

![screenshot - 27 08 2015 - 22 06 29](https://cloud.githubusercontent.com/assets/14004369/9531837/5940f020-4d08-11e5-94ef-282569ed14bf.png)

**Comment by MorrisJobke** [comment]
@djmcd89 Can I ask you to paste the error in here? Then it is also searchable and a lot better to read. Thanks

**Comment by djmcd89** [comment]
Sure, no problem.
Thanks for the fast response.

 Fatal 	index 	
Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(107): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/music\/api...')\n#9 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/apps\/music\/db\/track.php","Line":97} 	2015-08-27T20:18:47+00:00

Fatal 	index 	
Exception: {"Exception":"OCA\\Music\\AppFramework\\BusinessLayer\\BusinessLayerException","Message":"More than one result","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/music\/utility\/scanner.php(252): OCA\\Music\\BusinessLayer\\AlbumBusinessLayer->addAlbumIfNotExist('Unconscious Sta...', '2013', 135, 'root')\n#1 \/var\/www\/owncloud\/apps\/music\/utility\/scanner.php(375): OCA\\Music\\Utility\\Scanner->update(Object(OC\\Files\\Node\\File), 'root')\n#2 \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(283): OCA\\Music\\Utility\\Scanner->rescan('root')\n#3 [internal function]: OCA\\Music\\Controller\\ApiController->scan()\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'scan')\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'scan')\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ApiController', 'scan', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/music\/api...')\n#11 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/apps\/music\/businesslayer\/albumbusinesslayer.php","Line":103}

**Comment by djmcd89** [comment]
Hi, any news on this ?

**Comment by jmp9292** [comment]
same error here!




Fatal	index	Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(116): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/music\/api...')\n#9 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/apps\/music\/db\/track.php","Line":97}	2015-09-17T09:08:29+00:00
Fatal	index	Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(116): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/music\/api...')\n#9 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/apps\/music\/db\/track.php","Line":97}	2015-09-17T09:02:44+00:00
Fatal	index	Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(116): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()\n#2 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/music\/api...')\n#9 \/var\/www\/owncloud\/index.php(40): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/apps\/music\/db\/track.php","Line":97}

**Comment by maystar** [comment]
Same problem here. When running 
```
occ music:scan -v user
```
in the terminal I got this output:
```
Start scan for user                                 
  [OCP\Files\NotFoundException]  
                             
Exception trace:
 () at /srv/www/htdocs/owncloud/lib/private/files/node/node.php:82
 OC\Files\Node\Node->getFileInfo() at /srv/www/htdocs/owncloud/lib/private/files/node/node.php:176
 OC\Files\Node\Node->getId() at /srv/www/htdocs/owncloud/apps/music/utility/scanner.php:368
 OCA\Music\Utility\Scanner->rescan() at /srv/www/htdocs/owncloud/apps/music/command/scan.php:89
 OCA\Music\Command\Scan->execute() at /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /srv/www/htdocs/owncloud/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /srv/www/htdocs/owncloud/lib/private/console/application.php:94
 OC\Console\Application->run() at /srv/www/htdocs/owncloud/console.php:68
 require_once() at /srv/www/htdocs/owncloud/occ:11

music:scan [--all] [--debug] [user_id1] ... [user_idN]
```

Is there any way to get  the media file name which causes this exception?

I'm using ownCloud version 8.1.3 and music app version 0.3.5. Most of my music files are located on a external local folder. OS is openSUSE 13.2 (arm) with apache 2.4.10 and mysql 5.6.25.

**Comment by jerome-pouiller** [comment]
Same problem here also. With nearly same backtrace:
````
$ sudo -u www-data php -f ./occ music:scan -v user
Start scan for user


                                 
  [OCP\Files\NotFoundException]  
                                 


Exception trace:
 () at /home/www-sysmic-org/owncloud-8.2.0/lib/private/files/node/node.php:84
 OC\Files\Node\Node->getFileInfo() at /home/www-sysmic-org/owncloud-8.2.0/lib/private/files/node/node.php:178
 OC\Files\Node\Node->getId() at /home/www-sysmic-org/owncloud-8.2.0/apps/music/utility/scanner.php:386
 OCA\Music\Utility\Scanner->rescan() at /home/www-sysmic-org/owncloud-8.2.0/apps/music/command/scan.php:93
 OCA\Music\Command\Scan->execute() at /home/www-sysmic-org/owncloud-8.2.0/3rdparty/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /home/www-sysmic-org/owncloud-8.2.0/3rdparty/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /home/www-sysmic-org/owncloud-8.2.0/3rdparty/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/www-sysmic-org/owncloud-8.2.0/3rdparty/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/www-sysmic-org/owncloud-8.2.0/lib/private/console/application.php:97
 OC\Console\Application->run() at /home/www-sysmic-org/owncloud-8.2.0/console.php:69
 require_once() at /home/www-sysmic-org/owncloud-8.2.0/occ:11


music:scan [--all] [--debug] [user_id1] ... [user_idN]
````
I'm using ownCloud version 8.2.0 with music v0.3.8. Most of music files are also located on an external local folder.

**Comment by MorrisJobke** [comment]
Mmh...okay. I also noticed this problem in other issues. Thanks for the report.

**Comment by jerome-pouiller** [comment]
It seems patch bellow solve issue:

```diff
--- owncloud-8.2.0/apps/music/utility/scanner.php    2015-10-30 15:44:34.886591857 +0100
+++ owncloud-8.2.0-mine/apps/music/utility/scanner.php  2015-10-30 15:41:44.483771671 +0100
@@ -383,10 +383,16 @@
                                // break scan - 20 files are already scanned
                                break;
                        }
+                       try {
                        if(in_array($file->getId(), $fileIds)) {
                                // skip this file as it's already scanned
                                continue;
                        }
+                       } catch (\OCP\Files\NotFoundException $e) {
+                           // just ignore the error
+                           $this->logger->log('updateById - file not found - '. $file , 'debug');
+                           continue;
+                       }
                        if($debug) {
                                $before = memory_get_usage(true);
                        }
```

**Comment by jmp9292** [comment]
how i can patch this issue?

**Comment by MorrisJobke** [comment]
> how i can patch this issue?

I will build it into the next release ;)

**Comment by jancborchardt** [comment]
@jerome-pouiller can you open a pull request with that fix?

(@MorrisJobke doesn’t seem you built it into the release yet.)
