### ISSUE TITLE
Unknown artist on SMB Storage with getID3 error Could not open 

### ISSUE THREAD

**Issue by griou** [owncloud/music#415]
### Steps to reproduce
1. Mount a SMB Storage with admin or personal OC WEB-GUI
2. Run scan
### Expected behaviour

mp3 tag are read
### Actual behaviour
- no mp3 tag has been read => Unknown artist for all files. 
- files are readable and writable with OC WEB-GUI  
- music play works fine
- editing mp3 tags located on this storage works fine under windows network drive
- "public $option_max_2gb_check = false;" in getid3.php had no effect 
### Server configuration

**Operating system**: 26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux (VBOX under FreeNAS phpVirtualBox plugin)
**Web server:** Apache/2.4.16 (Ubuntu)
**Database:** 5.5.44-MariaDB-1ubuntu0.14.04.1 - (Ubuntu)
**PHP version:**PHP 5.5.28-1+deb.sury.org~trusty+1 (cli) (built: Aug 16 2015 09:30:05)
**ownCloud version:** 8.1.1.3
**fresh install:** yes
**List of activated apps:**
Enabled:
- activity: 2.0.1
- files: 1.1.10
- files_external: 0.2.3
- files_locking:
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 0.6.0
- music: 0.3.7
- provisioning_api: 0.2
- templateeditor: 0.1
- user_external: 0.4

Disabled:
- encryption
- external
- user_ldap
- user_webdavauth`

**The content of config/config.php:**
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => '192.168.0.11',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.0.11/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbtableprefix' => 'oc_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no
#### ownCloud log (data/owncloud.log)

`{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"update - \/username\/files\/Media\/musique\/Artistes\/Pavement\/Crooked Rain\/07 - Gold Soundz.mp3","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"update - mimetype audio\/mpeg","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"getID3 error occured","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"getID3 error message: Could not open \"oc:\/\/username\/files\/Media\/musique\/Artistes\/Pavement\/Crooked Rain\/07 - Gold Soundz.mp3\" (!is_readable; !is_file)","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"fallback metadata extraction - removed code","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"extracted metadata - artist: , album: , title: Gold Soundz, track#: 7, year: , mimetype: audio\/mpeg, length: , bitrate: , fileId: , this->userId: , userId: username","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"addArtistIfNotExist - exists - ID: 3","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"addAlbumIfNotExist - exists - ID: 3","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"addTrackIfNotExist - added - ID: 10837","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}
{"reqId":"YeATWcePUFgElzadCq2h","remoteAddr":"","app":"music","message":"imported entities - artist: 3, album: 3, track: 10837","level":0,"time":"2015-08-31T17:28:12+00:00","method":"--","url":"--"}`

**Comment by paulijar** [comment]
@griou Is this issue still present with the latest Music app version (currently 0.5.4)?

**Comment by griou** [comment]
Sorry I can't tell you, I don't use this set up anymore (Music app and OC SMB mount) and my owncloud version is not up to date, I can't install Audio Player neither Music app.

I have run a quick test to check if 3rdparty getid3.php was working fine with a SMB folder mounted manually (e.g. : `sudo mount -t cifs //192.168.0.90/test -o user=username /mnt/smb/test`) and I was able to read metadatas with this script [https://github.com/JamesHeinrich/getID3/blob/master/demos/demo.simple.php] so if the bug still occurs it must not be a 3rdparty issue.

**Comment by paulijar** [comment]
I assume that this old issue has got fixed when we stopped using the `oc://` stream wrapper in v0.3.13 (commit 330fc142a2). If anyone still runs into issues like this, they should open a new bug report.
