### ISSUE TITLE
The app grab any image file in the folder to use as album cover and provide no way to change it, except deleting the image

### ISSUE THREAD

**Issue by pellaeon** [owncloud/music#417]
### Steps to reproduce
1. create a empty folder
2. put music files in the folder
3. put a image file in the folder
4. move the image file to somewhere else
### Expected behaviour

The album cover should be reset to unknown
### Actual behaviour

Original image file is kept using as cover

**Comment by MorrisJobke** [comment]
ah .... interesting use case and fully valid I think

**Comment by mitar** [comment]
+1
