### ISSUE TITLE
Use folder name as album name when ID3 tag in music file is not set

### ISSUE THREAD

**Issue by pellaeon** [owncloud/music#418]
The app will group all files with empty ID3 album tag into "Unknown Album", even if the files are in different folder.

I suggest using the parent folder name as album name when ID3 album tag is not set. --Except in user home folder, in that case it is better to still set it to "Unknown Album".

@MorrisJobke what do you think?

**Comment by MorrisJobke** [comment]
Really nice idea :+1:
