### ISSUE TITLE
Re-enable seeking after switching to Backbonejs

### ISSUE THREAD

**Issue by pellaeon** [owncloud/music#421]
Seeking is disabled now due to some AngularJS problem, seeking for FLAC and SoundManager2 supported format should be possible. We should re-enable seeking after switching to Backbone completely.

**Comment by paulijar** [comment]
cc @gnarula 
The seeking was enabled by #536. Seeking is still disabled with Aurora, but migrating to Backbonejs would not help on that. Hence, I'm proposing to close this issue.

**Comment by pellaeon** [comment]
Some background on this, a year ago (I think) @MorrisJobke was going to rewrite the app with Backbonejs, so we decided to enable seeking after migration. But the migration never happened, so we could definitely enable it now.

What are the problems with seeking and Aurorajs now?

**Comment by gnarula** [comment]
Aurorajs' FLAC demuxer doesn't support seeking https://github.com/audiocogs/flac.js/issues/8

**Comment by pellaeon** [comment]
Ah, right, the issue can be closed by now.

**Comment by paulijar** [comment]
@pellaeon Aurora.js' seeking for MP3 files, on the other hand, works but not with all files. With most of my MP3 files, attempting to seek caused the playback to be stopped and it could not be resumed. But with my newer MP3 files, seeking worked fine so it seems to be an issue in Aurora's mp3.js. Some seeking related change was recently merged to mp3.js (https://github.com/audiocogs/mp3.js/pull/20), so it might be worth the shot to give it a new try.
