### ISSUE TITLE
FLAC vorbis - tracknumber and date tags not recognized

### ISSUE THREAD

**Issue by AsavarTzeth** [owncloud/music#430]
### Steps to reproduce
1. Tag FLAC files with following date format (2015-01-01)
2. Upload FLAC files to ownCloud
3. Wait for automatic scan or scan manually
4. Check your how things are presented in the Music app
### Expected behaviour

Like MP3 files I expect the tracks to be prefixed with a 01, 02, 03, etc.
I also expect the album name to be followed by date, example ( Album Name (2015) )

Note the date format I use is the default from MusicBrainz. This however is no issue with id3 tags, which still work with this format. So I am unsure if it is related to my issues.
### Actual behaviour

Track numbers are not recognized and sorting falls back to alphabetic. I am pretty sure this contributes to some similar ampache api issues I have after upgrade (but that is another issue).

I also don't have any dates represented, example (Album Name () )
### Server configuration

**Operating system**:
Ubuntu 15.04

**Web server:**
nginx 1.6.2-5ubuntu3.1

**Database:**
postgresql 9.4.4-0ubuntu0.15.04

**PHP version:**
php-fpm 5.6.4+dfsg-4ubuntu6.2

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
updated

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - documents: 0.10.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - music: 0.3.7
 - provisioning_api: 0.2
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - gallery
 - music.old
 - news
 - ownnote
 - storagecharts2
 - tasks
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'cloud.hembas.se',
  ),
  'datadirectory' => '/volume1/owncloud',
  'overwrite.cli.url' => 'https://cloud.hembas.se',
  'dbtype' => 'pgsql',
  'version' => '8.1.1.3',
  'dbpassword' => '',
  'dbhost' => '/var/run/postgresql',
  'dbtableprefix' => 'oc_',
  'installed' => 'true',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_domain' => 'cloud.hembas.se',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'info',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'logfile' => '/var/log/nginx/owncloud.log',
  'logtimezone' => 'Europe/Stockholm',
  'asset-pipeline.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:**
no
### Client configuration

**Browser:**
Chromium 45.0.2454.85 (64-bit)

**Operating system:**
Arch Linux
#### Web server error log

Nothing related is logged
#### ownCloud log (data/owncloud.log)

Nothing is logged, even under debug (tried rescan)
#### Browser log

Not sure how to do this

**Comment by paulijar** [comment]
The support for date tags formatted like yyyy-mm-dd was added with the commit shown above. I did not see any problem in the track number extraction with FLAC files. I assume it might have got fixed with b5f63717481cde.
