### ISSUE TITLE
Owncloud music hangs

### ISSUE THREAD

**Issue by freakyy85** [owncloud/music#431]
### Steps to reproduce
1. rm -rf music/
2. download latest music zip from apps.owncloud.org.
3. unzip, check enabled inside ownlcoud
### Expected behaviour

The upgrade should work without problems
### Actual behaviour

$ cd owncloud
$ ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Checked database schema update
Checked database schema update for apps
Updated database
Updating <music> ...
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'DELETE FROM `oc_music_scanned_users`;':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_music_scanned_users' doesn't exist
Update failed
Maintenance mode is kept active
$
### Server configuration

**Operating system**:
Linux baby.freakyonline.de 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux

**Web server:**
apache2

**Database:**
MySQL

**PHP version:**
PHP 5.4.45-0+deb7u1 (cli) (built: Sep 10 2015 08:34:47)
**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
updated from i dont know

**List of activated apps:**
Activity  2.0.2
Antivirus App for files  0.7.0.1
Default encryption module  1.0.0
Deleted files  0.6.3
Documents  0.10.2
External storage support  0.2.3
File Locking  
First Run Wizard  1.1
Mail Template Editor  0.1
PDF Viewer  0.7
Pictures  0.6.0
Provisioning API  0.2
Share Files  0.6.2
Text Editor  0.4
Versions  1.0.6
Video Viewer  0.1.3
Chat  0.4.0.0
MP3 Player  1.2.5
Storage Charts 2 Application  2.6.1

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'someid',
  'passwordsalt' => 'somesalt',
  'secret' => 'thesecret',
  'trusted_domains' =>
  array (
    0 => 'mydomain.tld',
    1 => 'cloud.mydomain.tld',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://mydomain.tld/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'mymailnick',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'maildomain',
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => 'theDBPAss',
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'memcache.local' => '\OC\Memcache\Memcached',
  'memcache.distributed' => '\OC\Memcache\Memcached',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
none right now, but plugin installed

**Are you using encryption:** yes/no
yes encryption used.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
none.
### Client configuration

**Browser:**
Chrome, latest

**Operating system:**
Windows 10
#### Web server error log

[Mon Sep 21 16:30:56 2015] [notice] child pid 11646 exit signal Aborted (6)
[Mon Sep 21 16:30:56 2015] [notice] child pid 11917 exit signal Aborted (6)
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st_, memcached_server_write_instance_st, const char_, size_t, const char_, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st_, memcached_server_write_instance_st, const char_, size_t, const char_, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
[Mon Sep 21 16:30:57 2015] [notice] child pid 11906 exit signal Aborted (6)
[Mon Sep 21 16:30:57 2015] [notice] child pid 11913 exit signal Aborted (6)
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st*, memcached_server_write_instance_st, const char*, size_t, const char*, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion`memcached_failed(rc)' failed.
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st_, memcached_server_write_instance_st, const char_, size_t, const char_, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st_, memcached_server_write_instance_st, const char_, size_t, const char_, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st*, memcached_server_write_instance_st, const char*, size_t, const char*, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion`memcached_failed(rc)' failed.
[Mon Sep 21 16:44:25 2015] [notice] child pid 10949 exit signal Aborted (6)
[Mon Sep 21 16:44:25 2015] [notice] child pid 11983 exit signal Aborted (6)
[Mon Sep 21 16:44:25 2015] [notice] child pid 12010 exit signal Aborted (6)
[Mon Sep 21 16:44:25 2015] [notice] child pid 12571 exit signal Aborted (6)
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st_, memcached_server_write_instance_st, const char_, size_t, const char_, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st_, memcached_server_write_instance_st, const char_, size_t, const char_, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion `memcached_failed(rc)' failed.
apache2: libmemcached/storage.cc:341: memcached_return_t memcached_send_ascii(memcached_st*, memcached_server_write_instance_st, const char*, size_t, const char*, size_t, time_t, uint32_t, uint64_t, bool, bool, memcached_storage_action_t): Assertion`memcached_failed(rc)' failed.
[Mon Sep 21 16:44:26 2015] [notice] child pid 12008 exit signal Aborted (6)
[Mon Sep 21 16:44:26 2015] [notice] child pid 12185 exit signal Aborted (6)
[Mon Sep 21 16:44:26 2015] [notice] child pid 12198 exit signal Aborted (6)
#### ownCloud log (data/owncloud.log)

{"reqId":"VgAamrAJU4sAADFNYzsAAAAD","remoteAddr":"79.210.60.67","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-21T14:56:26+00:00"}
{"reqId":"xJdrQ+yKOsoiCJxb1g3h","remoteAddr":"","app":"update","message":"Exception: {\"Exception\":\"Doctrine\\DBAL\\Exception\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'DELETE FROM `oc_music_scanned_users`;':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_music_scanned_users' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'DELETE FROM `oc...', Array)\n#2 \\/var\\/www\\/owncloud\\/lib\\/private\\/db\\/statementwrapper.php(75): Doctrine\\DBAL\\Statement->execute()\n#3 \\/var\\/www\\/owncloud\\/apps\\/music\\/appinfo\\/update.php(25): OC_DB_StatementWrapper->execute()\n#4 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(1174): include('\\/var\\/www\\/ownclo...')\n#5 \\/var\\/www\\/owncloud\\/lib\\/private\\/updater.php(408): OC_App::updateApp('music')\n#6 \\/var\\/www\\/owncloud\\/lib\\/private\\/updater.php(305): OC\\Updater->doAppUpgrade()\n#7 \\/var\\/www\\/owncloud\\/lib\\/private\\/updater.php(195): OC\\Updater->doUpgrade('8.1.3.0', '8.1.3.0')\n#8 \\/var\\/www\\/owncloud\\/core\\/command\\/upgrade.php(181): OC\\Updater->upgrade()\n#9 \\/var\\/www\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Command\\/Command.php(253): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \\/var\\/www\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(874): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \\/var\\/www\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(195): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 \\/var\\/www\\/owncloud\\/3rdparty\\/symfony\\/console\\/Symfony\\/Component\\/Console\\/Application.php(126): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 \\/var\\/www\\/owncloud\\/lib\\/private\\/console\\/application.php(94): Symfony\\Component\\Console\\Application->run(NULL, NULL)\n#14 \\/var\\/www\\/owncloud\\/console.php(68): OC\\Console\\Application->run()\n#15 \\/var\\/www\\/owncloud\\/occ(11): require_once('\\/var\\/www\\/ownclo...')\n#16 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":53}","level":4,"time":"2015-09-21T14:56:51+00:00"}
{"reqId":"VgAaurAJU4sAADFLYiUAAAAC","remoteAddr":"79.210.60.67","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-21T14:56:58+00:00"}
{"reqId":"VgAa2rAJU4sAAC@bC04AAAAI","remoteAddr":"79.210.60.67","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-21T14:57:30+00:00"}
{"reqId":"VgAa@rAJU4sAAC6VhqoAAAAE","remoteAddr":"79.210.60.67","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-21T14:58:02+00:00"}
{"reqId":"VgAbGrAJU4sAADFPZBAAAAAF","remoteAddr":"79.210.60.67","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-21T14:58:34+00:00"}
{"reqId":"VgAbOrAJU4sAADFNYz0AAAAD","remoteAddr":"79.210.60.67","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-21T14:59:06+00:00"}
{"reqId":"VgAbWrAJU4sAADEhQ9oAAAAG","remoteAddr":"79.210.60.67","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(64): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(135): handleException(Object(RemoteException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-21T14:59:38+00:00"}
{"reqId":"VgAbW7AJU4sAADFPZBEAAAAF","remoteAddr":"79.210.60.67","app":"index","message":"Exception: {\"Exception\":\"OC\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/app.php(98): OC_App::loadApp('music')\n#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/util.php(127): OC_App::loadApps(Array)\n#2 \\/var\\/www\\/owncloud\\/lib\\/base.php(873): OC_Util::setupFS()\n#3 \\/var\\/www\\/owncloud\\/index.php(40): OC::handleRequest()\n#4 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/app.php\",\"Line\":118}","level":4,"time":"2015-09-21T14:59:39+00:00"}
{"reqId":"tTHCRpNVRFdSiuwIosx+","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2015-09-21T15:00:01+00:00"}
{"reqId":"tTHCRpNVRFdSiuwIosx+","remoteAddr":"","app":"no app in context","message":"Error while running background job: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2015-09-21T15:00:07+00:00"}

**Comment by paulijar** [comment]
I don't believe that this error is valid anymore. The bug is about unhandled exception when referencing non-existing DB table *PREFIX*music_scanned_users, but the current code base does not contain any references to this table. Closing.
