### ISSUE TITLE
Blank page after OC 8.2

### ISSUE THREAD

**Issue by briskspirit** [owncloud/music#434]
Upgraded to OC 8.2 from 8.1.3 and your app stopped to work, just see blank page. Tried to reinstall and this doesn't helped..

**Comment by MorrisJobke** [comment]
Is there anything in the owncloud.log file in the data dir?

**Comment by briskspirit** [comment]
nope, even with loglevel set to 0

**Comment by briskspirit** [comment]
So any ideas how to catch this error if logs are empty?..

**Comment by MorrisJobke** [comment]
> So any ideas how to catch this error if logs are empty?..

Anything the the browsers JS console? Or in the network tab of the browsers web development console. Maybe there is a request that fails (should also be possible to spot in the access log of the webserver).

Or in the error log of the web server.

**Comment by briskspirit** [comment]
Will try to catch today and write back.

**Comment by MorrisJobke** [comment]
@briskspirit Awesome :) Thanks

**Comment by briskspirit** [comment]
apache2 log is ok
console gave js error:
Error: [$injector:unpr] http://errors.angularjs.org/1.2.21/$injector/unpr?p0=eProvider%20%3C-%20e

And this(on all pages)
Failed to load resource: the server responded with a status of 404 (Not Found)
https://xxx/assets/jquery.min.map

**Comment by MorrisJobke** [comment]
> And this(on all pages)
> Failed to load resource: the server responded with a status of 404 (Not Found)
> https://xxx/assets/jquery.min.map

That one can be ignored.





> console gave js error:
> Error: [$injector:unpr] http://errors.angularjs.org/1.2.21/$injector/unpr?p0=eProvider%20%3C-%20e

This looks interesting. Just to verify: You don't use a JS blocker, right?

**Comment by briskspirit** [comment]
Nope, no blockers. And all worked fine before upgrade to OC 8.2

**Comment by MorrisJobke** [comment]
> Nope, no blockers. And all worked fine before upgrade to OC 8.2

That's even weirder. Because this is the JS part only. What apps do you have installed?

**Comment by briskspirit** [comment]
Anything else I can do/check?

**Comment by MorrisJobke** [comment]
> Anything else I can do/check?

I don't know anything yet :(

**Comment by pedronariyoshi** [comment]
Same thing here. Even same JS error. Besides the official apps, I have: Archive, Documents, Music and ODF reader enabled.

**Comment by briskspirit** [comment]
Oh, about my list of apps - tried to shut off ALL of them, leaving just Music app ))

**Comment by briskspirit** [comment]
Additional error, just got it in log:

**Comment by Akhenaton** [comment]
Same here 
`Error 	no app in context 	Error while running background job: Autoload path not allowed: /var/www/owncloud/apps/music/backgroundjob/cleanup.php`

**Comment by MorrisJobke** [comment]
I will have a look at this on monday. Thanks for the report.

**Comment by ravermeister** [comment]
got a blank page too, if I try to run the command interface:
    Clean up relations (album/artist and playlist/track)
    PHP Fatal error:  Call to undefined method OC\DB\Connection::prepareQuery() in
    /home/ravermeister/cloud.rimkus.it/apps/music/command/resetdatabase.php on line 85

but no errors in apache log

**Comment by MorrisJobke** [comment]
> Clean up relations (album/artist and playlist/track)
> PHP Fatal error:  Call to undefined method OC\DB\Connection::prepareQuery() in
> /path/to/owncloud/apps/music/command/resetdatabase.php on line 85

That one is fixed with https://github.com/owncloud/music/pull/411

**Comment by MorrisJobke** [comment]
I still can not explain the problems that occur for @briskspirit.

**Comment by briskspirit** [comment]
But I am not the only one who has this error )

**Comment by MorrisJobke** [comment]
@pedronariyoshi Anything more in your web dev console? Or at least the complete link that is shown there (because it holds debug information)

**Comment by briskspirit** [comment]
Tried to re-enable and update to 0.3.8 and got this errors to logs:

Exception: {"Exception":"OC\\NeedsUpdateException","Message":"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/app.php(118): OC_App::loadApp('music')\n#1 \/var\/www\/owncloud\/lib\/private\/util.php(130): OC_App::loadApps(Array)\n#2 \/var\/www\/owncloud\/lib\/base.php(830): OC_Util::setupFS()\n#3 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#4 {main}","File":"\/var\/www\/owncloud\/lib\/private\/app.php","Line":139}

===========

Error while running background job: Autoload path not allowed: /var/www/owncloud/apps/music/backgroundjob/cleanup.php


Even tried to install from scratch... removed app dir, DB tables and preferences ...

**Comment by briskspirit** [comment]
And here is full error from browser console(Safari latest):

Error: [$injector:unpr] http://errors.angularjs.org/1.2.21/$injector/unpr?p0=eProvider%20%3C-%20e
c4136fabf9eded279619adec13e5ef55b.js:882:279
d4136fabf9eded279619adec13e5ef55b.js:882:454
(анонимная функция)4136fabf9eded279619adec13e5ef55b.js:884:277
q4136fabf9eded279619adec13e5ef55b.js:855:294
gc4136fabf9eded279619adec13e5ef55b.js:884:251
c4136fabf9eded279619adec13e5ef55b.js:866
fc4136fabf9eded279619adec13e5ef55b.js:866:278
Xc4136fabf9eded279619adec13e5ef55b.js:865:363
(анонимная функция)4136fabf9eded279619adec13e5ef55b.js:1061
c4136fabf9eded279619adec13e5ef55b.js:3:26041
fireWith4136fabf9eded279619adec13e5ef55b.js:3:26841
ready4136fabf9eded279619adec13e5ef55b.js:3:3316
q4136fabf9eded279619adec13e5ef55b.js:3:722

**Comment by briskspirit** [comment]
Sorry for a lot of posts, but for convenience , here is FireFox log:

Content Security Policy: Page parameters blocked download of resource to self ("script-src https://xxxxxx.im 'unsafe-eval'"). music
Error: [$injector:unpr] http://errors.angularjs.org/1.2.21/$injector/unpr?p0=eProvider%20%3C-%20e

So maybe all things is because or this unsafe-eval errors? I am getting them a lot after 8.2

**Comment by MorrisJobke** [comment]
Ah... It just seems like you use the `asset-pipeline.enabled` feature of the config.php and then the JS files gets concatenated. Maybe this is causing the issue.

@pedronariyoshi Do you also have enabled this setting?

@pedronariyoshi @briskspirit Can you try to disable this and retry if it is working then?

**Comment by Akhenaton** [comment]
I do use also the asset-pipeline.enabled feature of the config.php. It speeds up a lot my Gallery app.
I will try to disable it as a temporary workaround.

**Comment by MorrisJobke** [comment]
> I do use also the asset-pipeline.enabled feature of the config.php. It speeds up a lot my Gallery app.
> I will try to disable it as a temporary workaround.

Okay. So this seems to be the root of the issues. Good to know. Let me check why it causes issues.

**Comment by briskspirit** [comment]
Yep, that was a problem! Now all works like it should. And no errors in browser console!

**Comment by pedronariyoshi** [comment]
Yes! Disabling the pipelining is a workaround this bug.

Pedro Nariyoshi

**Comment by Akhenaton** [comment]
But only a "workaround". We (I) really need the "assets" setting for speeding-up things in other apps.

Many thanks to MorrisJobke to have quickly pick up this issue !

**Comment by Spacefish** [comment]
I still experience the same bug with the latest master branch of owncloud (Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.2.21/$injector/unpr?p0=eProvider%20%3C-%20e)

Disabling pipelining fixes the problem.

The patch linked here (#20461) is present in my installation, but does not resolve the issue.

**Comment by trupf** [comment]
This bug is still existing in current version (v0.3.10 2016-03-09). Are there any plans to resolve it? Minification is important as it speeds up owncloud considerably. I'm not sure if this issue in Debian: 
refers to the same issue, but if it is resolved there you may check what they have changed:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796814

**Comment by benediktg** [comment]
@MorrisJobke has once recommended me to better let asset pipelining be disabled because it does not improve the performance that much anyway.

**Comment by paulijar** [comment]
I have found a fix for this bug with asset pipelining. There is a single injection annotation missing. In the file js/public/app.js the block
`.run(function(Token, Restangular){
		// add CSRF token
		Restangular.setDefaultHeaders({requesttoken: Token});
	});
`
should be
`.run(['Token', 'Restangular',
	function(Token, Restangular){
		// add CSRF token
		Restangular.setDefaultHeaders({requesttoken: Token});
	}
]);
`
With this change, the code survives minification and works like a charm.

**Comment by Gomez** [comment]
Cool @paulijar! Would you create a PR and ping me? I can test it.

**Comment by paulijar** [comment]
Ping @Gomez. I created the pull request. I hope it went right since this is my first open source contribution ever :).
