### ISSUE TITLE
Get tags in right encoding

### ISSUE THREAD

**Issue by briskspirit** [owncloud/music#435]
After scan I saw artists and song names like Áàíäåðîñ , in DB it written wrong too, but there is utf8 collation set.
Can you fix this please so your app will read tags in utf8 and store them that way.

Thanks.

**Comment by paulijar** [comment]
@briskspirit This is likely the same issue as #410, or at least closely related. The problem and fix comes from the getID3 library and is handled there in https://github.com/JamesHeinrich/getID3/issues/80. The most recent Music app releases contain the fixed version of getID3. Can you retest with Music app 0.4.3?

**Comment by paulijar** [comment]
I assume this has got fixed.
