### ISSUE TITLE
ID3 Tags not properly scanned

### ISSUE THREAD

**Issue by Laures** [owncloud/music#440]
I created an arm 32bit docker image for my raspberry and in there all set id3 tags on my mp3s are interpreted as empty strings. for owncloud my collection looks like this:

``` json
[
  {
    "id": 1,
    "name": "",
    "albums": [{
        "name": "",
        "year": null,
        "cover": null,
        "id": 1,
        "tracks": [{
            "title": "",
            "number": null,
            "artistId": 1,
            "albumId": 1,
            "files": {"audio/mpeg": "http://192.168.1.83/remote.php/webdav/music/01 When I'm Gone.mp3"},
            "id": 1
          }]
      }]
  },
...
  {
    "id": 12,
    "name": "Unknown artist",
    "albums": [{
        "name": "",
        "year": null,
        "cover": null,
        "id": 12,
        "tracks": [{
            "title": "",
            "number": null,
            "artistId": 12,
            "albumId": 12,
            "files": {"audio/mpeg": "http://192.168.1.83/remote.php/webdav/music/12 _Untitled Hidden Track_ ___.mp3"},
            "id": 12
          }]
      }]
  }
...
]
```
### Steps to reproduce
1. install owncloud with owncloud music on alpine linux
2. upload tagged audio file
3. id3 check music app and see a pretty white page
### Expected behaviour

audio files should show up with title / artist / thumbnail
### Actual behaviour

the page is white because everything is shown as an empty string (playback works)
only tags with no content seem to work. files with no artist are shown as unknown artist
### Server configuration

**Operating system**:
alpine linux

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.0.8

**Updated from an older ownCloud or fresh install:**
fresh, dockerized version

**List of activated apps:**
    owncloud-mysql 
    owncloud-videoviewer 
    owncloud-pdfviewer 
    owncloud-music 
    owncloud-documents 
    owncloud-tasks 
    owncloud-texteditor 
    owncloud-calendar 
    owncloud-contacts
    owncloud-external 
    owncloud-encryption 
    owncloud-mozilla_sync 

**The content of config/config.php:**

$CONFIG = array (
  'datadirectory' => '/DATA/data',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/webapps/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/DATA/apps',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'version' => '8.0.8.0',
  'dbname' => '',
  'dbhost' => 'mysql',
  'dbuser' => '',
  'installed' => true,
  'loglevel' => '3',
  'logfile' => '/DATA/logs/owncloud/owncloud.log',
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'instanceid' => 'ocydjoamlggx',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '192.168.1.83',
  ),
  'overwrite.cli.url' => 'http://192.168.1.83',
  'dbtype' => 'mysql',
  'dbtableprefix' => 'oc_',
  'dbpassword' => '',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
chrome

**Operating system:**
windows 10
#### Web server error log

2015/11/01 12:50:20 [warn] 34#0: *71 an upstream response is buffered to a temporary file /tmp/nginx/fastcgi_temp/5/02/0000000025 while reading upstream, client: 192.168.1.2, server: owncloud.psi, request: "GET /remote.php/webdav/music/07%20I%20Feel%20You.mp3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/music/"
2015/11/01 12:50:21 [warn] 34#0: *71 an upstream response is buffered to a temporary file /tmp/nginx/fastcgi_temp/6/02/0000000026 while reading upstream, client: 192.168.1.2, server: owncloud.psi, request: "GET /remote.php/webdav/music/07%20I%20Feel%20You.mp3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/music/"
2015/11/01 12:50:23 [warn] 34#0: *71 an upstream response is buffered to a temporary file /tmp/nginx/fastcgi_temp/7/02/0000000027 while reading upstream, client: 192.168.1.2, server: owncloud.psi, request: "GET /remote.php/webdav/music/07%20I%20Feel%20You.mp3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/music/"
2015/11/01 12:50:24 [warn] 34#0: *71 an upstream response is buffered to a temporary file /tmp/nginx/fastcgi_temp/8/02/0000000028 while reading upstream, client: 192.168.1.2, server: owncloud.psi, request: "GET /remote.php/webdav/music/07%20I%20Feel%20You.mp3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/music/"
2015/11/01 12:51:53 [warn] 33#0: *99 a client request body is buffered to a temporary file /tmp/nginx/body/9/02/0000000029, client: 192.168.1.2, server: owncloud.psi, request: "POST /index.php/apps/files/ajax/upload.php HTTP/1.1", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/files"
2015/11/01 14:13:22 [warn] 17#0: *6 a client request body is buffered to a temporary file /tmp/nginx/body/1/00/0000000001, client: 192.168.1.2, server: owncloud.psi, request: "POST /index.php/apps/files/ajax/upload.php HTTP/1.1", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/files"
2015/11/01 14:13:25 [warn] 17#0: *9 a client request body is buffered to a temporary file /tmp/nginx/body/2/00/0000000002, client: 192.168.1.2, server: owncloud.psi, request: "POST /index.php/apps/files/ajax/upload.php HTTP/1.1", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/files"
2015/11/01 14:13:29 [warn] 17#0: *9 a client request body is buffered to a temporary file /tmp/nginx/body/3/00/0000000003, client: 192.168.1.2, server: owncloud.psi, request: "POST /index.php/apps/files/ajax/upload.php HTTP/1.1", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/files"
2015/11/01 14:13:34 [warn] 17#0: *9 a client request body is buffered to a temporary file /tmp/nginx/body/4/00/0000000004, client: 192.168.1.2, server: owncloud.psi, request: "POST /index.php/apps/files/ajax/upload.php HTTP/1.1", host: "192.168.1.83", referrer: "http://192.168.1.83/index.php/apps/files"
2015/11/01 15:01:06 [error] 18#0: *91 access forbidden by rule, client: 172.17.42.1, server: owncloud.psi, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "192.168.1.83"
#### ownCloud log (data/owncloud.log)

{"reqId":"295faa1a869d30ed0f975880d46c25e6","remoteAddr":"192.168.1.2","app":"PHP","message":"Trying to get property of non-object at \/usr\/share\/webapps\/owncloud\/lib\/private\/ocsclient.php#186","level":3,"time":"2015-11-01T12:38:15+00:00"}
{"reqId":"295faa1a869d30ed0f975880d46c25e6","remoteAddr":"192.168.1.2","app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2015-11-01T12:38:15+00:00"}
{"reqId":"295faa1a869d30ed0f975880d46c25e6","remoteAddr":"192.168.1.2","app":"PHP","message":"Trying to get property of non-object at \/usr\/share\/webapps\/owncloud\/lib\/private\/ocsclient.php#186","level":3,"time":"2015-11-01T12:38:16+00:00"}
{"reqId":"295faa1a869d30ed0f975880d46c25e6","remoteAddr":"192.168.1.2","app":"PHP","message":"Trying to get property of non-object at \/usr\/share\/webapps\/owncloud\/lib\/private\/ocsclient.php#186","level":3,"time":"2015-11-01T12:38:16+00:00"}
{"reqId":"295faa1a869d30ed0f975880d46c25e6","remoteAddr":"192.168.1.2","app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2015-11-01T12:38:16+00:00"}
{"reqId":"af14b171fa7be06b32b50bb454648836","remoteAddr":"192.168.1.2","app":"PHP","message":"Trying to get property of non-object at \/usr\/share\/webapps\/owncloud\/lib\/private\/ocsclient.php#186","level":3,"time":"2015-11-01T12:38:25+00:00"}
{"reqId":"af14b171fa7be06b32b50bb454648836","remoteAddr":"192.168.1.2","app":"PHP","message":"Trying to get property of non-object at \/usr\/share\/webapps\/owncloud\/lib\/private\/ocsclient.php#186","level":3,"time":"2015-11-01T12:38:25+00:00"}
{"reqId":"af14b171fa7be06b32b50bb454648836","remoteAddr":"192.168.1.2","app":"core","message":"Invalid OCS content returned for app music","level":4,"time":"2015-11-01T12:38:25+00:00"}

**Comment by Laures** [comment]
you can find my dockerfile here: https://github.com/BenevolentCoders/rpi-owncloud

**Comment by pellaeon** [comment]
@Laures could you try decoding your music files with [getID3](https://github.com/JamesHeinrich/getID3/) ? it's the underlying library music-app uses to decode ID3 tags.

**Comment by paulijar** [comment]
@Laures Is this issue still present with the latest Music app version (currently 0.5.4)?

**Comment by paulijar** [comment]
With almost a month without reply, I assume that this old issue is gone by now. Closing.
