### ISSUE TITLE
Music 0.3.8: Does not work in ownCloud 8.1.4

### ISSUE THREAD

**Issue by kneiser** [owncloud/music#441]
I was able to successfully update to this version of music. It displays the music file names, but it will not play any mp3 files. No errors apparent in ownCloud log.

**Comment by MorrisJobke** [comment]
Is there a notification at the top once you click the play icon?

**Comment by kneiser** [comment]
I did not see anything. I tried playing several mp3s each time nothing happened.

**Comment by MorrisJobke** [comment]
> I did not see anything. I tried playing several mp3s each time nothing happened.

Is the play bar visible?

**Comment by zaphbbrox** [comment]
same here.. no play bar, only the play icon at the song name.
Downgraded to 0.3.7 and it's working

**Comment by inc002** [comment]
same here.. no play bar, only the play icon at the song name.
Downgraded to 0.3.7 (just unzip folder music to apps folder) and it's working

**Comment by MorrisJobke** [comment]
I'm on it. Will release something soon.

**Comment by aauzi** [comment]
I was facing that as well and managed to turn around the problem with the attached patch.

[music-0.3.8-2.patch.zip](https://github.com/owncloud/music/files/74324/music-0.3.8-2.patch.zip)

**Comment by benediktg** [comment]
In my opinion this issue is obsolete now since 9.0.1 is the current version and Music works there…

**Comment by MorrisJobke** [comment]
> In my opinion this issue is obsolete now since 9.0.1 is the current version and Music works there…

Not really ... I need to check this out. The goal is to have a single app that works on all current versions.
