### ISSUE TITLE
Owncloud Music 0.3.8 Korean encoding

### ISSUE THREAD

**Issue by JinhaPark** [owncloud/music#448]
I would really appreciate if the Korean letters also show up as well.

Thanks in advance.

**Comment by meowers** [comment]
Most of my music is Japanese and all I can see is question marks.

**Comment by pellaeon** [comment]
Do you guys have Korean & Japanese characters in ID3 tags or the file names, or both?

**Comment by JinhaPark** [comment]
They are contained in both. However it fails when the MP3 file contains Korean characters in ID3 tags. 
Thank you for your interests.

**Comment by pellaeon** [comment]
If possible, could you send me the files?

**Comment by JinhaPark** [comment]
Sure. It's sent to your email.

**Comment by pellaeon** [comment]
@JinhaPark your music file cannot be correctly parsed in getID3, the PHP library that parses ID3 tags. This means the problem is not on the music app's side. Below is the byte sequence of the `artist` field parsed in id3v2 from your music file `부활-06-Never Ending Story.mp3`:
```
0000000: c2ba c38e c388 c2b0                      ........
```

`album` field:
```
0000000: c2bb c3b5 c2ba c2ae                      ........
```

Do you have any idea what encoding are used in those fields? And do you know any application that can correctly parse the file?

**Comment by KKido** [comment]
I think it's UTF-16 in HEX.
First one will be 슺쎎쎈슰 then. @JinhaPark am I right?
I'm using this site: https://codepoints.net/

**Comment by pellaeon** [comment]
I don't think so, searching for 슺쎎쎈슰 on google returns no result, which is highly unlikely.

**Comment by JinhaPark** [comment]
@pellaeon 
 Recently I also found out that it shows up well on the mobile owncloud clients (both iPhone/Android), showing the correct filename.
However the problem still resides when the files are opened through Music app from the desktop PCs. 

Also same problem rised in Audacity: recognizes the file name but {"Artist Name", "Track Title","Album Title"} in "MetaData Tags" do not show up with correct encodings. 

The problem was with the mp3 file itself. I'll need to change the metadata tags in the mean time.

Thank you very much for your time and effort.

Jinha Park

@KKido
 it rather shows something like ºÎÈ° »õº®

**Comment by pellaeon** [comment]
There is no problem with the filename, but music app reads the ID3 tags. The problem lies within your ID3 tags.

If you cannot find an application that is able to parse your tags, it likely means the tags are encoded incorrectly at the first place.

**Comment by JinhaPark** [comment]
@pellaeon 
That's right.

**Comment by meowers** [comment]
I think I may have found the problem. Well at least for me. I used getID3 to check one of my songs that were only appearing as question marks. The ID3v1 tag would show question marks, but the ID3v2 would show as Japanese. 

From what I understand ID3v1 uses ISO-8859-1 which is only Latin characters. ID3v2 uses UFT-8 or UTF-16, but they both recognize Asian characters. 

If the Music app ignored the ID3v1 tags it would fix the Asian characters issue. If not, I'd have to figure out how to delete all the ID3v1 tags in my music. 

![3](https://cloud.githubusercontent.com/assets/6345920/13567386/12cb1370-e4af-11e5-95a9-b495a8f984c7.JPG)

**Comment by pellaeon** [comment]
@meowers it seems to be that the way getID3 is implemented. Music app calls getID3's `CopyTagsToComments()`, which only seems to look at id3v1 tags.
