### ISSUE TITLE
Argument 10 passed to OCA\\Music\\Controller\\ApiController::__construct() must be an instance of OCP\\Files\\Folder, null given

### ISSUE THREAD

**Issue by mitar** [owncloud/music#456]
I am getting quite a lot of the following errors in the log:

> "app":"PHP","message":"Argument 10 passed to OCA\Music\Controller\ApiController::__construct() must be an instance of OCP\Files\Folder, null given, called in
>  \/var\/www\/owncloud\/apps\/music\/app\/music.php on line 89 and defined at \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php#63","level":3

Using 7f79afb4ae9a6ecd8f530d87106f960306c0a15a version.

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/music/pull/452 <- could possibly fix this.

**Comment by mitar** [comment]
Hm, but it s a different exception?

**Comment by MorrisJobke** [comment]
> Hm, but it s a different exception?

Ah right. This one here is in the controller.

As a workaround you can drop the music database and rescan it. 

```
./occ music:reset-database
```

Then the rescan will happen and the error should be gone.

**Comment by MorrisJobke** [comment]
The actual fix would involve a try catch in the controller method and drop the entries then there directly.

**Comment by mitar** [comment]
> As a workaround you can drop the music database and rescan it. 

Yes, I did this few hours ago. But it is back. :-(

**Comment by MorrisJobke** [comment]
Okay :(

**Comment by paulijar** [comment]
@mitar So much has changed in the Music app after the reporting of this issue that I doubt that this is still valid. Do you still have the problem with Music app 0.5.0?

**Comment by mitar** [comment]
I haven't yet updated. But I think we should probably close this and if I will issues we can always reopen.

**Comment by paulijar** [comment]
Closing for now
