### ISSUE TITLE
»This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later.«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#461]
@MorrisJobke what is the minimum ownCloud version? I can prepare a pull request if you don’t have time.

**Comment by MorrisJobke** [comment]
woot? Minimum should be 7 - maximum is current master. 

https://github.com/owncloud/music/blob/master/appinfo/info.xml#L9

**Comment by jancborchardt** [comment]
Seems that’s super-old syntax. See https://github.com/owncloud/core/pull/21808/files#diff-fea49f0732d061e089d5ce81b2483176L10 on how the syntax needs to be :)

**Comment by gouglhupf** [comment]
In the current master branch the bug does not occur. In the 0.3.10 release the "<dependencies>" tags are missing. Commit "dc8809b" has fixed it. fixes #461

**Comment by jancborchardt** [comment]
@MorrisJobke @gouglhupf  is that one released on the app store yet?

**Comment by gouglhupf** [comment]
The current version in the app store is 0.3.10. So the fix is not included.

**Comment by gouglhupf** [comment]
The only difference form the master and the "0.3.10" release is the info.xml fix and this fix: https://github.com/owncloud/music/commit/35a958f2f7f3519bf61f40ce5ef4a06f7c645947.

**Comment by jancborchardt** [comment]
@MorrisJobke mind releasing a new version to fix this?

**Comment by benediktg** [comment]
@MorrisJobke I think this is fixed now.

**Comment by MorrisJobke** [comment]
Yep. Fixed in 0.3.11 that I released yesterday.
