### ISSUE TITLE
Music "Light" request

### ISSUE THREAD

**Issue by traxxion** [owncloud/music#464]
This is a request for a version of the Music app that strips out all library functions and simply plays a file when clicked in the "Files" app and/or presents the files as in the "Files" app. 

The library functions of audio playback software are ever a hindrance to functionality (always have been) and assume that unlike any other files in the world, audio files somehow require ID3 tagging in order to be "organised". ID3 tags are extremely useful, but as a means of organisation are often mistaken.

If it is not a very difficult request, I would really appreciate a light version of Music for owncloud that removes the scanning and library database functions, or minimises them. This would also provide a fallback app for those who encounter library and db bugs. 

If it also presents the album art, either that already present in the folder or album art otherwise retrieved that would be good, as long as the mechanism is as simple as possible! 

Presenting ID3 tags read directly from the "current" file/folder would be nice.

A playlist function would be very beneficial.

Thanks

**Comment by paulijar** [comment]
I, too, believe that if the user clicks on an audio file in the Files app, then more often than not she would just like to listen to that specific track. Throwing her to the Music app distracts the natural flow.

It is also possible that the clicked audio file is outside of the path which has been configured to be scanned by the Music app. In that case, the clicked audio file will not show up in the Music app and it is impossible to play it.

I would prefer to see opening an audio file from the Files app to work like this:
1. Clicking the audio file would bring up a small pop-up player and start playing the track.
2. The pop-up would have buttons for play/pause, a seek bar, and possibly a volume control.
3. The pop-up would also have a link "Show in music library" which would open the full Music app. This link could be hidden if the track is not within the path scanned by the Music app.

**Comment by paulijar** [comment]
This feature is implemented in the brand new release v0.5.0.
