### ISSUE TITLE
Can listen music files in iOS apps but not in OwnCloud PC

### ISSUE THREAD

**Issue by Biopticon** [owncloud/music#465]
I can access my music files and listen them in my iPhone and iPad apps but not in my OwnCloud Music app on my PC? Do I need to install a music (e.g. MP3) player program under Win 7 on my PC?

**Comment by paulijar** [comment]
@Biopticon This is a very old issue but for some reason no-one has ever responded. Do you still have the problem with the most recent Music app version (currently 0.5.0)? If yes, then which web browser are you using? As an answer to your question, there's no need to install any extra applications to your PC.

**Comment by paulijar** [comment]
With no reply in one month, I assume that this issue has got fixed by newer releases of the Music app.
