### ISSUE TITLE
Can't scan music 

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/music#469]
Hello 

An new issue for me. I can't scan music. 
### Steps to reproduce
1. Using the occ command to scan for music 
### Expected behaviour

I can't scan for music. An error appears. 
### Actual behaviour

Scan stops with this error log. 

```
root@h2530151:/var/www/owncloud# sudo -u www-data php occ music:scan --debug Lars
Start scan for Lars



  [OCP\Files\NotFoundException]



music:scan [--all] [--debug] [user_id1] ... [user_idN]
```
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache 2.4.7
**Database:**
Mysql 14.14
**PHP version:**
Php 5.5.9
**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Fresh install 

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - audios: 1.2.5
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - files_videoviewerplus: 0.0.1
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - music: 0.3.8
  - news: 7.1.1
  - notes: 2.0.0
  - notifications: 0.1.0
  - ocdownloader: 1.5
  - ownbackup: 0.3.7
  - provisioning_api: 0.3.0
  - tasks: 0.8.1
  - templateeditor: 0.1
Disabled:
  - encryption
  - external
  - files_w2g
  - galleryplus
  - ownnote
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocpsovzwa7ww",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "81.169.130.87",
            "cloud.smartdroidblog.de",
            "h2530151.stratoserver.net"
        ],
        "datadirectory": "\/mnt\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/81.169.130.87\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APC",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ],
            [
                "cloud.smartdroidblog.de",
                11211
            ]
        ],
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 
No

**Comment by Happyfeet01** [comment]
[code] Info    music   Rescan finished (0/0)   2016-03-23T08:47:59+00:00
Info    music   Rescan triggered    2016-03-23T08:47:55+00:00
Info    music   Rescan finished (0/931) 2016-03-23T08:47:55+00:00
Info    music   Rescan triggered    2016-03-23T08:47:51+00:00
Info    music   Rescan finished (0/0)   2016-03-23T08:47:51+00:00
Info    music   Rescan triggered    2016-03-23T08:47:47+00:00
Info    cli Memcache \OC\Memcache\APCu not available for local cache    2016-03-23T08:47:46+00:00
Info    music   Rescan finished (0/0)   2016-03-23T08:47:00+00:00
Info    music   Rescan triggered    2016-03-23T08:46:56+00:00
Info    cli Memcache \OC\Memcache\APCu not available for local cache[/code]

**Comment by derkostka** [comment]
Hi,

same issue for me. But i don´t get any Errors, here is the log, is dies not even begin to scan. Any possibility to debug ?

{"reqId":"JtItc1jUBdGaLIT\/JZuN","remoteAddr":"","app":"music","message":"Rescan triggered","level":1,"time":"March 26, 2016 17:44:13","method":"--","url":"--"}

{"reqId":"JtItc1jUBdGaLIT\/JZuN","remoteAddr":"","app":"music","message":"Rescan finished (0\/0)","level":1,"time":"March 26, 2016 17:44:13","method":"--","url":"--"}

**Comment by pellaeon** [comment]
I suggest changing loglevel to debug (change the value to `0` if I remember correctly) and see if there are related log messages.

**Comment by paulijar** [comment]
@Happyfeet01 @derkostka Is this old issue still valid with the most recent Music app version (currently 0.5.0)?

**Comment by paulijar** [comment]
With no reply in one month, I assume that this issue has got fixed by newer releases of the Music app.
