### ISSUE TITLE
Track filtering

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#47]
> The track listing accepts one of two possible parameters to filter down the list only to those tracks corresponding to a given `album` or `artist`.

**Comment by jancborchardt** [comment]
Closing in favor of search: https://github.com/owncloud/music/issues/367

**Comment by jancborchardt** [comment]
Or wait, this is Shiva API?

**Comment by paulijar** [comment]
It seems to me that this Shiva API feature was implemented already 9 days after this issue has been created, in commit b6e51ffb34. I don't know why this issue has been hanging here for five years but now I'm closing it.
