### ISSUE TITLE
[OC 9RC2] blank page

### ISSUE THREAD

**Issue by tflidd** [owncloud/music#470]
Testsystem: OC 9.0 RC2, Debian 8, Apache, mod_php 7.0.4 (dotdeb), mysql
#### Steps to reproduce
1. Download music app 0.3.8
2. Activate app
3. go to music app

#### what happens
Blank screen.

#### logfiles
````
{"reqId":"YsyhGShrysBsTJfKfpqI","remoteAddr":"my-ip","app":"PHP","message":"Call to undefined method OC\\L10N\\L10N::findLanguage() at \/var\/www\/oc9\/apps\/music\/controller\/pagecontroller.php#43","level":3,"time":"2016-03-06T11:42:53+00:00","method":"GET","url":"\/oc9\/index.php\/apps\/music\/"}
````

**Comment by MorrisJobke** [comment]
I just released 0.3.9 on the App Store and on github: https://github.com/owncloud/music/releases/tag/v0.3.9

This is fixed in that version.
