### ISSUE TITLE
"PHP","message":"Call to a member function __toString() on string at \/var\/www\/owncloud\/apps\/music\/db\/artist.php#51","level":3,"time"

### ISSUE THREAD

**Issue by Akhenaton** [owncloud/music#473]
OwnCloud 9.0.0 Music 0.3.9

Got a spinning weel on a blank page when calling the music app.

The log shows : 
{"reqId":"OBzZzfDiVOrUOlojsFLh","remoteAddr":"private-data","app":"PHP","message":"Call to a member function __toString() on string at \/var\/www\/owncloud\/apps\/music\/db\/artist.php#51","level":3,"time":"2016-03-08T18:49:27+00:00"}

Any idea ?

**Comment by MorrisJobke** [comment]
Most likely https://github.com/owncloud/music/pull/476 will fix it.

**Comment by JB1985** [comment]
@MorrisJobke 

i have install the fix -> https://github.com/owncloud/music/commit/120446424a098f2568be5c47bab8b9d70e08f49f

But I can not hear music. All time it is loading ... but bothing to hear :( I cant see anything in the logs.

Trying with firefox and chrome.

OC9.0 with Music 0.3.9 with the fix above.

**Comment by MorrisJobke** [comment]
> Trying with firefox and chrome.

Okay. But if the error is gone, then this is the first part of the fix. @JB1985 Could you check the web developer tools console for some output?

**Comment by JB1985** [comment]
HEAD https://oc3.jaba.hosting/remote.php/webdav/Muzik%202016/muzikj%202016.mp3 401 (Unauthorized)

**Comment by MorrisJobke** [comment]
> HEAD https://oc3.jaba.hosting/remote.php/webdav/Muzik%202016/muzikj%202016.mp3 401 (Unauthorized)

This is fixed with https://github.com/owncloud/music/pull/475

**Comment by JB1985** [comment]
Thanks! Works :+1:

**Comment by MorrisJobke** [comment]
@JB1985 I just released 0.3.10 with both fixes included.

**Comment by Akhenaton** [comment]
Woooh, that's quick..... and Works ! Thank you.   :clap:
