### ISSUE TITLE
Any way to change sort order?

### ISSUE THREAD

**Issue by smartroad** [owncloud/music#477]
Is there anyway to change the sort order? I would just like the list to display albums. At the moment all I have is a massive list sorted by artist/album/album year

One of my 'Albums' has about 100 tracks by different artists and years so my list is very large and unwieldy. I have been looking for a settings 'cog' but can't seem to find one :disappointed: I guess it is hardcoded at the moment or I am blind and can't see it!

**Comment by MorrisJobke** [comment]
cc @owncloud/designers for some idea about this use case

**Comment by paulijar** [comment]
Closing as duplicate of #429
