### ISSUE TITLE
Can't play any song: JS Error 401 (Unauthorized)

### ISSUE THREAD

**Issue by sarkona** [owncloud/music#479]
Hi there,
Iam really new to owncloud. But here is my setting:
owncloud 9.0
music: 0.3.10

My Problem is that no Song wont play. I really searched the web for hours but didn't find a solution. 
I think there is a problem with Javascript. My Developertool in Chrome tells me something like this:

HEAD https://xxx.xxx.xxx/remote.php/webdav/song.mp3 401 (Unauthorized)
HTTPSource.start 
@ aurora.js?v=cc0676c…:3780Asset.start 
@ aurora.js?v=cc0676c…:86Player.preload 
@ aurora.js?v=cc0676c…:3454Player.play 
@ aurora.js?v=cc0676c…:3463(anonymous function) 
@ app.js?v=cc0676c…:380k.$digest 
@ angular.min.js?v=cc0676c…:109k.$apply 
@ angular.min.js?v=cc0676c…:112(anonymous function) 
@ angular.min.js?v=cc0676c…:193x.event.dispatch 
@ jquery.min.js?v=cc0676c…:5v.handle 
@ jquery.min.js?v=cc0676c…:5

And this error comes when I want to play a song. The loading image appears but is grey and wont change or play anything.

What can I do to make that run?

**Comment by sarkona** [comment]
Really no Idea? No one? Please give me a hint for that....

**Comment by paulijar** [comment]
@sarkona I have no idea what has caused this problem, but quite much has changed in the Music app during the last year. Do you still have this problem with Music app 0.5.0?

**Comment by paulijar** [comment]
With no reply in one month, I assume that this issue has got fixed by newer releases of the Music app.
