### ISSUE TITLE
Faulty app code

### ISSUE THREAD

**Issue by ezraholm50** [owncloud/music#483]
Music  0.3.10
ownCloud 9.0.0 (stable)

Enabling the app gives me the error that the app has a faulty code.
Before the new version 3.10 it had no errors. Might needs to be signed again since its an approved app?

Thanks for this app!

**Comment by enoch85** [comment]
cc @MorrisJobke

**Comment by MorrisJobke** [comment]
@ezraholm50 Which PHP version and webserver do you use?

**Comment by ezraholm50** [comment]
Php 7.0.5-2 and Apache 2.4.12

Op vr 1 apr. 2016 10:39 schreef Morris Jobke <notifications@github.com>:

> @ezraholm50 <https://github.com/ezraholm50> Which PHP version and
> webserver do you use?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/music/issues/483#issuecomment-204309511>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by MorrisJobke** [comment]
Is there anything in the owncloud log?

**Comment by ezraholm50** [comment]
No... shows up empty, just a core error because of files_antivirus.
I'll try the dev console from the browser to investigate. Will report back.

**Comment by MorrisJobke** [comment]
> I'll try the dev console from the browser to investigate. Will report back.

Thanks

**Comment by ezraholm50** [comment]
Error went away, tested it a few times. Removing the folder, no errors anymore?!
Must be my build... sorry for the inconvenience!
