### ISSUE TITLE
Music 0.3.10 blank screen on Owncloud 9 when "asset-pipeline.enabled" is set to "true"

### ISSUE THREAD

**Issue by roru69** [owncloud/music#484]
Music 0.3.10 blank screen on Owncloud 9 when "asset-pipeline.enabled" is set to "true" in Config.php

This setting is recommended bij Gallery+ 15 to speed up things. Everything works except Mucic 0.3.10 which shows a blank sceen when.

When the setting is removed, Music works as expected.

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/owncloud/music/issues/434
