### ISSUE TITLE
No playlist options and controls over the scroll bar

### ISSUE THREAD

**Issue by alaintxu** [owncloud/music#487]
I can not see any playlist options. I am currently using OwnCloud 9.0.0 and 0.3.10 version of the app. I can only see the list of all songs and the controls. Aren't they implemented yet?

Another issue is that the controls appear over the scroll bar on the top-right side. When scanning the files, the scanning message also appears over the scroll bar on the bottom-right side.

**Comment by paulijar** [comment]
The playlist controls were finally integrated with PR #555. The issue of controls appearing over the scroll bar was fixed earlier by PR #540.
