### ISSUE TITLE
App can't be updated from 0.3.10 to 0.3.11

### ISSUE THREAD

**Issue by RealRancor** [owncloud/music#488]
Hi,

when trying to update from 0.3.10 to 0.3.11 the following message is shown:

> App can't be installed because the version in info.xml/version is not the same as the version reported from the app store

The appstore download at https://apps.owncloud.com/content/show.php/Music?content=164319 is indeed serving 0.3.10 instead of 0.3.11.

The issue might be caused by https://github.com/owncloud/appstore-issues/issues/55

**Comment by MorrisJobke** [comment]
Thanks for noticing.

**Comment by MorrisJobke** [comment]
I will try to reupload, maybe this helps.

**Comment by MorrisJobke** [comment]
> I will try to reupload, maybe this helps.

Didn't helped, but I now provided a link to the github release download, which works.

**Comment by RealRancor** [comment]
Works now, thanks for fixing :+1:
