### ISSUE TITLE
Rescanning music generates lots of "Info" log entries

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#489]
Music app V 0.3.11 on ownCloud 9.1.0 pre alpha (git)

When you rescan your library, you do get tons of "Info" messages logged.
Maybe the logging level could be set to "Debug" and just a start and end task log entry could be made on level "Info".

```
...
Info    music   Rescan finished (10322/10322)   2016-04-11T11:10:26+02:00
Info    music   Rescan triggered                2016-04-11T11:10:17+02:00
Info    music   Rescan finished (10320/10322)   2016-04-11T11:10:17+02:00
Info    music   Rescan triggered                2016-04-11T11:10:08+02:00
Info    music   Rescan finished (10300/10322)   2016-04-11T11:10:07+02:00
...
```

**Comment by MorrisJobke** [comment]
Maybe @benediktg want to have a look at this :)

**Comment by benediktg** [comment]
I am not getting "spam" into the logs after executing
```
sudo -u www-data php /var/www/owncloud/occ music:scan --all
```

(Owncloud v9.0.1 and Music v0.3.11 (git master))

**Comment by MorrisJobke** [comment]
> I am not getting "spam" into the logs after executing

Because you have a higher log level. Maybe change it to info (second lowest) ;)

**Comment by benediktg** [comment]
OK, now I see it, too…
