### ISSUE TITLE
Music Stutter/Clicking Sounds.

### ISSUE THREAD

**Issue by Somesite** [owncloud/music#490]
On the latest beta OwnCloud 9.0.1 and the latest Music app my music seems to have a stutter or static.

**Comment by Somesite** [comment]
It appears the player also doesn't work on Internet Explorer 11.
Firefox has a massive stutter.
Chrome has static.

**Comment by pellaeon** [comment]
This app use in-browser Javascript to decode music files other than ogg. In-browser Javascript decoder does work with lower performance, if you have a low-spec computer, it's likely the sound will have stutter.
Also, please test if your network is fast enough.

**Comment by Somesite** [comment]
120Mbit down and 30 Mbit up. Haswell-E hexacore cpu with 32gb ram. I don't think my network or pc is the issue.

**Comment by Somesite** [comment]
When I view source on the music player I have the the following errors:
Failed to parse SourceMap: https://blah.com/apps/music/js/vendor/angular/angular.min.js.map
Failed to parse SourceMap: https://blah.com/apps/music/js/vendor/angular-route/angular-route.min.js.map
Failed to parse SourceMap: https://blah.com/apps/music/js/vendor/aurora/aurora.js.map
Failed to parse SourceMap: https://blah.com/apps/music/js/vendor/aurora/flac.js.map
Failed to parse SourceMap: https://blah.com/apps/music/js/vendor/aurora/mp3.js.map

**Comment by pellaeon** [comment]
That's probably not the problem.
What format is your music in?

**Comment by paulijar** [comment]
The sound distortion problems got fixed (for most browsers) by #535 released in the version 0.3.13. So did the IE11-compatibility mentioned on the second post. Closing.
