### ISSUE TITLE
mp3-file does not play.

### ISSUE THREAD

**Issue by yasuoiwakura** [owncloud/music#492]
hi there,

simple scenario: i have a directory wich includes mp3-files.
i open the dir.
i click one mp3.

cool screen opens, music database with pictures etc. very nice.

But the one file i clicked - it does not play.
sure i can now dive into the music library but thats not what i wanted, i just wanted to play the files i just clicked online.

Ok i shared the directory and tried as anonymous.
i click mp3, it offers download. i click the "..." and "play", mp3 plays finally - but no controls :-/

i know the final goal of this app is to have a nice and fancy music library and all - but should just play a single file also work?

OC9.0.1 on clean Ubuntu 14.04 with music app enabled

**Comment by paulijar** [comment]
This was fixed on PR #529

**Comment by paulijar** [comment]
Cc @gnarula. Could this be closed now?

**Comment by gnarula** [comment]
Yes indeed
