### ISSUE TITLE
Music Page stays blank, no error messages at all

### ISSUE THREAD

**Issue by ravermeister** [owncloud/music#495]
Hi, I'm really stuck. since OC 8.x the music app no longer works for me. 
I'm using an folder on the server machine for my music, configured in OC as external share.
my OC server is running with apache https and a self signed certificate. 

Whenever I enter the music page I just get the owncloud menu title and the rest is a blank page.
in chome I get this JS error:
 `2b96ad7f703325fd6928db2ac6a8bcfa.js:971Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.2.21/$injector/unpr?p0=eProvider%20%3C-%20e`

but I'm not sure if this has something to do with the issue.

I even checked out the source from github, but it gave the same result. 
I did a clean reinstall (removing all OC_music* tables, and the config entries in OC_appconfig)
but after the activation of the app, the above error occurs. 

what can I do?

thanks in advance

**Comment by ravermeister** [comment]
I think this is a duplicate of https://github.com/owncloud/music/issues/434
I use asset-pipeline.enabled too. are there any plans to solve the issue with
'asset-pipeline.enabled' ?

**Comment by MorrisJobke** [comment]
> I use asset-pipeline.enabled too. are there any plans to solve the issue with
> 'asset-pipeline.enabled' ?

Not yet :(

**Comment by MorrisJobke** [comment]
But I would welcome help on this topic :)

**Comment by MorrisJobke** [comment]
I will close this as duplicate.
