### ISSUE TITLE
It only scans ogg, mp3 but not mp4

### ISSUE THREAD

**Issue by Tristan79** [owncloud/music#497]
Owncloud 9.0.x
OSX Server 5.1
Music 0.3.11

Owncloud works great only the music app scans only mp3, ogg but not mp4 (or flac) thus missing 99% of my music collection. Also https://cloud.catmonkey.nl/apps/music/ampache does nothing but redirect back to the files overview and /server/xml.server.php shows 

<root>
<error code="401">Invalid Login</error>
</root>

but most importantly it does not see mp4. I'm I missing a mime type or is it something else?

Tristan

I should read better: https://github.com/owncloud/music/issues/463 almost same problem, except the mp3 on the external storage are being indexed. (wait.. checked,.. at least some of them, seems 50% is missing, seems the external storage that work has no space in the folder names.

Still mp4 does not work even if I do not have external storage.

update: did not run  occ maintenance:mimetype:update-db before checking local storage. I see it adds mp4. Tried it still fails... :-/

log file contains directly at startup:

{"reqId":"nQHlX2KTnnSaaATuOzjA","remoteAddr":"85.150.8.200","app":"core","message":"Error while running background job (class: OC\BackgroundJob\Legacy\RegularJob, arguments: Array\n(\n    [0] => OCA\Music\Backgroundjob\CleanUp\n    [1] => run\n)\n): {\"Exception\":\"Doctrine\\DBAL\\Exception\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_music_albums` SET `cover_file_id` = NULL\n\t\t\t\tWHERE `cover_file_id` IS NOT NULL AND `cover_file_id` IN (\n\t\t\t\t\tSELECT `cover_file_id` FROM (\n\t\t\t\t\t\tSELECT `cover_file_id` FROM `oc_music_albums`\n\t\t\t\t\t\tLEFT JOIN `oc_filecache`\n\t\t\t\t\t\t\tON `cover_file_id`=`fileid`\n\t\t\t\t\t\tWHERE `fileid` IS NULL\n\t\t\t\t\t) mysqlhack\n\t\t\t\t);':\n\nSQLSTATE[HY000]: General error: 1093 You can't specify target table 'oc_music_albums' for update in FROM clause\",\"Code\":0,\"Trace\":\"#0 \\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(175): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE `oc_musi...', Array)\n#2 \\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/apps\\/music\\/utility\\/helper.php(80): Doctrine\\DBAL\\Statement->execute()\n#3 \\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/apps\\/music\\/backgroundjob\\/cleanup.php(28): OCA\\Music\\Utility\\Helper->cleanUp()\n#4 [internal function]: OCA\\Music\\Backgroundjob\\CleanUp::run()\n#5 \\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/lib\\/private\\/backgroundjob\\/legacy\\/regularjob.php(31): call_user_func(Array)\n#6 \\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/lib\\/private\\/backgroundjob\\/job.php(52): OC\\BackgroundJob\\Legacy\\RegularJob->run(Array)\n#7 \\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/cron.php(171): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#8 {main}\",\"File\":\"\\/Users\\/Tristan\\/Sites\\/monkey.nl\\/owncloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"2016-05-13T00:00:29+00:00","method":"GET","url":"\/cron.php","user":"--"}

**Comment by paulijar** [comment]
@Tristan79 Is this issue still present with the latest Music app version (currently 0.5.4)?

**Comment by paulijar** [comment]
With almost a month without reply, I assume that this old issue is gone by now. Closing.
