### ISSUE TITLE
Fatal cron error

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/music#504]
Running 9.0.2 and music 0.3.11 I am getting this error in my log file every now and then.
How do I fix it?
```
Fatal	cron	An exception occurred while executing 'SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1' with params ["OC\\BackgroundJob\\Legacy\\RegularJob", "[\"OCA\\\\Music\\\\Backgroundjob\\\\CleanUp\",\"run\"]"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
```
Not sure if my other thread is related.,,,
https://github.com/owncloud/music/issues/297

Thanks

**Comment by MorrisJobke** [comment]
This error appears when the mysql is not reachable. Nothing that could be fixed on our side. Check if the mysql web server is running.
