### ISSUE TITLE
Is there any reason to use aurora.js to play mp3 files?

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#533]
Music player currently uses soundmananger2 library to play .ogg files and aurora library to play .mp3 and .flac files. The former does not support .flac files and the latter does not support .ogg files but .mp3 files could be played by both. Is there any reason why aurora has been selected for .mp3?

The reason I'm asking is because aurora has a lots of problems playing mp3 files. At least these:
- Some mp3 files do not play at all (as noticed in README.md)
- There is some distortion in the playback quite often (#490). Especially if the web browser is doing anything else while playing music in one tab.
- The sound quality is totally unacceptable on Android Chrome. (https://github.com/audiocogs/aurora.js/issues/173)
- The mp3 playback does not work on Internet Explorer versions older than 11.

According to my tests, all of these would be fixed by changing the mp3 playback engine to soundmanager2. Playback would still not work on IE8, but IE9 would work fine.

I also tested that updating aurora.js and its MP3 plugin to most recent released versions does not help on any of the above mentioned problems.

**Comment by paulijar** [comment]
@MorrisJobke, @pellaeon, @gnarula, anyone?

**Comment by pellaeon** [comment]
Chromium has no built in codec for MP3 (but Chrome does), see https://www.chromium.org/audio-video

**Comment by paulijar** [comment]
Okay @pellaeon, thanks for the info. Maybe PlayerWrapper could then detect the situation somehow and fall back to aurora.js only on Chromium?

**Comment by pellaeon** [comment]
Yes, that is possible, pull requests welcomed :-D

2016-09-04 17:37 GMT+08:00 Pauli Järvinen <notifications@github.com>:
