### ISSUE TITLE
Never ending scan Process

### ISSUE THREAD

**Issue by n0o0ne** [owncloud/music#538]
Hi,

After updating to 0.3.12 and adding new music, i was asked to scan the audio files.
First i thought that there are to many files. But after deleting all files and adding 22 files the error is still there. Just saying Scanning music ... 0 of 22 forever. 

Error log
`Error  PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:18:16+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:18:12+00:00
Error   PHP Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php:772 Stack trace: #0 /usr/share/webapps/owncloud/lib/private/Files/View.php(2032): OC\Files\Filesystem::normalizePath('/n01/files/Musi...') #1 /usr/share/webapps/owncloud/lib/private/Files/View.php(1150): OC\Files\View->unlockFile('/n01/files/Musi...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /usr/share/webapps/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 /usr/share/webapps/owncloud/lib/private/Files/Stream/OC.php(122): fclose(Resource id #637) #6 [internal function]: OC\Files\Stream\OC->stream_close() #7 {main} thrown at /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php#772  2016-09-22T08:17:57+00:00
Error   PHP Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php:772 Stack trace: #0 /usr/share/webapps/owncloud/lib/private/Files/View.php(2032): OC\Files\Filesystem::normalizePath('/n01/files/Musi...') #1 /usr/share/webapps/owncloud/lib/private/Files/View.php(1150): OC\Files\View->unlockFile('/n01/files/Musi...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /usr/share/webapps/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 /usr/share/webapps/owncloud/lib/private/Files/Stream/OC.php(122): fclose(Resource id #637) #6 [internal function]: OC\Files\Stream\OC->stream_close() #7 {main} thrown at /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php#772  2016-09-22T08:17:57+00:00
Error   PHP Cannot 'break' 2 levels at /usr/share/webapps/owncloud/apps/music/3rdparty/getID3/getid3/module.audio.ogg.php#511   2016-09-22T08:17:48+00:00
Debug   music   update - mimetype audio/flac    2016-09-22T08:17:48+00:00
Debug   music   update - /n01/files/Music/Red - Of Beauty and Rage 2015 /01 Descent.flac    2016-09-22T08:17:48+00:00
Info    music   Rescan triggered    2016-09-22T08:17:48+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:17:35+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:17:28+00:00
Error   PHP Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php:772 Stack trace: #0 /usr/share/webapps/owncloud/lib/private/Files/View.php(2032): OC\Files\Filesystem::normalizePath('/n01/files/Musi...') #1 /usr/share/webapps/owncloud/lib/private/Files/View.php(1150): OC\Files\View->unlockFile('/n01/files/Musi...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /usr/share/webapps/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 /usr/share/webapps/owncloud/lib/private/Files/Stream/OC.php(122): fclose(Resource id #637) #6 [internal function]: OC\Files\Stream\OC->stream_close() #7 {main} thrown at /usr/share/webapps/owncloud/lib/private/Files/Filesystem.php#772  2016-09-22T08:12:43+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:12:42+00:00
Error   PHP PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/openssl.so' - /usr/lib/php/modules/openssl.so: cannot open shared object file: No such file or directory at Unknown#0 2016-09-22T08:12:23+00:00`

**Comment by n0o0ne** [comment]
Hmmm tried some .mp3 files, now the mp3s are recognized. The 22 files were FLAC but still not recognized. The earlier Version played FLACs without any problems.

**Comment by rwggit** [comment]
Same Problem here.
I think the reason is an error in module.audio.ogg.php. My log-sile shows following message:
Error  PHP  Cannot 'break' 2 levels at /var/www/owncloud/apps/music/3rdparty/getID3/getid3/module.audio.ogg.php#511 
After replacing "break 2" by "break" scanning seams to work.

**Comment by TimelessTraveler** [comment]
Thanks rwggit, your solution worked for me.
