### ISSUE TITLE
getID3 class loaded whether application is active or not

### ISSUE THREAD

**Issue by apotek** [owncloud/music#551]
(tried to use the template, but I get a 404 when I click on the link to it).

The way the getID3 class is loaded (in the music.php via `require`) causes class declaration conflicts with other applications that also use this library. 

```
// in stable5 getid3 is already loaded
if(!class_exists('getid3_exception')) {
	require_once __DIR__ . '/../3rdparty/getID3/getid3/getid3.php';
}
```

Can this be loaded via autoloader when the class is actually required, or, at least, can this be moved out of music.php, so that the class is not declared just by enabling the app whether it is currently active or not?

I am using audioplayer for music library management, and this app for being able to use ampache api to tomahawk. Both apps use getID3, which is a common dependency obviously for any multi-media app. 

Thinking it was an audioplayer issue, I created an issue for it [here](https://github.com/Rello/audioplayer/issues/78) https://github.com/Rello/audioplayer/issues/78, but in discussing with the developer, it became clear that the issue is not in that application's code, but in the way the getID3 class is being loaded in the music app.

Fixing the methodology of this class-load and removing it from music.php would increase interoperability with other applications.

**Comment by Rello** [comment]
Hello,
I think the declaration needs to be moved into the `/music/utility/extractorgetid3.php`

because now we have the issue that music is claiming its local getID3 in a way that no other app can use its own.
This is especially difficult, as Music is distributing a pretty outdated version of getID3. Also other apps might need some local modifications of get ID3 which they can not distribute now.

can you please look at changing this?
thank you

**Comment by apotek** [comment]
Here's a cheap PR for this. I know there's a better way, but I was worried about being more aggressive and breaking things. Sorry for the mistaken commits that I had to revert. https://github.com/owncloud/music/pull/552

**Comment by Rello** [comment]
Thank you

**Comment by apotek** [comment]
Previous PR was messy. This is one commit and with proper attribution https://github.com/owncloud/music/pull/553

It seems like travis doesn't have the mp3 test files uploaded :(

**Comment by paulijar** [comment]
Travis has started failing like that somewhere between PRs #544 and #547, i.e. 2-3 weeks ago. I don't think that anything relevant has changed on Music app, so maybe Travis or its configurations have changed somehow. Interestingly, the tests run on CORE_BRANCHes stable8.2, stable9, and stable9.1 always pass and the others always fail.

Btw, Music will no longer distributes very old getID3 if PR #550 is merged.

**Comment by Rello** [comment]
Hello, 
even so getID3 is updated now - "blocking" the class by an app is not the way to go in my opinion.
- If one app fails to push an update quickly, all others suffer
- If an other app needs to tweak the class locally (in Audio Player to be able to handle stream files) it does not have a chance

And that another app tries to define the app the same way as Music and let the activation sequence decide the competition - not a good idea.

@paulijar can you please comment on what you think to correct your code?

**Comment by paulijar** [comment]
@Rello Yes, obviously it's a bad thing if applications interfere each other. Hiding everything getid3-related in the Music app behind the class ExtractorGetID3 sounds right to me.

At the moment, there is a direct dependency to getid3 library also here: https://github.com/owncloud/music/blob/ee70561a66a301947d588e4479fc04a3a3ee339c/controller/apicontroller.php#L373. I suspect that this file may break if the `require_once` is moved. That dependency is removed in commit d6705390b if #547 is merged.

Hence, natural order could be to merge #550, then #547, and finally #551. The #551 should be improved so that the instance of getID3 class is created within ExtractorGetID3 and not injected from `app/music.php`.

**Comment by apotek** [comment]
This is probably naive feedback, and I am exposing how little I know the underlying mechanisms of core here, but I'll take that chance. From a pure OOP perspective, wouldn't this be the way this should work?

1. Use ownclouds autoload mechanism (does one exist) so that when `new getID3` is called, the class is loaded as needed (I know, I'm thinking of composer with /vendor, or Kohana here). 

2. Then, each owncloud application that needs to use that class would create their own inherited class prefixed with the app name like `class MusicGetID3 extends getID3` and `class AudioPlayerGetID3 extends getID3`. Any special methods, or needs that aren't being addressed in the main "shared" version could be patched, overridden, extended here.

I see that the main OC composer.json file includes a require for "lukasreschke/id3parser". And the autoload for the public directory seems to be `lib/public` (I was expecting `3rdparty`).  Obviously I am just scratching at the surface here, but it seems in the age of PSR-4 and autoload that there should be a much more architecturally sound way to share resources than using require or require_once at all. 

Happy to be schooled, even with just a good link :). Thanks.

**Comment by paulijar** [comment]
@apotek I probably have even less knowledge on the library loading in owncloud (and PHP in general) but I still try to comment.

Your proposed architecture sounds clean and nice. However, it is quite problematic to extend a 3rd party class which has not been initially designed to act as a base class. The inherited class would most probably need to use interfaces which are not part of the public API of the library. Hence, compatibility issues could easily emerge when the version of the 3rd party library changes. To play it safe, each application would still need to ship their own version of the base library.

**Comment by paulijar** [comment]
#553 was merged with slight changes

**Comment by Rello** [comment]
Nice to read!
Good job
Now users can run both apps again
