### ISSUE TITLE
Music app missing in Nextcloud store

### ISSUE THREAD

**Issue by blizzz** [owncloud/music#558]
Heyo, in the appinfo it's cool to see that at least master is compatible with Nc 11. It would be awesome to also have a release avaiable from there. There's also a guide if neeeded: http://nextcloudappstore.readthedocs.io/en/latest/developer.html

Keep rocking!

**Comment by paulijar** [comment]
The next release of the Music app happens hopefully in the near future. The plan is to make it available both in Nextcloud and ownCloud app stores.

**Comment by e-alfred** [comment]
Is it possible to install it manually? Cloning the Git repository?

**Comment by Retnuh66** [comment]
I would also like to see this app in the nextcloud store

**Comment by srt10coupe** [comment]
same here

**Comment by andreaphsz** [comment]
same here (for owncloud marketplace)

**Comment by paulijar** [comment]
I'm happy to announce that the Music app version 0.4.1 has now been released to Nextcloud app store and ownCloud marketplace, finally.
