### ISSUE TITLE
Error on upgrade from 0.3.12 to 0.4.1

### ISSUE THREAD

**Issue by Mte90** [owncloud/music#571]
I get that error on NextCloud during the upgrade:
```
An exception occurred while executing 'DROP TABLE `oc_music_playlist_tracks`;': SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'xxxxx_owncxxx.oc_music_playlist_tracks'
```
I am using nextcloud 12

**Comment by paulijar** [comment]
@Mte90 Thanks for the report. I think I made a mistake on the upgrade logic and the application may now try to drop the same table twice, on some server versions. I'll try to fix this ASAP.

In the meantime, if you want to hack it yourself, you can probably fix the issue by commenting out the line 
```
$sqls[] = 'DROP TABLE `*PREFIX*music_playlist_tracks`;';
```
in the file apps/music/migration/premigration.php

**Comment by Mte90** [comment]
I don't have the access on my installation (using a third parties provider) but I will wait for a new release :-)

**Comment by paulijar** [comment]
I believe I managed to fix this with 4025bd4fe9. I don't have time to make a new release today but I try to do it tomorrow or later this week.

**Comment by paulijar** [comment]
Version 0.4.2 (https://github.com/owncloud/music/releases/tag/v0.4.2) is out now. It should fix the issue.

**Comment by Mte90** [comment]
now is working :-D
