### ISSUE TITLE
Sign app by a certificate issued from Nextcloud

### ISSUE THREAD

**Issue by svankan** [owncloud/music#574]
I made an upgrade from Nextclodu 12.01 RC4 to RC5 and it complains about this on top of the screen.

There were problems with the code integrity check. More information…

It’s the music app and the same thing happened from version 12.0 to 12.01 RC4.
Last time I deleted the app removed the files and installed it again.

When I click at the integrity check message I can rescan and check the files.

“Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation. (List of invalid files… / Rescan…)”

If I click list of invalid files it shows this:
"Technical information

The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
Results

    music
        EXCEPTION
            OC\IntegrityCheck\Exceptions\InvalidSignatureException
            Certificate is not valid.

Raw output

Array
(
[music] => Array
(
[EXCEPTION] => Array
(
[class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
[message] => Certificate is not valid.
)

    )

)"

Please check here:
https://help.nextcloud.com/t/nextcloud-12-0-1rc4-help-test/18860/55?u=svankan

Answer:
Yes. The app has to be signed by a certificate issued from Nextcloud, it seems to have a certificate at https://github.com/nextcloud/app-certificate-requests2 but uses the one from ownCloud for the signature.json file. Please tell the author to use the Nextcloud certificate there as well.

**Comment by paulijar** [comment]
Thanks for the report. I hadn't realized that also Nextcloud is interested about signature.json which is mandatory part of releasing to ownCloud marketplace. At the moment, the same release package is distributed in ownCloud marketplace and Nextcloud store, but plainly, distinct packages with differing signature should be used.

This problem should not cause any other issues except the warning being shown to the admin. Hence, I will not hurry into making a fix release but I will keep this in mind when making any future releases.

**Comment by LukasReschke** [comment]
> Thanks for the report. I hadn't realized that also Nextcloud is interested about signature.json which is mandatory part of releasing to ownCloud marketplace.

Nextcloud supports signature.json as well but they are not mandatory as we already ensure the integrity of the app on download.

**Comment by e-alfred** [comment]
I get this too and it is the only problem I faced thought I have a lot of apps installed. Is there a way to fix this until a new release comes out (without disabling integrity checks altogether which is the worst idea of all)?

**Comment by paulijar** [comment]
For anyone looking for a DIY solution to get rid of the warning before the next Music app release is out, these steps should work:
1. Delete the file `apps/music/appinfo/singature.json`
2. Fake the version number of current Music app installation to older version by executing the SQL statement `update oc_appconfig set configvalue='0.4.2' where appid='music' and configkey='installed_version';`
3. Reload Nextcloud
=> The app installation process is run again and afterwards the warning should be gone.

**Comment by e-alfred** [comment]
I only deleted the signature.json file and the message went away. I didn't fake the version number.

**Comment by paulijar** [comment]
The release 0.4.4 is now available on Nextcloud app store and ownCloud marketplace, and it has been signed with respective certificates on each.
