### ISSUE TITLE
[Question] Why not using an Owncloud - Ampache bridge or something like that?

### ISSUE THREAD

**Issue by Psy-Virus** [owncloud/music#575]
Hey there,
I really hope I do not annoy someone with a question in the issue section.

I'm asking myself since I know about the Music app for Owncloud, why the wheel has to be reinvented. Maybe it's my lack of knowledge.. but - Ampache itself is actively being developed and has a working API. So why hassling with a new (instance?) of it?
Don't get me wrong, a music player is something, Owncloud needs. And I appreciate the work everyone is doing here. But why not building a bridge instead of reinventing a working wheel?

Wouldn't it also bring new wind to the Ampache software in form of new developers and users to also develop this old and great software further? From my point of view, it's a win win situation.

I'm just curious so I hope no one feels offended.

Greetings and thanks four your time

Psy :-)

**Comment by paulijar** [comment]
No harm asking :).

If I understood correctly, in your suggested architecture people would need to install both ownCloud+Music and Ampache server. In the current architecture you can use (some) Ampache-enabled players without installing Ampache. If you are already running Ampache server anyway, then that's not a problem for you but I guess that most people are not.

I'm not very familiar with Ampache so pardon me if I say something stupid, but I would imagine that the suggested "Owncloud - Ampache" bridge would actually need to be added to Ampache. Owncloud already provides the WebDAV API and I believe that Ampache could plug into it if it would desire. In this solution, ownCloud Music app would play no role.

**Comment by e-alfred** [comment]
Installing an Ampache server next to Nextcloud/Owncloud adds a lot of administration work for users. It is quite an advantage of the Music app that it includes an Ampache compatible interface to connect compatible players without a lot of additional work.

**Comment by Psy-Virus** [comment]
Thanks for the answers :-)
Of course it would add some more admin work to it. Well I rechecked it and Ampache has a WebDAV API too. But Ampache is also completely made for those "media stuff" Like getting all informations out of tags, dealing with problematic tags (encoding, umlauts and so on). Things that this app has to reinvent(?).
Why I mention it is, I got several errors while I was trying to scan for my music that probably are either related to a non completely standard TAG or file name. Or something that simply goes wrong while the app is scanning the files. On top of that, the scan process is about a 100 times slower than Ampache's.

And with Ampache I don't have any problems scanning or managing my music library.
I guess what I want to say is that this app probably needs a bunch of work until it gets usable for day to day use and that it is maybe easier to build a bridge first to get something bug free running and then work on a stand alone way.

Just my opinion. And I know it sounds kinda like I don't respect the work you put in it. Please don't think that. It's absolutely only meant constructive.

Thanks :-)

**Comment by paulijar** [comment]
@Psy-Virus I found this short discussion about something similar what you are requesting: https://groups.google.com/forum/#!topic/ampache/ghN1YLCEXYA. Based on the answer there, I believe that what you are aiming for can be achieved already today by mounting the ownCloud WebDAV API as a local file system and then giving the mount point to Ampache as local catalog. But none of this has anything to do with the ownCloud Music app.

What kind of errors did you get when scanning your music collection, and which version of Music app were you using?

**Comment by Psy-Virus** [comment]
Yeah well my thought was about to have a plugin/ an app in Owncloud to access my already set up Ampache library, not the other way around. ^^

I mean to have two tabs open is also okay for me but I thought to bring it up and hear what you think and if you may want to catch up on it.

To the Error, it's I guess a string conversion thing or so. I didn't look into it...

```
  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'INSERT INTO `oc_music_albums`(`name`,`disk`,`user_id`,`album_artist_id`,`hash`) VALUES(?,?,?,?,?)' with params ["\x48\x61\x6c\x74\x20\x64\x65\x6e\x20\x4d\x75\x6e\x64\x2c\x20\x68\xf6\x72\x20\x61
  \x75\x66\x20\x7a\x75\x20\x68\x65\x75\x6c", 1, "Psy-Virus", 5094, "ecdaadf0dc54169228fdcd1f5a451e2f"]:
  SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF6r auf...' for column 'name' at row 1
```

It says, it has a problem with inserting the name column. What is the name referring to? The title, the artist?

:-)

**Comment by e-alfred** [comment]
> Yeah well my thought was about to have a plugin/ an app in Owncloud to access my already set up Ampache library, not the other way around. ^^

This sounds like a job for a completely new app. This app has an Ampache server but no client integrated.

**Comment by Psy-Virus** [comment]
I don't know what kind of Ampache Server is used but Ampache is able to build a network, kinda like the federal cloud. If this would be implemented, I think a client is not needed then (?)

**Comment by paulijar** [comment]
I don't quite see, what would be the added value from an app which would simply be another UI to the Ampache server. There already is Ampache's own web UI and plenty of stand-alone music players which can act as Ampache clients. I can't figure any synergy from Ampache UI running within ownCloud. To make it worthwhile to implement a new app, it should bring at least some benefit over the existing alternatives.

That being said, if someone would be interested to implement that kind of ownCloud app, they are of course free to do it. There's room for all kinds of apps. But don't hold your breath while waiting for it to happen; there's probably not that many active developers following the discussions of the Music app these days.  During the last year probably more than 95 % of the contributed code lines to this app are from myself which tells about the low number of contributors.

I'll open a new issue for the exception from `INSERT INTO 'oc_music_albums'` as that is clearly a bug which should be fixed. My best guess is that the audio file in question claims to use UTF-8 encoding but the content is actually Latin-1 encoded. The error message seems to indicate that the offensive character is 0xF6 which is 'ö' in Latin-1 but nothing valid in UTF-8. The GetID3 library we use for metadata extraction cannot handle such encoding mismatches, but some exception handling should be added to the Music app so that one offensive file wouldn't break the whole scanning process.

**Comment by Psy-Virus** [comment]
All in all, it came to my mind, because I'm often in the Owncloud web UI but not in the Ampache web UI (except for administrating my music library). And I guess I'm simply a fan of having everything in one place and not to struggle with a thousand logins and stuff. Even if it's not that much of an effort in this case^^

Anyways, thanks for your time and the discussion, appreciate it!

And thanks for looking into the bug.

Psy :-)

**Comment by e-alfred** [comment]
You can also use the "External Sites" feature of Owncloud/Nextcloud to have your login pages in one place.

**Comment by Psy-Virus** [comment]
Yeah, that was the first thing I did because of no alternative :-)

But thanks for the hint tho!

:-)

**Comment by e-alfred** [comment]
You can try this app and see if it fits your use case better (basically a Subsonic client for Owncloud):

https://github.com/visit1985/subphonic
