### ISSUE TITLE
DB exception while scanning: "Incorrect string value"

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#576]
Issue originally reported by @Psy-Virus in #575:

I got several errors while I was trying to scan for my music that probably are either related to a non completely standard TAG or file name. Or something that simply goes wrong while the app is scanning the files.

```
  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'INSERT INTO `oc_music_albums`(`name`,`disk`,`user_id`,`album_artist_id`,`hash`) VALUES(?,?,?,?,?)' with params ["\x48\x61\x6c\x74\x20\x64\x65\x6e\x20\x4d\x75\x6e\x64\x2c\x20\x68\xf6\x72\x20\x61
  \x75\x66\x20\x7a\x75\x20\x68\x65\x75\x6c", 1, "Psy-Virus", 5094, "ecdaadf0dc54169228fdcd1f5a451e2f"]:
  SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF6r auf...' for column 'name' at row 1
```

It says, it has a problem with inserting the name column. What is the name referring to? The title, the artist?

EDIT: Instead of asking I could simply look into the db *facepalm*. It's the album..
The album of the erroring song has umlauts spaces and a ',' in it.

EDIT2: The version is the latest version, the store provides `0.4.3`.

:-)

**Comment by paulijar** [comment]
@Psy-Virus I just published a new release 0.4.4 which should fix this issue. The scanner now converts any invalid characters to replacement characters (�) to prevent database problems. It would be great if you could give it a try and tell if it works for you.

**Comment by Psy-Virus** [comment]
Hey, I'm sorry for the late reply.

It seems to work. If there's another error, I'll let you know.

But I have one question, With how many files did you test the app?
I'm asking because it's taking forever for me to load/display the songs that are scanned and it's not even finished...

**Comment by paulijar** [comment]
@Psy-Virus Okay, thanks for the info.

I've been testing the app with at most some 7000 tracks. IMHO it was still quite usable with that amount although a bit slow. I assume that the limit for usability might be somewhere around 10000 tracks. In my tests, Chrome browser performed better with large collections than Firefox which was still better than Edge. IE was even worse.

How large is your collection? If you can give any numbers from the time taken to complete the scan and time taken to load the albums view, I would be interested.

**Comment by Psy-Virus** [comment]
I'm by about 160k tracks...

> it's taking forever for me to load/display the songs that are scanned
That wasn't a metaphor :-D
It is endless loading. I was letting the tab open for hours and it was still loading after I checked it again. So I guess there was a time out.

Maybe chunked loading would be a good work around for that. Like in the activity app.

I know what I have there isn't typical but to be prepared for the worst case is never a bad thing, I guess

:-)

**Comment by paulijar** [comment]
@Psy-Virus Wow, that's a lot of tracks. It's no surprise that the app chokes on that.

The overall design of the app is such that it scales quite badly for large collections. Over the past months, I've been able to push the limit of usability from ~3k to the mentioned ~10k tracks with some optimizations, but supporting >100k tracks would require more principal changes.

One day, I might try to further improve the scalability but that's not very high on my priority list: My gut feeling is that quite small percentage of the potential user base have >10k tracks in their collections. At the same time, there are plenty of other things to improve in the app and my time is limited.
