### ISSUE TITLE
Music 0.5.0 breaks password protected shares

### ISSUE THREAD

**Issue by wscheicher** [owncloud/music#578]
Probably since updating Music to 0.5.0 the password submit button for authenticating link shares stays disabled despite having entered a password.

Since that started working again after disabling Music i report this here.

**Comment by pekidi** [comment]
i am facing with the same problem!!!!
I notice that password submit is working on Safari and Internet Explorer. On Chrome, Firefox and Opera does not working.

After disabling the app the password button is working as expected.

I ope the problem will be solved in the next release.

**Comment by paulijar** [comment]
Thanks for the report. I'll investigate the issue.

**Comment by paulijar** [comment]
A quick fix release 0.5.1 was just published to fix this issue.

**Comment by pekidi** [comment]
great,

for me is working

thank u
