### ISSUE TITLE
Collaborate with GNOME Music for music syncing

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#58]
GNOME has a cool Music app in development, working on it are @seiflotfy @kyoushuu @roignac @felipeborges.

I talked to Seif at GUADEC and we should synchronize the music library of GNOME Music and ownCloud Music. This is probably best done through GNOME Online Accounts, where Files, Calendar and Contacts are already handled through.

@seiflotfy, can you talk to Debarshi/rishi about GOA integration? And @kabum probably knows better what we expose – Ampache something? cc @butonic

**Comment by paulijar** [comment]
After 7 years of idling, I don't think that there is any more a reason to keep this issue open. The Music app nowadays provides rather mature Ampache and Subsonic API implementations. There are more than 20 client applications which have been tested to work on one of these APIs. If GNOME Music or any other player app want's to play files from ownCloud/Nextcloud, then they may pick to implement either of these two APIs.
