### ISSUE TITLE
Each folder scan containing music files should also update the browser screen

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#580]
When you scan a collection, you see a counter beeing updated in steps of 10
But this update is not reflected in a page update by eg adding a new album.
Would be great to see an update when eg a folder containing music files was added

**Comment by paulijar** [comment]
You can hit the refresh button in the lower-left corner of the screen to update the view during the scanning. Automatic updating after every 10 tracks would slow the scan significantly, and make using the app impossible during the scan if several thousands of audio tracks are scanned: just imagine what would happen if reloading the page takes e.g. 10 seconds and it happens automatically every 2 seconds.

**Comment by mmattel** [comment]
understood.
maybe a small note about that would be helpful.
info, pressing browser reload during scanning interrupts it

**Comment by paulijar** [comment]
Yes, it could help. The refresh arrow in the lower left corner is very subtle and easy to miss. I myself didn't notice its existence before I saw from the source codes that there is such thing :).

**Comment by paulijar** [comment]
I'll keep the possibility to add some hint note to scanning in mind. I'm closing this issue as the original request is not suitable for the current design of the Music app.
