### ISSUE TITLE
[Feature Request]: play music in files app: show album art

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#582]
Would be great to show the album art (cover) when you play a music track in the files app.
Space seems to be for avaiable...

![image](https://user-images.githubusercontent.com/3321281/30640963-71580afe-9e05-11e7-9994-05de703af849.png)

**Comment by paulijar** [comment]
At the moment, the player in the Files app shows the cover if Files app itself shows it. That is, embedded cover images can be shown but covers from separate image files cannot. Also, if the Files app hasn't loaded the image yet by the time the playing is started, then even the embedded cover is not visible. So clearly, there's room for improvement.
