### ISSUE TITLE
[Feature Request] ./occ music:scan --unscanned option

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#583]
Would be great to have an ``--unscanned`` option.
So if something get added not to run the complete scan again, only for those who are missing.

**Comment by paulijar** [comment]
Thats's how `./occ music:scan` should work already today. If you start the scan, interrupt it with CTRL+C, and then start it again, you should see that the same file names are not printed to screen again. If you really need to rescan also the previously indexed files, then you have to run first `./occ music:reset-database`.

**Comment by mmattel** [comment]
ah, ok, maybe a better description in the command would clarify that.
Currently scan reads full and not "intelligent" :smile: 
Like "scans unscanned files"
Same for reset-database, "resets the database to enable a full scan"
BTW: also valid in combination with a user_id?
(Sorry for beeing picky)

**Comment by paulijar** [comment]
You can specify the target user(s) also for the `reset-database` command if that is what you were asking.

**Comment by paulijar** [comment]
Yeah, the in-app descriptions of the commands could be better. I do something to them once I have time.
