### ISSUE TITLE
[Feature Request] ./occ music:scan --group option

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#584]
Scan not only for a user / list of users, but also for a group like
``./occ music:scan --group=Family``
Would improve scanning resource needs :smile:

**Comment by mmattel** [comment]
Update note:
Would need a logic to see which resources are common for the group and add the db entry for the particular file for many users. Anything what is not common is the classical way.

**Comment by paulijar** [comment]
The way the index database of the Music app is built basically forces us to scan files separately for each user. So if there would --group option on the music:scan command, then it would be merely a convenience to save typing the names of the users belonging to the group. There wold be no performance benefit. As such, I don't think the the gains would justify the added complexity.

**Comment by mmattel** [comment]
But eases admins life...
There is a files:scan --group option now in core, see https://github.com/owncloud/core/pull/30020

**Comment by paulijar** [comment]
Okay, thanks for the info about `files:scan`. I guess that if you have large groups, then this might be a good feature: writing 3 user names on the command line is not much of a problem but writing 30 may be.

**Comment by greku** [comment]
I'm starting to implement this small enhancement to get my hands on the music app. I think the description is quite clear to start with.

**Comment by paulijar** [comment]
This feature has been implemented with the PR #613 and will be part of the next release.
