### ISSUE TITLE
[question] is there a way to play an entire folder in files app?

### ISSUE THREAD

**Issue by KrullBorg** [owncloud/music#585]
instead of play only a single file, is there a way to play the entire folder? or selected files in the current folder? thanks in advance

**Comment by paulijar** [comment]
The "embedded music player" showing up in the bottom of the Files app can play only one file at a time. The "full screen music player" can play all tracks of an album or artist or any custom playlist, but it doesn't care about the folders of the file system.

**Comment by paulijar** [comment]
Update: The Music app version 0.9.0 released yesterday can play the whole folder. You just start playing the first file and the playback automatically continues to the next files in the same folder.
