### ISSUE TITLE
After the scan the music page is still empty

### ISSUE THREAD

**Issue by LaurentGui** [owncloud/music#593]

**Comment by paulijar** [comment]
@LaurentGui Thanks for the report. Is this the same issue as #588? Does this still happen on the brand new release v0.5.4?

**Comment by LaurentGui** [comment]
In fact, it's look like there is no files, but when it scan it find my 78 files. After the scan, when i put the mouse on menu tracks it show 0 tracks. Yet I can listen to music in directories.
 
Version
Nextcloud 12.0.3
Music 0.5.4

**Comment by paulijar** [comment]
@LaurentGui Are there any errors in the web browser developer tools console (opens with F12 on most browsers) when the page is loaded? How about in the nextcloud.log file on the server?

**Comment by paulijar** [comment]
With no additional info, it's impossible to study this issue. Closing.
