### ISSUE TITLE
Cannot use object of type Closure as array

### ISSUE THREAD

**Issue by ArthurKnoep** [owncloud/music#594]
After installing the module, I try to refresh the owncloud page and I get a HTTP 500 code

So I look the error.log on my server : 
PHP Fatal error:  Cannot use object of type Closure as array in /usr/share/owncloud/lib/private/navigationmanager.php on line 24

**Comment by paulijar** [comment]
I have to say I have never seen such an error. Which version of ownCloud are you using?

**Comment by ArthurKnoep** [comment]
Yes I totally forgot to write the version number:  
PHP: PHP 5.6.30-0+deb8u1
Apache: Apache/2.4.10 (Raspbian)
Owncloud: 7.0.4+dfsg-4~deb8u4

I have installed owncloud by the packet manager (`apt-get install owncloud`)

**Comment by paulijar** [comment]
That's a very old version of ownCloud (released in 2014). You probably shouldn't try to use the packet manager for this on Raspbian. The latest stable version offered on https://owncloud.com/download/ is 10.0.3. Furthermore, any recent version of the Music app does not work on ownCloud versions older than 8.2 and the older Music app versions are horribly bugged.

**Comment by ArthurKnoep** [comment]
Ok thanks for your quick reply.

I'm going to try to install an update of owncloud

**Comment by ArthurKnoep** [comment]
Thanks again for reply

I have upgrade my owncloud installation (with difficulty) but it's works, I have owncloud 10.0.3 and I have installed the music module without problem

**Comment by paulijar** [comment]
Okay, great. Cheers!
