### ISSUE TITLE
Ampache support

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#60]
credits to @DeepDiver1975

**Comment by jeppebundsgaard** [comment]
Tried to connect to the ampache-server from Amarock in KDE. The connection check reports that it is connected. But Amarock does not scan the music collection. It reports a time out of the server connection. Please tell me which log files of settings you need from me.

Another problem - maybe connected: In the Music App, I see all my music. But when I click on the track or album to play it, I get the message: "Numre som ikke kunne afspilles blev sprunget over." (something like: "Tracks that could not be played is skipped").

**Comment by MorrisJobke** [comment]
> Tried to connect to the ampache-server from Amarock in KDE. The connection check reports that it is connected. But Amarock does not scan the music collection. It reports a time out of the server connection. Please tell me which log files of settings you need from me.

Is there something in the owncloud.log in the data dir?



> Another problem - maybe connected: In the Music App, I see all my music. But when I click on the track or album to play it, I get the message: "Numre som ikke kunne afspilles blev sprunget over." (something like: "Tracks that could not be played is skipped").

That's only an issue of the codecs that are in your browser.

**Comment by jeppebundsgaard** [comment]
There is nothing in the logs. I retested the creation of the Ampache-setting in Amarock. When hitting test connection, it does connect (I tried to change to a wrong password, and that failed). 
I get an error telling me that it cannot download the playlist.

All my files are are in ogg-format. Does that help? 
My browser should have the codecs to play ogg. So I find it strange that it won't play them.

Here is the information about Amarock:
Amarok Version: 2.8.0
KDE-version: 4.14.13
Qt-version: 4.8.6
Phonon-version: 4.8.3
Phonon-motor: GStreamer (4.8.2)
PulseAudio: Ja

Amarok-scripts:
    Amarok Script Console 1.0 (stoppet)
Lyricwiki .2 (kører)
Dansk Netradio 1.0.8 (kører)
Free Music Charts 1.6.0 (kører)
Librivox.org 1.0 (kører)
Cool Streams 1.0 (kører)

Amarok-plugins:
    DAAP-samling (deaktiveret)
Lyd-cd-samling (deaktiveret)
MTP-samling (deaktiveret)
MySQLServer-samling (aktiveret)
MySQLe-samling (aktiveret)
UPnP-samling (deaktiveret)
Universal Mass Storage-samling (deaktiveret)
iPod-, iPad- og iPhone-samling (deaktiveret)
Ampache (aktiveret)
Jamendo (deaktiveret)
Last.fm (deaktiveret)
MP3tunes (deaktiveret)
Magnatune-butikken (deaktiveret)
Musikbutik med MP3 (deaktiveret)
Podcast-liste (deaktiveret)
gpodder.net (deaktiveret)

**Comment by e-alfred** [comment]
I have a strange phenomenon running the music app on OWncloud 8.1 on Ubuntu 14.04 (Apache 2.4, Mysql 5.5, PHP 5.5). Sometimes I can't connect some or any Ampache client (Tomahawk, Amarok, Just Player) to my Owncloud running the music app. After a reboot  of the server, everything works normal again and I can connect every client to the Owncloud instance again. Every client has a separate generated password and HTTPS is activated (trusted certificate from Wosign).

**Comment by Keirul** [comment]
Tried adding the stream in JustPlay and Tomahawk, they both auth succesfully but I don't get a list of songs. On the backend itself there is no problem, everything loads just fine. 
I'm running Owncloud 9.0.0.0 on Ubuntu 14.04, if you need more info let me know.

**Comment by luci84tm** [comment]
Same issue here like you have @Keirul 
I'm running OC 9.0.0 on my pi3(Debian Jessie) -> nginx 1.9.11 -> sqlite3.

**Comment by autious** [comment]
I'm having issues using the Android app Amplify https://play.google.com/store/people/details?id=112847915098897311295 with the owncloud music ampache interface.

Based on the error message, i think the JSON parser in the app is looking for a "version" field which doesn't arrive, could i be correct?

**Comment by tenleftfingers** [comment]
Getting "Nothing in here. Upload your music!" even though I've added a folder "Level 42 - Level Best" through the Personal->Music section. Still nothing, even after reboot. /var/www/owncloud.log is empty.

**Comment by miton18** [comment]
same as  @Keirul and luci84tm, configuration and connexion OK for Amarok, but I can't see any song...

**Comment by moi90** [comment]
Does not work with viridian-cli, owncloud 8.2.10,  music v0.3.13:
```
$ viridian-cli 
Username 'moi' found for Ampache Server 'https://xxx.xxx.xxx/owncloud/index.php/apps/music/ampache'.
Connect using these credentials? [Y/n]: 
[Error] Authentication Failed -- Retry = 1
[Error] Authentication Failed -- Retry = 2
[Error] Authentication Failed -- Retry = 3
Traceback (most recent call last):
  File "/usr/share/viridian/AmpacheTools/AmpacheSession.py", line 779, in __call_api
    dom = xml.dom.minidom.parseString(x)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: mismatched tag: line 79, column 7
Traceback (most recent call last):
  File "/usr/bin/viridian-cli", line 94, in <module>
    for artist in ampache_conn.get_artists():
TypeError: 'NoneType' object is not iterable
```

**Comment by paulijar** [comment]
I tested Android application Power Ampache with Music 0.4.1 and Nextcloud 12, and this combination seemed to work fine. I tested also Amorak player on Windows, but no songs or albums were shown. There were errors printed to nextcloud.log with message like `"The requested uri(/nextcloud/index.php/apps/music/ampache/server/xml.server.php/server/xml.server.php) cannot be processed by the script '/server/xml.server.php')"`, i.e. somehow the `server/xml.server.php` had been appended twice. The server address I had given Amorak was `https://<server_address>/nextcloud/index.php/apps/music/ampache`. This makes me believe that Amorak forms the incorrect URI and there may be nothing we can do within the Music app.

**Comment by paulijar** [comment]
Tested also Tomahawk on Windows with Music 0.4.1 on Nextcloud 12. Also this combination worked fine.

**Comment by paulijar** [comment]
Tested also org.ampache.amplify on Android. It couldn't connect the server on Nextcloud and showed error message `Cannot load data from server (org.xml.sax.SAXException: Unknown node 'version')`. My interpretation of this is just the opposite what @autious suggests above: The Amplify application breaks down because the response contains the tag 'version' which Amplify does not expect. This tag belongs to the handshake and ping messages as per the Ampache XML API definition (https://github.com/ampache/ampache/wiki/XML-API) but maybe the Amplify app uses older version of the API (?).

**Comment by xXSTrikeXx** [comment]
Tried Subsonic.

Error Message:
length=50; regionStart=0;
regionLenght=-1

I´m using latest versions.
Thats all. I cant find Just Player in App store. I try later other Apps. 
Another Question: Why there are still 2 music Apps? I thinks they doing the same, except music app can handle ampache. I like the design more of the audio player, but it doesn´t support ampache. Thats crap. Why not one good version? 👍

**Comment by paulijar** [comment]
@xXSTrikeXx As I have understood it, Subsonic server provides Subsonic API which is different from the Ampache API. The ownCloud Music app provides only the Ampache API, so Subsonic clients cannot be connected to it. The "real" Ampache server provides both Ampache API and Subsonic API, so it can serve both Ampache clients and Subsonic clients.

There is an open feature request #329 to add the support for the Subsonic API to the Music app. But that's probably not going to happen any time soon, as the request has not moved for the past 3 years. Sadly, I'm the only active developer in this project at the moment and I have no plans to start working on that issue.

As for the question about two music playing apps, I guess that people have different personal preferences. There are many nice features in the Audio Player app, but overall I prefer the simple design of the Music app. It's also quite typical phenomenon for open source software that there are multiple alternatives for the same task and none of them are perfect.

**Comment by xXSTrikeXx** [comment]
Well I cant find any version thats working on androids. Power Ampache the login works, but the App sucks itself. it stucks and shows the music but it never comes to a playback. I have a UpNp Dongle and I need to find a better way to connects the music to Hifi. Any suggestions? At the moment I'm using fritzmedia app. Thats fine, but there its recommed to download the music or start a broadcast (internet radio). I think the best way is to buy a better internet radio, but not at this time. Thx for fast reply and Enlightenment.

**Comment by paulijar** [comment]
@xXSTrikeXx Personally, I have been able to play successfully at least MP3 files on Power Ampache from Nextcloud 12 and recent Music app versions. Trying to use some of the features of Power Ampache make the app crash, but the basic playback does work for me.

Have you been able to connect any PC Ampache client to your cloud instance? At least Tomahawk should work. So can we rule out the possibility that the Music app Ampache API does not not work on your installation for some reason?

**Comment by amenolo** [comment]
Last app release and last NC stable release: no luck at all.

Tested desktop clients (Tomahawk and Amarok) reteurn an _Invalid Login - passphrase does not match_ error.
Tomahawk log quote:

> sab dic 23 2017 - 11:08:05 [0]: "C:/Users/***/AppData/Local/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js" : "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root>
> 	<error code='401'>Invalid Login</error>
> </root>
> " 
> sab dic 23 2017 - 11:08:05 [0]: "C:/Users/***/AppData/Local/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js" : "Let's reauth!" 
> sab dic 23 2017 - 11:08:05 [0]: "C:/Users/***/AppData/Local/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js" : "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root>
> 	<error code='401'>Invalid Login - passphrase does not match</error>
> </root>
> " 
> sab dic 23 2017 - 11:08:05 [0]: "C:/Users/***/AppData/Local/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js" : "Old auth token: undefined" 
> sab dic 23 2017 - 11:08:05 [0]: "C:/Users/***/AppData/Local/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js" : "New auth token: undefined" 
> sab dic 23 2017 - 11:08:05 [0]: "C:/Users/***/AppData/Local/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js" : "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root>
> 	<error code='401'>Invalid Login</error>
> </root>

Tested android clients (Tomahawk and Power Ampache) return a _Something went wrong_ and connection generic error, due to same reason as before, I guess.

In both cases I used my username and app password as account.
App itself works flawlessly.

Any hint? Thanks.

**Comment by paulijar** [comment]
@amenolo I'm not quite sure what you mean with "username/app password". You are supposed to use your Nextcloud account username and a separate password which you have generated from the _Personal_ settings view with the _Generate API password_ button. In case you already did that, please also make sure you don't misinterpret any of the look-alike characters `1, I, l, o, O, 0` in the generated password.

**Comment by amenolo** [comment]
_app password_ meant _generated API password_ and no doubt about letters, I had always double checked (and used copy&paste here on PC, BTW)...maybe I'm missing something in NC settings, who knows...

**Comment by paulijar** [comment]
@amenolo Okay, that's weird. Have you checked if there's any more details in the nextcloud.log or in the logs of your HTTP server? If there's nothing interesting in nextcloud.log, you can also try to first change the log level to 0 (=debug). It generates a lot of log, though, so you probably shouldn't leave it enabled for extended period of time.

**Comment by Zykino** [comment]
@amenolo @paulijar No problem with latest release of NC. Tested Power Ampache and Amdroid.
But both app are old and don't have a "Play a random list of songs in my library".

Are subsonic compatibles app better?

**Comment by paulijar** [comment]
@Zykino 
> don't have a "Play a random list of songs in my library".

Do you mean that you would want to play in random order over your whole library? If so, then I've been thinking that I could make the Music app provide "All tracks" as a playlist in the Ampache API. This would enable the random play at least on Power Ampache.

**Comment by Zykino** [comment]
Yes exactly that.
I did not wanted to create it myself : I do not want to manually add new tracks to the list once synced. I sync it with Syncthing (and display on my NC instance) so everything runs smoothly in background.

I am ok to go on the interface and once in a while click on the "scan new tracks" buttons. But if it can be handled in a Cron job / on a hook event that would be pretty neat :)

**Comment by paulijar** [comment]
@Zykino Okay, I have now implemented providing "All tracks" as a playlist in the Ampache API. The feature shall be included in the next release which will probably be published within 1-3 weeks.

**Comment by floe** [comment]
AFAICT Ampache has a feature called "channels" (https://github.com/ampache/ampache/wiki/Channels) which is sort of a "poor man's Icecast server", and which I would find immensely useful. Is this also possible with the Ampache implementation within the Music app? I haven't been able to find any references...

**Comment by paulijar** [comment]
@floe Sorry, that's not supported in the Music app. The "real" Ampache server provides some half a dozen different protocols so that it can serve as replacement for many different servers. The Music app, on the other hand, provides only the Ampache XML protocol.

**Comment by floe** [comment]
Thanks for the quick response :-) Any ideas whether there's something similar available for Nextcloud? If not, no worries...

**Comment by floe** [comment]
Sorry, too-unspecific question earlier. I've been googling around, and it seems that this functionality is currently not available for Nextcloud. I think it would be a nice addition, though - can you maybe give me a pointer where I could hack this in? After some code browsing, it seems that `controller/ampachecontroller.php` would be the right place to start?

**Comment by paulijar** [comment]
@floe I'm not really at all familiar with Icecast so I'm only guessing here. But I assume that Icecast has a protocol of its own which consists of HTTP requests and responses. You probably can't just hack it to any existing module but you should create new modules to handle the protocol.

It may of course be educative to look how the Ampache protocol has been implemented on top of the Music app. I'm not the original author of this part of the code, but roughly it goes like this:
1. File `appinfo/routes.php` directs HTTP requests with certain path to `ampachecontroller.php` and its function `ampache`. Note that `routes.php` defines this with the name `ampache#ampache` where the first part refers to the controller and the second part to the function name.
2. The function `AmpacheController.ampache()` gets the URL parameters and dispatches the request according the parameter called `action`. Each action has its own handler function.
3. The handler functions fetch the requested data from `BusinessLayer` and build the responses using templates which can be found under `templates/ampache`.
4. As final related component, all HTTP requests to the Music app go through the module `middleware/ampachemiddleware.php`. It checks if the request is in fact an Ampache request and, if so, checks the Ampache session token. Requests with invalid token are blocked.

**Comment by floe** [comment]
Thanks, this is quite helpful. FWIW, the Icecast "protocol" is not much more than MP3 frames with a few extra headers over HTTP, there's an old PHP implementation in just 100 LOC (https://github.com/gadgetguru/PHP-Streaming-Audio). I'll have a look if I can put together an alpha for testing using an existing playlist.

**Comment by marcelklehr** [comment]
I also get 401 - Invalid password, with the logs even with debug level showing nothing more than

    FileHooks::updated triggered for a non-existing file

**Comment by paulijar** [comment]
@marcelklehr Apart from actually having incorrect password, the Ampache login may fail also because of differences in the system time of the client and the server: to succeed, the client clock must not be more than 100 seconds ahead of the server clock and not more than 6000 seconds behind it. Could this be your problem? That 100 seconds is actually quite tight requirement; I think we could loosen that to e.g. 10 minutes without compromising the security too much.

Ideally, the client should query the server's current time and use that on Ampache handshake instead of its own local time, and this would eliminate the need for the clocks to be in sync. But at least Power Ampache doesn't seem to do this, and we can't fix this on the server.

**Comment by marcelklehr** [comment]
@paulijar Interesting. The clocks are within 10s of each other, though, afaict. When I use the Ampache URL with `/server/xml.server.php` I get `Something went wrong.` instead of the 401, so I guess that is no good either.

**Comment by paulijar** [comment]
@marcelklehr Yeah, the 401 indicates that at least the request has reached the Music app. The call probably gets blocked already earlier if the message is just `Something went wrong`.

Do you see any message in addition to the code 401? Looking at the code, it seems to me that 401 can be emitted with five different messages: `Invalid Login`, `Invalid Login - cannot parse time`, `Invalid Login - session is outdated`, `Invalid Login - timestamp is in future`, or `Invalid Login - passphrase does not match`. At least Power Ampache seems to be showing the error message from the server.

**Comment by marcelklehr** [comment]
Yep, it's the passphrase mismatch. I've tried to reproduce this with curl in the terminal:

```
echo "TOKEN" | sha256sum | cut -c 1-64 > hash && curl -v "https://SERVER/index.php/apps/music/ampache/server/xml.server.php?action=handshake&user=USERNAME&timestamp=""$(php -r 'echo time();')""&auth=""$(php -r 'echo time();' | cat - ./hash | sha256sum | cut -c 1-64)"
```

yields

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root>
	<error code='401'>Invalid Login - passphrase does not match</error>
</root>
```

**Comment by marcelklehr** [comment]
So, I couldn't stop myself from debugging a little and it turns out that in my case, [the array of hashes](https://github.com/owncloud/music/blob/master/controller/ampachecontroller.php#L164) is empty, which is why the login fails.

I also know why: I'm using the LDAP user backend and for some reason because of that my userid in the nextcloud database is some kind of numeric id instead of the identifier I login with.

**Comment by paulijar** [comment]
@marcelklehr Okay, thanks for debugging, that's an interesting piece of information! I'm not familiar with the LDAP integration of Nextcloud/ownCloud but I now read some online documentation. It was stated [here](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_auth_ldap.html#expert-settings) that, by default, the internal user name for LDAP users will be the UUID of the user.

I believe that it would be possible for the Music app to map the LDAP user name to the internal name on Nextcloud using the API method [ILDAPProvider::getUserName](https://docs.nextcloud.com/server/13/developer_manual/api/OCP/LDAP/ILDAPProvider.html#OCP\LDAP\ILDAPProvider::getUserName). However, there doesn't seem to be equivalent API on ownCloud. Hence, it would probably be easiest if we just show the (internal) user name on the Music app settings page. Maybe not the neatest possible solution but should be sufficient to make the Ampache feature usable also for the LDAP users.

**Comment by marcelklehr** [comment]
> However, there doesn't seem to be equivalent API on ownCloud. Hence, it would probably be easiest if we just show the (internal) user name on the Music app settings page. Maybe not the neatest possible solution but should be sufficient to make the Ampache feature usable also for the LDAP users.

@paulijar yep, I agree :) :+1:

**Comment by cervantesd** [comment]
Hello,

Cannot connect with my account, seems like if we are using an account with a dot it doesn't work.

**Comment by npodbielski** [comment]
I this possible to run this API behind reverse proxy? It works with PowerAmpache but only directly otherwise application hangs.

**Comment by paulijar** [comment]
> I this possible to run this API behind reverse proxy? It works with PowerAmpache but only directly otherwise application hangs.

I have no idea, but aren't proxies supposed to be invisible for both clients and servers? So if the proxy is doing its job properly, then the Music app should see the proxy just as any other client app and PowerAmpache should see the proxy just the same as any actual Ampache server.

**Comment by npodbielski** [comment]
> So if the proxy is doing its job properly
Theoretically. In practice not every kind of communication can be serve that way, but ampache seems to use some kind of xml files which are ok to pass through reverse proxy. 
I tested this application with PowerAmpache and it works OK. 
I had some problems but it turns out it was caused by something else not music plugin.

**Comment by jakobroehrl** [comment]
It's working pretty good, thanks. 
Is it in the feature possible to use the owncloud passwort for login on ampache?

**Comment by paulijar** [comment]
@jakobroehrl Nope, using the ownCloud password with the Ampache API is not possible now or in the future. There are technical and security reasons for this.

**Comment by jakobroehrl** [comment]
@paulijar Thank you!
Another question: I can stream with ampache or directly with webdav. Where is the difference? What's better?

**Comment by paulijar** [comment]
@jakobroehrl It mostly depends on which client you want to use. Or were you planning to implement your own client? There are a few music player applications which can connect to remote server via Ampache API. I guess there are some players supporting WebDAV, too, but I'm not familiar with those.

The Ampache API of the Music app serves the files organized by the scanned metadata. Meanwhile, the WebDAV API of ownCloud reveals them organized by the directory hierarchy. This is probably the most significant difference in the capabilities of the APIs.

**Comment by paulijar** [comment]
After a year of inactivity, I think it's time to close this bundle issue of miscellaneous Ampache problems and requests. Any future bug reports and feature requests should be filed in their own, more specific github issues.
