### ISSUE TITLE
Play progressbar not working

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#606]
When you play a file, the progressbar is not working and stays empty.
Clicking on it does not change anything (responseless)
OS: W10x64, browser: Opera

![image](https://user-images.githubusercontent.com/3321281/34413874-6a173a38-ebe6-11e7-9955-eae3c23cce3d.png)

**Comment by paulijar** [comment]
Thanks for the report. Does this happen on all files or only on some specific files or file types? On those files, does it happen only with the Opera browser?

**Comment by mmattel** [comment]
All files, just tested with macOS/Safari, same thing.

**Comment by paulijar** [comment]
I just downloaded and tested Opera 49.0.2725.64 on Windows 10 x64, but could not reproduce the issue. I tested files of types mp3, flac, wav, ogg, m4a, and all of them worked fine.

**Comment by mmattel** [comment]
Just retested, W10x64
Works on IE11 and on Chrome (62.0.3202.94)
Deinstalled Opera completely and reinstalled (49.0.2725.64), tested direct after installation.
The progressbar says loading then plays. It is not start playing while loading (like in IE11 or Chrome). The text Loading never goes away, it just starts to play. The bar does not react on any click.

**Comment by paulijar** [comment]
Do you see any errors in the console view of the browser developer tools? Some console prints may show up only if you set `'debug' => true` in your config.php file.

**Comment by paulijar** [comment]
After 5 years of inactivity, I think it's time to close this old bug. Whatever it was, it has probably got already solved, considering that no-one else has ever reported anything like this.
