### ISSUE TITLE
Set library location.

### ISSUE THREAD

**Issue by maxolasersquad** [owncloud/music#608]
It would be useful to be able to define the location of the music/audio library. Currently all audio in all synced folders gets added to the Music app, through I only care to have my actual audio folder available.

**Comment by paulijar** [comment]
This option is available under the Personal settings: Press the "cogwheel" icon on top-right, select "Personal", navigate to section "Music", and you can see the option "Path to your music collection".

**Comment by maxolasersquad** [comment]
I see. Many of the Apps put a cogwheel in the bottom-left for settings, but others put it in the user settings menu. I guess the real issue is a lack of a standard with Own/Nextcloud.

Thank you for your input.

**Comment by paulijar** [comment]
Yeah, the idea to put the cogwheel to bottom-left of the Music app has been brought up before. I now created a feature request #609 for this idea. Maybe I or someone else will then pick it up for development some day.
