### ISSUE TITLE
Add settings link to the bottom of the navigation pane

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#609]
The settings of the Music app can be currently found from the Personal settings of the cloud. It is somewhat difficult to find them from there and it would be better to add link to them also to the navigation pane on the left side of the Music app itself.

Pressing the link should open the settings view to the main pane of the app. The music playback should not stop when this happens. It should also be noted that it is possible to change the music library path from the settings and this clears the music collection and enforces a rescan. Some new application logic would be needed to handle this without reloading the app.

**Comment by greku** [comment]
I would be interested to look into this change. Although I would not have much time this week.

**Comment by paulijar** [comment]
@greku Okay, great! I'm rather busy, too, for the next ~2 weeks so I probably can't review and merge any PR during that time anyway.

**Comment by greku** [comment]
I would like to change the URL of the settings api to add the "api/" prefix to be the same as the other api urls. This makes it easier to use the same Restangular instance as for the rest of the app and I think it is a good idea in general. Can I change this? or do you think other people might be using this api outside of the music app?

https://github.com/owncloud/music/blob/59ea8cf953fc9c500d9f0ec838ee97178555645f/appinfo/routes.php#L57-L61

**Comment by paulijar** [comment]
I guess those URLs can be changed. I find it unlikely, although not impossible, that some external party is using this API. If anyone complains, *then* we can add extra routings with the old URLs. 

Also the README.md should be updated to reflect this change. Interestingly, this file states already today that the Settings API can be found from `/api/settings`. But on the section about Ampache it's talking about `/settings`.

**Comment by greku** [comment]
I made the changes to have the settings accessible within the app. Playing doesn't stop while going to the settings. I would suggest to remove the music settings from 'Personal' page. I don't think it is useful to have it at two places. I seems not many apps have settings in Personal. What do you think?

**Comment by paulijar** [comment]
Good question. Initially, I thought that the settings could be kept in both places. Some people *could* be used to finding the settings under 'Personal'. On the other hand, it's quite difficult to find the settings from 'Personal' and very easy to find them from the left pane of the app itself, so the usefulness of the old place is very limited.

How is your implementation, is there shared code between the old settings view and the new one? Or would keeping both mean double the maintenance effort?

**Comment by greku** [comment]
That's the challenge too, the front-end in the personal settings is quite different (but same user experience). So far, with the changes I made, that would mean double maintenance effort as I kept the original implementation too. (php controller side is the same for both)
The original implementation is not angular-based and translation is done with the fake-template.php. (which would be nice to get rid of by the way, or adapt the translation extractor to work with php template too)

The new settings implementation I made for the app is angular based, like the rest. I'm not completely familiar with angular, but if we want to re-use the settingsview/controller under Personal, we would need to write another module too, and potentially tweak further the controller or write a new one as well. The controller currently calls a method of the parent maincontroller to refresh the library (no possible under Personal).

There are not many settings (unless you plan to use ampache, you may not even know that there are settings), and they are not the kind of things you look for every day. So it is likely that even someone that found it in Personal before just doesn't remember anymore where he found it. The new link being quite visible in the app, he will just find it quickly when he needs it.
If we would like to avoid people not finding back the settings in Personal. We could also keep it for some time listed in Personal with a message and link saying "settings are available in the music app".
Having it in one place is also easier and clearer to document in the manual.

**Comment by paulijar** [comment]
Good points. Considering all this, I guess it's best to remove the Music settings under 'Personal'.

**Comment by paulijar** [comment]
Implemented in #625.
