### ISSUE TITLE
Power Ampache action not supported error , Unable to create playlists.

### ISSUE THREAD

**Issue by linuxmarvel** [owncloud/music#611]
I have the music app currently enabled on Nextcloud 12.0.5 and Power Ampache installed on my phone and connected to the server . When I open the app (Power Ampache) I get an error pop saying- 

Ampache error 
code :405
error:action not supported 

I am also unable to create local playlists using the app (Power Ampache) , the above error appears when I try to.
Is this normal behavior as I know this setup is still experimental and some features in Power Ampache don't work at the moment with the music app 

All other app features work perfectly and I can stream music to the phone with no problems.

**Comment by paulijar** [comment]
I can see the exactly same behavior on Power Ampache. This might be related to the fact that the Ampache API implementation of the ownCloud Music app has no support for playlists. It might be that the Power Ampache has somewhat lacking error handling, and failing to fetch the remote playlists prevents also the use of local playlists.

**Comment by linuxmarvel** [comment]
Well it's good to know it's not something specific to my setup at least. Is this something that can be implemented, in the music app or is it really down to the client end and something power ampache needs to incorporate?

**Comment by paulijar** [comment]
I just ran a quick test and saw that just adding a dummy Ampache API service always returning an empty set of playlists is enough to make the local playlists work on Power Ampache. But even adding the proper support for remote playlists *shouldn't* be too difficult.

I'll fix this one way or another for the next Music app release. Thanks for the report.

**Comment by linuxmarvel** [comment]
Brilliant thankyou for efforts this application is Great.

**Comment by antoniotari** [comment]
hello, this is Antonio, the developer of Power Ampache, I'll be working on this issue, I'll keep you posted

**Comment by paulijar** [comment]
@antoniotari Okay, great! The next release of of the ownCloud Music app (hopefully coming out still during February) is going to contain proper (read-only) support for remote playlists on the Ampache API. But it's still a good idea for the client app to be prepared for cases where a service is not supported on the server. People may be using old versions of the ownCloud Music or some other server software with incomplete Ampache API implementation.

**Comment by paulijar** [comment]
@antoniotari Btw, I see that Power Ampache is also querying the endpoint `tags` which is another currently unsupported ampache API action on the ownCloud Music app. And when we return the error code 405 "unsupported" then Power Ampache retries the query several times.

When I attempted to add a service to return some mock-up data for the `tags` endpoint, I didn't see it being used anywhere on the Power Ampache UI. Nor did Power Ampache make any follow up queries like `tag_songs` or `tag_artists`. Is Power Ampache actually using the data from `tags` for anything? I could implement the endpoint at some point in the future but if there is no client using it, then I probably won't bother.

**Comment by paulijar** [comment]
Music app v0.5.6 with support for remote playlists on the Ampache API has now been published.

**Comment by linuxmarvel** [comment]
@paulijar 
The update works brilliantly. I can create local playlists on Power Ampache as well as server read only ones I'm happy to close this issue unless you feel it should remain open .

**Comment by antoniotari** [comment]
hey @paulijar , there's a options menu on the upper right screen (the button with 3 vertical dots), to see the tags filter go on the ARTISTS page tap on the options menu and tap on "filter by tag", if there's any tag you can see it there

**Comment by paulijar** [comment]
@antoniotari Okay, thanks for the info. Now I found it.
