### ISSUE TITLE
[Feature Request] "Intelligent Playlists" based on criterias

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#619]
As the name titles.
Could start using as criterias ID3 tags like Genre.
Cool if it would have the ability to exlude like !Genre="abc"

**Comment by paulijar** [comment]
I have been thinking to add support for genres at some point. I was just thinking that the genres could show up as read-only playlists, below the user-created lists. Of course that would still be somewhat short of "intelligent" playlist, as there would be no way to invert a rule or combine multiple criteria.

The biggest blocker in adding the genres support is that we would need to scan the genre tag and save it into the database. That means that all the old users would need to rescan their library after the update. Sometimes it's unavoidable but at least I wouldn't want to enforce rescan too often. So if the genres would be added, it might be good idea to try to figure out any other database changes we would need in the near future and try to make those all in one release.

**Comment by mmattel** [comment]
Having auto generated "playlists" based on genre is a good idea.
Please consider having the possibility of user defined but genre based conditions inlcuding a negation. This would enable the scenario "all but". Example, all music files but not Audiobooks...

**Comment by paroj** [comment]
#779 is related.

Also, I would appreciate a "Recently added" auto-playlist as in "N songs from sorted by date".

This all boils down to generating a playlist based on some "search criterion" and then periodically re-executing the search to keep the playlist up to date.

**Comment by paulijar** [comment]
There is also the issue https://github.com/owncloud/music/issues/903 about the recently added tracks.

**Comment by paulijar** [comment]
The Music v1.9.1 now contains the "Smart playlist" feature which allows the user to generate lists filtered by artists, genres, or play history. It's possible that more criteria will be added later.

**Comment by Offerel** [comment]
Thanks for the explanation. Actually, the Advanced Search is already quite good and actually suffices for my purposes. But could you expand it a little to make it more user-friendly? I'll create a feature request so that we can separate the topics again.
