### ISSUE TITLE
Crashes scanning OGG files

### ISSUE THREAD

**Issue by aegisgfx** [owncloud/music#624]
Yup, it does

**Comment by paulijar** [comment]
Does this happen for you with all OGG files or always on some particular file? Is there anything related in the owncloud.log/nextcloud.log file?

**Comment by aegisgfx** [comment]
There was a very long string of errors but it always happened when I hit files with OGG extension, after I converted them to MP3 the error stopped and scanning continued.

**Comment by paulijar** [comment]
Well, I have several OGG files and the app doesn't crash when scanning those. So obviously just having an OGG file is not enough to reproduce this. More likely, there was something untypical in one or several of your OGG files and the Music app couldn't handle that.

So if you can provide the error logs or a sample of a file causing this, then maybe we can find out the reason. But without those, these really not much we can do.

**Comment by aegisgfx** [comment]
I'll see if I can restore some of those ogg files and I'll re run it in command line, thats where I saw the error.

**Comment by aegisgfx** [comment]
Its looking like it might have been a permission error, I restore the files and scanned them fine this time. Looks like OGG format was not the issue.

**Comment by paulijar** [comment]
I think there's no more reason to keep this issue open.
