### ISSUE TITLE
Disable files-music-player on "shared file" page on Nextcloud 13+

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#630]
When an individual audio file is shared via link, the Music app provides a player to play the file from the share page directly in the browser. However, Nextcloud starting from version 13 provides similar functionality natively. This makes the functionality provided by the Music app redundant, unnecessary, and weird.

Note that the player provided by Music app is still valuable for all older cloud versions. Also, it's still valuable on NC13+ for shared folders, just not for individual shared files.

**Comment by n00bundercover** [comment]
(alternatively, it would be nice to be able to deactivate the in-built music player of nextcloud here. The player of this app offers some nice features, like displaying tags. But I guess that would be in the scope of nextcloud devs)

**Comment by paulijar** [comment]
This feature is now published as part of release v0.6.0.
