### ISSUE TITLE
Playing whole folder from the file view

### ISSUE THREAD

**Issue by paulprovost** [owncloud/music#641]
Firstly, this is a great piece of software. I'm loving it already.

A question or enhancement request. Using the Files View embedded player, I am able to play individual files, but the player stops after one file. Is there a way to play a whole folder of files?

Thanks!

**Comment by paalweb** [comment]
I was also thinking that being able to play a full folder would make this wonderful software even better! 
And, if possible, navigation between tracks would be beautiful 👍

**Comment by veddox** [comment]
This would be the single greatest enhancement to this plugin, at least for my and my users' purposes :-) I've browsed to source code myself to see how it could be implemented - unfortunately, I have too little webdev experience to implement this myself :-(

**Comment by paulijar** [comment]
Version 0.9.0 with this feature is now released!

**Comment by reiner-text** [comment]
It's an endless loop, isn't it?

**Comment by paulijar** [comment]
> It's an endless loop, isn't it?

Yep, that's right.

**Comment by reiner-text** [comment]
Do you think of an option to make it configurable? One track, one track endless, all tracks, all tracks endless … or something else.

**Comment by reiner-text** [comment]
What bothers me personally is the endless loop. Playing a folder should be finished after the last track, imho.

**Comment by lil5** [comment]
> What bothers me personally is the endless loop. Playing a folder should be finished after the last track, imho.

@paulijar I agree with @reiner-text  although were it to be optional the use of a button or dropdown for: `shuffle`, `endless shuffle`, `loop`, `loop once`, `replay x3`, `no replay` would be very nice :ok_hand: 

The complexity starts with defaults and if that could be changed and how.
