### ISSUE TITLE
New ownCloud coding standard released

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#643]
@paulijar 
There has been a new coding standard released recently which can be installed via composer.
Maybe you want to take a look on.
It also improves performance...

https://github.com/owncloud/coding-standard

**Comment by paulijar** [comment]
Thanks for the heads-up. I'll have a look.

**Comment by mmattel** [comment]
@paulijar great !
When will you publish the next release so we can use the success life ?

**Comment by paulijar** [comment]
I don't have any plans about the next release yet. Usually I have made new releases at maximum once per month, or more seldom if there is no much new content or if I'm busy doing other things. Only exceptions have been quick fix releases if critical regression errors have been found; in those cases there may have been several releases within a few days.

This particular enhancement does not really benefit the end user at all, so this is not a reason to hurry with the next release. The automatic performance optimizations made by the tool are so micro-level that it is impossible for the user to notice the difference.

**Comment by paulijar** [comment]
New release v0.7.0 was published yesterday.
