### ISSUE TITLE
Allow export/import of playlist

### ISSUE THREAD

**Issue by e-alfred** [owncloud/music#645]
It would be great to be able to import and export playlists into files so they could be saved in case of a library rescan. This could potentially also fix https://github.com/owncloud/music/issues/644.

**Comment by fwicht** [comment]
Yep it would be great to add this feature. This app could then very well become a powerful tool which could come as a replacement for any cloud music service (e.g. Spotify, Apple Music, ...). I'm currently working on an XSLT transformation which could parse an XML file (e.g. the one from iTunes/Music app) into an SQL file which could be imported into the database.

**Comment by paulijar** [comment]
Export/import of playlists is now available on Music v0.16.0.
