### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nunojesus** [owncloud/music#646]
Hi, concrats for your project!
Do you have a logotype? If you need one I can do it for free, I love to contribute to opensource projects, so if you want one just say it.

Cheers!

**Comment by paulijar** [comment]
Hi,
Thanks for the offer. The Music app currently has this kind of icon in-app: 
![music-dark](https://user-images.githubusercontent.com/8565946/40447496-767356e6-5edb-11e8-9368-47ab3f164706.png)
... but nothing which I would call a logotype. It would certainly be nice to show one on the github landing page if you would want to contribute it :). 

PS. I checked your portfolio https://github.com/nunojesus/graphic-design-portfolio and those logos looked really nice!

**Comment by nunojesus** [comment]
Thanks for your words.
Do you have any request for the logo, like shape, color or something where I can get inpired?

Greetings.

**Comment by nunojesus** [comment]
The name of the app is Music app or are you thinking in other name? 

Thanks

**Comment by paulijar** [comment]
The name of the app is just "Music". I think that the logo should include the "double note" symbol in one way or another as that has been used as app's icon for years. I'd prefer the color palette to consist of blue, black and white, at least as main colors.

**Comment by nunojesus** [comment]
Hello, I start to working in your logo, I create this one with some variations, for the  concept I used the music note and a cloud, see if you like it or not.

![music](https://user-images.githubusercontent.com/34600369/40569630-3d380600-607b-11e8-8513-e887d181bb08.png)

**Comment by paulijar** [comment]
Including the cloud metaphor is a good fit.

The third one from left on the top row is the clearest alternative, but after looking at these a bit longer, I also like how the note is hidden in the striped cloud on the top-left alternative. Maybe the top-left one could use a bit darker shade of blue; using just light blue on white background doesn't give quite enough contrast.

Maybe there could be also a variant with somewhat larger text on the right side of the icon?

**Comment by nunojesus** [comment]
Now that im looking I see that I have to change the design, I will study something or make another concept.
Greetings

**Comment by nunojesus** [comment]
Hi see if you like this alternative.
![musica](https://user-images.githubusercontent.com/34600369/40579400-5a7e8f4c-611e-11e8-9b91-b40cffc4512c.png)

**Comment by paulijar** [comment]
I like this one:
![40579400-5a7e8f4c-611e-11e8-9b91-b40cffc4512c](https://user-images.githubusercontent.com/8565946/40584756-3fe7b654-61af-11e8-8885-37608c91b704.png)

...although I'm not certain if I like the stripe pattern of the cloud. Maybe it could be just like this:
![blue](https://user-images.githubusercontent.com/8565946/40584856-551d9ece-61b1-11e8-8705-114bbd2a3a9f.png)

Or maybe there could be some other kind of graphical effect which would be a bit more subtle. I don't know what would that be, though.

Also, maybe the font choice could be considered. This kind of very simple font style works well when used in small size but in large size it doesn't look very interesting.

The rectangular "button-like" logo variants with no text also look nice and would work great as an application icon on a mobile or PC software. However, that kind of applications are out of scope of this project so these icons are probably not needed.

**Comment by nunojesus** [comment]
See if you like one of this logos, I put also diferent fonts for you to chose.

![nuvem](https://user-images.githubusercontent.com/34600369/40591272-0341eaa6-6206-11e8-91e9-009c496b4b15.png)

**Comment by paulijar** [comment]
The top-most one of the latest set is my favorite of all the variations shown so far, both for the cloud and the font. I have a feeling that the vertical alignment of text is a little bit off, but otherwise I would be happy with it.

**Comment by nunojesus** [comment]
Hi, you are  right, the text is a little bit off, I will put in the right place.
This one is also my favorite.

Can I finish it? what files do you want? png, svg, eps? What sizes do need?

Greetings!

**Comment by paulijar** [comment]
Yes, let's lock this alternative and you are free to finalize it. Svg and png formats are enough. The png could be ~1000 pixels wide and if we need any other sizes, we can easily create those from the svg.

**Comment by nunojesus** [comment]
Hi, Im sorry for the late reply, tomorrow I will make the PR with the logo that you want. Greetings Nuno

**Comment by paulijar** [comment]
Resolved in #649
