### ISSUE TITLE
Not working via https

### ISSUE THREAD

**Issue by FadeFx** [owncloud/music#654]
Hi, i want to use ampache on my nextcloudpi installation and just found put that i can not connect to  it as long as the "force https" option is enabled in nextcloudpi panel. This makes it somewhat cumbersome as i would prefere to have https connections only. Any idea on how to workarround that?
Tested with power ampache on android

**Comment by paulijar** [comment]
Hello. The app *should* work via HTTPS. I'm personally running my own server on RaspberryPi and using HTTPS connection, and it does work also with PowerAmpache on Android. I'm not familiar with nextcloudpi, though, but maybe I'll give it a dry during my summer vacation.

Just to make clear, does the app work correctly when used from the web UI but only fails with Ampache connection?

Is it possible that it would be some SSL certificate issue? I.e. are you using a valid certificate verified by a trusted party (like Let's Encrypt)?

**Comment by FadeFx** [comment]
The app works perfectly over https on the webinterface, the letsencrypt certificate is  correctly set up via the nextcloudpi pannel, i first thougt it was a general problem but everything works as intended when force https is disabled in nextcloudpi pannel

**Comment by FadeFx** [comment]
Sorry, have to correct my post, the function in nextcloudpi pannel is "nc httpsonly"

**Comment by paulijar** [comment]
I don't know if it is relevant but I have configured my server so that any attempt to connect to http is redirected to https.

**Comment by FadeFx** [comment]
According to the nextcloudpi doku thats exactly what nc-httpsonly does. I have also posted that issue to the nextcloudpi forums, we will see if nachoparker or someone overthere has an idea why it blocks in that configuration.

**Comment by paulijar** [comment]
And have you explicitly configured PowerAmpache to connect to address https://...? It may not be able to follow the redirect http -> https even if it is in place.

**Comment by FadeFx** [comment]
Yes, i just copied the url out of the settings page of music app which says https://

**Comment by FadeFx** [comment]
Strange, for some unknown reason it started to work now, i changed nothing thou...

**Comment by paulijar** [comment]
Weird stuff. But good thing it works now.
