### ISSUE TITLE
Support for timestamped lyrics

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#657]
At the moment (v0.8.0) the details pane can show the track lyrics stored as ID3 tag. In case the track metadata contains only the synced/timestamped lyrics, those are shown as raw text data:
![synced_lyrics](https://user-images.githubusercontent.com/8565946/43271978-960ea32c-9101-11e8-9830-ec676094edff.png)

This format is rather cumbersome to read because repeating rhymes may be included only once, with multiple timestamps indicating each time the same rhymes is repeated.

The Music app should have a parser which would interpret the timestamps and create a chronological presentation of the lyrics. In the second phase, we could add a highlighting for the current line of lyrics which would move as the playback progresses. This second phase would probably require separating the lyrics from the list of other details. The details pane could maybe have two tabs, "Metadata" and "Lyrics".

**Comment by reiner-text** [comment]
> The details pane could maybe have two tabs, "Metadata" and "Lyrics".

\[Cover]

Encoder | Metadata | Lyrics | …

The _metadata_ should be sorted, _encoder data_ and _file data_ should be separated in a new tab ("Encoder" or "General" or something), and the _lyrics_ absolutely in a separate tab.

**Comment by paulijar** [comment]
Full support for showing time-synced lyrics with highlighting, along with the tabbed layout for the track details pane, has been released in the Music app v0.15.0.
