### ISSUE TITLE
Music App Preventing Proper Saving Of Text Documents

### ISSUE THREAD

**Issue by ChildLearningClub** [owncloud/music#659]
Steps to reproduce
1. Enable Music App Try To Save .md or .txt file get failed! Message
2. Disable Music App Everything Saves Properly
3. Enable Music App Try To Save .md or .txt file get failed! Message

### Expected behaviour
Enable Music App Without Error

### Actual behaviour
Get Error 

### Server configuration
**Operating system**:

**Web server:**
apache2
**Database:**
mariadb
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
nextcloud 13.05
**Updated from an older ownCloud or fresh install:**
updated from older
**Where did you install ownCloud from:**
github
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxxxxxxxxxxxxxx',
    1 => 'xxxxxxxxxxxxxxxx',
  ),
  'datadirectory' => '/media/data',
  'overwrite.cli.url' => 'xxxxxxxxxxxxx',
  'dbtype' => 'mysql',
  'version' => '13.0.5.2',
  'dbname' => 'xxxxxxxxxx',
  'dbhost' => 'xxxxxxxxx',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxx',
  'installed' => true,
  'maintenance' => false,
  'data-fingerprint' => 'xxxxxxxxxxxxxxxxxxxxx',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\Movie',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
  ),
  'loglevel' => 2,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);

**Comment by paulijar** [comment]
Thanks for the report.

I tested this on Nextcloud 13.0.5 and PHP 7.0 but could not reproduce the problem. Are you saying that there's an error message which says just "Failed!" and nothing more? Can you find any more details from nextcloud.log file?

Are you using the most recent version of the Music app (currently v0.9.0)?

**Comment by Bellusterra** [comment]
Hi Pauli,
  
  

 Thank you for making a great app for all to share, reporting bugs is the least I can do.   
  
      Yes, when using the markdown editor it does auto saves, it would first say saving then shortly after simply say “failed!” If I would edit and then close out the editor I would get a notification that the document had not been saved, and to continue keeping the document open or changes would be lost. I was getting something similar happening in the notes app. I was getting a log error message, but don’t remember off the top of my head exactly what it said and will have to check later and get back to you.
  
  I was using v0.9.0
  

  
  
   James
  
  
>

**Comment by Bellusterra** [comment]
Error
  
 files_texteditor
  
  2018-08-11T16:18:45+0900
  
   File: /test5/content/index.md modified since opening.
  
  

  
  

 Here is the error log I was getting.   

  

  
>

**Comment by paulijar** [comment]
Well, that doesn't really shed any more light on this mystery. Nor does it explain what is the connection to the Music app.

If you want to investigate further, you could try to set the logging level to 'debug' and rerun the error case. This can be done by editing the file `nextcloud/config/config.php` and changing the value of `loglevel` to `0`. Don't forget to change it back to `1` afterwards, the debug logging makes the size of the log file grow rather rapidly.

**Comment by paulijar** [comment]
With no further info and after four years of inactivity, there's basically 0-chance to investigate this issue. Hopefully the problem has got solved in the meantime. And if not, then anyone still running into this may freely report a new issue. Closing.
