### ISSUE TITLE
App layout is totally broken on Nextcloud 14.0.0-beta3

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#660]
The app used to work well on NC 14.0.0-alpha, but something has changed since and now everything is messed up:
![image](https://user-images.githubusercontent.com/8565946/44163691-bda0ba80-a0cc-11e8-8e9c-b786c5b7a79a.png)

The main issue seems to be that the `#app-view` element has 0-width. Smaller problems are caused by the fact that the width of `#app-navigation` has been increased from 250px to 300px.

**Comment by ChristophWurst** [comment]
Hi,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We usually try to keep up compatibility with previous app versions, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827. You can run occ app:check-code to validate that there are no issues with deprecated or private message calls.

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket: .

**Comment by paulijar** [comment]
The release v0.9.1 fixes the layout on Nextcloud 14.
