### ISSUE TITLE
ID3 tags aren't all read

### ISSUE THREAD

**Issue by jimbolaya** [owncloud/music#666]
I'm using Nextcloud 13.0.6 and Audio Player 2.4.0.

I have about 3200 songs in an externally mounted folder.  I think some of my files don't have an ID3 tag associated with them, but the vast majority do. 

I see the Artist and Album for some of my files, but around 2900 say Unknown for the Artist and Album. I've spot checked a number of the files using "exiftool -json <filename>" to see what's listed for the file and all the ones I've checked have both of those fields filled. 

Please let me know what other information I can provide.

**Comment by paulijar** [comment]
You do realize that this repository is for the Music app and not for the Audio Player app? The Audio Player app is hosted at https://github.com/Rello/audioplayer. Or do you see the same problem with the Music app?

**Comment by jimbolaya** [comment]
Sorry about that. I'm not sure how I ended up here. 

I'll try installing the Music app and see if I see the same issue, but I'll close since you're right I mis-posted.
