### ISSUE TITLE
getScrollBarWidth() should not be used

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#667]
Instead `OC.Util.getScrollBarWidth()` should be used. See https://github.com/nextcloud/server/pull/11681

You use it in https://github.com/owncloud/music/blob/b3f61bfc5df828c78653d4d8c16bc612ece68c43/js/embedded/embeddedplayer.js#L257 and https://github.com/owncloud/music/blob/b3f61bfc5df828c78653d4d8c16bc612ece68c43/js/public/files-music-player.js#L247

**Comment by paulijar** [comment]
Ok, thanks for the heads up.
