### ISSUE TITLE
Album view splits by Artist

### ISSUE THREAD

**Issue by FadeFx** [owncloud/music#672]
When i sort music by album, it still first sorts by artist, this is no problem with normal albums, but sampler and compilations are spread all over the place...

Imo it should then sort the albums by album title and leave the artist out in sorting.

**Comment by paulijar** [comment]
>  this is no problem with normal albums, but sampler and compilations are spread all over the place...

What you should do, is to add the tag *album artist* to all your tracks belonging to a compilation. You can set it as "Various Artists" or whatever you like. Then the album will be kept intact. After all, that's what the *album artist* tag is intended for: to have a common nominator when album has tracks from several artists.

In the screen shot below, I have set *album aritst* of the tracks shown as "Eri esittäjiä" (that's "Various artists" in Finnish) and the *track artist* to be the performer of the particular track. You can see how the *track artists* are shown after the the track title in this case.

![image](https://user-images.githubusercontent.com/8565946/49180486-7a0d4c00-f35d-11e8-9946-d64df01fb22f.png)

**Comment by FadeFx** [comment]
That has helped, its quite an effort for a big collection, especially as there are albums by  artists where there is one or two tracks with featured artists, this means i also have to finde these albums and set the album artist mane correctly, but if i know it works, it is well worth the effort.
