### ISSUE TITLE
Add support for PHP 7.3

### ISSUE THREAD

**Issue by steve95** [owncloud/music#673]
PHP 7.3 is out, and Nextcloud 15 has been released with support for it; it would be nice to have it also in this app (it's the only thing that's preventing me from updating).

**Comment by steve95** [comment]
I've tested it and it seems to work fine!

**Comment by paulijar** [comment]
Okay, great! Thanks for the info! I guess we can close this issue then. The next release will contain the support for PHP 7.3.
