### ISSUE TITLE
M3U files listed as tracks on NC13+

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#674]
Currently, I get the m3u files listed in the music app. I was wondering whether that is normal or not? They show up under "Artiste inconnu" which means "Unknown Artist" as shown below with just the name of the file without the extension (as album and title). For me, there is no use to see it listed. Shouldn't the m3u file just be ignored by the music app.

![m3u_playlist](https://user-images.githubusercontent.com/259454/50045306-e348cb00-0090-11e9-861f-64e1b6af4b91.png)

_Originally posted by @greku in https://github.com/owncloud/music/issues/652#issuecomment-447581533_

**Comment by paulijar** [comment]
https://github.com/owncloud/music/issues/652#issuecomment-447596839
https://github.com/owncloud/music/issues/652#issuecomment-447642502
https://github.com/owncloud/music/issues/652#issuecomment-447650465

**Comment by greku** [comment]
I added the script for the migration. I added it to the post_migration. This way is easy to test as it runs when launching the maintenance:repair command. If you think another step is better, I can change it.

In the script, I do a complete clear of the cache after removing the playlist tracks. But I'm not sure if it is necessary to drop everything or the collection would be enough?
https://github.com/greku/music/blob/3085de7b6afb1ab087b87796b0988af62cc77586/migration/playlistcleanup.php#L56

The script will run on every update of the music app, but actually it would be enough to run it once only (with nextcloud >= 13). Is there a way to remember that the migration script has run, so that it is not run for future updates?

**Comment by paulijar** [comment]
> In the script, I do a complete clear of the cache after removing the playlist tracks. But I'm not sure if it is necessary to drop everything or the collection would be enough?

Dropping the collection in this case would be enough from the functional point of view.  It might leave some unused album covers in the cache but that wouldn't be a significant problem. On the other hand, this makes no difference because the whole cache is anyway dropped on all updates by the pre-migration step:
https://github.com/owncloud/music/blob/2736c513c3026f6dd8db30037f19c01df86ae128/migration/premigration.php#L67

> Is there a way to remember that the migration script has run, so that it is not run for future updates?

In the pre-migration step, we do this by checking the previous installed version and running some operations only if the previous version is older than some threshold:
https://github.com/owncloud/music/blob/2736c513c3026f6dd8db30037f19c01df86ae128/migration/premigration.php#L41

> (with nextcloud >= 13)

I believe we shouldn't check the cloud version here. It is well possible that the same issue is present on some or all of the onwCloud versions 10.x ... 12.x (current production version being 10.0 and master branch version 11.0). I also suspect that the maintainer of the cloud instance can alter the file extension to mime mappings.

> If you think another step is better, I can change it.

The differences of the steps are not well documented and this would need some investigation. The only description I have found is this: https://docs.nextcloud.com/server/latest/developer_manual/app/info.html

Based on it, me best guess is that things happen in the following order during the installation:
1. Pre-migration repair steps are run
2. Database schema changes are executed (if any)
3. Post-migration repair steps are run
4. The new application version is installed
5. Install repair steps are run.

Hence, the selected step may have influence on if the previously installed version number is still accessible and if other application PHP modules (like the TrackBusinessLayer) can be safely used from the migration step. But all this is just guessing and it should be tested and verified.

**Comment by paulijar** [comment]
@greku I pulled your branch (even though there was no PR) and gave it some finishing touch and now it's merged to master. Thanks for your contribution!

**Comment by greku** [comment]
Sorry for not finishing it further, I got caught by other things. Thank you
for your support as usual.

**Comment by paulijar** [comment]
The fix is now published in the Music app v0.9.4 => closing
