### ISSUE TITLE
Power Ampache freezing after login

### ISSUE THREAD

**Issue by rkunschke** [owncloud/music#675]
On my device the App freezes after login in when it trys to load the covers.... On 1.09.47-1.09.49
Android 8.0

**Comment by paulijar** [comment]
You might want to report this to the developer of the Power Ampache app antoniotari11@gmail.com. At the moment, there is nothing in this report which would hint that the problem would in fact be in the ownCloud Music app.

Have you checked if the owncloud.log/nextcloud.log file contains any insight after the freeze of Power Ampache?

Is your music collection maybe especially large? I haven't seen this kind of problem on my collection of 178 albums where almost all albums have an embedded cover art image. But I have no experience on using Power Ampache with larger collections.

**Comment by paulijar** [comment]
Closing as there's currently no reason to assume that this would be a problem in the Music app.
