### ISSUE TITLE
On Android app - Albums tab is filled, but Artists is blank

### ISSUE THREAD

**Issue by Poecilia** [owncloud/music#676]
Hi,
I've scanned in my entire music library, which is large. When I download the Android app and sign in, all the albums appear fine, but the artist tab remains empty. Artists do appear in the Nextcloud Music Player version.

**Comment by paulijar** [comment]
Thanks for the report. By "Android app", are you referring to Power Ampache application or which app?

**Comment by Poecilia** [comment]
Hi paulijar,
Yes, I meant the Android app of Power Ampache. However, the problem seems to have resolved itself. I can now see the artists as well as the albums.

There is another issue you may already be aware of, which is that Power Ampache does not deal well with compilations. It seems to turn a compilation album into 20+ mini albums, with one song each. Should I close this thread and open a new one?

**Comment by paulijar** [comment]
> However, the problem seems to have resolved itself. I can now see the artists as well as the albums.

Okay, that's a bit weird. But you said that your collection is huge, so maybe it took some time.

> Power Ampache does not deal well with compilations. It seems to turn a compilation album into 20+ mini albums, with one song each.

Is this really only on Power Ampache or do you see the same phenomenon on the Music app web UI? The album division shown on Power Ampache should be the one provided by the Music app, so it would be very much unexpected if there was a difference.

The thing is, you should have the *Album artist* tag set for your tracks belonging to a compilation album. You can set it to "Various artists" or anything you like, as long as all the tracks of one album have the same *Album artist*. The tracks may still have the actual performer in the *Track artist* field, and both the Music app web UI and Power Ampache show this performing artist on the track. But if you have no *Album artist* set, then the Music app assumes that *Album artist* is the same as the *Track artist* and the tracks of the compilation in fact belong to separate albums which just happen to have the same name.

**Comment by paulijar** [comment]
Closing, as the original problem seems to have resolved itself (and probably was anyway more a problem of Power Ampache than one of the Music app).
