### ISSUE TITLE
First track unrecognized except for cover art

### ISSUE THREAD

**Issue by skeltonn** [owncloud/music#677]
App works perfectly for all tracks except some first tracks on some albums. Funny enough it identifies the cover art each track should have... very curious. Instead each of the relevant tracks is given its own "Unknown Artist" album.

![image](https://user-images.githubusercontent.com/6005278/50733128-26a4cf80-114d-11e9-9bd6-ee3d237bc32a.png)

**Comment by paulijar** [comment]
Thanks for the report.

What do you see if you view the details of one of the problematic tracks? You can open the details view by hovering cursor over the track name and pressing the "i" icon shown after the track name. The details view shows all the metadata of the track exactly like it was extracted from the file. In the main view, on the other hand, some fallback and arbitration logic is used to make the best guess about the artist/album/track titles.

**Comment by skeltonn** [comment]
Looks like the tracks in question have no metadata. For example, here's "Piano Man".

![image](https://user-images.githubusercontent.com/6005278/50742499-c146f200-11d1-11e9-9a4a-0ab5179fbb35.png)

**Comment by paulijar** [comment]
It seems to me, that the first track actually *has* metadata which contains string "Track 1" as title and "Unknown artist" as artist etc. The Music app does not fill those fields here with any "place holders", but shows what it has read from the file metadata. If there was no metadata or reading it would have failed, then the details view would be completely empty.

Can you check the metadata of the first track with any other application?

**Comment by skeltonn** [comment]
You're right. Each track in question had unknown's written for the metadata. Confused on how that came to be, but it's not Music's fault. Thanks for the help. Case closed.
