### ISSUE TITLE
Download&Enable - Not null violation

### ISSUE THREAD

**Issue by qwerted2017** [owncloud/music#678]
Hi,
Try to download and enable app, but get this:
"An exception occurred while executing 'ALTER TABLE oc_music_artists ADD "hash" VARCHAR(32) NOT NULL': SQLSTATE[23502]: Not null violation: 7 ERROR: "hash" column contains NULL values"

I've try to delete and install app music again - no results

Nextcloud 15.0.2, postgresql 9.6.

Log:
{"reqId":"5YQnTFG6WYrguiISIfNH","level":3,"time":"2019-01-21T10:48:37+03:00","remoteAddr":"<ip_addr>","user":"<user>","app":"settings","method":"POST","url":"/settings/apps/enable","message":{"Exception":"Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException","Message":"An exception occurred while executing 'ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL':\n\nSQLSTATE[23502]: Not null violation: 7 ОШИБКА:  столбец \"hash\" содержит значения NULL","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":128,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->","args":["An exception occurred while executing 'ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL':\n\nSQLSTATE[23502]: Not null violation: 7 ОШИБКА:  столбец \"hash\" содержит значения NULL",{"errorInfo":["23502",7,"ОШИБКА:  столбец \"hash\" содержит значения NULL"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":964,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver"},{"errorInfo":["23502",7,"ОШИБКА:  столбец \"hash\" содержит значения NULL"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":260,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":83,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MDB2SchemaManager.php","line":123,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/legacy/db.php","line":188,"function":"updateDbFromStructure","class":"OC\\DB\\MDB2SchemaManager","type":"->","args":["/var/www/html/nextcloud/apps/music/appinfo/database.xml"]},{"file":"/var/www/html/nextcloud/lib/private/Installer.php","line":134,"function":"updateDbFromStructure","class":"OC_DB","type":"::","args":["/var/www/html/nextcloud/apps/music/appinfo/database.xml"]},{"file":"/var/www/html/nextcloud/settings/Controller/AppSettingsController.php","line":441,"function":"installApp","class":"OC\\Installer","type":"->","args":["music"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"enableApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[["music"],[]]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":58,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[23502]: Not null violation: 7 ОШИБКА:  столбец \"hash\" содержит значения NULL","Code":"23502","Trace":[{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":954,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"->","args":["ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":260,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":83,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MDB2SchemaManager.php","line":123,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/legacy/db.php","line":188,"function":"updateDbFromStructure","class":"OC\\DB\\MDB2SchemaManager","type":"->","args":["/var/www/html/nextcloud/apps/music/appinfo/database.xml"]},{"file":"/var/www/html/nextcloud/lib/private/Installer.php","line":134,"function":"updateDbFromStructure","class":"OC_DB","type":"::","args":["/var/www/html/nextcloud/apps/music/appinfo/database.xml"]},{"file":"/var/www/html/nextcloud/settings/Controller/AppSettingsController.php","line":441,"function":"installApp","class":"OC\\Installer","type":"->","args":["music"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"enableApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[["music"],[]]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php","Line":106,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[23502]: Not null violation: 7 ОШИБКА:  столбец \"hash\" содержит значения NULL","Code":"23502","Trace":[{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php","line":104,"function":"query","class":"PDO","type":"->","args":["ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL"]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":954,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDOConnection","type":"->","args":["ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":260,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["ALTER TABLE oc_music_artists ADD \"hash\" VARCHAR(32) NOT NULL"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":83,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MDB2SchemaManager.php","line":123,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/legacy/db.php","line":188,"function":"updateDbFromStructure","class":"OC\\DB\\MDB2SchemaManager","type":"->","args":["/var/www/html/nextcloud/apps/music/appinfo/database.xml"]},{"file":"/var/www/html/nextcloud/lib/private/Installer.php","line":134,"function":"updateDbFromStructure","class":"OC_DB","type":"::","args":["/var/www/html/nextcloud/apps/music/appinfo/database.xml"]},{"file":"/var/www/html/nextcloud/settings/Controller/AppSettingsController.php","line":441,"function":"installApp","class":"OC\\Installer","type":"->","args":["music"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"enableApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[["music"],[]]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php","Line":104}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","version":"15.0.2.0","id":"5c457a7f2378a"}

**Comment by paulijar** [comment]
Have you maybe had an earlier version of the Music app installed some years ago? That kind of errors could be a result if there has been a way older version of Music app installed before which has been removed but some database tables have been left behind. The error message indicates that the installation process could not add a new mandatory column "hash" to the DB table because the table already contains data which does not have this column set.

The Music app does have a migration logic to drop any incompatible data when updating from and earlier version. However, if this earlier version is no longer installed but has just left its DB tables behind, then the Nextcloud/ownCloud core does not trigger our migration code.

If you have direct access to your DB, you could try to run the following commands on it, and then retry the installation:
```
DELETE FROM `oc_music_artists`;
DELETE FROM `oc_music_albums`;
DELETE FROM `oc_music_tracks`;
DELETE FROM `oc_music_playlists`;
```

**Comment by paulijar** [comment]
Great! Case closed.
