### ISSUE TITLE
Treat multi-disc albums as a single album

### ISSUE THREAD

**Issue by maxolasersquad** [owncloud/music#680]
When an albums spans multiple "discs" they appear as separate albums. Example:

![image](https://user-images.githubusercontent.com/177150/51987631-f19c4c00-2470-11e9-8cef-899f04861af7.png)

It would be preferable to combine to have the single album listed once with it's track ordered by disc number first and track second. Example:

![image](https://user-images.githubusercontent.com/177150/51987998-a20a5000-2471-11e9-8a3e-5c6784b3ff5b.png)

**Comment by paulijar** [comment]
Yes, I agree. This is something I have been thinking about before. On the combined album, maybe we should then show the track numbers (for example) as 1-1, 1-2, 1-3, ... , 2-1, 2-2, 2-3, ...

Technically, I believe we need to keep the discs as separate albums in the database, because we need to provide the discs separately in the Ampache API. Or at the least the API looks like it's intended to be used this way. But maybe we could merge the discs into one album on the web UI front-end code. We just need to be smart on this so that the post-processing doesn't take too much time even on huge music collections.

**Comment by paulijar** [comment]
Okay, I guess that people may have different opinions on this :). My point of view is that this is supposed to be a list of albums, not a list of discs. An album being split to multiple discs is just a technical detail originating from the limited capacity of a single disc.

One possibility would also be to combine the multiple discs into one album, but have a subtitle for each disc. So the tracks list would look something like:
```
An album name

Disc 1
1. Some track
2. Another track
3. Yet another track
Disc 2
1. A track on the second disc
2. Another
...
```
This, however, would take somewhat more effort.

**Comment by maxolasersquad** [comment]
> My point of view is that this is supposed to be a list of albums, not a list of discs. An album being split to multiple discs is just a technical detail originating from the limited capacity of a single disc.

That is my point of view as well. The Black Sabbath album 13 is **an** album, not two albums. I'm also not familiar with any other music service that treats multi-disc albums as two separate entities.

Here's a quick mock-up of what you are saying above about the subtitle, which I think looks nice.

![image](https://user-images.githubusercontent.com/177150/52007770-34741900-249d-11e9-864f-65370611e2db.png)

I was trying to find in the Ampache API documentation details on how multi-disc albums are to be handled and didn't find anything. Is that inferred from reading the code?

**Comment by maxolasersquad** [comment]
I found the documentation about how Ampache handles multi-disc albums at https://github.com/ampache/ampache/wiki/XML-API under the **Album XML** section.

**Comment by paulijar** [comment]
> Here's a quick mock-up of what you are saying above about the subtitle, which I think looks nice.

Yes, that's exactly what I had in mind.

> I was trying to find in the Ampache API documentation details on how multi-disc albums are to be handled and didn't find anything. Is that inferred from reading the code?

I took another look, and this isn't actually explicitly stated in the documentation. What hints towards this, is the example of an album document here: https://github.com/ampache/ampache/wiki/XML-API#xml-document-examples
Edit: You seem to have found this yourself while I was writing this :).

**Comment by Faldon** [comment]
It seems, that the Ampache people struggle with the same problem. A database redesign shall be undertaken, according to https://github.com/ampache/ampache/issues/1015 
But it seems, personal resources are little there.

Would it be possible and feasible to redesign the music database while providing "fake" album information to the Ampache API?
If either the disk information is moved to the track table or a or a relation between album and tracks with the disk number added is introduced, the current API could be generated by "calculating" track numbers, like 101, 102, 201...

**Comment by paulijar** [comment]
> Would it be possible and feasible to redesign the music database while providing "fake" album information to the Ampache API?
If either the disk information is moved to the track table or a or a relation between album and tracks with the disk number added is introduced, the current API could be generated by "calculating" track numbers, like 101, 102, 201...

Indeed that would be possible. However, I would also like to avoid making breaking changes on the database schema whenever possible. Forcing all the users to rescan their libraries is not a small thing as the scanning may take quite some time on huge collections. Maybe this schema change could be handled with a migration script without full rescan but that would require some careful engineering.

**Comment by Faldon** [comment]
Re-scanning the music collection can be a huge task, I know.
I'm struggling with it a little bit. I just had a look at my own database (and, alas, I definitely need Ampache access or a neat custom API to design a custom music player. :smile: ). My collection consists, with a few exceptions, of m4a. And if I noticed it right, only the multi-disc albums I own as mp3 have the correct disc number information.
I would gladly have a look at this and try to work out a migration way.

**Comment by lachlan-00** [comment]
This has been merged into the ampache core branch without editing the database structure.

It works in the web interface and over api/subsonic.

**Comment by lachlan-00** [comment]
Another FYI for you all, this has now been merged into the develop branch and is ready for power users to test. After it stabilises it will release as Ampache 4.0.0 with an api version of 400001

The api version will not change when fully released but there are new methods and a change to how the existing stats method works.

**Comment by Nosirus** [comment]
No news ?

**Comment by lachlan-00** [comment]
The API and new version have been released but it depends on how this integrates with music.

**Comment by paulijar** [comment]
The Music release v0.13.1 is now out, and there, we show multi-disc albums as one album. The UI shows the tracks numbers as 1-1, 1-2, 1-3, ..., 2-1, 2-2, ... .

In the Ampache and Subsonic APIs, the disc number is "mangled" into the track number so that track numbers of the multi-disc albums are like 101, 102, 103, ... 201, 202... . The tracks numbers of single-disc albums are not altered.

The change involves a change to the database schema. There is a migration script run during the installation, which should take care of this, and no rescan should be necessary.
