### ISSUE TITLE
ErrorException: Undefined index: filesize

### ISSUE THREAD

**Issue by cdamken** [owncloud/music#681]
browser
Chrome 71.0.3578
browser.name
Chrome
level
info
logger
php
os
Mac OS X 10.14.3
os.name
Mac OS X
release
10.1.0.4
runtime
php 7.0.32
runtime.name
php
transaction
/apps/music/api/album/116082/cover
url
https://cloud.damken.com/index.php/apps/music/api/album/116082/cover
```
ErrorException: Undefined index: filesize
#15 music/3rdparty/getID3/getid3/module.tag.apetag.php(37): handleError
#14 music/3rdparty/getID3/getid3/module.tag.apetag.php(37): Analyze
#13 music/3rdparty/getID3/getid3/module.tag.lyrics3.php(113): Analyze
#12 music/3rdparty/getID3/getid3/getid3.php(535): analyze
#11 music/utility/extractorgetid3.php(45): extract
#10 music/utility/extractorgetid3.php(69): parseEmbeddedCoverArt
#9 music/utility/coverhelper.php(204): readCover
#8 music/utility/coverhelper.php(78): getCoverAndHash
#7 music/controller/apicontroller.php(435): cover
#6 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(153): executeController
#5 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(85): dispatch
#4 /var/www/owncloud/lib/private/AppFramework/App.php(100): main
#3 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): __invoke
#2 /var/www/owncloud/lib/private/Route/Router.php(342): match
#1 /var/www/owncloud/lib/base.php(909): handleRequest
#0 /var/www/owncloud/index.php(54): null
```

**Comment by paulijar** [comment]
I changed the title of this report because the original title had nothing to do with the supplied stack trace. Those "rewinddir(): XXX is not a valid Directory resource" message showing up in the debug logs is a core-side problem followed at https://github.com/owncloud/core/issues/25289.

**Comment by paulijar** [comment]
@cdamken Can you give any more information about this problem? What were you doing when this occurred? Did this happen once or every time you do the same thing?

**Comment by paulijar** [comment]
With no further information about the steps leading to this exception, there's no way to investigate this further. Closing.
