### ISSUE TITLE
Issues with the dark theme in nextcloud

### ISSUE THREAD

**Issue by cromefire** [owncloud/music#683]
All the icons and button are black and so is the background in dark mode, which makes it almost impossible to see the buttons:
![image](https://user-images.githubusercontent.com/26320625/52526454-2d2ce680-2cb9-11e9-92e6-1d41c37f4de2.png)

**Comment by paulijar** [comment]
Thanks for the report.

@nextcloud/designers Can anyone describe, how individual applications are supposed to handle the dark theme? Is there any documentation?

**Comment by Faldon** [comment]
For Nextcloud I have got a fix up my sleeves. But unfortunately, this would break compatibility with Owncloud.
I'll dig a little deeper if there is a common fix possible.
