### ISSUE TITLE
App asking login details when playing

### ISSUE THREAD

**Issue by henriquebs12** [owncloud/music#684]
Frequently when I click on a file to play it (using the music app), the browser asks my login and password, with the browser's native interface.

I've just did a fresh install and used the scan command to find my files.

If I just reload the page, it will sometimes play, sometimes ask the login details again. There is NOTHING in my logs, and I'm with debug mode enabled, with logging set to 0.

**Comment by paulijar** [comment]
Thanks for the report.

Which version of ownCloud or Nextcloud are your using? Which browser? Do you mean that this may happen multiple times during one browsing session?

**Comment by henriquebs12** [comment]
It is the latest Nextcloud 15.0.4. But it stopped happening. If anything changes again I let you know.

**Comment by paulijar** [comment]
Presumably this problem was somewhere else than the Music app itself. Closing.
