### ISSUE TITLE
[Feature request] Gapless Playback

### ISSUE THREAD

**Issue by stroudmw** [owncloud/music#685]
Is gapless playback possible?

**Comment by hbruecher** [comment]
would be highly appreciated

**Comment by paulijar** [comment]
The new Music v1.6.0 now makes the playback gapless. It starts buffering the next song in queue once the currently playing song is fully buffered. Then, it starts playing the new song about 200 ms before the previous playback ends. This way, the listener should not hear any kind of gap, provided that the source material is gapless.
