### ISSUE TITLE
Player crashes while playing some files

### ISSUE THREAD

**Issue by LeonsDepot** [owncloud/music#686]
Hi,

when playing some .flac files the player crashes. I think that the files are not damaged because they are played normally by the "Windows Media Player" and the "Black Player".

The error occurs, for example, with the following file from minute 1:10.
File: https://drive.google.com/file/d/1TtGIlDbdIl7f2l6lvIMYdr3jreaxQP-b/view?usp=drivesdk

**Comment by LeonsDepot** [comment]
Okay the player crashes only in Firefox Desktop/Android ( i dont own a Iphone for testing it). Chromium, and Opera play this song very well.

I close this issue and repost it on bugzilla :+1:

**Comment by paulijar** [comment]
Yeah, the playback stops on Firefox at 1:10 even if you just play the file from the link above. So this is clearly not an issue of the Music app or ownCloud/Nextcloud.
