### ISSUE TITLE
Music app greyed out 

### ISSUE THREAD

**Issue by dropitlikecross** [owncloud/music#687]
Nextcloud version (eg, 12.0.2): 15.0.4
Operating system and version (eg, Ubuntu 17.04): Ubuntu 18.04
Apache or nginx version (eg, Apache 2.4.25): nginx/1.15.8
PHP version (eg, 7.1): 7.3

The issue you are facing:
Music app is greyed out for agree and install

![757cb4556e13b596c3f7f4763908c2e92ac055f7](https://user-images.githubusercontent.com/44788043/53235707-d4584780-36d5-11e9-94da-86095dfdb37d.png)

**Comment by paulijar** [comment]
This is probably because the support for PHP 7.3 is not yet included in the latest Music app release. The support has been already added, so this should get fixed with the next release.

**Comment by paulijar** [comment]
@dropitlikecross Music app v0.9.4 with the support for PHP 7.3 is now published. Did this solve the issue for you?

**Comment by paulijar** [comment]
I assume this is fixed now.
