### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by Kondou-ger** [owncloud/music#69]
There should be a volume slider.

And don't say "use your operating systems volume control", as:
1. Every application should be able to control itself
2. Clicking on a small button somewhere and then changing the volume is a bit cumbersome
3. I'm using ALSA and don't have one: 
![screenshot406](https://f.cloud.github.com/assets/1410802/1062244/b17e78e6-1233-11e3-98fd-f75a31b5d838.png)

@kabum @jancborchardt

**Comment by e-alfred** [comment]
Hello,

I would be indeed practical to have a volume control in the music app because not every platform lets you control volumes separately in an easy fashion (like Kmix for example).

**Comment by paulijar** [comment]
Implemented in #537
cc @gnarula
