### ISSUE TITLE
No way to easily restart playback

### ISSUE THREAD

**Issue by benapetr** [owncloud/music#691]
Pressing the << button always move to previous song, most of music players restart playback of current song, unless it's already on song beginning (pressing twice go to previous song, pressing once restarts playback).

**Comment by paulijar** [comment]
Well, I can think of at least three ways to restart playback:
1. Click on the left end of the progress bar
2. Click another track and then again the track you were listening
3. Click << button followed by >> button (or vice versa). Btw, you can also use the arrow keys from the keyboard for the same purpose.

The behavior you described would of course be possible to implement, too. But to be able to say that "most" players do that, you would need to test pretty many players :).

I just now tested two PC player programs and one home stereo system. One of those programs and the home stereo handled the "Previous" button as you described and the other program handled it like the ownCloud Music app currently does.

**Comment by paulijar** [comment]
The requested functionality of the "<<" button is now implemented and released in the version 0.9.5
