### ISSUE TITLE
Playback in Nextcloud with Firefox

### ISSUE THREAD

**Issue by dbeurle** [owncloud/music#692]
I'm having troubling with playback using Nextcloud 15 and Firefox 66 on Fedora 29.  It works without problem on 'Web' the GNOME bundled web browser, so I think the problem lies with the Firefox playback.  Is this a known problem or are there any steps suggested for debugging this issue?

Thanks.

**Comment by paulijar** [comment]
This is not a know issue. There might be something wrong with the audio codecs on your Firefox installation.

What do you see, if you open the developer console on Firefox and try to play some track? What is the file format of your audio files and have you tested any other formats?

Also, if you have installed any plugins on Firefox, then one of those could be blocking the playback. There once was a similar error reported by a user who had a plugin designed to specifically block audio playback from javascript.

**Comment by dbeurle** [comment]
Okay it seems it's an isolated problem due to the particular firefox I had.  An update seemed to fix it.
