### ISSUE TITLE
exception when render JSONResponse fileinfo details pane

### ISSUE THREAD

**Issue by greku** [owncloud/music#693]
I have an issue with some of my audio files when opening the details pane.
The server returns http code 500 when requesting the file details.
The error is caused by an exception in JSONResponse encode: https://github.com/nextcloud/server/blob/2e36069e24406455ad3f3998aa25e2a949d1402a/lib/public/AppFramework/Http/JSONResponse.php#L71

This seems to be due to strange characters present in the fileinfo/encoder string. (see attached picture)
![issue_fileinfo_mp3](https://user-images.githubusercontent.com/259454/55674893-1373de00-58bb-11e9-9696-1b008bd70ebd.png)

I have music app version 0.9.3, nextcloud 13.

**Comment by paulijar** [comment]
Thanks for the report. I believe we should add sanitazing of the details data to about here: https://github.com/owncloud/music/blob/master/utility/detailshelper.php#L42.

This kind of thing already happens for the fields which are added to the database, but this path is is not executed when getting data for the details data: https://github.com/owncloud/music/blob/master/utility/extractorgetid3.php#L84.

**Comment by greku** [comment]
Thanks for the guidance. This seems to solve the problem on my setup. Please review the change too.

**Comment by paulijar** [comment]
The fix is now released in version 0.9.5
