### ISSUE TITLE
alphabet navigation artists/albums starting by number

### ISSUE THREAD

**Issue by greku** [owncloud/music#696]
I have artist that start with a number like "3...". in that case, it is sorted before 'A', but clicking on the first element of the alphabet link "A" doesn't go to the top of course,  and therefore, not up to this artist "3...". My suggestion is to add '#' symbol before A, that goes to the top of the list.
See: https://github.com/greku/music/tree/alpha_nav_num

**Comment by paulijar** [comment]
Solved by #697
