### ISSUE TITLE
Introduce intelligent filters

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/music#7]
I'd like to see the list of music reworked.

The Main list should only show these items:
- Compilations (see issue #5)
- Artists (the list as it is today, enhanced by issue #6)
- Albums and [EPs](http://en.wikipedia.org/wiki/Extended_play#Defining_EP) (files that have a non empty "album" tag and there is more than one file per artist/album combination, grouped by artist -> album)
- Singles (files that do not have an "album" tag set, have an empty "album" tag or that are the only ones having the given artist/album combination)
- Genres
- Years

---

Originally reported by @dryo at https://github.com/owncloud/apps/issues/130

**Comment by paulijar** [comment]
It's time to close this decade-old issue. The Music app is today quite different from what it was at the time when this feature request was submitted. IMHO, this is also too broad to be handled as a single feature request, containing multiple items each requiring a significant amount of work. Some of those items I could consider while others I don't really like.
