### ISSUE TITLE
After I upgraded the plug-in, I was unable to use version 16.

### ISSUE THREAD

**Issue by CF673** [owncloud/music#701]
After I upgraded the plug-in, I was unable to use version 16.

**Comment by CF673** [comment]
An exception occurred while executing 'CREATE TABLE `oc_audioplayer_artists` (`id` INT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `name` VARCHAR(256) DEFAULT NULL, INDEX artists_user_id_idx (`user_id`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1005 Can't create table 'pan_cf673_com.oc_audioplayer_artists' (errno: -1)

**Comment by paulijar** [comment]
The error message is about a database table of the Audioplayer app which is completely separate app from the Music app. I can see you reported (probably) the same bug in Chinese also for the Audioplayer app here: https://github.com/Rello/audioplayer/issues/395.

So is this error related only to Audioplayer or is there some connection to the Music app?

**Comment by paulijar** [comment]
I assume this is an Audioplayer issue. Closing.

**Comment by Rello** [comment]
@paulijar thanks....
