### ISSUE TITLE
Integrate Music with Viewer

### ISSUE THREAD

**Issue by jtagcat** [owncloud/music#704]
Hey, [Viewer](https://github.com/nextcloud/viewer) is efforts in making previews universal and solving the problem of having tens of preview apps being available (while having similar functions, inconsistent UI). Would be much appreciated if you'd take a look at [this](
https://github.com/nextcloud/viewer/issues/126).

**Comment by paulijar** [comment]
I think there's no need to keep this ticket open on the Music app side. If Music playing support is added to Viewer, it will happen in the Viewer project and followed there.
