### ISSUE TITLE
Can't install "Music" app. -> Exception occurred while executing 'ALTER TABLE...

### ISSUE THREAD

**Issue by ErkanF** [owncloud/music#707]
An exception occurred while executing 'ALTER TABLE oc_music_artists ADD PRIMARY KEY (`id`)': SQLSTATE[42S02]: Base table or view not found: 1932 Table 'nextcloud.oc_music_artists' doesn't exist in engine

**Comment by paulijar** [comment]
This is the first time I see an error message like that, so I don't really know what's wrong. You could try to remove all the database tables of the Music app and then retry the installation and see if that helps. That is, in your database management console, run
```
drop table oc_music_albums;
drop table oc_music_ampache_sessions;
drop table oc_music_ampache_users;
drop table oc_music_artists;
drop table oc_music_cache;
drop table oc_music_playlists;
drop table oc_music_tracks;
```

**Comment by ErkanF** [comment]
Thx for your answer Paulijar, I have made what you said but now, it seem unfortunatly worse... I have this message now when I try to install it.

An exception occurred while executing 'CREATE TABLE `oc_music_artists` (`id` INT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `name` VARCHAR(256) DEFAULT NULL, `image` VARCHAR(256) DEFAULT NULL, `mbid` VARCHAR(36) DEFAULT NULL, `hash` VARCHAR(32) NOT NULL COMMENT 'Unique hash formed from the artist name. The name field as such is too long to be indexed.', UNIQUE INDEX user_id_hash_idx (`user_id`, `hash`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1813 Tablespace for table '`nextcloud`.`oc_music_artists`' exists. Please DISCARD the tablespace before IMPORT

**Comment by paulijar** [comment]
Sorry to hear that :(. Could you maybe find any help from the following post: https://stackoverflow.com/questions/15694168/error-tablespace-for-table-xxx-exists-please-discard-the-tablespace-before-imp ?

**Comment by ErkanF** [comment]
Thats's great it has worked when I removed all " oc_music_XXXXX.idb " files in /var/lib/mysql/nextcloud. thanks a lot.

**Comment by paulijar** [comment]
Great! 👍

**Comment by paulijar** [comment]
I think it's unlikely that the root cause for this problem was in the Music app itself. More likely, the problem was somewhere between the Nextcloud application installation framework and the database management system. => Case closed for the Music app
