### ISSUE TITLE
Questionmarks instead of title

### ISSUE THREAD

**Issue by simmeeeeeee** [owncloud/music#711]
When playing music, only two question marks are displayed in a diamond instead of author and title. I tried to reinstall owncloud but it did not help.
![issue](https://user-images.githubusercontent.com/53971593/62821800-ca8aa980-bb7a-11e9-8213-52d55bd2be73.PNG)

**Comment by paulijar** [comment]
Thanks for the report. 

Those are "unicode substitution characters" which basically means that the metadata of the track contained characters which could not be interpreted as valid characters. This could happen at least when the metadata contains data in one encoding but claims to use another encoding. For example, the metadata could claim to be in UTF-8 but actually contain Latin-1 encoded characters.

If, however, the metadata of the file would be valid but it would still be broken on the Music app, then it would mean that that the data somehow gets corrupted when the Music app reads it. I have never seen this happen, but maybe some kind of server setup could cause it.

Do you see this problem on multiple files obtained from many different sources? Or is it only one file which has been tested to have this problem? Should the artist and title contain just Latin characters or is it some more exotic language?

**Comment by simmeeeeeee** [comment]
Hi, it is in itself normal German language. (With letters like ä ö ü ß). The error occurs randomly, both for titles with these letters and for titles without.

**Comment by paulijar** [comment]
By "randomly", do you mean that it happens on some files and doesn't happen on others? Or that taking a single file, it may sometimes happen and sometimes it doesn't?

**Comment by simmeeeeeee** [comment]
It happens on some files (about 70 %). While loading the file, the title is displayed correctly.
![grafik](https://user-images.githubusercontent.com/53971593/63042709-e2d82c80-beca-11e9-9cbe-08e375f55bc8.png)

**Comment by paulijar** [comment]
Is there anything common on those files where the problem occurs? Maybe they have been all tagged with the same software, or they all reside on some externally mounted SMB share?

During the "Loading..." phase, the title shown is based only on the file name. It gets replaced with the track title and artist name from the ID3/APE tags once this metadata has been extracted.

**Comment by simmeeeeeee** [comment]
The files actually have no ID3 tag, just the file name. All files were recorded with the same software and saved in the same folder. When I add tags, the file loads infinitely and never plays.

**Comment by paulijar** [comment]
Do those tagged files work fine when played on some other application on your PC?

**Comment by paulijar** [comment]
Is this old issue still valid with the latest versions of Music? If it is, then would it be possible to get a sample file demonstrating this issue?

**Comment by paulijar** [comment]
There's no way to investigate this any further without a sample file.
