### ISSUE TITLE
Plasma Integration support

### ISSUE THREAD

**Issue by Thesola10** [owncloud/music#713]
There is an extension available for Google Chrome and Firefox called Plasma Integration, which allows the browser to interact with features of the Plasma desktop (and other Linux desktops).
The feature that does not currently work is the media player control, which exposes the currently playing media from within the browser to the desktop, allowing the user to use their media keys to control it. Currently, music playing from ownCloud Music isn't detected by Plasma Integration whatsoever, when other websites (such as YouTube) do work.

Could someone look into what is preventing the extension from "seeing" the music playback?

**Comment by Thesola10** [comment]
The issue was filed and fixed on the KDE team's side with the latest release of the Firefox plugin.

**Comment by paulijar** [comment]
Okay, great!
