### ISSUE TITLE
getID3 incompatibility

### ISSUE THREAD

**Issue by Rello** [owncloud/music#715]
Hello @paulijar 

with this change, the getID3 was separated. 
https://github.com/owncloud/music/issues/551

but for some reasons, the issue is back. when using occ from another app (Audio Player in this case), your implementation is being used. perhaps due to the declaration in `/app/music.app`?

in general this should not be an issue as James adapted the getID3 for our need with the file pointer
https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.php#L408

but for some reason, your getID3 differs here with another sequence in the function call
https://github.com/owncloud/music/blob/master/3rdparty/getID3/getid3/getid3.php#L410

can you adapt music to the stock-getID3, so all apps using it don´t get errors?
`Error	PHP	get_resource_type() expects parameter 1 to be resource, int given at /var/www/domains/tnonline.net/htdocs/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#437`

in parallel we need to find out why your part is accessed at all. I might open a NC request for this

**Comment by paulijar** [comment]
Okay, that's interesting.

Music app is still using the modified getID3 v1.9.16 version as there has been no pressing reason to update to v1.9.17 (which includes the file pointer API out-of-the-box). But this sounds like one, so I'll make the update in a few days.

**Comment by Rello** [comment]
thank you.
you might want to check this also regarding the "why is this happening at all":
https://github.com/nextcloud/server/issues/17027

**Comment by paulijar** [comment]
I just released a new Music app version 0.10.1 where the getID3 library is lazy-loaded to avoid it being loaded in the reported use case. Furthermore, the getID3 library was updated to the "stock" version 1.9.17.

**Comment by Rello** [comment]
Thank you, @paulijar
