### ISSUE TITLE
Streaming to wlan speaker with mobile (eg chromecast, Sonos, ...)

### ISSUE THREAD

**Issue by jakobroehrl** [owncloud/music#717]
Hey guys, 
are here someone who streams the music to wlan speakers?
I tested a lot. 
Sonos is only working if I expose the music files with samba. 
Chromecast works for me, if I play the music on the mobile phone and forward it to the chromecast.
Are there any other working setups?
Thanks!

**Comment by paulijar** [comment]
As described in #720, the DSub version 5.5.1 is compatible with the Music app, and can be used to stream to Chromecast. For me, the Chromecast streaming worked first very unreliably but much better after I checked "Use device proxy" in the Casting settings of DSub. There were still quite many hick-ups but I have seen these with Chromecast on other apps, too. My Android version is rather antique, so your mileage may vary.

Apart from DSub, I don't know of any working solution to stream audio from the Music app to an external playback device. As no-one has commented here about any other possibilities for more than a year, I think that this issue can be closed now.
