### ISSUE TITLE
Too many requests due to Album covers

### ISSUE THREAD

**Issue by ilvalle** [owncloud/music#719]
Both browser and the server are suffering because a lot of requests are made to fetch the album covers when a user access the music homepage. Is there a better way to fetch only those 'visible' in the page?

**Comment by paulijar** [comment]
Yes, that might be a problem with large music collections. I haven't seen any issues like this when having 200+ albums with covers. But I guess, that if you have thousands of albums with covers, then you will very likely run into problems.

There might be some smarter ways to load the covers. However, if we implement some mechanism like that, then we should make certain that we don't hinder the user experience of the owners of the small to medium sized music collections too much. But pull requests are welcome if anyone has idea about how to make this smoothly.

**Comment by paulijar** [comment]
Lazy-loading of album art has been implemented in v0.12.0 which was just released.
