### ISSUE TITLE
the app music has a reference to file placeholder.js delete since nextcloud version 16

### ISSUE THREAD

**Issue by lerd2805** [owncloud/music#721]
[jsresourceloader] Error: Could not find resource core/js/placeholder.js to load GET /apps/music/ from xxx.xx.xxx.xx by xxxxxx at 2019-10-25T22:35:41+00:00

Hi, I don't know if this really counts as a bug, but when trying to use the music app in nextcloud version 17, an error is registered that the placeholder.js file cannot be found, I don't know if it can be corrected so that this error does not appear.

I apologize if this does not count as an issue and my bad English.

**Comment by paulijar** [comment]
Yes, I actually noticed this myself maybe a week ago, but had already forgotten :). So it's good to have a reminder here.

**Comment by lerd2805** [comment]
Thanks you are right if I manually add this file the error stops appearing.

**Comment by paulijar** [comment]
The fix is now released in v0.11.1.
