### ISSUE TITLE
I'd like to help your owncloud

### ISSUE THREAD

**Issue by tjalsrb97** [owncloud/music#722]
We are Kwangwoon University students in South Korea and our major is computer engineering. We are very interested in listening to music, so I'm studying about the music software owncloud.
But It's not easy to understand because we are just normal students and don't know how to use. So we felt that many people wanting to study music software needs to read easy document(README).
Because of this reason, we propose the questions.

How do you think we propose documents that are easy to understand owncloud?
To make it easier for us to understand the owncloud, why don't we give more details about the owncloud?
Can I submit README document in Korean for Koreans using the owncloud?
Please read the issue carefully and think positively. Thank you for reading the long article. ^_^

**Comment by paulijar** [comment]
Thanks for the interest on the Music app and sorry for the delayed answer.

The language of this github project is English and I'd like to keep it that way. After all, as the owner/maintainer of the project, I feel I'm somewhat responsible of all the content in this project repository. If part of the content would be written in a language I don't understand, it would make my position difficult.

What you could do, is to create a new fork of this project. You could keep the source codes of your fork in sync with the main repository if you like. But in your own fork, you would be free to use the Wiki feature of github to create whatever documents you want.
