### ISSUE TITLE
Details of a song is logging errors

### ISSUE THREAD

**Issue by lerd2805** [owncloud/music#726]
Hi dear friend,

When I try to open the details of a song is logging these errors:

[PHP] Error: Use of undefined constant self - assumed 'self' (this will throw an Error in a future version of PHP) at /var/www/nextcloud/apps/music/utility/detailshelper.php#44

GET /apps/music/api/file/1043/details
from xx.xx.xx.xx by xxxxxxxx at 2019-11-19T19:25:58+00:00

[PHP] Error: Use of undefined constant self - assumed 'self' (this will throw an Error in a future version of PHP) at /var/www/nextcloud/apps/music/utility/detailshelper.php#45

GET /apps/music/api/file/1043/details
from xx.xx.xx.xx by xxxxxxxx at 2019-11-19T19:25:58+00:00

I use PHP version 7.2.24, i fixed by adding single quote on this variable in detailshelper.php line 44 and 45:

ORIGINAL CODE:

                        // cleanup strings from invalid characters
                        array_walk($data['audio'], [self, 'sanitizeString']);
                        array_walk($data['comments'], [self, 'sanitizeString']);

MODIFY CODE: 

                        // cleanup strings from invalid characters
                        array_walk($data['audio'], ['self', 'sanitizeString']);
                        array_walk($data['comments'], ['self', 'sanitizeString']);

I know it's not a bug, it may be due to a change of the php version to declare the variable self.

Sorry for my bad english, I thank you for such an excellent job you do with this app.

Regards.

**Comment by paulijar** [comment]
Hi. I actually made the same fix in commit a9201fd484 two weeks ago, but haven't had time to publish a new release. My target is now to make the release this week, probably during weekend.

**Comment by paulijar** [comment]
The release v0.11.1 fixing this issue is now public, a bit sooner than I expected.
