### ISSUE TITLE
Ampache 4.0.0 with new API out

### ISSUE THREAD

**Issue by lachlan-00** [owncloud/music#727]
Hi (pressed enter in title)

Ampache has a new release coming with an updated API (4) and subsonic updated to 1.13 and a lot of extra methods and changes.

I'm going to be releasing in the next month and would like to help if I can

**Comment by paulijar** [comment]
Okay, thanks for the info and the offer.

Is there any reference client which would be utilizing the new API? Is there any documentation about the XML API except the rather cursory https://github.com/ampache/ampache/wiki/XML-API ?

**Comment by lachlan-00** [comment]
I'm working on building the documentation out further. The method list gives decent details about each function.
https://github.com/ampache/ampache/wiki/XML-methods

 if you have any examples of documentation or specific needs let me know. i want to make it as easy as possible for people to pick up.

**Comment by paulijar** [comment]
@lachlan-00 Okay, thanks for the info. I was mostly missing for example responses, but you seem to have added them to https://github.com/lachlan-00/python3-ampache/tree/master/docs/xml-responses just a few days ago. That goes a long way, thanks for those.

Btw, I noticed that the contents of your albums.xml example seem to be incorrect. It appears to be a copy of artist.xml.

**Comment by lachlan-00** [comment]
That's good to know thanks for checking them out. I'll have another look and fix those up and once I add error responses I'll add links into the Ampache wiki.

**Comment by paulijar** [comment]
The newly released Music v0.17.0 includes a quite large chunk of the Ampache API v4.0.0. There might be some features from 4.1.0 or 4.2.0, too, but I'm not certain. As we have never covered 100% of the Ampache API and probably never will, I think it's time to close this issue. Improving the Ampache API support will of course still continue in the future releases.
