### ISSUE TITLE
Subsonic API: support JSON output (f=json parameter)

### ISSUE THREAD

**Issue by MichaelBechHansen** [owncloud/music#730]
Some Subsonic client apps rely on the JSON-response feature of the Subsonic API.
Clients amy request JSON response by using the f=json parameter as documented in the 'introduction' section of http://www.subsonic.org/pages/api.jsp.

It seems owncloud will only respond with XML in the Subsonic API, even when f=json is requested.

Related to https://github.com/owncloud/music/issues/724

**Comment by paulijar** [comment]
That really shouldn't be the case. The support for json responses was actually implemented *before* the xml responses because the first client I used was [Supersonic](https://www.microsoft.com/fi-fi/p/supersonic/9wzdncrdmspv?rtc=1&activetab=pivot:overviewtab) which uses `f=json`. Supersonic still works fine on my system, so I'm quite amazed if the json responses don't work on your system.

**Comment by MichaelBechHansen** [comment]
Which version was f=json added in?
Maybe it's an issue with an older server...

At least when using this against a play:Sub customer server:
https://SERVERURL/index.php/apps/music/subsonic/rest/ping.view?c=test&f=json&v=1.9.0

I get an XML response back:
`
<?xml version="1.0" standalone="yes"?>
<subsonic-response status="failed" version="1.8.0">
    <error code="10" message="Required credentials missing"/>
</subsonic-response>
`

**Comment by MichaelBechHansen** [comment]
Hmmm... forget the comment about older servers.
Reading your comment again, it's clear that JSON-support predated XML-support.
Still, the server return XML when given the f=json parameter.

**Comment by paulijar** [comment]
Okay, seems you have found an edge case which I hadn't considered. Your request is missing the mandatory username (u=...) and password (p=...) parameters. The thing is, the Music app now checks these credentials already before reading the f= parameter. As the credentials are missing, the handling is terminated before evaluating the f=json, and the error response is given in the default format (xml).

The "real" Subsonic server is able to give the error response in json format in this case, as can be seen by fetching http://demo.subsonic.org/rest/ping.view?c=test&f=json&v=1.9.0. => To be fixed on the Music app.

**Comment by MichaelBechHansen** [comment]
OK.

Giving invalid u/p parameters also gives back an XML response:
https://SERVERURL/index.php/apps/music/subsonic/rest/ping.view?c=test&f=json&v=1.9.0&u=admin&p=I_DONT_KNOW

Response:
< ?xml version="1.0" standalone="yes"? >
< subsonic-response status="failed" version="1.8.0" >
    < error code="40" message="Invalid Login"/ >
< /subsonic-response >

**Comment by paulijar** [comment]
Yes, also checking the validity of the credentials happens before evaluating the f=json parameter.

**Comment by paulijar** [comment]
This has been fixed in v0.12.0 which was just released.
