### ISSUE TITLE
Is it possible to use an external drive different from the NextCloud Data drive?

### ISSUE THREAD

**Issue by hialvaro** [owncloud/music#732]
I've got a HDD with my music, it's different from the Nextcloud Data drive. Is it possible to be used as my "music directory"?

**Comment by paulijar** [comment]
Yes, it's possible.

You should enable the "External storage support" app on your Nextcloud instance. Then you will see "Extrernal storages" under your administrator settings. There, you can map a new "Local" storage, which allows you to make any folder available on your server file system visible within your Nextcloud instance. Then, you can use the settings view of the Music app to select the newly mapped external storage as your music collection path.

**Comment by hialvaro** [comment]
> Yes, it's possible.
> 
> You should enable the "External storage support" app on your Nextcloud instance. Then you will see "Extrernal storages" under your administrator settings. There, you can map a new "Local" storage, which allows you to make any folder available on your server file system visible within your Nextcloud instance. Then, you can use the settings view of the Music app to select the newly mapped external storage as your music collection path.

Thank you very much!
