### ISSUE TITLE
Albums with multiple discs are being displayed separately with no visual clue why.

### ISSUE THREAD

**Issue by RobertZenz** [owncloud/music#735]
If you've got an album which spans multiple discs (`DISC` tag on the files), then each disc is being displayed as its own album. However, there is no visual clue as to why that is the case.

Maybe the disc number could be displayed in the album title if the `DISCS` tag is not "1".

**Comment by paulijar** [comment]
Yes, this is something which has annoyed myself for a long time. But it has never been the most urgent issue, so I haven't invested my time on it, yet.

The right solution for the problem would be the one discussed in #680. Adding the disc number label after the album name is also an option, which has crossed my mind before. I might consider implementing it as a temporary solution, but I'm a bit worried that making this solution would make it even less likely, that I find time and motivation to do the right thing any time soon :).

**Comment by RobertZenz** [comment]
Odd that I managed to miss that issue.

Duplicate of #680.
