### ISSUE TITLE
Blank Metadata in DSub when Ampersand (&) is used

### ISSUE THREAD

**Issue by The1AndMany** [owncloud/music#736]
Sorry if this is in the wrong spot, but I'm not sure whether this is an issue with DSub or the Music app.

### Steps to reproduce
1. Use Nextcloud & DSub
2. Connect the two

### Expected behaviour
All metadata should populate properly

### Actual behaviour
Some metadata appears to return an empty string, despite the metadata being there and showing up fine in the web interface. Initial troubleshooting suggests ampersands (&) cause this behavior.

| Description | Mobile | Web |
|-------------|--------|------|
Viewing Album Listing (Zelda & Chill) | ![Screenshot_20200115-133509_DSub](https://user-images.githubusercontent.com/26637883/72473703-209ff080-379c-11ea-9d68-a83e1b7d5948.png) | ![Screenshot_2020-01-15 Music - Skip Cloud(1)](https://user-images.githubusercontent.com/26637883/72473722-272e6800-379c-11ea-9e34-4603cd124b01.png)
Viewing Album Tracks (Featuring multiple artists, listed with &) | ![Screenshot_20200115-133525_DSub](https://user-images.githubusercontent.com/26637883/72473707-23024a80-379c-11ea-86f2-6e896946100b.png) | ![Screenshot_2020-01-15 Music - Skip Cloud](https://user-images.githubusercontent.com/26637883/72473724-285f9500-379c-11ea-88d1-c87580d9f024.png)
Viewing Artist Listings (I have a handful that include &, and a cursory glance indicates several are in the resulting entry) | ![Screenshot_20200115-133449_DSub](https://user-images.githubusercontent.com/26637883/72473699-1ed62d00-379c-11ea-98f2-09161abb1fc8.png) | (Impractical to display on web)

**Comment by paulijar** [comment]
This is the correct place :).

Which version of Music app are you using? This bug should be fixed as of v0.12.0.

**Comment by The1AndMany** [comment]
Ah, that explains it. I was using v0.11.1, but for some reason my instance didn't notify me that an update was available. Sorry about that!

Updated, issue seems to be gone. Thanks a bunch!
