### ISSUE TITLE
Broken CSS in dark mode (NC18)

### ISSUE THREAD

**Issue by moviuro** [owncloud/music#739]
Hi,

I have an issue with the music app on Chromium 79 and Firefox 72 on Linux x86_64. When scrolling past the first screen, I get a white background even though I enabled the "dark mode".

See [screenshot](https://sco.popho.be/s/daxRxrEoSCtbydr/preview) (link valid until 2020-02-26).

This issue is specific to the music app and doesn't happen in the Gallery, or "Files" views (Nextcloud 18.0.0 on FreeBSD 12.0).

If you need more info, I'm available.

**Comment by paulijar** [comment]
Thanks for the report.

I couldn't reproduce this issue on Nextcloud 17.0.0 (and Win10, Firefox 72/Chrome 79). Might be something specific to NC18, but I don't currently have test environment with this cloud version.

I guess you have already made forced reload to rule out some weird browser caching issues?

**Comment by moviuro** [comment]
> I couldn't reproduce this issue on Nextcloud 17.0.0 (and Win10, Firefox 72/Chrome 79). Might be something specific to NC18, but I don't currently have test environment with this cloud version.

It seems indeed to be due to NC18, as I don't recall having the issue with NC17 previously.

> I guess you have already made forced reload to rule out some weird browser caching issues?

Yup, tried different accounts, browsers, force refresh, anonymous session...

**Comment by paulijar** [comment]
I now managed to set up a test environment with NC18. This kind of looks like a Nextcloud core bug, but anyway, I managed to create a workaround within the Music app.

Music app version 0.13.0 including also this fix was just released.

**Comment by moviuro** [comment]
@paulijar thanks! Did you open or find the related bug for Nextcloud core though? It'd be nice to have it fixed once and for all for all present and future applications.

**Comment by paulijar** [comment]
@moviuro I now had time to look into Nextcloud server issues, and I believe that https://github.com/nextcloud/server/issues/19474 has the same root cause. I added my comments there.
