### ISSUE TITLE
Scans not working recursively

### ISSUE THREAD

**Issue by terencedesu** [owncloud/music#740]
I have just set up my music collection on an SMB drive and want to scan it. I set the path to the folder of music in the settings, but when I go to an album folder in the Files section and start playing, then switch to Music it offers to scan but only scans the one folder I am playing. I believe it is supposed to be recursive for the whole path in the settings but it doesn't do it. It would take to long to add each album one at a time.

**Comment by paulijar** [comment]
The thing is, for the Music app, a file exists only if it has been indexed by the Files app. For normal local files, the indexing happens automatically, but for the external files (like the ones on mounted SMB drive), it happens only once you browse to each folder.

I *think* you could force Files to scan all the folders by using the command line tool `occ files:scan`. It worked for mea at least with a local external storage, and a few files. With a large set of files on SMB, it will probably take quite some time, and you may need to leave it running overnight.

In case you are not familiar with `occ`, this is a command line utility which can be found from the root of the ownCloud/Nextcloud installation. It has to be run as the "web server user", so the full command would be something like
```
sudo -u www-data ./occ files:scan someUserName
```

After the Files app has found the files, you can perform also the metadata scanning of the Music app by running
```
sudo -u www-data ./occ music:scan someUserName
```
This does the same thing as scanning on the Music app web UI, but might be slightly faster. Also, on huge music collections, there is a risk that a web server timeout would stop the scanning but with `occ` this should not happen.

**Comment by terencedesu** [comment]
Thanks for the info. I wonder if it may have been a browser issue. I use the Brave browser, which was where I observed that it wasn't working. I then tried it on Chrome and it did end up searching recursively. not sure why it did that, but it is now catalogued. Not sure what the difference was between browsers, though.

**Comment by paulijar** [comment]
This shouldn't be a browser issue. The scanning logic happens mostly on the server-side. But maybe the Files app had indexed your SMB share in the meantime as a background job. I don't know if it does that, but at least I find it plausible.
