### ISSUE TITLE
automatic cache control?

### ISSUE THREAD

**Issue by AvverbioPronome** [owncloud/music#741]
I tried putting a nginx cache in front of my nextcloud installation, but i found that it broke the subsonic endpoint (search works, listing does not). 

### Expected behaviour
Enable cache -> listing works

### Actual behaviour
Enable cache -> listing does not work, search works, playback works

### Server configuration
Client: android 9, Audinaut
Reverse proxy: Ubuntu 18.04 lts, Nginx 1.14.0
Application machine: Ubuntu 19.10 arm64 on a raspberry pi 3, docker, Nextcloud 18.0.0 inside three alpine containers.

it looks like it's working if I put 
```
	location /apps/music/subsonic {
		add_header Cache-Control "no-cache";
		try_files $uri @lampone_nc;
	}
	location / {
		try_files $uri @lampone_nc;
	}
	location @lampone_nc {
		proxy_cache my_cache;
		proxy_bind 10.9.0.3;
		set $lampone 10.9.0.5;
		proxy_pass http://$lampone:3000;
		proxy_set_header Host            $host;
		proxy_set_header X-Forwarded-For $remote_addr;
	}
```
in the nginx config on the proxy. To have it work out of the box would be cooler. (I read nginx documentation and they promise they honor headers applications send them.)

**Comment by AvverbioPronome** [comment]
I found a better way:

```
map $sent_http_content_type $proxy_bypass {
        "text/html"     1;
        "application/json"      1;
        default 0;
}
upstream example {
        server 10.9.1.5:3000; # wireguard
        server 10.9.0.5:3000 backup; # tinc
}

server {
        server_name example.com;
        include snippets/listen;
        include snippets/ssl_conf;

        location / {
                proxy_pass http://example;
                proxy_redirect http:// $scheme://;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Scheme $scheme;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_cache my_cache;
                proxy_cache_bypass $proxy_bypass;
        }
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
}
```

**Comment by paulijar** [comment]
Thanks for the report.

Personally, I have no experience on the reverse proxies, so I'm a bit lost here. There's lot of stuff in your examples, but are you now suggesting some specific headers, which should be added to the Subsonic responses by the Music app?

**Comment by AvverbioPronome** [comment]
Yeah, `Cache-Control`: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
I used  `no-store, no-cache, must-revalidate` but that's probably too aggressive.

**Comment by paulijar** [comment]
Hmm, I believe that that header `Cache-Control: no-store, no-cache, must-revalidate` is already included in all the Subsonic REST API responses, as well as in most other REST API methods of the Music app, when using Nextcloud. I think that adding this header is the default behavior of Nextcloud, unless the app creating the response specifically enables caching.

On the other hand, when running Music app on ownCloud, then cache header is a bit less aggressive `Cache-Control: no-cache, must-revalidate`. But the fact, that there is a difference between ownCloud/Nextcloud, makes me believe that this header is indeed added by the cloud core and not by my HTTP server settings.

**Comment by AvverbioPronome** [comment]
I really don't know, at this point. Maybe it was some other issue with one
of my nginx containers. I really don't know.

**Comment by paulijar** [comment]
Closing because it's not clear, what should be changed if anything.
