### ISSUE TITLE
Covers don’t show for albums with m4a files

### ISSUE THREAD

**Issue by vasilisvg** [owncloud/music#743]
Since I updated to v0.13.0 covers of files with the `.m4a` extension (AAC encoding) don’t show up in Album View, while they used to in previous versions. It doesn’t seem to matter if there’s a `cover.jpg` in the folder. If it’s an m4a, it doesn’t show up.
Covers of mp3 and flac files still work. 
I noticed there is a difference in the HTML source code between `.m4a` and `mp3`. M4a looks like this

```
/apps/music/api/album/13096/cover
```
Which returns an empty JSON. And mp3 looks like this:

```
/apps/music/api/cover/f1c9f1ea52953f6492e01f62fb1a0d57
```
Which returns an image, as expected.

**Comment by ChrisJAllan** [comment]
Bisection shows that commit 49c253617ca8f2441bf9d7f600e5d81a58de28e9 introduced the issue.

**Comment by paulijar** [comment]
Thanks for the report @vasilisvg and thanks for investigating @ChrisJAllan. This probably should be reported for the getID3 project then.

**Comment by paulijar** [comment]
For the record, the different kinds of cover URLs `/apps/music/api/album/13096/cover` and `/apps/music/api/cover/f1c9f1ea52953f6492e01f62fb1a0d57` mentioned in the OP are "business as usual". All the covers are first referred to with URLs like the first one. Once the cover has been fetched for the first time, and the server has created the possibly down-scaled and cropped version of the image, then the cover gets an URL looking like the second one. This URL contains hash of the image data, which is useful for client-side caching: The client can now safely assume, that if the hash of the image has not changed, then the previously cached version of the image may be used.

In the reported case, the getID3 bug was preventing the reading of the image data. Hence, the second type of URL was never assigned for the cover.

**Comment by paulijar** [comment]
The Music release v0.13.1 is now out, and there, I have included the most recent development version of getID3 (because it may take some time before the next official release of getID3 comes). Could you @vasilisvg test if this solved the issue?

**Comment by vasilisvg** [comment]
Yes! This issue seems to be solved. Thank you very much!
