### ISSUE TITLE
Some multi-disc albums are showing up as a single album with tracks in the wrong order

### ISSUE THREAD

**Issue by justinweiss** [owncloud/music#746]
I have a few multi-disc albums that are showing up as a single album, but the track numbers are going:

1, 1, 1, 2, 2, 2, 3, 3, 3, etc, for a 3-disc album. Each set of tracks goes in alphabetical order. Track number and disc number are correct in the tags, and the filenames look like `3-02 Track Name.m4a` for disc 3, track 2.

Most of my multi-disc albums display fine, as separate albums per disc. There are just a few that display this way.

The only thing that seems different between the ones that display correctly and the ones that don't is format. MP3 albums show up as separate discs. M4A albums are shuffled together into a single "disc" with incorrect numbering.

**Comment by paulijar** [comment]
Thanks for the report. M4A files seem to be using tag `disc_number`, while we currently consider only tags `discnumber` and `part_of_a_set`. Should be easy to fix once I have time.

**Comment by paulijar** [comment]
The release v0.13.1 fixing this issue is now out.
