### ISSUE TITLE
error while running root@snoopy4:~# occ music:scan --all

### ISSUE THREAD

**Issue by cdamken** [owncloud/music#749]
oC10.4
music: 0.13.2
I ran:
```
root@snoopy4:~# root@snoopy4:~# occ music:scan --all
```
After a while:
```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2097160 bytes) in /var/www/owncloud/apps/sentry/vendor/sentry/sentry/lib/Raven/Serializer.php on line 86
You have new mail in /var/mail/root
```

I think 1 GB should be enough

**Comment by paulijar** [comment]
Thanks for the report. How large is your music collection? Is that "after a while" more like seconds, or minutes, or hours?

**Comment by paulijar** [comment]
With no more information available, this issue can't be investigated. Personally, I'm running my cloud instance on RaspberryPi 3 with a grand total of 1 GB RAM available, and I have never seen such a problem, even when scanning a test library of > 60'000 songs.
