### ISSUE TITLE
[Subsonic API] Support starring part of the Subsonic API

### ISSUE THREAD

**Issue by MichaelBechHansen** [owncloud/music#750]
Looking at https://github.com/owncloud/music/blob/master/controller/subsoniccontroller.php it seems starring/favourites are not supported or exposed in the Subsonic API.

This would be an awesome addition.

**Comment by paulijar** [comment]
I initially thought that we should first have the starring/favorite feature on the web UI, and then reveal it through the Subsonic API. But on the second thought, it is significantly smaller task to do it only for the Subsonic API, and that's what I have now done. The feature will be included in the next release. I'll consider doing the web UI support at some later time, if I find time and motivation.

**Comment by paulijar** [comment]
The starring feature of the Subsonic API has now been released in the version 0.14.0.
