### ISSUE TITLE
Nextcloud 19 compatibility 

### ISSUE THREAD

**Issue by brymchik** [owncloud/music#753]
I don't know if it is already planned or discussed (i can't it find posted here) but in next version of Nextcloud - 19, there is an issue. The version is  beta 4 currently, so it might be Nextcloud issue as well. 

The case is - no collection loaded and error:

`Failed to load the collection: -1`

is fired. In browser console following error is loaded:

`POST https://xxx.xxx.xxx.xxx/index.php/apps/music/api/prepare_collection net::ERR_EMPTY_RESPONSE`

**Comment by paulijar** [comment]
Thanks. I *think* I have successfully tested NC19 alpha at some point, but this might have broken since then. I'll take a look.

**Comment by paulijar** [comment]
I now installed Nextcloud 19.0.0 beta 4, but I couldn't reproduce this issue. My test collection had just 3 tracks, but at least that worked flawlessly: `prepare_collection` returned normally, and the those three tracks were shown on the UI.

Can you find any more details from `nextcloud.log` on your server?

**Comment by brymchik** [comment]
Well, it must be something in my configuration then. In nextcloud.log there is no errors at all. I try do dig into it more and will try with clean install. Any tips for resolving it are welcomed :)

**Comment by paulijar** [comment]
You could temporarily enable the debug logging, run the test, and then check again nextcloud.log. That could reveal something new. To enable debug logging, edit `config/config.php` and set the value of `loglevel` to `0`.

**Comment by brymchik** [comment]
I tried to track this down with no luck. Logs leads to php itself or some of the modules loaded. The php process dies with Segregation error and leaves no error log except Apache "pid No: Segregation Error (11)". So I might give you some details in scenario I'm testing - CentOS 7, php 7.4.5, postgres. I expect I'll have to setup/upgrade Nextcloud instance with this after 19 is official so I'm testing for compatibility issues. It’s not a memory problem - tried without limits as well. It is not a timeout - the error is thrown immediately.

I understand it is maybe a bit outside Music app itself but I'm thankful for any help. All other things work, so it is something Music app uses (module or call) that breaks.

**Comment by paulijar** [comment]
Sounds weird. I found nothing of interest by googling that kind of error message.

If the error happens within `prepare_collection`, then it's likely that it happens in one of these two functions:
https://github.com/owncloud/music/blob/a29cdce64a5261682b72bce9dde76f5ecdb4c84a/utility/collectionhelper.php#L59
https://github.com/owncloud/music/blob/a29cdce64a5261682b72bce9dde76f5ecdb4c84a/utility/collectionhelper.php#L75

In a situation like this, the best way to debug would probably be to start adding logging to those functions, to find out, what is the line of code where the PHP dies.

**Comment by brymchik** [comment]
Just to let you know - after a lot of testing it turns out that in system a particular build of php 7.4.5 have a problem. I did recompile/reinstall it from sources and it was ok. Versions from remi repo and centos official one are fine too. 

Sorry for this all mess but it was hard for me to pinpoint what exactly was the problem. Obviously with a particular php compile/library so it is not a Music problem at all.

Thanks for the help!

**Comment by paulijar** [comment]
Okay, thanks for the info, and glad you could figure it out.
