### ISSUE TITLE
Subsonic version string 1.10.1 not compatible with apps because it is not published as such on the subsonic website

### ISSUE THREAD

**Issue by jheyens** [owncloud/music#758]
Hi, 
is there a reason why [this is set to '1.10.1'](https://github.com/owncloud/music/blob/511b17f6f1d2fc00d9cdff4d73c8cc43ec01c9ff/controller/subsoniccontroller.php#L52
)?

According to the [subsonic pages](
http://www.subsonic.org/pages/api.jsp#Versions), there is no (probably because it has been yanked?) version 1.10.1, [manually crafting the download uri](http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.10.1.xsd) does not yield a result either.

I wouldn't really mind, but unfortunately, this breaks the [UltraSonic app](https://github.com/ultrasonic/ultrasonic), which [hardcodes all versions](https://github.com/ultrasonic/ultrasonic/blob/b4ece442c8492ce941a9c32779819d8d0dc36217/core/subsonic-api/src/main/kotlin/org/moire/ultrasonic/api/subsonic/SubsonicAPIVersions.kt#L12) pubicly available on the subsonic website.

Jens

**Comment by paulijar** [comment]
Thanks for the report. I hadn't noticed this, as the Subsonic API documentation mentions on many methods that the method was changed on version 1.10.1, and apart from the list of versions, it never mentions 1.10.2. Based on the comments in http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.10.2.xsd, the only difference of 1.10.1 and 1.10.2 is the `albumCount` attribute on the Genre node. As we do support this attribute, it would definitely be more appropriate to use the version 1.10.2. I shall change this for the next version.

**Comment by powerlocke-ctrl** [comment]
Thanks for updating API-version. 
Do you plan to work further on this topic, to make it to more apps compatible? 
See also my Issue 757 - Sorry for request again.

**Comment by paulijar** [comment]
This change has now been published in the Music app v0.14.1.

@powerlocke-ctrl The API support will probably gradually improve also in the future, but all features of the API might not get ever implemented. I'll comment the situation of #757 more on that ticket.
