### ISSUE TITLE
Player is broken on mobile dark mode

### ISSUE THREAD

**Issue by szaimen** [owncloud/music#761]
I am currently running NC18.0.4 and music v0.14.1
When accessed from Chromium mobile 81 based Browser or Firefox mobile 75 beta 6 based browser, the Player on dark mode seems to be broken:
![image](https://user-images.githubusercontent.com/42591237/82664153-63ce0c80-9c31-11ea-8537-10aac5ddc051.png)
I hope this can be fixed on your side. 
Thanks!

**Comment by paulijar** [comment]
Thanks for the report.

Did you try reloading the page? I have noticed, that sometimes this is required in order for the dark theme to start working as intended. Note that at least Chrome for Android is very reluctant to reload resources which it has cached once. Hence, mere reload is not enough, but you need first go to the "History", select "Clear browsing data...", select at least "Cached images and files", and hit "Clear data". Then go back to Nextcloud and reload the page.

**Comment by szaimen** [comment]
> Thanks for the report.
> 
> Did you try reloading the page? I have noticed, that sometimes this is required in order for the dark theme to start working as intended. Note that at least Chrome for Android is very reluctant to reload resources which it has cached once. Hence, mere reload is not enough, but you need first go to the "History", select "Clear browsing data...", select at least "Cached images and files", and hit "Clear data". Then go back to Nextcloud and reload the page.

I tried to reload but it didn't work. 
Didn't know, that it caches those ressources that badly.
Thank you, that worked.

**Comment by paulijar** [comment]
No problem. I suspect there may be some Nextcloud server bug behind this. But for the Music app, there isn't much we can do to improve the situation, because when we read the current theme from the server variable `OCA.Accessibility.theme`, it holds a wrong value until the reload.

**Comment by szaimen** [comment]
okay, thanks for the clarification!
I opened https://github.com/nextcloud/server/issues/21069 to hopefully get that fixed on the server side.
