### ISSUE TITLE
exclude folders

### ISSUE THREAD

**Issue by hhenne1** [owncloud/music#762]
I can't seen to find a way do exclude a folder from automatic scanning.
I tried adding .noaudio and/or .nomedia files to certain folders, but they get added anyway.. is there a way to exclude folders currently implemented?

**Comment by paulijar** [comment]
Such feature is not currently available, but it could be a feasible idea for future development. This is also quite similar to the feature request #760: the same outcome could be achieved with either of these two mechanisms, but depending on the case, one may be handier.

**Comment by dgedgedge** [comment]
Such a feature would be great.
I do have issues with Mac .AppleDouble directory.
It is difficult to avoid having them go to nextcloud folder when managing the file tree with Mac.

In the .AppleDouble you will find some files with the same name as the original file but with a content specific to Apple...
The files having the same extention, they are indexed by music.

The idea would be to have a generic feature to exclude some path based on regexpr and/or plain folder specification.

For example exclude files when they have /.AppleDouble/ pattern in their path.

I did looked to the code. It seems to me that the change should be located in method: 
pathIsUnderMusicFolder of scanner.php.

The method whould have to be renamed in  pathIsUnderMusicFolderAndValid.

**Comment by paulijar** [comment]
This feature is implemented now, and will be part of the next release.
![image](https://user-images.githubusercontent.com/8565946/95255429-01655980-082a-11eb-8f77-c22609d39bcf.png)

**Comment by paulijar** [comment]
Music v0.17.0 with this feature is now released.

When you add a folder to be excluded, no already scanned tracks are removed from the library. For the exclusions to take effect, you need to either reset and rescan the library, or use the command line utility
`occ music:scan --remove-obsolete`.
