### ISSUE TITLE
Does not support multiple "Paths to your music collection"

### ISSUE THREAD

**Issue by coamtaker618** [owncloud/music#766]
I'm migrating to this from a standalone SubSonic server so I'm not sure how much of this is in the APIs--or merely just features I was enjoying.  However this app does not seem to support multiple paths to your music collection.  In SubSonic I find it very handy to have multiple folders that the app allows me to select between to sort of change my library (client side) on the fly.  Or at least allow me to sort server-side beyond a single folder of artists/albums/songs.

**Comment by paulijar** [comment]
This is closely related to #760, although with a focus on the Subsonic API.

**Comment by coamtaker618** [comment]
@paulijar agreed. 760 did not come up in a brief search, thank you for pointing that out.
