### ISSUE TITLE
Aif Aiff format support 

### ISSUE THREAD

**Issue by astrocycles** [owncloud/music#767]
Hi,
Are you planing to add full quality player : Aiff, Aif ? 

thanks

**Comment by paulijar** [comment]
There are no such plans at the moment. It seems to me, that neither Firefox, Chrome, nor Edge support playing the aiff format. With a quick lookup, I could not find any javascript libraries either which would enable the aiff playback so this looks like a dead-end.

Based on someone's comment, apparently the Safari browser would support playing aiff files. However, I can't verify this claim as Safari is nowadays Mac-only.

If the browser-side support for this format ever becomes available in the main-stream PC browsers, then adding the support also to the Music app should be a no-brainer. Until then, there's no chance.

**Comment by astrocycles** [comment]
Hi,

Thanks for your prompt reply.

**Comment by JoshuaPettus** [comment]
Seeing as aiff/aif is an apple format, I would expect Saffari to support it.

In the mean time, I'm pretty sure can convert your .aiff to .wav, without any data loss, as both are uncompressed audio files

**Comment by paulijar** [comment]
While investigating https://github.com/owncloud/music/issues/1030, I accidentally noticed that the [Aurora.js](https://github.com/audiocogs/aurora.js/) library, which we were already using, is actually able to play .aiff files without any extra plugins. Similarly, it can play .wav, .au, and .caf files. So now in Music v1.8.0, also the .aiff playback is possible even if the browser at hand has no native support. The Music app always first tries to use the native codec and uses the Aurora.js only as a fallback solution. The limitation of this fallback solution is that seeking within the song is not possible, nor is adjusting the playback speed. There's also a good chance that it will fail on some files, but at least the few sample files I could find played fine.

The gotcha is that Music app can see and play only such files which have been mapped to MIME types `audio/*` on your cloud instance. Neither ownCloud nor Nextcloud map the .aif/.aiff/.aifc files by default. You can automatically add those mappings with Music v1.8.0 by running
```
sudo -u www-data php occ music:register-mime-types
```
.

**Comment by djtulan** [comment]
Hi!

I noticed, that AIFF / AIF files are not registered anymore on a nextcloud-snap image.

I run the command on my server, and it created the correct json file:
`sudo nextcloud.occ music:register-mime-types`

`/var/snap/nextcloud/current/nextcloud/config/mimetypemapping.json`

But the aiff files are not shown in my music app. All the other formars (wav, mp3, flac) work fine.
nextcloud-snap version is 27.1.4
music app version 1.9.1

**Comment by paulijar** [comment]
@djtulan I have seen that sometimes the `occ music:register-mime-types` doesn't fix the mime type mappings of the existing files even though it is actually supposed to do that. I'm not certain, if this depends on the Nextcloud version or something else. However, any newly uploaded files should still get the correct mime mappings after the script has been run. So if you remove one of your aiff files and then re-upload it to your Nextcloud, then it probably should become visible in Music. It might be enough also to just reupload and rewrite the existing file, without deleting the original copy, but I don't remember for certain.

**Comment by djtulan** [comment]
@paulijar You are absolutly right. New uploaded files are listet now. 
But I have seen another Problem. And I think there is still a Problem with AIFF files:

![Screenshot_20231220_091137](https://github.com/owncloud/music/assets/1506204/d0d8badf-9b71-4aab-84ed-da9573f3e832)

The title of the AIFF tag looks a bit faulty. When I open it with an ID3 editor, everything looks correct.

**Comment by paulijar** [comment]
@djtulan Could you share one aif file with this problem with me? You can find my email address from my GitHub profile.

**Comment by djtulan** [comment]
@paulijar , I sent you a DL link for the file.
Hex Editor shows that bytes, if this is helpful?

![Screenshot_20231220_114120](https://github.com/owncloud/music/assets/1506204/09869275-f85d-4bc2-97b7-c20e73929960)

**Comment by paulijar** [comment]
@djtulan I opened a new issue https://github.com/owncloud/music/issues/1115 for this title problem, as that's clearly separate from the original feature requirement, and this issue is already closed anyway.
