### ISSUE TITLE
Feature request: Group by artists

### ISSUE THREAD

**Issue by TheDarkTron** [owncloud/music#769]
I cant find the feature to group the library by artist. It would be nice if there would be a tab on the left top for this. Like with Album, Folders and Genres.
![image](https://user-images.githubusercontent.com/19347475/84632160-cd6acf00-aeee-11ea-8306-a3f20efe7fc3.png)

**Comment by paulijar** [comment]
Well, the *Albums* view already groups first by artist and then by album. I've been considering that maybe it should be renamed as *Artists and albums*. Also, the *All tracks* view orders the tracks according the contributing artist. I don't quite see, what could you achieve with a dedicated *Artists* view which wouldn't already be possible with one of these two views. Well, maybe for a huge collection it would be useful to have a view where artists were collapsed to a more compact form than in the current *Albums* view.

**Comment by TheDarkTron** [comment]
Thank you! I didn't notice the Album's view first sorts by artist. That's exactly what I needed :)
