### ISSUE TITLE
sort on track number when in folder view

### ISSUE THREAD

**Issue by tob123** [owncloud/music#770]
hello,
thanks for this great work.

question:
what is the supposed behavior of track sorting when in folder view ?
i see the tracks are sorted alphabetically based on the artist and track title.
for example track name "allegro con spirito"
![image](https://user-images.githubusercontent.com/11362436/85220832-1c14df00-b3af-11ea-8de3-8f606c0dc070.png)
in album view the track order is correct:
![image](https://user-images.githubusercontent.com/11362436/85220904-99405400-b3af-11ea-91cf-6cc390a6b33f.png)

while the file names are like this:
/mnt/mp3/klassiek/schubert/der tod und das madchen $ ls
01- Allegro.flac
02- Andante con moto.flac
03- Scherzo. Allegro molto - Trio.flac
04- Presto.flac
05- Presto.flac
06- Andante.flac
07- Menuetto. Allegro - Trio.flac
08- Allegro con spirito.flac

some system info:
nextcloud 18.0.5
php version: 7.3.18

**Comment by paulijar** [comment]
Yes, the Folders view currently sorts the tracks the same way as the All tracks view; that is, first by the track artists and then by the track title. Sorting by the track number would be a bit problematic here as the contents of a single folder may or may not represent a single album.

Now thinking about it, sorting the tracks in the Folders view according the file name could make a lot of sense. As the view is categorized according the file system entities, it would be fitting to do also the sorting according the file system. This would solve your example case, and still wouldn't be too surprising for those users who have directory hierarchy divided some other way than according to albums.

**Comment by tob123** [comment]
sounds great. thanks a lot for the fast response!

**Comment by paulijar** [comment]
In the new Music app release v0.15.0, the Folders view is sorted according to the file names.

**Comment by tob123** [comment]
thanks. works!!
