### ISSUE TITLE
Seekbar (progress bar) not working on latest Chrome browser. (84+)

### ISSUE THREAD

**Issue by yku12cn** [owncloud/music#782]
It's quite easy to reproduce.
Have the latest Google Chrome installed.
Use the Chrome to access your music file on your nextcloud folder.
Play the music.

The music will play. However, every time you click the seekbar, it return to the beginning of the music instead of jumping to where you click.

On IE(not the latest edge version), Firefox, or Safari, it all works just fine.

**Comment by paulijar** [comment]
Thanks for the report.

However, I couldn't reproduce the issue. I used Chrome "Version 84.0.4147.105 (Official Build) (64-bit)" on Windows 10. I tested on Nextcloud 17 and 13, and using files of types mp3, flac, m4a, m4b, ogg, and opus.

Is there anything more you can tell about your test environment?

**Comment by yku12cn** [comment]
> Thanks for the report.
> 
> However, I couldn't reproduce the issue. I used Chrome "Version 84.0.4147.105 (Official Build) (64-bit)" on Windows 10. I tested on Nextcloud 17 and 13, and using files of types mp3, flac, m4a, m4b, ogg, and opus.
> 
> Is there anything more you can tell about your test environment?

Thanks for your reply. I forget to mention. I tested on nextcloud 19.0.1.
I also noticed that the seekbar for video doesn't work with nextcloud 19.0.1 + chrome either.

**Comment by paulijar** [comment]
I tested also Nextcloud 19.0.1 but it made no difference.

You mentioned in your opening post also the Safari browser. Are you maybe testing on an Apple device?

What do you see if you press F12 to open the developer console?

**Comment by yku12cn** [comment]
> I tested also Nextcloud 19.0.1 but it made no difference.
> 
> You mentioned in your opening post also the Safari browser. Are you maybe testing on an Apple device?
> 
> What do you see if you press F12 to open the developer console?

...Interesting. I didn't expected this to be like this. To be more specific:
My nextcloud server is running on a remote computer. If you like, I can create an account for you to test.
1) Win10 + Chrome + nextcloud19.0.1:  Seekbar fail
2) Win10 + IE11 + nextcloud19.0.1:  Seekbar good
3) Win7 + Chrome + nextcloud19.0.1: Seekbar fail
4) Andriod + Chrome + nextcloud19.0.1: Seekbar fail
5) iOS + Safari + nextcloud19.0.1:  Seekbar good
6) iOS + Chrome + nextcloud19.0.1:  Seekbar good ( yes, it's not a typo )
7) Ubuntu 20.04 + Firefox + nextcloud19.0.1:  Seekbar good

**Comment by paulijar** [comment]
I now tested on your server, but I still couldn't reproduce the issue. I tested Chrome on Win10 and Android. On Android, the Chrome version was 84.0.4147.111. This is most bizarre, indeed.

Otherwise I would say that it has to be something in your Chrome installation (like some faulty plugin), but as you have tested Chrome on many platforms, even that seems unlikely.

Have you tested this with multiple audio file formats, or in which format were your files?

**Comment by yku12cn** [comment]
> I now tested on your server, but I still couldn't reproduce the issue. I tested Chrome on Win10 and Android. On Android, the Chrome version was 84.0.4147.111. This is most bizarre, indeed.
> 
> Otherwise I would say that it has to be something in your Chrome installation (like some faulty plugin), but as you have tested Chrome on many platforms, even that seems unlikely.
> 
> Have you tested this with multiple audio file formats, or in which format were your files?

I also tested multiple format. Including .wav, .mp3, .m4a... Maybe even more.
Just test Ubuntu 20.04 + Chrome, seekbar is broke.
So it is related to Chrome on my end.
I will try something else, will keep you update.

**Comment by yku12cn** [comment]
I tried a clean win10 installation with only Chrome installed.
Still able to reproduce this issue.
I also asked one of my friend to try on his machine. He can reproduce as well.
Every setup I can come up with except "iOS + Chrome" can reproduce this issue.

I really don't understand why you can't reproduce it. Are we missing some key elements?

**Comment by paulijar** [comment]
Here is one very similar issue on another project: https://github.com/sampotts/plyr/issues/1101

On that linked issue, the problem got solved when the user used a public address for the server instead of the localhost address 127.0.0.1 (if I understood correctly). Also, some other sources have hinted, that this kind of issues could occur if the server does not handle the bytes range HTTP requests correctly, and return the right kind of headers for those requests. I guess that this could happen if there is a bad configuration on the web server or on a reverse proxy.

But now the interesting question is, why can't I reproduce the issue even on your server. When you are testing on the server, are you using the same public domain name as I am? Or are you maybe reaching the server directly by IP or some other alias name?

**Comment by yku12cn** [comment]
> Here is one very similar issue on another project: [sampotts/plyr#1101](https://github.com/sampotts/plyr/issues/1101)
> 
> On that linked issue, the problem got solved when the user used a public address for the server instead of the localhost address 127.0.0.1 (if I understood correctly). Also, some other sources have hinted, that this kind of issues could occur if the server does not handle the bytes range HTTP requests correctly, and return the right kind of headers for those requests. I guess that this could happen if there is a bad configuration on the web server or on a reverse proxy.
> 
> But now the interesting question is, why can't I reproduce the issue even on your server. When you are testing on the server, are you using the same public domain name as I am? Or are you maybe reaching the server directly by IP or some other alias name?

Yeah.. pretty strange indeed. I also access my server using the same domain as you did. Since my server is "https" only.
As I said earlier. I also asked one of my friend try on his side. He can reproduce the issue as I do.
I setup several virtual machines with different setup. All of them can reproduce.  I already run out of ideas.

**Comment by yku12cn** [comment]
@paulijar 
I figured out.. Finally.
It turns out that.. The case you mentioned is correct.
Actually there are two ways to access my server. With "www" or without.
The issue only triggered if the browser is Chrome and by adding "www" or removing "www". The issue can be "fixed".

But I still have no idea how to properly fix it..

**Comment by paulijar** [comment]
Nope, I still can't reproduce the issue on your server. 

I see that you are using Cloudflare on your site. I'm not intimately familiar with it, but I understood that they are proxying the site access through over 200 data centers all over the world. Hence, I'm probably not accessing your site through the same data center as you are. I wonder if this could be the significant difference?

If you open the developer tools in Chrome, and view the Network tab, what kind of HTTP responses do you see on those failed seeking attempts? The request should be for a URL like `https://<domain>/nextcloud/remote.php/webdav/<filename>?requesttoken=<long_string_of_characters>`. If the byte range requests are being handled properly, the response should have the status code 206 and one of the headers in the response should be something like `Content-Range: bytes 4423680-4868630/4868631`.

**Comment by yku12cn** [comment]
> Nope, I still can't reproduce the issue on your server.
> 
> I see that you are using Cloudflare on your site. I'm not intimately familiar with it, but I understood that they are proxying the site access through over 200 data centers all over the world. Hence, I'm probably not accessing your site through the same data center as you are. I wonder if this could be the significant difference?
> 
> If you open the developer tools in Chrome, and view the Network tab, what kind of HTTP responses do you see on those failed seeking attempts? The request should be for a URL like `https://<domain>/nextcloud/remote.php/webdav/<filename>?requesttoken=<long_string_of_characters>`. If the byte range requests are being handled properly, the response should have the status code 206 and one of the headers in the response should be something like `Content-Range: bytes 4423680-4868630/4868631`.

You mean when you using chrome on your end, such would be made when you click the seekbar.

On my end, once the music is loaded, clicking seekbar won't trigger any network activity. It just starts the music from the beginning. I also check the console tab, nothing special over there as well.

**Comment by paulijar** [comment]
> You mean when you are using chrome on your end, such request would be made when you click the seekbar.

Yest, that's what I meant. When ever you jump to a location within the file which is not buffered yet, the browser should make a new partial content request. And sometimes it makes multiple requests, probably because it can't know the exact byte offset matching the desired time offset, and it needs to make some kind of binary search.

What about the initial file load then? Also that one should have the status code 206.

**Comment by yku12cn** [comment]
> > You mean when you are using chrome on your end, such request would be made when you click the seekbar.
> 
> Yest, that's what I meant. When ever you jump to a location within the file which is not buffered yet, the browser should make a new partial content request. And sometimes it makes multiple requests, probably because it can't know the exact byte offset matching the desired time offset, and it needs to make some kind of binary search.
> 
> What about the initial file load then? Also that one should have the status code 206.

Well, those music loaded without a bl

**Comment by yku12cn** [comment]
> > You mean when you are using chrome on your end, such request would be made when you click the seekbar.
> 
> Yest, that's what I meant. When ever you jump to a location within the file which is not buffered yet, the browser should make a new partial content request. And sometimes it makes multiple requests, probably because it can't know the exact byte offset matching the desired time offset, and it needs to make some kind of binary search.
> 
> What about the initial file load then? Also that one should have the status code 206.

I tried a 100MB music file which takes more than 10 secs to load. I also bypass the cloudflare for my "www." domain.
Seekbar is still broken on chrome. Firefox is fine.
Both of them, regardless the music is fully loaded or not, clicking seekbar doesn't generate any network activity.

**Comment by paulijar** [comment]
So does the initial file load then complete with the status code 200 instead of 206 for you? Because this would be a signal for the browser that the server does not support the HTTP range requests, but the whole file needs to be downloaded before seeking to the end is possible. And according to what I have read on similar issues all over the internet, the seeking in Chrome does not work at all without properly working range request, while all the other browsers can still seek.

> I temporarily bypass the cloudflare for my www. domain. You can flush your dns and try again. This time there shouldn't be any difference between our topologies.

Still no difference. For me, the partial content requests respond properly with 206, and I can seek to both buffered and unbuffered areas of the file.

**Comment by yku12cn** [comment]
> So does the initial file load then complete with the status code 200 instead of 206 for you? Because this would be a signal for the browser that the server does not support the HTTP range requests, but the whole file needs to be downloaded before seeking to the end is possible. And according to what I have read on similar issues all over the internet, the seeking in Chrome does not work at all without properly working range request, while all the other browsers can still seek.
> 
> > I temporarily bypass the cloudflare for my [www](http://www). domain. You can flush your dns and try again. This time there shouldn't be any difference between our topologies.
> 
> Still no difference. For me, the partial content requests respond properly with 206, and I can seek to both buffered and unbuffered areas of the file.

For firefox, it's 206, for chrome, it's 200.
To be honest, I originally thought this is just an UI issue. I never excepted this to be this bizarre.
I'm uploading a VMware virtual machine to my server so that you can download and try out on your side. This is a clean Ubuntu 20.04 build with both firefox and chrome installed. I already tested it on my end should be able to reproduce.

This is by far the most extreme topology sync I have ever done. If you still can't reproduce, I will just close this issue.

**Comment by paulijar** [comment]
@yku12cn Unfortunately, my CPU is so old that I cannot use the latest versions of VMware Player. I managed to find downloads of older versions from the VMware site (although they were pretty well hidden), but your virtual machine cannot be loaded on the version 12.5.9 which apparently is the latest version compatible with older CPUs. Trying to open the machine gives an error stating that the image "was created by a VMware product that is incompatible with this version of VMware Player and cannot be used".

**Comment by yku12cn** [comment]
> @yku12cn Unfortunately, my CPU is so old that I cannot use the latest versions of VMware Player. I managed to find downloads of older versions from the VMware site (although they were pretty well hidden), but your virtual machine cannot be loaded on the version 12.5.9 which apparently is the latest version compatible with older CPUs. Trying to open the machine gives an error stating that the image "was created by a VMware product that is incompatible with this version of VMware Player and cannot be used".

Man.. that's a really old CPU you have. However, you may be able to boot the machine by creating a 12.5 machine and replace the disk file with mine. There are some tweaks though. 
Anyway, I have done nothing special. You can also try to download the latest Ubuntu(https://releases.ubuntu.com/20.04/ubuntu-20.04.1-desktop-amd64.iso), create a virtual machine, install Ubuntu with everything set to default. Then, download and install Chrome. That pretty much is what I did.
BTW, why Chrome always get 200 respond? I tried a very simple media playback page, it seems Chrome is so reluctant with 206.

**Comment by paulijar** [comment]
> Man.. that's a really old CPU you have.

Yeah, I'm surprised myself how well this decade old desktop PC has served me. After adding some memory and an SSD some years ago, it feels like new. At work, I'm using a 3-year old laptop and it doesn't feel faster than my home PC in any significant way.

> you may be able to boot the machine by creating a 12.5 machine and replace the disk file with mine

This actually worked, and I could test your image. However, the seeking was still working fine both on Chrome and Firefox when tested against your server. On both browsers, the requests for audio file streaming were responded with 206.

> why Chrome always get 200 respond? I tried a very simple media playback page, it seems Chrome is so reluctant with 206.

This is the million dollar question and probably key to the whole problem. 

How the system is supposed to work, is that first the browser sends a HTTP request which includes the header `Range: bytes=0-`. This is a signal for the server that the browser supports range requests, and wants to read a range starting from the beginning of the file. If also the server supports range requests, then it responds with 206. If it doesn't, it ignores the range header, and returns the normal download status code 200. Based on the status code of the response, the browser knows if the server can support range requests.

As a side note, the end of the range is not defined in the browser's initial request, so the server first starts sending a range spanning all the way to the end of the file. However, when the browser sees that the server supports range requests, it may cancel the request before the whole file has been downloaded. Then later, the browser makes new range requests starting from some offset, when more data needs to be buffered.

Now, my best guess is that on your system, the header `Range: bytes=0-` somehow gets lost en route before the request reaches the server. Then, the server sees it as just an ordinary request for file download, and responds with 200. I have no idea, who could "eat" the header, but maybe it is some firewall, or router, or proxy. Also, it's most bizarre if this happens on Chrome but not on Firefox. But maybe this could be related to the fact that different browsers send a bit different headers, and they are differently ordered. On Chrome, the header `Range: bytes=0-` is the last one to be sent, which would make it a potential victim of some off-by-one errors.

**Comment by yku12cn** [comment]
> This is the million dollar question and probably key to the whole problem.
> 
> How the system is supposed to work, is that first the browser sends a HTTP request which includes the header `Range: bytes=0-`. This is a signal for the server that the browser supports range requests, and wants to read a range starting from the beginning of the file. If also the server supports range requests, then it responds with 206. If it doesn't, it ignores the range header, and returns the normal download status code 200. Based on the status code of the response, the browser knows if the server can support range requests.
> 
> As a side note, the end of the range is not defined in the browser's initial request, so the server first starts sending a range spanning all the way to the end of the file. However, when the browser sees that the server supports range requests, it may cancel the request before the whole file has been downloaded. Then later, the browser makes new range requests starting from some offset, when more data needs to be buffered.
> 
> Now, my best guess is that on your system, the header `Range: bytes=0-` somehow gets lost en route before the request reaches the server. Then, the server sees it as just an ordinary request for file download, and responds with 200. I have no idea, who could "eat" the header, but maybe it is some firewall, or router, or proxy. Also, it's most bizarre if this happens on Chrome but not on Firefox. But maybe this could be related to the fact that different browsers send a bit different headers, and they are differently ordered. On Chrome, the header `Range: bytes=0-` is the last one to be sent, which would make it a potential victim of some off-by-one errors.

I believe I have just figured it out the root cause, after trying some manual requests.

First thing first, there is nothing wrong with your plug-in.
Secondly, there is nothing wrong with my server's configuration. My server returns the correct header "Accept-Ranges: bytes" correctly

The real reason is that, I have a .js script handles local cache. For some reason, when cache mismatch, it will force a 200 status. And only Chrome allow that .js script to override the 206 status.
After removing that script, problem solved.
I haven't figured out how to handle the cache properly, but that's not related to this project.

With that been said, I still have no idea why you can't reproduce this issue. This should apply to all Chrome browsers.
Anyway, sorry for taking up so much of your time. We can close this.

**Comment by paulijar** [comment]
Okay, great. There are many weird aspects on this case, but at least it now makes some kind of sense.
