### ISSUE TITLE
Feature: Support Internet radio playlist file?

### ISSUE THREAD

**Issue by ei8fdb** [owncloud/music#784]
Thank you for creating this great application. I use it daily on my cloud server and mobile for listening to music.

Is there a possibility to support Internet radio station playlists? For example, I'd like to play an Internet radio station. I save the radio station as 'Star FM Nürnberg Germany.pls', and it contains:

```
[playlist]
NumberOfEntries=1
Title1=starfm Nürnberg
File1=http://85.25.209.152:80/nuernberg.aac
```

I see it mentioned in PR ##718.
Thanks!

**Comment by paulijar** [comment]
This is a plausible idea for future development, and one day, I may pick this up. Or if someone else wants to implement this, pull requests are welcome. :)

Just to clarify, are you mainly talking about playing such .pls file from the Files app, or showing and playing it within the Music app, or showing and playing the internet radio stations in a Subsonic client?

**Comment by ei8fdb** [comment]
Hi @paulijar If I can give a few options 😄 going from least to most preferable levels of functionality.

- The least would be playing a .pls file from the Files app
- A really nice level of functionality would be adding that .pls file (from the Files app) to a user created playlist in the Music app and then playing the station in the Music app
- The ideal would be finding a station (searching or browsing a list e.g. from something like http://www.radio-browser.info/gui/), adding the station to a playlist, playing the station in the Music app **and** in a Subsonic client

I can't contribute code, but I can contribute interface designs, if it's of interest?

**Comment by paulijar** [comment]
BTW, there already is the application https://apps.nextcloud.com/apps/radio on Nextcloud which theoretically already offers the possibility to listen to radio stations listed at http://www.radio-browser.info. However, it didn't seem to work at least for me at all, because it was trying to access the external site radio-browser.info directly from the front-end, and the CORS check blocked such calls. I believe that the app should either relay the calls through its own back-end, or then modify the Content Security Policy to allow the calls.

**Comment by paulijar** [comment]
> The ideal would be finding a station (searching or browsing a list e.g. from something like http://www.radio-browser.info/gui/), adding the station to a playlist, playing the station in the Music app and in a Subsonic client

Yeah, this would actually make the feature useful for an average user. Finding and defining the streaming URLs by hand is a bit too cumbersome for the most people to bother. But this will also be seriously more work.

I wouldn't want to mix the radio stations with the normal playlists on the Music web UI. Instead, I would aim for having a separate view "Internet radio", where all the imported radio stations would be listed.

Even though it was your least favorite alternative, I would probably start by enabling the playback of the internet radio .pls (and .m3u) files in the Files app. This can be made with no or minimal UI changes, and most of the created logic should be reusable in the next phase when creating that specific Music app view. After we have that view listing the radio streams, providing the same data via Subsonic API will be trivial.

**Comment by ei8fdb** [comment]
> However, it didn't seem to work at least for me at all, because it was trying to access the external site radio-browser.info directly from the front-end, and the CORS check blocked such calls. I believe that the app should either relay the calls through its own back-end, or then modify the Content Security Policy to allow the calls.

Yes you're right Radio app does exist. I have used the Radio app for a long time, however it is no longer working because it is [using a deprecated webservice endpoint and hasn't been updated to the Radio-Browser.info API](https://git.project-insanity.org/onny/nextcloud-app-radio/-/issues/113).

The original developer at the moment, is not updating the app. So I thought I'd ask here if there was a possibilty to support Internet radio streams.

**Comment by ei8fdb** [comment]
> > The ideal would be finding a station (searching or browsing a list e.g. from something like http://www.radio-browser.info/gui/), adding the station to a playlist, playing the station in the Music app and in a Subsonic client
> 
> Yeah, this would actually make the feature useful for an average user. Finding and defining the streaming URLs by hand is a bit too cumbersome for the most people to bother. But this will also be seriously more work.

Absolutely, I can understand that is more work. I just thought I'd propose an "ideal" functionality situation.

> I wouldn't want to mix the radio stations with the normal playlists on the Music web UI. Instead, I would aim for having a separate view "Internet radio", where all the imported radio stations would be listed.

Yes, that makes sense. So something like 
 
> Even though it was your least favorite alternative, I would probably start by enabling the playback of the internet radio .pls (and .m3u) files in the Files app.

This makes perfect sense. Not that it was my least favourite - any support for Internet streams is better than no support - more my guess that it might be the least amount of work required to implement it. 

> This can be made with no or minimal UI changes, and most of the created logic should be reusable in the next phase when creating that specific Music app view. After we have that view listing the radio streams, providing the same data via Subsonic API will be trivial.

Super! If it helps, here is the kind of workflow I was thinking might be both easy for the user, and least amount of work for implementation:

## Possible UI design implementation

1. View on first install
![1-Internet-Radio-Menu-Exists](https://user-images.githubusercontent.com/1899506/93758036-01e5d980-fc08-11ea-814f-bf4bf2d7ccbf.png)
When the user installs the app, the Internet Radio menu heading exists by default.

2. Import radio stream file
![2-Import-Radio-Stream-Playlist](https://user-images.githubusercontent.com/1899506/93758098-188c3080-fc08-11ea-9b19-d948218f3918.png)
The user would click on the "more vertical" icon. They'd choose import from file. 

3. Navigate and choose Internet stream
![3-Navigate-To-Playlist-File](https://user-images.githubusercontent.com/1899506/93758355-93ede200-fc08-11ea-9d0f-c103d75d9f38.gif)
The user then navigates to the location of the stream file(s). Here the file picker UI only supports file selection - it would be nice if the user could specify a directory which contains a number of Internet streams. (In my case here, I have all my streams stored in a directory called "Internet Radio")

4. Internet stream is added
![4-Radio-Stream-Added](https://user-images.githubusercontent.com/1899506/93758463-cac3f800-fc08-11ea-8814-ef924fe3a2f9.png)
When this completes the Internet stream is listed, displaying stream metadata. If the user clicked on the ℹ️ icon they'd possibly see more metatadata if available.

## Would the app support finding Internet streams via the scan function?

As an aside, when I was testing this I found this behaviour: 

I uploaded a stream file (.pls) to a new Music app directory, and the "scan" function did not start, and so could not pick it up as a valid music file.

The scan function was only available *after* I uploaded a valid music file (e.g. mp3) into the directory.

I guess the need here would be for the Music app to support Internet Stream files (.pls, etc) as valid music files? Or would that not be possible? I can see where this may become confusing if a .pls was being used as a playlist for an album.

Not sure what the best thing would be to do here.

I hope that helps!

Thank you for creating the Music app and considering adding this functionality. I appreciate it a lot. I hope the designs are useful. If not, or you need alternatives, let me know.

**Comment by paulijar** [comment]
Thanks for the mock ups. I'll consider implementing something like this later when I have time. I hope it would be later this year, and not in the "unforeseen future".

**Comment by ei8fdb** [comment]
Great. I'll keep an eye on this thread. If you need testing @ me and I'll be happy to test. :+1:

**Comment by paulijar** [comment]
I missed my target of releasing the internet radio support during 2020 by a bit more than a month, but now it's out in Music v1.0.0!

It works pretty much like the mock-up above. In addition, playing and importing the playlist files with external audio streams is possible also from Files. The imported radio stations are provided via the Subsonic API, too.

If you want to play HLS type radio stations (the ones with a URL ending m3u or m3u8), you need to whitelist those separately in the `config.php` file. Other kinds of streams (like mp3 or aac) work by default.

Importing a whole directory of radio streams at once is not supported. But unless you have many dozens of the internet radio PLS files, it shouldn't take too long to import them one-by-one, especially if you make this from Files.

**Comment by ei8fdb** [comment]
Hea @paulijar that's great! Releasing it in v1.0.0 is much nicer. :) I've tried it already and it works really nicely. Thanks very much for implementing this.

Is there anything else you'd like to implement that I can help with providing some design?

**Comment by paulijar** [comment]
At some point, I'd like to make the proper integration to http://www.radio-browser.info so that radio stations could be browsed, searched, and added without leaving the Music app UI. But I'm not quite sure, how should this look like. Maybe some kind of pop-up selector? 

I'm a bit worried that there probably is no suitable UI components already available in Nextcloud and/or ownCloud server, so we might need to create those from scratch. On one hand, creating own components gives a lot of freedom, but on the other hand, it requires a lot of time and effort.

**Comment by ei8fdb** [comment]
> At some point, I'd like to make the proper integration to http://www.radio-browser.info so that radio stations could be browsed, searched, and added without leaving the Music app UI. But I'm not quite sure, how should this look like. Maybe some kind of pop-up selector?

OK! I'll have a look and see how this might work. I'm guessing you would be using their API to interact with radio-browser.info? If so it would be helpful to know what data it can provide the Music app.

I'll open a ticket for this specific bit?

> I'm a bit worried that there probably is no suitable UI components already available in Nextcloud and/or ownCloud server, so we might need to create those from scratch. On one hand, creating own components gives a lot of freedom, but on the other hand, it requires a lot of time and effort.

Yup agreed. I'll be trying my best to use the Owncloud/Nextcloud UI components as much as possible.

**Comment by paulijar** [comment]
> I'm guessing you would be using their API to interact with radio-browser.info? If so it would be helpful to know what data it can provide the Music app.

Yes, this is the plan. The API seems to be documented in https://de1.api.radio-browser.info/. Basically, it seems to provide all the data needed to implement browsing like it works at https://www.radio-browser.info via the links in the top pane: "By popularity...", "By category.." and "Search".

> I'll open a ticket for this specific bit?

Yes, please, opening a new feature request would make sense.

**Comment by JoshuaPettus** [comment]
I just want to say, excellent job on this feature!  It works great. Paired with the subsonic support, this is something I didn't know I needed.  Even for radio stations that I have a link but not a .pls file (Quite a few of the NPR ones I want to listen to), they are stupidly easy to make.

Thanks so much!

**Comment by atkinsom** [comment]
Thanks guys for an excellent addition to an already super app. The Internet Radio feature is lights out the coolest add on to this app after the repeat song option in the last release. FYI I was able to import a .pls file with multiple stations in the list and it imported with no issues!!! Just went to https://www.radio-browser.info/#!/search and did a search for 70's and it gave me a list of 26 stations. I then clicked the PLS link at the top of the page which downloaded the whole list in one file. I then imported that file and bingo all the stations were listed with no issues!!! :)
Just wondering if there's a location in the GUI or in the back-end of the app after the import of the stations where I can go and edit the station name? I looked but couldn't find anything. Nice to have but not a killer as I can edit beforehand but if I make a mistake would save me the hassle of re-importing the whole file again. Again I can't say enough about this app and have gotten more than a few people to hop on board and they love it. Cheers

**Comment by paulijar** [comment]
Renaming the stations is not supported for now. At some future update, I'm planning to add a details view for the radio stations where it would be possible to edit the station name and URL.

**Comment by JoshuaPettus** [comment]
It is possible to rename the station name in the .pls file and re import

**Comment by atkinsom** [comment]
> 
> 
> It is possible to rename the station name in the .pls file and re import

Thank you Joshua. I just did that as I made another naming mistake LOL! Worked perfect. Never realized how much I would like this feature :)
