### ISSUE TITLE
Metadata decoding issue with WAV ID3v2.3 (RIFF ID3v2.3) tags

### ISSUE THREAD

**Issue by magneticflux-** [owncloud/music#788]
Versions:
- Nextcloud 19.0.3
- Music 0.16.0
- Firefox 81.0

Certain files show corrupted data, and I can't find any pattern in it.

Things I've checked for correlation:
- Albums
- File format
- Special characters in the fields

Here's an example of the corruption in the UI:
![image](https://user-images.githubusercontent.com/9124288/94789530-a3a0bf80-039a-11eb-867c-fe413e881243.png)

And here are the exact copy-pasted corrupted titles for _Consouls 1-1_:
```
Format: 0. 'title here'
1. 'ÐõÐõ'
2. 'PRßPRß'
3. '0'
4. 'Shy Guy Beach (Mario Kart Super Circuit)'
5. 'In the Bar (Streets of Rage II)'
```

And this is what the UI shows for track 1:
![image](https://user-images.githubusercontent.com/9124288/94790111-76084600-039b-11eb-8eb1-085eeeca36f3.png)

What makes me think this is an issue with the Music app is that none of my other players corrupt the metadata in this way. These are the players I've used successfully:
- Windows File Explorer
- Windows Media Player
- VLC media player
- Foobar2000
- Mp3tag

**Comment by paulijar** [comment]
Thanks for the report. If you could share one such problem file with me, I could take a look. You can find my email from my github profile.

**Comment by magneticflux-** [comment]
I sent you an email with two example files, one that works and one that is broken.

**Comment by paulijar** [comment]
Thanks. I was able to reproduce the issue. The Music app is using an external library getID3 to extract the metadata, and for some reason, it extracts corrupted data from one of your files. I could reproduce this issue also by using a demo application provided with the library. I'll report this issue onward to the getID3 project.

**Comment by paulijar** [comment]
I have merged the latest development version of getID3 including a fix to this issue. Hence, this should get fixed once I get the next Music app version published.

**Comment by paulijar** [comment]
Music v0.17.0 with this fix is now released.
