### ISSUE TITLE
How to remove a title from a playlist

### ISSUE THREAD

**Issue by stvogel** [owncloud/music#789]
I can add files to a playlist by simply dragging and dropping the title to the playlist.
But how can I remove a title from the playlist within the frontend?
Or do I have to use some subsonic-client to do that?

**Comment by paulijar** [comment]
When you are viewing a playlist on the web UI, and you hover the mouse over some track, there is an X symbol show after the track name. Pressing this symbol removes the track from the list.
![image](https://user-images.githubusercontent.com/8565946/94989507-056d4f00-057e-11eb-921c-f8dbecb69355.png)

In case you are using a touch screen device with no mouse, the X should become visible when you tap on the track name to start paying it. This may depend on the used device/browser, though. If the X symbol wouldn't become visible, then you could still remove the track by tapping on the spot after the track name where the symbol is supposed to show up.

**Comment by stvogel** [comment]
Hi @paulijar 
thanks for your help. I just realized I had the bug in Nextcloud described here: https://github.com/nextcloud/server/issues/11127
so that I was not able to see any of the icons.
Now that I can see them, it's really kind of obvious.
Thanks for pointing it out!
