### ISSUE TITLE
Include icons on the sidebar

### ISSUE THREAD

**Issue by lazerl0rd** [owncloud/music#794]
For ownCloud's Files app and most fo Nextcloud's apps that utilise a sidebar, there exists icons for each element:

![image](https://user-images.githubusercontent.com/24303423/96879378-e292d400-1473-11eb-8844-6fc47e1a3e54.png) ![image](https://user-images.githubusercontent.com/24303423/96879409-eb83a580-1473-11eb-9f3d-559e545abb21.png) ![image](https://user-images.githubusercontent.com/24303423/96879452-f9392b00-1473-11eb-88f8-48e28f6a230d.png)

I believe it would improve the look of Music's AI to also have the same for the following:

![image](https://user-images.githubusercontent.com/24303423/96879595-24237f00-1474-11eb-82be-6cc5c9f8cea6.png)

If I were to pick from [Material Design's Icons](https://material.io/resources/icons), it would be:

"Albums" would use `albums`.
"Folders" would use `folder`.
"Genres" would use `audiotrack`.
"All tracks" would use `library_music`.

**Comment by paulijar** [comment]
True. And thanks for looking up suitable icons, the biggest reason for not having icons has been, that I haven't figured out what kind of icon would be a good fit for each view.

**Comment by paulijar** [comment]
Navigation pane icons are now included in the freshly released version 0.17.2.
