### ISSUE TITLE
stuck loading new songs

### ISSUE THREAD

**Issue by 4sito** [owncloud/music#797]
i added 700 tracks to my nextcloud server but when I "scan for new music" it looks like it's stuck on the 179th song, because it keeps loading indefinitely. I let it download for nearly 30 minutes and it's at the same point.

**Comment by paulijar** [comment]
Thanks for the report. Is there anything in the nextcloud.log file? You caould also try to scan from the command line with something like
```
sudo -u www-data ./occ music:scan your_user_name
```
The command line scanning has the benefit of showing the file name where the scanning is going. Then, it will become clear which file is causing the issue. Then you could check, if there is anything out of the ordinary with that file (maybe a permission issue or something in the contents of the file).

**Comment by 4sito** [comment]
hi, thanks for your reply, I checked the log files in /var/log/ and in /snap/nextcloud/current/logs ( I installed it via snap) and there is nothing. I also tried the command that you wrote  but it didn't work (I assume it doesn't because I installed it via snap).

**Comment by paulijar** [comment]
The `nextcloud.log` file should be found in the nextcloud data directory.

I'm not familiar with snap packages, but I guess that it should be possible to use the command line tool `occ` if the nextcloud installation works in general. Let's try step-by-step.
1. Locate the root directory of your nextcloud installation and `cd` to it
2. Under that directory, you should find a file named `occ`. Ensure you have execution rights for that file.
3. Find out, which Linux user name your web server uses. I believe that `www-data` is the most common, but it may be something else. If you don't know, then one hint is that at least the `apps` directory under the nextcloud root directory should be owned by the web server user.
4. Now you should be able to run the command `sudo -u <web_server_username> ./occ music:scan <your_nextcloud_user_name>`

**Comment by 4sito** [comment]
ok so i checked the existence of the www-data user then I went to the `/var/www/html/nextcloud` folder and checked the ownership of the files with  "`stat -c %U *`"and all the files in the folder are owned by www-data. Now I "`chmod +x`" the occ file and performed the comand you wrote and it prints 
```
"An unhandled exception has been thrown:
ParseError: syntax error, unexpected end of file, expecting ')' in /var/www/html/nextcloud/config/config.php:17
Stack trace:
#0 /var/www/html/nextcloud/lib/private/Config.php(64): OC\Config->readData()
#1 /var/www/html/nextcloud/lib/base.php(145): OC\Config->__construct()
#2 /var/www/html/nextcloud/lib/base.php(582): OC::initPaths()
#3 /var/www/html/nextcloud/lib/base.php(1089): OC::init()
#4 /var/www/html/nextcloud/console.php(48): require_once('/var/www/html/n...')
#5 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#6 {main}"
```

btw now I have also restarted the scan excluding some files from the "/music" folder and it's currently at 210,

**Comment by paulijar** [comment]
```
ParseError: syntax error, unexpected end of file, expecting ')' in /var/www/html/nextcloud/config/config.php:17
````
So what is there in your file `config.php`, especially around the line 17? The error message hints that the end of the file might be missing. If you post the whole file, be sure to substitute any sensitive information like passwords and secrets with `****` or something.

**Comment by 4sito** [comment]
ok, so I left it overnight and all songs have been uploaded. I don't really now what the problem really was.
Thank you so much for your attention and all your replies. 
I hope you have a nice day!
