### ISSUE TITLE
Unhandled Exception On Manual Scan

### ISSUE THREAD

**Issue by michaeljalves** [owncloud/music#799]
When I issue the manual command 'occ music:scan --all' in Music 17.2 I get the following:

An unhandled exception has been thrown:
TypeError: Return value of "OCA\Music\Command\Scan::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/apps/                          mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#3 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#4 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

**Comment by paulijar** [comment]
Thanks for the report. Which version of ownCloud or Nextcloud are you using?

**Comment by michaeljalves** [comment]
I am using Nextcloud 20.01.

**Comment by paulijar** [comment]
Hmm, I now downloaded NC 20.0.1, but I couldn't reproduce the issue. The command `sudo -u www-data ./occ music:scan --all` scanned my few test files without any issues.

**Comment by michaeljalves** [comment]
On mine I had added several music collections and it said 0 for new music.
I even tried a reset. Here is the full text of my scan.
 _  _         _      _             _
| \| |_____ _| |_ __| |___ _  _ __| |
| .` / -_) \ /  _/ _| / _ \ || / _` |
|_|\_\___/_\_\\__\__|_\___/\_,_\__,_|

https://www.hanssonit.se/nextcloud-vm


root@cybersysintegration:/var/www/nextcloud# sudo -u www-data ./occ
music:scan --all
Start scan for alves
Found 0 music files to scan
Searching cover images for albums with no cover art set...
Searching cover images for artists with no cover art set...
Start scan for luvisi
Found 0 music files to scan
Searching cover images for albums with no cover art set...
Searching cover images for artists with no cover art set...
An unhandled exception has been thrown:
TypeError: Return value of "OCA\Music\Command\Scan::execute()" must be of
the type int, "null" returned. in
/var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0
/var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920):
Symfony\Component\Console\Command\Command->run()
#1
/var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266):
Symfony\Component\Console\Application->doRunCommand()
#2
/var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142):
Symfony\Component\Console\Application->doRun()
#3 /var/www/nextcloud/lib/private/Console/Application.php(215):
Symfony\Component\Console\Application->run()
#4 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#5 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#6 {main}root@cybersysintegration:/var/www/nextcloud

**Comment by michaeljalves** [comment]
I tried the same command on my friend's Nextcloud RPi 19.04 and it worked
fine. He is using the latest version of Music also. It found new music with
no problem. I am curious it is using a Mail console command.

**Comment by paulijar** [comment]
> I am curious it is using a Mail console command.

That's curious indeed. I wonder if installing the Mail app now screws up things, as I don't have it installed on my system. It has been noticed before that the `occ` is kind of funny in how it doesn't keep the apps separated from each other, and one app can affect another app's commands. 

Now it could be that maybe the Mail app brings its own version of the Symfony library and this shadows the version shipped with the Nextcloud server. The error message in the opening post suggests that the system expected Music app's function `Scan::execute()` to return a value while it doesn't. I previously checked the Symfony documentation from some online source and saw that a return value has been added to the signature of the `execute()` function on some version update.

**Comment by michaeljalves** [comment]
I removed the mail app and the error stopped, your hypothesis about mail
overriding the command appears to be valid, but it still does not see any
of the new music I added even though visible through a directory listing.
All my collections are FLAC type files.

**Comment by paulijar** [comment]
The case was exactly as I suspected above: The Nextcloud server ships one version of the Symfony library, and the Mail app ships another, probably newer, version of the same lib. The version shipped with the server allows for individual `occ` commands to return either integer value or nothing. The version shipped with the Mail app is more strict, and requires that all commands must return an integer value. When the Mail app is installed, all `occ` commands of all apps use the Symfony version shipped with it. I could reproduce the error after installing the Mail app.

Fortunately, the Symfony versions on all the supported Nextcloud and ownCloud versions seem to allow for the command to return an integer value. Hence, it is easy to fix the problem by adding `return 0` to the end of the `execute()` function of each of the `Command` class of the Music app.

**Comment by michaeljalves** [comment]
Glad it is fixable.

**Comment by michaeljalves** [comment]
One last thing. Do you have any documentation on how to setup Last.fm with
Music so I get more detailed information? I can't find anything on the net
for it.

**Comment by paulijar** [comment]
Music app v0.17.3 fixing also the `occ` issue has now been published. There may be bit of a delay before the Nextcloud apps management offers the new version; at least for me, it is already offered in my NC19 test installation but not on the NC20 test installation although both fetch the same package from the same source.

> I removed the mail app and the error stopped, (...), but it still does not see any
of the new music I added (...) All my collections are FLAC type files.

Your files not showing up in Music even with Mail app disabled suggests that you are having also some other issue. Have you made sure that your music files reside under the folder which has been set as "Path to your music collection" in the Settings view of the Music app?

> Do you have any documentation on how to setup Last.fm with
Music

There is this short description under the Admin section of the Music Settings:
![image](https://user-images.githubusercontent.com/8565946/98451443-295c1b80-214e-11eb-849d-4bb4dc7fd119.png)
This basically tells everything there is to setting up the Last.fm connection, but were you looking for more detailed step-by-step kind of tutorial?

**Comment by michaeljalves** [comment]
I found that opening the music folder made Nextcloud actually scan the
subdirectories and index after then Music found the new files. I'm not sure
why Nextcloud wouldn't automatically index the new files but after I
manually opened the folder then the main Music  folder went into Pending.

Thanks for the info on Last.fm. I missed seeing that part of the Admin
section.

**Comment by paulijar** [comment]
> I'm not sure why Nextcloud wouldn't automatically index the new files

Are your files on a SMB share or some other external storage? On such setups, Nextcloud may not automatically index the files, and it only happens once the folder is browsed. It might be also possible to trigger the scanning with `occ files:scan` although I'm not certain of this. From the point-of-view of the Music app, the files do not exist before Nextcloud has indexed them.

As the originally reported problem is now solved, I'll mark this issue as closed.
