### ISSUE TITLE
Internal Server Error after upgrade

### ISSUE THREAD

**Issue by sriptorium** [owncloud/music#800]
Hi,

Was greeted by this error when opening Music app after the last upgrade today.

The rest of the Nextcloud instance works fine, the internal server error only appears when entering Music app.

Logs show "error" level entry with many references to Music app as such : 

```
Error | index | RuntimeException: image not found: image:play-previous.svg webroot: serverroot:/var/www/xxxx

{"reqId":"vWJkkNaXQ7MviWXxglgc","level":3,"time":"2020-11-05T20:03:57+00:00","remoteAddr":"xxx","user":"xxx","app":"index","method":"GET","url":"/index.php/apps/music/","message":{"Exception":"RuntimeException","Message":"image not found: image:play-previous.svg webroot: serverroot:/var/www/xxx","Code":0,"Trace":[{"file":"/var/www/xxx/lib/private/legacy/template/functions.php","line":238,"function":"imagePath","class":"OC\\URLGenerator","type":"->"},{"file":"/var/www/xxx/lib/public/Template.php","line":49,"function":"image_path"},{"file":"/var/www/xxx/apps/music/utility/htmlutil.php","line":33,"function":"image_path","class":"OCP\\Template","type":"::"},{"file":"/var/www/xxx/apps/music/templates/partials/controls.php","line":6,"function":"printSvgPath","class":"OCA\\Music\\Utility\\HtmlUtil","type":"::"},{"file":"/var/www/xxx/apps/music/utility/htmlutil.php","line":64,"args":["/var/www/xxx/apps/music/templates/partials/controls.php"],"function":"include"},{"file":"/var/www/xxx/apps/music/utility/htmlutil.php","line":53,"function":"partialContent","class":"OCA\\Music\\Utility\\HtmlUtil","type":"::"},{"file":"/var/www/xxx/apps/music/templates/main.php","line":32,"function":"printPartial","class":"OCA\\Music\\Utility\\HtmlUtil","type":"::"},{"file":"/var/www/xxx/lib/private/Template/Base.php","line":178,"args":["/var/www/xxx/apps/music/templates/main.php"],"function":"include"},{"file":"/var/www/xxx/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/xxx/lib/private/legacy/OC_Template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/xxx/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/xxx/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/xxx/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/xxx/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/xxx/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/xxx/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/xxx/lib/private/URLGenerator.php","Line":236,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1","id":"xxx"}
```

Running NC 20.0.1.1
Ubuntu 20.04
PHP 7.4

Please let me know if you require more information.
Best regards.

**Comment by paulijar** [comment]
Hello. 
That kind of sounds like the update has somehow not happened completely. The application has been trying to load `play-previous.svg` which no longer exists in v0.17.2, as it has been replaced by `skip-previous.svg`. On your installation, the invalid reference has been found from the line 6 of the file `tamplates/partials/controls.php` which should look like this:
https://github.com/owncloud/music/blob/47b672b10fa5b2b6ba03a9bb4d04f2b10c81fe0f/templates/partials/controls.php#L6

But apparently, it still refers to the old file name on you installation.

**Comment by sriptorium** [comment]
Hi @paulijar 
Good morning, and thank your for your insight.
If we consider the possibility that my update was somehow incomplete, what would you suggest would be the safest way to update it completely now ?
Have a good day.

**Comment by paulijar** [comment]
Hello @sriptorium 

You could try to first remove the app through app management on the Nextcloud web UI. Then, check from the Nextcloud installation directory (might be something like `/var/www/html/nextcloud`) the subdirectory `apps`. If there still exist a directory `music` under `apps`, then remove it with `sudo rm -r music`. Then install again via the Nextcloud web UI.

**Comment by sriptorium** [comment]
Hi @paulijar 
Thanks yet again for your support.
Problem unfortunately is still not resolved.

After having removed the Music app from NC UI App page, checking the `/{install_dir}/apps/` folder showed that the `music/` folder was indeed completely removed. So I didn't need to do a `rm`...
Reinstalling from the webui, going to the Music app, still showed internal server error.
In the logs I can still see the same error previously documented above regarding the `play-previous.svg`.

However, I'm also seeing a 'PHP' error of a different kind, that did not incriminate the Music app itself but rather the file app  (see below).

So maybe I also have some other sort of problem...
Everything was running fine until I upgraded Music app, but this issue lead me to discover errors that might have been pre-existant but had remained unnoticed...

If this continues I might have to open a ticket on the community forum... 

Version check : 
```
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

Error log about PHP : 
`{"reqId":"xxx","level":3,"time":"2020-11-06T09:27:37+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/apps/files/","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/xxx/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/xxx/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/xxx/apps/files/lib/Controller/ViewController.php","line":139,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/xxx/apps/files/lib/Controller/ViewController.php","line":187,"function":"getStorageInfo","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/xxx/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/xxx/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/xxx/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/xxx/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/xxx/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/xxx/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/xxx/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1","id":"xxx"}`

**Comment by paulijar** [comment]
Okay, that's curious. I wonder if it is possible that this would be some kind of server-end caching issue. If somehow, the server is still using the old PHP files although they should have been updated, then that would explain the observed results.

Just to make sure, can you check the contents of your file `nextcloud/apps/music/templates/partials/controls.php`, and especially the line 6?

**Comment by sriptorium** [comment]
Hi @paulijar 

Here are the first few lines of `apps/music/templates/partials/controls.php`

```
<?php use \OCA\Music\Utility\HtmlUtil ?>

<div id="controls" ng-controller="PlayerController" ng-class="{started: started}">
       <div id="play-controls">
                <img ng-click="prev()" class="control small svg" alt="{{ 'Previous' | translate }}"
                        src="<?php HtmlUtil::printSvgPath('skip-previous') ?>" />
                <img ng-click="play()" ng-hide="playing" class="control svg" alt="{{ 'Play' | translate }}"
                        src="<?php HtmlUtil::printSvgPath('play-big') ?>" />
                <img ng-click="pause()" ng-show="playing" class="control svg" alt="{{ 'Pause' | translate }}"
                        src="<?php HtmlUtil::printSvgPath('pause-big') ?>" />
                <img ng-click="next()" class="control small svg" alt="{{ 'Next' | translate }}"
                        src="<?php HtmlUtil::printSvgPath('skip-next') ?>" />
```

extract of my nc config file regarding cache settings 

```
(...)
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => xxx,
    'timeout' => 0.0,
    'password' => 'xxx',
  ),
(...)
```

Some redis caching would need a purge ?

**Comment by sriptorium** [comment]
Hi @paulijar 
Very interesting :

So for some completely other reason, I have had to reboot the entire server.
And after complete shutdown and start, the problem entirely disapeared all together.
The process must have conveniently flushed all cache in the process.

Thanks for your help anyhow, but we have something to keep in mind ;-) 

Best regards.

**Comment by paulijar** [comment]
@sriptorium 
Okay, good it worked out for you. I'm not an expert on Redis or other PHP caching techniques but if this kind of problems occur, then you probably have some problem with the configuration. If this has happened once, then it will likely bite you again on some future software update.
