### ISSUE TITLE
choose where to scan for music (Nextcloud 20)

### ISSUE THREAD

**Issue by sebtech33** [owncloud/music#803]
hi i cant seem to find a way to choose here to scan for the music files. i have a specified folder for music and i would like to only find files from that folder. in audio player its a page in settings to choose here to scan, but there arent a page more this and when i opened the music plugin for the first time i wasnt able to choose where to scan. it scans all the folders in my nextcloud instance and that does not work for me.

**Comment by paulijar** [comment]
Hi @sebtech33,

There is a Settings button in the Music app itself:
![image](https://user-images.githubusercontent.com/8565946/98988817-e1b00800-2530-11eb-85f3-4948ebe399c8.png)

From there, you can find the selection "Path to your music collection". Optionally, you may also ignore some folders under the selected path.

**Comment by sebtech33** [comment]
> Hi @sebtech33,
> 
> There is a Settings button in the Music app itself:
> ![image](https://user-images.githubusercontent.com/8565946/98988817-e1b00800-2530-11eb-85f3-4948ebe399c8.png)
> 
> From there, you can find the selection "Path to your music collection". Optionally, you may also ignore some folders under the selected path.

omg.. now i feel stupid thank you :) the web page info in the bottom left covered it so i didnt see it. thank you again :)

**Comment by paulijar** [comment]
No problem! :D
