### ISSUE TITLE
[Feature Request] Support for LoginFlow

### ISSUE THREAD

**Issue by sunjam** [owncloud/music#804]
![loginflow](https://user-images.githubusercontent.com/1787238/99339990-f98ed100-283b-11eb-8552-5f472b501056.PNG)

Please considering adding Loginflow support for Nextcloud, since it greatly simplifies credentials by adding support for the webui and removing the need to generate a one-time password or know the webdav address.  Users can simplify login via their standard password or use other forms of authentication.

[Documentation located here](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html).

Thank you for considering!

**Comment by paulijar** [comment]
I'm not familiar with the LoginFlow but I now read the documentation. How I understood it, it is a mechanism that a client application can use to obtain access to a Nextcloud account. And the clients must build the support according the documentation if they want to use it. But I didn't understand, how would this affect the Music app. Can you elaborate, what kind of support did you have in mind? What is the use case?

**Comment by paulijar** [comment]
Closing as out-of-scope
