### ISSUE TITLE
How to add last-fm api key to Nexcloud config?

### ISSUE THREAD

**Issue by poltrian** [owncloud/music#809]
Hello

could someone describe what i have to add in the Nexcloud config File für using last.fm Api?

 Thanks and also thanks for the great app!

**Comment by Gene-W** [comment]
Hello, did you find an answer to this? I'm looking for the same information too. +1:

**Comment by poltrian** [comment]
Yes, you can find a Manual under the settings in the Music app. Then got to admin and you will find these:

"There is no settings UI for the server-wide settings of the Music app but some settings are available by adding specific key-value pairs to the file <cloud root>/config/config.php. The available keys are described below.

music.lastfm_api_key

To see the artist biography and other information from Last.fm in the details view, you need to create an API account with Last.fm. For this, use the Last.fm form. Only 'Contact email' and 'Application name' need to be filled in the form. You are then provided with an API key which should be used as a value for this key."

You need an Api key and have to put them in you NC config: e.g.

'music.lastfm_api_key' => 'YourApiKey',

You can then find in the music app some information about your Artist. 

Move the mouse over the album name and click on what appears

**Comment by paulijar** [comment]
As it's evident that users might not immediately find the explanation from the Settings view, and indeed it's quite concise, I now created a guide to the wiki: https://github.com/owncloud/music/wiki/Setting-up-Last.fm-connection

I don't know if people are going to find it from the wiki, either, but I guess there is a chance that it will show up in their Google search. Or then they may find this issue :).

**Comment by Gene-W** [comment]
Very good, thank you for the details!

**Comment by sureloc** [comment]
I'm afraid to mess something up, exactly where in the config file should the API key be entered? 
The end of the file looks like this 
![configNC](https://github.com/owncloud/music/assets/69294325/21c3f984-8cfc-4e58-b5be-4792b3b47d98)

**Comment by paulijar** [comment]
@sureloc The structure of the config.php file is like
```
<?php
$CONFIG = array (
  'key1' => 'value1',
  'key2' => 'value2',
  'arrayKey3' => array(
    0 => 'first array value',
    1 => 'second array value',
  ),
  'key4' => 'value4',
);
```
So the file is a collection of key-value pairs, and some of the values are actually arrays of multiple values.

You can add the new key-value pair after or before any of the existing key-value pairs, for example to the end of the list just before `);`. Any white-space characters in the file are insignificant. If you mess up the file structure, then you cloud just stops working. If that happens, you should revert what ever you did. If in doubt, then it's a good idea to create a backup copy before editing.
