### ISSUE TITLE
M4A Files not playing

### ISSUE THREAD

**Issue by jonsacbibit** [owncloud/music#810]
I had started an nextcloud server on Ubuntu 20 LTS, utilizing LAMP. 
It will flawlessly play all other media files however M4As cannot play. It just throws an error in the right top corner. The album artwork and ID and other information is showing however no playback. 
I seen this was supported but wasn't sure if there were any issues with this API not supporting this file type.

Nothing in the error logs -- the rest of the server runs great; seems like it just might not be supported and I just want some clarification on that. 

Thanks!

**Comment by jonsacbibit** [comment]
Also, the error has no code or specifications, just "Cannot play file (filename)".

**Comment by paulijar** [comment]
Which browser are you using? To play any file type besides MP3 and FLAC, the browser must have a built-in decoder to support the type. And even for those two types, the user experience is better when the browser provides support.

I have successfully tested M4A files on Firefox, Chrome, the "new" Edge (which is basically just Chrome in disguise), and even on IE11. For testing purposes, I still have an ancient Chromium version 55.0.2850.0 available which does not have support to play M4A.

**Comment by inthreedee** [comment]
This can happen if the .m4a file is using the lossless ALAC codec as opposed to the lossy AAC codec.  Firefox, for example, cannot play ALAC encoded m4a's but will play AAC encoded m4a's.  Converting these files to the more standard FLAC is one option to preserve the lossless audio.  They take up the same space and it can be done very quickly with ffmpeg:

```ffmpeg -i file.m4a out.flac```

I wrote a bash script to scour my media library for all ALAC-encoded m4a's and convert them automatically.  To use it, run it from the base folder of your media library.  When it asks, type "m4a" for the input file extension, "alac" for the codec, "flac" for the output file extension, and "y" to move the old files.

It will convert only the ALAC encoded m4a's to FLAC, preserving all metadata and folder structure, then move the old m4a out into a folder named "converted" with all directory structure intact just in case.

It supports converting to and from other formats as well, though I haven't actually tested that.

```
#!/usr/bin/env bash

################################################################
# Batch convert audio files using ffmpeg
# Searches the current working directory and subdirectories
# Optionally moves the old files to a converted directory
################################################################

if [ ! -x "$(command -v ffmpeg)" ]; then
    echo "convert-audio.sh: ffmpeg not found on this system" 1>&2
    exit 1
fi

shopt -s globstar

# Get info from the user
while [ -z "$in_ext" ]; do
    read -p "Enter input file extension (ie. mp3, m4a, wav, flac): " in_ext
done

if [ "$in_ext" = "m4a" ]; then
    # m4a can have aac or alac codecs. Do we want to only target one of these?
    echo ""
    echo "m4a files use either the aac (lossy) or alac (lossless) codec"
    while read -p "Which codec do you want to convert from? (aac/alac/both): " codec; do
        case "$codec" in
            "aac")
                break
                ;;
            "alac")
                break
                ;;
            "both")
                break
                ;;
            *)
                echo "You must type 'aac', 'alac', or 'both'"
                ;;
        esac
    done  
fi

echo ""
while [ -z "$out_ext" ]; do
    read -p "Enter output file extension: " out_ext
done

echo ""
while read -p "Move old files when done? [y/n]: " yn; do
    case "$yn" in
        [Yy]*)
            move_old="true"
            break
            ;;
        [Nn]*)
            move_old="false"
            break
            ;;
        *)
            echo "Please type 'y' or 'n'"
            ;;
    esac
done
echo ""

# Search the current directory and subdirectories
for file in **/*."$in_ext"; do
    # Are we excluding a codec?
    if [ ! -z "$codec" ] && [ "$codec" != "both" ]; then
        # Get the codec of this file
        file_codec="$(ffprobe -v error -select_streams a:0 -show_entries stream=codec_name -of default=nokey=1:noprint_wrappers=1 "$file")"

        # Does the file codec match the user input?
        if [ "$file_codec" != "$codec" ]; then
            # Skip this file
            continue
        fi
    fi

    outfile="${file%.*}"
    # Don't overwrite files that already exist
    if [ -f "$outfile.$out_ext" ]; then
        echo "WARNING! DESTINATION FILE EXISTS:"
        echo "'$outfile.$out_ext'"
        continue
    fi
    
    # Do the conversion
    echo "Converting to $out_ext:"
    echo "'$file'"
    ffmpeg -hide_banner -loglevel error -i "$file" "$outfile.$out_ext"

    # Move the old file out to a converted directory
    if [ "$move_old" = "true" ]; then
        echo "Moving old file..."
        mkdir -p "$(dirname "./converted/$file")" && mv "$file" "./converted/$file"
    fi
done
```

**Comment by paulijar** [comment]
In conclusion, the Music app can play only what can be played by the browser. If you find a file which plays in your browser (*) but not in the Music app, then it's an interesting case and should be reported. Otherwise, there is likely nothing we could do in the Music app (except maybe transcoding would be a possibility, but there is already a feature request #428 opened for this).

(*) You can e.g. download the file and open the local file to the browser to test this.

**Comment by JoshuaPettus** [comment]
That's a nicely done script.  Thanks!  Certainly saved me some time going through the process manually.   Also handy for scouring my library and turning aiff to wav format
