### ISSUE TITLE
Power Ampache Invalid Session Token after Update nextcloud from 19.0.6 to 20.0.3

### ISSUE THREAD

**Issue by florom** [owncloud/music#811]
Hi Devs,

It is a pitty that it isnt working anymore and I cannot give you more information that this Log Entry from the music app:

{"reqId":"FK7AeXLloocCaIln1Tx9b","level":0,"time":"2020-12-16T12:57:04+00:00","remoteAddr":"XXXX","user":"XXXX","app":"music","method":"GET","url":"/index.php/apps/music/ampache/server/xml.server.php?auth=XXXXXaction=ping&version=350001","message":"Invalid Login - invalid session token","userAgent":"okhttp/3.10.0","version":"20.0.3.2"}

The Power Ampache App also shows; Something went wrong: Invalid Login - invalid session token

Probably you can look into it.

Thanks

**Comment by paulijar** [comment]
This is a duplicate to #791. Please upvote the root cause issue https://github.com/nextcloud/server/issues/23544 at Nextcloud server.

**Comment by florom** [comment]
Ah ok, I searched for Power Ampache so it did not show up.
Anyways I upvoted and commented the root cause.

Thanks.

**Comment by florom** [comment]
It works with Nextcloud 20.0.5 

Thanks!
