### ISSUE TITLE
only few folders with music are detected

### ISSUE THREAD

**Issue by adosix** [owncloud/music#812]
I ve tried severl times rescan music folder which is in external storage (local HDD drive) and all files shows and plays correctly in file explorer on nextcloud but when I scan files only few folders are added to mosic and always the same folders. Tried several times to change path and rescan whole music folder, nothing changed.

**Comment by paulijar** [comment]
Music can find only files which have been indexed by the cloud first. I *think* that the files on external storage are not indexed by default, but only when you browse to those folders in the Files app. It is also possible, that the indexing would happen in a background task at some later time, but this probably depends on your configuration.

You probably could force the cloud to index your external folder with the command line tool `occ files:scan`. The command should be something like
```
cd /path/to/your/owncloud_or_nextcloud
sudo -u www-data ./occ files:scan your_user_name
```
Check `occ files:scan --help` for details.

**Comment by paulijar** [comment]
@adosix Were you able to solve the issue?

**Comment by adosix** [comment]
Yes i solved it by rescanning given folder. U can use `sudo -u www-data php occ files:scan --all` to rescan all folders recursively but be prepared to wait a while.

**Comment by adosix** [comment]
But It would be appreciated if rescan button was in the nextcloud app gui

**Comment by hypervtechnics** [comment]
This is mentioned here: 
https://docs.nextcloud.com/server/20/admin_manual/configuration_files/external_storage_configuration_gui.html?highlight=scan%20files#adding-files-to-external-storages
https://docs.nextcloud.com/server/20/admin_manual/configuration_server/background_jobs_configuration.html#cron
