### ISSUE TITLE
Play time counter counts till 60

### ISSUE THREAD

**Issue by fruitdumonde** [owncloud/music#814]
**Issue Description:**
The play time shown above the progress bar counts seconds from 0 - 60.
The issue was observed with all tested mp3 files.

**Expected Behavior**
The counter should count from 0 - 59.

**Screen Recording**
https://user-images.githubusercontent.com/55314929/104080190-efc78f80-5226-11eb-9ecc-f0a573cdba4e.mp4

**Versions**
- Music v0.17.3
- Nextcloud 20.0.4
- Firefox 84.0.2 (64-Bit)
- OS Win 10

**Comment by paulijar** [comment]
Thanks for the report. This is fixed now, and the fix shall be included in the next release.

**Comment by paulijar** [comment]
This is now fixed in the freshly released Music v1.0.0.
