### ISSUE TITLE
[Feature Request] Album creation date

### ISSUE THREAD

**Issue by inthreedee** [owncloud/music#817]
The subsonic API v1.14.0 added “created” to the “getAlbumList2” method. It gives the date an album was added to your library.  This is used by the Play:Sub iOS app to show the most recently added albums, sorted by date. 

I don’t know if there are plans to update the API being used, but sorting albums by their creation date is a handy feature!

```
<xs:complexType name="AlbumID3">
<xs:attribute name="id" type="xs:string" use="required"/>
<xs:attribute name="name" type="xs:string" use="required"/>
<xs:attribute name="artist" type="xs:string" use="optional"/>
<xs:attribute name="artistId" type="xs:string" use="optional"/>
<xs:attribute name="coverArt" type="xs:string" use="optional"/>
<xs:attribute name="songCount" type="xs:int" use="required"/>
<xs:attribute name="duration" type="xs:int" use="required"/>
<xs:attribute name="playCount" type="xs:long" use="optional"/>
<!--  Added in 1.14.0  -->
<xs:attribute name="created" type="xs:dateTime" use="required"/>
<xs:attribute name="starred" type="xs:dateTime" use="optional"/>
<xs:attribute name="year" type="xs:int" use="optional"/>
<!--  Added in 1.10.1  -->
<xs:attribute name="genre" type="xs:string" use="optional"/>
<!--  Added in 1.10.1  -->
</xs:complexType>
```

quoted from:
http://www.subsonic.org/pages/inc/api/schema/subsonic-rest-api-1.16.1.xsd

**Comment by paulijar** [comment]
Storing the creation and modification dates for albums and tracks has been on my mental TODO list. Such information would be necessary also for some of the features of the Ampache API.

**Comment by paulijar** [comment]
The `created` property is now included in the albums and songs in the Subsonic API in the freshly released Music v1.0.0.

**Comment by inthreedee** [comment]
Thank you!  I appreciate your work on this.

**Comment by paulijar** [comment]
One caveat about the implementation, though: the created/modified timestamps will carry meaningful information about your collection only when you add new tracks and albums. For all the content pre-existing in the library, the timestamps are set to the moment when the Music v1.0.0 was installed.
