### ISSUE TITLE
chmod of a folder changed in a recent version 

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/music#818]
Hi,

I noticed that the chmod of a folder changed in a recent version.

```
/usr/src/nextcloud/apps/music # ls dist/ -lat
total 1220
drwxr-xr-x    1 755      root          4096 Jan  7 19:51 .
drwxr-xr-x    1 root     root          4096 Jan  7 19:51 ..
drwxr-xr-x    1 755      root          4096 Jan  7 19:51 img
-rwx------    1 755      root          2109 Jan  7 19:51 manifest.json
-rwx------    1 755      root        821712 Jan  7 19:51 webpack.app.057db93b817b553117e1.js
-rwx------    1 755      root         29502 Jan  7 19:51 webpack.app.ca668275c81b26a18c2f.css
-rwx------    1 755      root        355823 Jan  7 19:51 webpack.files_music_player.582e6445fa6d673a9f66.js
-rwx------    1 755      root          7308 Jan  7 19:51 webpack.files_music_player.d9104b1156ce59881903.css
```

But yeah, as my webserver is running with nginx it can't read and serve those files.

I'm running this version:
0.17.3

I searched around to find the build script to try to fix it my self, didn't find much.

I [quick fix](https://lab.libreho.st/libre.sh/docker/nextcloud/commit/f67ab22c13f92fe8d4af1067d357d908871a9181) locally for me, but it might happen to somebody else, hence reporting it.

Have a nice evening!

**Comment by paulijar** [comment]
I don't know what was different on the creation of the release package 0.17.3 but I can confirm that there the files under `dist` had the access control mask `700`. Meanwhile, at least the version 1.0.0 and the latest version 1.4.1 have the mask `644`. So there should be no problems nowadays, and this old issue can be closed.
