### ISSUE TITLE
Display and controls not working properly after NC 20.0.6 update

### ISSUE THREAD

**Issue by Talw3g** [owncloud/music#819]
Hello,

I am running a dockerized implementation of Nextcloud, based on the nextcloud:production-apache image.
Since I updated to 20.0.6 (from 20.0.5 I believe), the display and controls of Music don't work properly (see image below).
The music is played correctly, but I can't skip a track or activate the random mode. It doesn't seem to be only a display problem, since I can't do anything more than play/pause with the media control keys...
Please tell me if you need any more information !

Thanks

![image](https://user-images.githubusercontent.com/12981757/106456512-e4662d80-648d-11eb-9495-4ea8f1e9b932.png)

**Comment by paulijar** [comment]
Hi. Which version of the Music app are you using? Based on the navigation pane on the left, it looks like a really old version which is definitely not compatible with any release of NC20. Could you first try to update the Music app to the latest version 0.17.3?

**Comment by Talw3g** [comment]
It is indeed in version 0.8.0... but I can't seem to be able to install another version : I tried removing the app and installing it again from the store, and I still get the 0.8.0 :/
Wrong version linked in the store ?

**Comment by Talw3g** [comment]
I've downloaded and manually installed v. 0.17.3, and it is working fine !
Don't know if it will update in the future, but that's good enough for now :)

**Comment by paulijar** [comment]
Okay, great. The updating via the Nextcloud application management should work regardless of the method used to install the app, as long as your web server has write access on the application files.

**Comment by RomainTT** [comment]
Hi @paulijar 
I have the exact same issue. Music version went back to 0.8.0 when upgrading Nextcloud image to 20.0.6.
I would like to avoid manual installation like @Talw3g did. Do you have any idea how to fix the update please ?

**Comment by RomainTT** [comment]
Maybe it is linked to [the issue described in this post](https://help.nextcloud.com/t/after-update-to-nc-20-0-6-cant-install-or-update-mail-app/105823/2). I will try to update to 20.0.7 as soon as it is available.

**Comment by paulijar** [comment]
One interesting piece of information is that the v0.8.0 was the last version where the Music app did not define the supported PHP versions in its info.xml file. The latest version claims support (=has been tested with) PHP versions 7.0 - 7.4.

**Comment by paulijar** [comment]
I just updated from NC 20.0.5 to 20.0.7. For me, no downgrading of the Music app happened; I had Music 0.17.3 installed from the app management before the update and it remained intact through the update.

I have a pretty strong hunch that this is somehow related to the checking of the supported PHP versions. The Nextcloud server seems to have one commit related to this in 20.0.6, which was reverted in 20.0.7. Probably there was some reason for reverting it...

**Comment by lrvick** [comment]
Same problem here on FreeBSD.

Unable to see versions newer than 8.0 in store.

When I attempted to manually install music_1.0.2 to my nextcloud 20.0.6 the install fails with:

```
Error: Function get_magic_quotes_runtime() is deprecated at /usr/local/www/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#170
```

**Comment by paulijar** [comment]
@lrvick That error seems like something which you will get when trying to run Music v0.8.0 with PHP 7.4. That's because that old Music version ships with getID3 library version which is not compatible with PHP 7.4.

Is there something preventing you from updating NC to 20.0.7 where the root cause of these problems is fixed? If that is not possible, then maybe you could try once again to disable Music, delete the folder `nextcloud/apps/music`, recreate the folder manually with the v1.0.2 files, and then enable Music. I don't know but it might work.

**Comment by lrvick** [comment]
That got me working for now. thanks!
