### ISSUE TITLE
Not compatible with Nextcloud 20.0.7

### ISSUE THREAD

**Issue by poltrian** [owncloud/music#820]
i would like update from 20.0.6 to 20.0.7. But the upater shows. These apps are not compatible, Mail, Music, TOTP.

Whats going wrong?

**Comment by RomainTT** [comment]
Maybe a link with #819

**Comment by paulijar** [comment]
Yeah, apparently something hairy is going on with the Nextcloud updated as multiple people are now having problems. By definition, the should be no breaking changes between the patch releases 20.0.x. The Music app just claims compatibility for Nextcloud versions 13 - 20, and that should cover all the patch releases with the major part falling into this range (and even minor releases if there ever were any).

That being said, I haven't yet had time to test Nextcloud 20 versions newer than 20.0.5.

**Comment by JoshuaPettus** [comment]
I updated anyway and it didn't actually disable music.  Music is working just fine on 20.0.7 for me.  It's just a very errant warning.

**Comment by paulijar** [comment]
I don't know but I have a hunch that checking the supported PHP versions of the apps doesn't quite work on NC 20.0.6. And this might be already fixed in 20.0.7 because at least there are some related changes.

**Comment by elhananjair** [comment]
> I updated anyway and it didn't actually disable music. Music is working just fine on 20.0.7 for me. It's just a very errant warning.
It is not working for me
![Music](https://user-images.githubusercontent.com/69236638/106995288-9dc74a80-678f-11eb-9625-85ba354f72a5.png)

**Comment by JoshuaPettus** [comment]
Honestly, that could be a lot of things.  Did you check your server log for the actual error?  
Sometimes I find the command-line updater is more reliable then the web one.

**Comment by ei8fdb** [comment]
If it helps, I've got Music app running on Nextcloud 20.0.7. 

Details of install -
PHP:
Version: 7.3.17
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 5 GB

DB:
Type: pgsql
Version: PostgreSQL 11.9 (Ubuntu 11.9-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

**Comment by elhananjair** [comment]
> Honestly, that could be a lot of things. Did you check your server log for the actual error?
> Sometimes I find the command-line updater is more reliable then the web one.

well today I tried to  update from CLI and it updated successfully but showing the same error. After that I tried removing it and install as new using CLI, and it installed well, but unfortunately my NC instance entirely stopped working. Then I removed it again. I really don't know why Music app is behaving different.

**Comment by JoshuaPettus** [comment]
Pronouns aren't the best when explaining what's going on.  When you say "it" you mean you removed the music app, updated with the command line, then put it back and NC failed?  Again, you need to find the actual error in your log.  It's hard to figure out what's going on without that.

**Comment by sokai** [comment]
**FYI:** maybe helpful/relevant → https://github.com/nextcloud/twofactor_totp/issues/1073#issuecomment-772667942 + https://github.com/nextcloud/server/pull/25335

**Comment by elhananjair** [comment]
> Pronouns aren't the best when explaining what's going on. When you say "it" you mean you removed the music app, updated with the command line, then put it back and NC failed? Again, you need to find the actual error in your log. It's hard to figure out what's going on without that.

hello, am sorry for not explaining precisely. Yeah I was checking logs and nothing was written there regarding Music app. Actually I installed it again from CLI and it worked. Thanks

**Comment by ei8fdb** [comment]
When I update my Nextcloud server version, I semi-regularly (once every 5-6 months) have the upgrade break my Nextcloud. My approach is to disable *all* apps from commandline, and rerun the upgrade, which usually works. 

Then I reenable each app one-by-one, until I find which one breaks things.

The Nextcloud upgrade process is pretty good actually as it will warn you if there's an app is *not* conpatible with the newer server version. It is rarely (but does happen) wrong.

My advice if this happens, disable all apps, upgrade, and reenable one-by-one.

**Comment by ei8fdb** [comment]
> Yeah I was checking logs and nothing was written there regarding Music app. Actually I installed it again from CLI and it worked. 

Ah great! Another Issue bites the dust.

**Comment by sokai** [comment]
FYI: For me it seems this (generic) _incompatibility problem_ is fixed with 20.0.7 (like I mentioned [mentioned above](#issuecomment-775127079)).

1. disable the Music app (= all the said to be not compatible apps)
2. upgrade Nextclout to 20.0.7
3. enable + upgrade the disabled apps (from 1.) – they are upgradeable now again/like normal
4. done :-)

**Comment by paulijar** [comment]
I guess there are no more open issues here, and this report can be closed.
