### ISSUE TITLE
Internet Radio Site With Numbers in URL Throwing Play Error

### ISSUE THREAD

**Issue by michaeljalves** [owncloud/music#821]
Any URL using an IP address and/or port number in the URL throws an error when trying to play when using Internet Radio.

**Comment by paulijar** [comment]
That really shouldn't be the case, I have successfully listened to both addresses containing an IP address and ones having a non-default port. Can you give an example of an URL which does not work? Have you ruled out the possible reasons listed under "Troubleshooting" when you view the "Getting started" found by clicking "..." next to the "Internet radio" in the navigation pane?

**Comment by michaeljalves** [comment]
Here is the URL:

http://stream.fr.morow.com:8080/morow_med.mp3

I went through the troubleshooting steps and could not remediate.

**Comment by paulijar** [comment]
I copied the URL above to a PLS file, and imported the file to Music. For me, the station was playing fine.

When you are experiencing the problem, can you find any error from the browser console?

**Comment by michaeljalves** [comment]
Here is the only log I could find in Nextcloud related to Radio:

{"reqId":"Mc1mYY7ZHnyPsu9xkP8R","level":3,"time":"2021-02-06T12:39:24-08:00","remoteAddr":"192.168.1.1","user":"alves","app":"index","method":"GET","url":"/apps/radio/api/recent","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An
exception occurred while executing 'SELECT DISTINCT \"stationuuid\",
\"name\", \"favicon\", \"urlresolved\", \"bitrate\", \"country\",
\"language\", \"homepage\", \"codec\", \"tags\" FROM \"oc_recent\" WHERE
\"user_id\" = ? ORDER BY \"id\" DESC' with params
[\"alves\"]:\n\nSQLSTATE[42P10]: Invalid column reference: 7 ERROR:  for
SELECT DISTINCT, ORDER BY expressions must appear in select list\nLINE 1:
...gs\" FROM \"oc_recent\" WHERE \"user_id\" = $1 ORDER BY \"id\" DESC\n

 ^","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":149,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":914,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":202,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":320,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Db/RecentMapper.php","line":84,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Service/RecentService.php","line":44,"function":"findAll","class":"OCA\\Radio\\Db\\RecentMapper","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Controller/RecentController.php","line":53,"function":"findAll","class":"OCA\\Radio\\Service\\RecentService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Radio\\Controller\\RecentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":79,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[42P10]:
Invalid column reference: 7 ERROR:  for SELECT DISTINCT, ORDER BY
expressions must appear in select list\nLINE 1: ...gs\" FROM \"oc_recent\"
WHERE \"user_id\" = $1 ORDER BY \"id\" DESC\n

 ^","Code":"42P10","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":906,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":202,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":320,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Db/RecentMapper.php","line":84,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Service/RecentService.php","line":44,"function":"findAll","class":"OCA\\Radio\\Db\\RecentMapper","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Controller/RecentController.php","line":53,"function":"findAll","class":"OCA\\Radio\\Service\\RecentService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Radio\\Controller\\RecentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":129,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42P10]:
Invalid column reference: 7 ERROR:  for SELECT DISTINCT, ORDER BY
expressions must appear in select list\nLINE 1: ...gs\" FROM \"oc_recent\"
WHERE \"user_id\" = $1 ORDER BY \"id\" DESC\n

 ^","Code":"42P10","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":127,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":906,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":202,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":320,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Db/RecentMapper.php","line":84,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Service/RecentService.php","line":44,"function":"findAll","class":"OCA\\Radio\\Db\\RecentMapper","type":"->"},{"file":"/var/www/nextcloud/apps/radio/lib/Controller/RecentController.php","line":53,"function":"findAll","class":"OCA\\Radio\\Service\\RecentService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Radio\\Controller\\RecentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":127}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0
(Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/88.0.4324.146
Safari/537.36","version":"20.0.7.1","id":"6021b2b90d070"}

**Comment by michaeljalves** [comment]
I've tried in Chrome and Edge with the same results.

**Comment by paulijar** [comment]
Those entries in the nextcloud.log are related to the Radio app, not the Music app. As a sanity check, you are experiencing the problem on the Music app and not on the Radio app, aren't you?

I wasn't expecting there to be anything of interest in the nextcloud.log. Instead, the playback errors can usually be found from the browser console. On Chrome and Firefox, you can open it by pressing the F12 key.

**Comment by michaeljalves** [comment]
Ok I uninstalled the Rdio app. Did F12 and went to console and found this.

Failed to load resource: net::ERR_CONNECTION_CLOSED
webpack.app.3c10265df54dc14d3706.js?v=f06a1be7-2:79 HTML5 audio: sound load
error
/apps/music/#/radio:1 Uncaught (in promise) DOMException: Failed to load
because no supported source was found.

**Comment by michaeljalves** [comment]
Some additional from the issues console in chrome:


   1. Content Security Policy of your site blocks the use of 'eval' in
   JavaScript`
   1.

      The Content Security Policy (CSP) prevents the evaluation of
      arbitrary strings as JavaScript to make it more difficult for an attacker
      to inject unathorized code on your site.

      To solve this issue, avoid using eval(), new Function(),
setTimeout([string],
      ...) and setInterval([string], ...) for evaluating strings.

      If you absolutely must: you can enable string evaluation by adding
      unsafe-eval as an allowed source in a script-src directive.

      ⚠️ Allowing string evaluation comes at the risk of inline script
      injection.
      2. AFFECTED RESOURCES
         1. 1 directive
         1.
            Source code Directive Status
            /apps/music/dist/web…f54dc14d3706.js:102 script-src blocked
         3.
         - Learn more: Content Security Policy - Eval
         <https://developers.google.com/web/fundamentals/security/csp#eval_too>
      2. 4
   Mixed content: load all resources via HTTPS to improve the security of
   your site
   1.

      Even though the initial HTML page is loaded over a secure HTTPS
      connection, some resources like images, stylesheets or scripts are being
      accessed over an insecure HTTP connection. Usage of insecure resources is
      restricted to strengthen the security of your entire site.

      To resolve this issue, load all resources over a secure HTTPS
      connection.
      2. AFFECTED RESOURCES
         1. 2 requests
         1.
            morow_med.mp3
            live.str3am.com
         2. 4 resources
         1.
            Name Restriction Status
            live.str3am.com:2010/ warned
            morow_med.mp3 warned
            morow_med.mp3 warned
            live.str3am.com:2010/ warned
         3.
         - Learn more: Preventing mixed content
         <https://web.dev/what-is-mixed-content/>

**Comment by paulijar** [comment]
Okay this output from Chrome seems to indicate that the problem is indeed one of those "usual suspects" mentioned in the troubleshooting: Your Nextcloud connection works on HTTPS but this stream URL uses plain HTTP. By default, the modern browsers block embedding such less secure content within the more secure page. You have to allow this separately if you want to do it.

On Chrome, press the padlock icon on the left side of the address bar and select "Site settings". Then find the option "Insecure content" and set its value to "Allow". Then try again to listen to the radio station.

On Firefox, the needed procedure is quite similar, but I can't remember the specific details.

**Comment by michaeljalves** [comment]
The setting was already set to allow. Morow plays now but not Aural Moon.

**Comment by paulijar** [comment]
What is the URL of Aural Moon? Can you play it directly by entering the stream URL to the web browser?

**Comment by michaeljalves** [comment]
URL is:

http://live.str3am.com:2010/

It will not play in Chrome or Edge but if I open it as a PLS file in JRiver
Media Player it plays fine.

**Comment by paulijar** [comment]
Aural Moon seems to be using a curious technical solution where the exact same URL serves a HTML page for the web browsers and audio stream for the players. Now, the Music app gets the HTML page which of course cannot be played. Apparently, the type of content returned depends on the user-agent string sent by the requester, and you should be able to bypass this by appending ; to the URL (by editing the PLS file before importing). See https://stackoverflow.com/questions/17221659/change-user-agent-of-audio-tag for a similar problem.

**Comment by michaeljalves** [comment]
Adding ";" did the trick. It works now. Thank you.
