### ISSUE TITLE
[Feature Request] Sort by albumartist/artistsort instead of artist tag

### ISSUE THREAD

**Issue by ksdrummer** [owncloud/music#825]
Hello,
I'm just trying out the music app on my nextcloud and I find it wonderful !

However, one important thing is missing  :
Most desktop/smartphone audio player are sorting artist by using the artistsort and/or albumartist tag if available, and then fall back to artist tag if not.

This is very useful to keep your music sorted by album. I just uploaded a compilation and I now have 13 artist with only 1 track in my library, which is not very convenient.

It would be so great if you could implement this !

Anyways, thank you for the good work, this app which is already great :clap:

**Comment by paulijar** [comment]
The Music app should be already utilizing the albumartist tag in the way you described. The artistsort and albumartistsort, on the other hand, are not currently used. But as there are many different ways to store the tags, it's possible that your files store the albumartist tag in some currently unsupported way. Could you share a sample file where this does not work for you? You can find my email address from my github profile.

**Comment by ksdrummer** [comment]
Yes sure !

**Comment by ksdrummer** [comment]
You're right, in the details I see "quodlibet::albumartist   Various Artists" 
I used quodlibet to tag the files.
This is strange because the other tags are also set with quodlibet but doesn't mention it on the tag name.

**Comment by ksdrummer** [comment]
Seems related to [this old quolibet bug](https://github.com/quodlibet/quodlibet/issues/1179). So I'll try to figure out another way to do it.

Music App rocks !

**Comment by paulijar** [comment]
So is the conclusion that no changes are needed for the Music app on this regard?

**Comment by ksdrummer** [comment]
Exactly, it was a quolibet related bug and not a missing feature of Music app. 
I added the missing albumartist tag to my files with kid3 and it is correctly displayed on my nextcloud. (Don't do it with easytag though, it destroys all the quolibet tags)

Music app is really great, thank you very much for the work done !
