### ISSUE TITLE
Enhancement : add desktop notification

### ISSUE THREAD

**Issue by Talw3g** [owncloud/music#828]
Hello,
I'm used to the desktop app "Musicbee" on win10, which displays a small notification when playing a new song with some basic info about it : album art, artist, song, year...
And I think it would be a nice feature to Music too ! I know NC already has the ability to display desktop notifications, so I'm hoping it's not too hard to implement... :)

Anyway, thank you for this wonderful app ! It does what it's supposed to, and it does it well !

**Comment by michaeljalves** [comment]
Internet radio stations also broadcast metadata showing Artist/Album/Song. It would be great to see that in the header if possible.

**Comment by paulijar** [comment]
@Talw3g Thanks for the suggestion. I'll try to find time to investigate this at some point. If such notification is added, it might be better to offer also a user-setting to opt out of it. I can imagine that some users would find it annoying, while they still would want to keep other desktop notifications from Nextcloud.

@michaeljalves Your request is separate from the original request here, and it is now followed in #829. But of course, if both the desktop notification would be added, and the song info from the radio station could be extracted, then also combining these two would make sense.

**Comment by paulijar** [comment]
The desktop notifications feature is now released in Music v1.2.0
