### ISSUE TITLE
Show artist/song information broadcasted by radio station

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#829]
Also (but this is another issue), the streamed webradio music title is displayed through VLC when playing, but does not appear and scroll horizontally in the web interface when playing from the Music app, so I unfortunately cannot see the title of the music that is playing.

_Originally posted by @TtuxX in https://github.com/owncloud/music/issues/779#issuecomment-782101234_

**Comment by TtuxX** [comment]
Hi there @paulijar ! :)

I hope you are doing fine !

Do you have by chance any update regarding this issue? I would love to see the titles of musics while listening to stations :)

Thank you very much again for your great work and sorry for the ping!

**Comment by paulijar** [comment]
Hi @TtuxX,

I agree that the feature would be cool. I did some googling on this last year but it seems that this might not be quite simple issue to solve. Apparently, there are at least two possible ways for the radio stations to deliver the song info: 
1. The more typical way would be to embed it within the audio stream at constant intervals, here is one explanation of how this works: https://stackoverflow.com/a/44090879
2. It's also possible that the metadata could be fetched separately by requesting the stream URL with different headers. But I couldn't find the link for this just now, and I'm not certain, how typical and/or standard this is.

The difficulty with the option 1 is that we utilize the services of the web browsers to stream and play the radio stations, and as far as I know, none of the browsers currently support extracting the metadata from those streams. I found a still open feature request for Firefox about this which was filed many years ago; I couldn't find it now though.

**Comment by medismail** [comment]
I implement the second method in this https://github.com/owncloud/music/pull/987, it is take information from stream with different headers, only limitation is that radio should support CORS.

**Comment by TtuxX** [comment]
Wow, thank you so much @medismail !! :)) Eagerly looking forward to testing this on the app !! Thank you again for your great time and work for us all !

**Comment by paulijar** [comment]
This feature is now released in Music v1.6.0. The app now supports four different mechanisms used by the radio stations to deliver the name of  the playing song. This should cover large majority of the stations which broadcast this kind of data. Feel free to open a new issue if you still can find a station where this doesn't work, and you are certain that the station in question does broadcast the metadata.
