### ISSUE TITLE
support for nextcloud 21

### ISSUE THREAD

**Issue by tob123** [owncloud/music#830]
Hello,

the music app is marked as untested on nextcloud 21.
after enabling it I found no issues yet, but perhaps you can share from your end whether nextcloud 21 is supported and update the app or release it accordingly on the nextcloud app store ?

thanks.

Tobias.

**Comment by paulijar** [comment]
Nextcloud 21 is not supported yet. When you try to reload the app after the initial load, it should fail. Unfortunately, Nextcloud has broken their API again, and some cumbersome changes are needed to the Music app to properly support NC21. Combine that with the fact that I'm busy with other duties in my life for the next few days, and we come to conclusion that it will probably take 1-3 weeks before NC21 can be supported.

As a general advise, it is usually better to refrain from updating to Nextcloud version X.0.0, unless you are adventurous in mind. The philosophy of NC seems to be to "move fast and break things" and the apps can't hold along. Things will often start to stabilize some 1-2 months after the initial release "X", and then the release "X+1" is already right around the corner, breaking things again.

**Comment by tob123** [comment]
hello paulijar, thanks.
yes, you are right. trying out things with the promised performance improvements tempted me to upgrade.

**Comment by JoshuaPettus** [comment]
Seeing as this is the most important app for me, I will definitely hold off till at least you are good :)

**Comment by paulijar** [comment]
> One question though, would PHP 8 be an issue for Music as well?

Music has not been tested with PHP 8. It may or may not work. But I just checked through a list of incompatible changes between PHP 7.4 and PHP 8, and I couldn't immediately notice anything which would affect us. One open question is the compatibility of the getID3 library (used for metadata extraction) with PHP8; I don't know its sources well enough to tell if it uses any of those incompatible constructs.

**Comment by JoshuaPettus** [comment]
Kinda putting the cart before the horse anyway. :)

**Comment by tob123** [comment]
hello, i am on php 7.3 and have no issues using the plugin. as far as I understand nextcloud-server supports 7.3,7,4 and 8 and higher; but does not require php 8.

**Comment by JoshuaPettus** [comment]
Nope it doesn't,  that's just one of the promised performance avenues with NC21 that I'd like to look into later. But it's relatively easy to switch between versions of PHP, can't downgrade an NC server. XD

**Comment by paulijar** [comment]
Version 1.0.3 with support for NC21 is now out! 

The new version should work also with PHP 8.0. I haven't actually manually tested this configuration, but the automated tests on the test server succeeded also with PHP 8.0. In those tests, a few mp3 files with metadata tags are scanned with `occ music:scan`, and then the library is browsed in various ways using the Ampache and Subsonic APIs. As all of this worked without issues, this is a pretty strong sign that at least the basic use cases function as intended. But if you see any problems, then please open new issues.

**Comment by JoshuaPettus** [comment]
Thank you so much for all you do!

**Comment by JoshuaPettus** [comment]
Just wanted to let you know it works great.  I'm now using it on NC21 with PHP8.0 no issues!  (Can't say the same for NC21 XD. There is a fun gotcha with a memory leak in OCC if PHP doesn't have the right setting: apc.enable_cli=1 in /etc/php/X.X/cli/conf.d/20-apcu.ini for those interested.)

**Comment by Gomez** [comment]
Unfortunately it does not work for me: https://github.com/owncloud/music/issues/838

**Comment by moviuro** [comment]
> There is a fun gotcha with a memory leak in OCC if PHP doesn't have the right setting: apc.enable_cli=1 in /etc/php/X.X/cli/conf.d/20-apcu.ini for those interested.)

Has this been documented on the nextcloud project?

**Comment by JoshuaPettus** [comment]
https://github.com/nextcloud/server/issues/25742

**Comment by Gomez** [comment]
But this is unrelated to my reported bug. I have apc.enable_cli=1 in my config. Still broken Nextcloud after enabling music.

**Comment by JoshuaPettus** [comment]
No, It has nothing to do with your issue,  just answering moviuro's question
