### ISSUE TITLE
Nextcloud 21: Failed to load collection. Internal server error

### ISSUE THREAD

**Issue by michaeljalves** [owncloud/music#831]
Received this shortly after updating. Logging shows the following:
{"reqId":"DGmEIP1zkRoRg7smracs","level":3,"time":"2021-02-22T11:40:07-08:00","remoteAddr":"192.168.1.1","user":"alves","app":"index","method":"POST","url":"/apps/music/api/prepare_collection","message":{"Exception":"OC\\DB\\Exceptions\\DbalException","Message":"An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"music_cache_index\"\nDETAIL:  Key (user_id, key)=(alves, cover_access_token) already exists.","Code":7,"Trace":[{"file":"/var/www/nextcloud/lib/private/DB/ConnectionAdapter.php","line":77,"function":"wrap","class":"OC\\DB\\Exceptions\\DbalException","type":"::"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":34,"function":"executeUpdate","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":55,"function":"add","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/CoverHelper.php","line":331,"function":"set","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Controller/ApiController.php","line":142,"function":"createAccessToken","class":"OCA\\Music\\Utility\\CoverHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"prepareCollection","class":"OCA\\Music\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/DB/Exceptions/DbalException.php","Line":70,"Previous":{"Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Message":"An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"music_cache_index\"\nDETAIL:  Key (user_id, key)=(alves, cover_access_token) already exists.","Code":7,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1146,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1747,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":236,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/ConnectionAdapter.php","line":75,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":34,"function":"executeUpdate","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":55,"function":"add","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/CoverHelper.php","line":331,"function":"set","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Controller/ApiController.php","line":142,"function":"createAccessToken","class":"OCA\\Music\\Utility\\CoverHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"prepareCollection","class":"OCA\\Music\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php","Line":55,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"music_cache_index\"\nDETAIL:  Key (user_id, key)=(alves, cover_access_token) already exists.","Code":7,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1138,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1747,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":236,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/ConnectionAdapter.php","line":75,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":34,"function":"executeUpdate","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":55,"function":"add","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/CoverHelper.php","line":331,"function":"set","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Controller/ApiController.php","line":142,"function":"createAccessToken","class":"OCA\\Music\\Utility\\CoverHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"prepareCollection","class":"OCA\\Music\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"music_cache_index\"\nDETAIL:  Key (user_id, key)=(alves, cover_access_token) already exists.","Code":"23505","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1138,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1747,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":236,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/ConnectionAdapter.php","line":75,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":34,"function":"executeUpdate","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Db/Cache.php","line":55,"function":"add","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/CoverHelper.php","line":331,"function":"set","class":"OCA\\Music\\Db\\Cache","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Controller/ApiController.php","line":142,"function":"createAccessToken","class":"OCA\\Music\\Utility\\CoverHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"prepareCollection","class":"OCA\\Music\\Controller\\ApiController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36","version":"21.0.0.18","id":"603411dab7e24"}

and after rescanning:

{"reqId":"ZJ632PCiuvwzK57np17y","level":3,"time":"2021-02-20T14:28:35-08:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"filesize(): stat failed for /luvisi/files/Music/Deep Purple/Deep Purple - Made In Japan [96kHz-24bit] 2014 [WAV](oan)/14 - Space Truckin' [Osaka - 16th August 1972].wav at /var/www/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#468","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php","line":468,"function":"filesize"},{"file":"/var/www/nextcloud/apps/music/3rdparty/getID3/getid3/module.audio-video.riff.php","line":1273,"function":"openfile","class":"getID3","type":"->"},{"file":"/var/www/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php","line":636,"function":"Analyze","class":"getid3_riff","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/ExtractorGetID3.php","line":74,"function":"analyze","class":"getID3","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/Scanner.php","line":183,"function":"extract","class":"OCA\\Music\\Utility\\ExtractorGetID3","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/Scanner.php","line":134,"function":"extractMetadata","class":"OCA\\Music\\Utility\\Scanner","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Utility/Scanner.php","line":109,"function":"updateAudio","class":"OCA\\Music\\Utility\\Scanner","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/music/lib/Utility/Scanner.php","line":481,"function":"update","class":"OCA\\Music\\Utility\\Scanner","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/music/lib/Command/Scan.php","line":117,"function":"scanFiles","class":"OCA\\Music\\Utility\\Scanner","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Command/Scan.php","line":91,"function":"scanUser","class":"OCA\\Music\\Command\\Scan","type":"->"},{"file":"/var/www/nextcloud/apps/music/lib/Command/BaseCommand.php","line":63,"function":"doExecute","class":"OCA\\Music\\Command\\Scan","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\Music\\Command\\BaseCommand","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/occ","line":11,"args":["/var/www/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.0.18","id":"6034133749dba"}

**Comment by paulijar** [comment]
Nextcloud 21 is not supported yet. There is already one issue opened for this: #830
