### ISSUE TITLE
Option to sync playlists with playlist files/folder

### ISSUE THREAD

**Issue by manuke42** [owncloud/music#832]
Hello, would it be possible to add some option to sync the changes of a playlist made in the Music app with a m3u file in the Files app?

I have many playlists and would have to export every one of them to a file to backup. Additionally i like to sync my music to my computer and get the latest playlist there too to work with local m3u players (i already like that the m3u files use relative paths, when they are exported from Music app). Maybe to make it more complete there could be an optional folder created in the Files app where the playlists are automatically synced?

**Comment by paulijar** [comment]
Maybe this kind of "advanced" option would be more suitable to be available on the command line with the `occ` tool 🤔. A cron job could then be set up to run it periodically. Not terribly handy, but on the other hand, this might not be so commonly used feature that it would justify sinking all the work needed to design and implement a new UI feature.

**Comment by paulijar** [comment]
Music v1.4.1 is now out, bringing the `occ` commands `playlist-export` and `playlist-import`. The OP's requirement should be fulfilled by running the former with the arguments `--all-lists` and `--overwrite`. To do this periodically, a cron job should be set up.

**Comment by M1scer** [comment]
I am just trying to get the playlist-import running. I want to import all playlists (.m3u) in a specific folder.
But i can not get the occ command running.

The command i tried (to import at least one playlist):
`sudo -u www-data php occ music:playlist-import --group admin --file "/Path/to/Playlist.m3u"`
I always get "Invalid file path" error but i am sure the path is correct.

And how do i import all lists in a folder?

A few examples of running the command would be helpful for me.

**Comment by paulijar** [comment]
@M1scer Sorry, importing all lists in a folder is not implemented for now. But you can import several lists with a single command by listing them one-by-one, by giving multiple `--file` arguments.

The path to the file should be given relative to the home folder of the user within the cloud file system. It doesn't matter if you prefix the path with `/` or not, the path is always resolved in relative manner.

**Comment by M1scer** [comment]
@paulijar is this planned to be added?

Thank you, now it is working fine. i tried it with a absolute path before.

**Comment by paulijar** [comment]
> is this planned to be added?

Possibly. Ideally, I'd like to have it so that the `--file` argument would support wildcard characters, enabling importing e.g. `some/path/*.m3u`.

**Comment by paulijar** [comment]
@M1scer The newly released Music v1.5.0 now allows using wildcard characters `*` and `?` in the `--file` argument of `occ music:playlist-import`. With this, it is possible to import e.g. all the playlist files from a certain folder.
