### ISSUE TITLE
PHP filesize(): stat failed .../getid3.php (when accessing through play:Sub)

### ISSUE THREAD

**Issue by numerfolt** [owncloud/music#837]
Hey there, this is my first issue here, so I tried to stick to the owncloud issue template (at least a bit).

**Steps to reproduce**
I connected to the subsonic server of my Nextcloud music installation using play:Sub on an iPhone.
In play:Sub I navigate to random folders of my library and the content is loaded.

**Expected behaviour**
Regardless of browsed folder there are no errors logged in my nextcloud and I can browse my whole music collection without problems.

**Actual behaviour**
(Apparantly) randomly this error pops up in my Nextcloud:
`Error: filesize(): stat failed for /username/path/to/song/17 Chanson d'Automne.wav at /var/www/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#468`
The music file's path and file itself are interchangeable although it seems to only happen to .wav files.
After that, I cannot browse the folder in the app anymore. It is displayed as being empty (although it definitively isnt).
I can see the folder content only after I remove and add the server again in the app.

**Additional Information**
The files where this error is displayed (when trying to access it from the app) are all at least 10MB in size. Most of them rather 20-50MB.

**Server configuration**
Operating system: Linux 5.10.17-v8+ aarch64 (NextCloudPi v1.35.0)
Nextcloud version: 20.0.4.0
Music version: 1.0.3
Web server: Apache 2
PHP version: 7.3

It could be a problem with the app (that's what I initially thought) as the error is just appearing when I try to access the music through the app. But why would the error pop up in my Nextclouds log if it was a problem of only the iPhone app.
Thanks in advance for any time and help!

**Comment by paulijar** [comment]
Thanks for the report. According to the error shown, something goes wrong when the getID3 library tries to parse the file. As I see it, there are only two occasions where the getID3 library is used as a result for an action from the Subsonic API: when getting song lyrics and when getting album art. Now I suspect that the error happens with the latter.

If you try to view the details of one of the reported problem files through the Music app web UI, then does that work? And is there any errors in the log in that case?

**Comment by numerfolt** [comment]
Hi, viewing the details and playing the songs does work. 
From what I have tested thanks to your idea, it seems to only affect .wav files regardless of size. 
No .flac or other large files threw the error. But all .wav files I pressed the "i" on threw it.
Oh, and it didnt matter whether they had thumbnails on them or not, so it's probably already when it tries to get the album art.
Thanks :)

**Comment by paulijar** [comment]
I could now also reproduce this error being logged when I viewed the data of a test wav file. So probably there isn't anything special in your wav files, but this now happens with all files of that type. I'll investigate this further later when I have time.

**Comment by numerfolt** [comment]
Ok, that's good to know, thanks!
In the meantime I'll just try to convert all the wav files to flac and see whether my problem with the app is fixed by that. 
I'll let you know as it could be interesting whether the logged error was the problem or not.

**Comment by numerfolt** [comment]
The problem with my app was fixed by converting all the music to .flac
Therefore it seems like the getID3 error was the cause for the problems I have. 
I'd gladly check again with .wav as soon as the error is fixed to make sure that it was the cause.
Thanks again :)

**Comment by paulijar** [comment]
Music v1.1.0 with fixed getID3 is now released. At least it no longer prints those `stat failed` errors but does it solve your actual problem?

**Comment by numerfolt** [comment]
I'm gonna check. 
I havent had the problem without .wav files, so I'm going to add some to the library, check if the problem is back (and the error message). 
If the problem is back, I will update the app and let you know the result.
