### ISSUE TITLE
long pauses between tracks

### ISSUE THREAD

**Issue by sureloc** [owncloud/music#841]
Don't know exactly when it started, but I've noticed that the pauses between songs (both when playing albums and on shuffle) have gotten longer, and are now several seconds, whereas before playback was almost gapless. 
Does this have something to do with Nextcloud 20 vs 21 or php versions? I'm on NC 20.0.8 with Nextcloudpi on a rpi 4.
It's more of a first world problem tbh, but still a bit annoying when it used to be faster...
Anyway, thanks for a great app!

**Comment by jthaman** [comment]
I just noticed this as well. I have the same setup: NextCloudPi and an Rpi 4. I don't think there were such long pauses when I started using Music.

**Comment by paulijar** [comment]
Thanks for the report. The method used to stream the music was changed slightly in Music v1.0.0 but was supposed to improve the performance if anything. But mostly it was just made to simplify the logic.

Personally, I haven't noticed the degradation of performance. But now when I tested it a bit, it seemed to me that changing the track took some more time on Chrome than on Firefox. Which browser are you using?

**Comment by sureloc** [comment]
I tested with a stopwatch on both Chrome (my main browser) and Firefox, no big difference between them. It takes between 7 and 15 seconds to start actual playback, even though the track name and album art changes immediately when clicking the next track button. Same on Chrome mobile.
Also, the music collection is on an SSD so drive speed shouldn't be an issue. Would rescanning the library help, or is there some other issue behind this?

**Comment by jthaman** [comment]
Thanks for your work on this project. It is definitely the most exciting thing to happen to my 15 year old mp3 collection in quite some time!!

I'm using both Firefox and Brave to access Nextcloud Music. I have not tried a mobile client.

**Comment by sureloc** [comment]
I added a new album today, which triggered a scan, and after that performance seems to be back to normal. 
Thanks again and sorry for wasting your time.

**Comment by paulijar** [comment]
@sureloc Rescanning the library should make no difference here. Probably it is something else which has caused the improvement in performance.

One possibility is that previously your server was busy serving the album art while the song change occurred. This could delay the start of the playback. The album art needs to be loaded again always after installing a new version of Music because the cache is then cleared, just in case. But after it has been loaded once, then it should be cached, and the performance is improved for the subsequent times of use.

**Comment by paulijar** [comment]
I guess there is no longer need to keep this issue open.
