### ISSUE TITLE
Subsonic Soundwaves Client - Soundwaves FLAC issue resolved

### ISSUE THREAD

**Issue by atkinsom** [owncloud/music#850]
Hi,

Just to let you know that the subsonic Soundwaves app now works with FLAC. I worked with the dev to test and resolve the FLAC file problem. The latest download from the Apple App Store is available. Thanks for a great app once again.
https://github.com/owncloud/music/wiki/Subsonic

Milenko

**Comment by paulijar** [comment]
Thanks for the info! I removed the note about the FLAC problem from the wiki.
