### ISSUE TITLE
Error message in Log file

### ISSUE THREAD

**Issue by RandomBloke85** [owncloud/music#855]
Hello

Let me first thank you again, for this really cool and reliable app and all the effort and work you put in there. It is much appreciated.

On my Android, I tried out a couple of free clients. All work fine, but I think DSub (latest version) and Ultrasonic work best.

However, I just checked my Error Log on Nextcloud and find this error message on a daily basis. Probably generated, each time I call the database. I don't understand too much of this, but it seems, like there is declaration error?

Argument 1 passed to OCA\\Music\\AppFramework\\BusinessLayer\\BusinessLayer::findOrDefault() must be of the type int, null given, called in /usr/local/www/nextcloud/apps/music/lib/Controller/SubsonicController.php on line 1126","Code":0,"Trace":

`{"reqId":"kZHBN22ohmfGpFLq804u","level":3,"time":"2021-05-04T09:32:13+00:00","remoteAddr":"192.168.*.**","user":"--","app":"index","method":"GET","url":"/index.php/apps/music/subsonic/rest/getPlaylist.view?u=ncboss&p=enc:6f7661777472626e66666a38&v=1.2.0&c=DSub&id=5","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\Music\\AppFramework\\BusinessLayer\\BusinessLayer::findOrDefault() must be of the type int, null given, called in /usr/local/www/nextcloud/apps/music/lib/Controller/SubsonicController.php on line 1126","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Music\\AppFramework\\BusinessLayer\\BusinessLayer::findOrDefault() must be of the type int, null given, called in /usr/local/www/nextcloud/apps/music/lib/Controller/SubsonicController.php on line 1126","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps/music/lib/Controller/SubsonicController.php","line":1126,"function":"findOrDefault","class":"OCA\\Music\\AppFramework\\BusinessLayer\\BusinessLayer","type":"->"},{"function":"trackToApi","class":"OCA\\Music\\Controller\\SubsonicController","type":"->"},{"file":"/usr/local/www/nextcloud/apps/music/lib/Controller/SubsonicController.php","line":526,"function":"array_map"},{"file":"/usr/local/www/nextcloud/apps/music/lib/Controller/SubsonicController.php","line":156,"function":"getPlaylist","class":"OCA\\Music\\Controller\\SubsonicController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"handleRequest","class":"OCA\\Music\\Controller\\SubsonicController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/apps/music/lib/AppFramework/BusinessLayer/BusinessLayer.php","Line":93},"CustomMessage":"--"},"userAgent":"DSub","version":"21.0.1.1","id":"6095230b38b30"}`

**Comment by paulijar** [comment]
The logged error message is the same as on https://github.com/owncloud/music/issues/853; do you possibly have the same situation? That is, does one of your playlists contain at least one broken/obsolete link to a track which doesn't exist? The Subsonic API implementation was missing some sanity checks, and it couldn't handle such playlists at all. I fixed this issue just yesterday, so probably your problem will be fixed, too, with the next release of the Music app.

**Comment by RandomBloke85** [comment]
Hi Pauli

In my case I just choose a composer, then an album and played it. I did not played a playlist. I know, in the end I always play a playlist, but I did not choose a playlist in the first place. And there was no missing file in it.

Maybe if played remotely and looses the connection for a moment or runs out of buffer, it generates the error? I use DSub mostly outside my LAN (in a train or the gym 😊).

I never noticed the error anyway, since everything works and plays just fine. I just found it in the Nextcloud log file a couple of times a day and thought it might be relevant.

**Comment by paulijar** [comment]
No, this definitely has nothing to do with losing connection. But if you have never seen anything go wrong, then the likely explanation is that you have "Sync Enabled" ticked in your DSub settings. When this is the case, DSub will periodically fetch all you playlists to check if there are any changes. Now, if any one of those playlists would have a broken file link, then fetching that list would fail and error like that would be logged.

I assume, that if you try to open each of your playlists in DSub for viewing, one-by-one, then you will find one which will not open.

**Comment by RandomBloke85** [comment]
Alright, you were spot on: Yes, "Sync Enabled" is ticked and yes, 3 out 20+ playlists didn't load due to an error (changed file on server and didn't updated the playlist). So I made my homework and will report back, if the error went away. Thank you.

**Comment by paulijar** [comment]
The fix for this problem has now been released in Music v1.2.0.
