### ISSUE TITLE
Cannot upgrade to latest version, Undefined table: 7 ERROR:  relation "oc_music_albums" does not exist

### ISSUE THREAD

**Issue by mrzapp** [owncloud/music#868]
When trying to update to the latest version, I get an error and cannot proceed.

* Nextcloud is v21
* Postgres is v13, all oc_music_* tables dumped, but same thing happened with them present

This is the error log:

```
[settings] Error: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'UPDATE "oc_music_albums" SET "created" = ? WHERE "created" IS NULL' with params ["2021-06-28 07:41:55"]:

SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oc_music_albums" does not exist
LINE 1: UPDATE "oc_music_albums" SET "created" = $1 WHERE "created" ...
               ^ at <<closure>>

 0. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException("An exception oc ... ^", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 149
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... ^")
 2. /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1071
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOPgSql\Driver {}, Doctrine\DBAL\Dr ... ]}, "UPDATE \"oc_mus ... L", {1: "2021-06-28 07:41:55"})
 3. /var/www/html/lib/private/DB/Connection.php line 222
    Doctrine\DBAL\Connection->executeUpdate("UPDATE \"oc_mus ... L", ["2021-06-28 07:41:55"], [null])
 4. /var/www/html/custom_apps/music/lib/Migration/TimestampInit.php line 60
    OC\DB\Connection->executeUpdate("UPDATE \"oc_mus ... L", ["2021-06-28 07:41:55"])
 5. /var/www/html/custom_apps/music/lib/Migration/TimestampInit.php line 51
    OCA\Music\Migration\TimestampInit->setCreated("*PREFIX*music_albums", "2021-06-28 07:41:55")
 6. /var/www/html/lib/private/Repair.php line 111
    OCA\Music\Migration\TimestampInit->run(OC\Repair {})
 7. /var/www/html/lib/private/legacy/OC_App.php line 1042
    OC\Repair->run()
 8. /var/www/html/lib/private/Installer.php line 160
    OC_App::executeRepairSteps("music", ["OCA\\Music\\Mi ... "])
 9. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 448
    OC\Installer->installApp("music")
10. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Settings\Controller\AppSettingsController->enableApps(["music"], [])
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
12. /var/www/html/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
13. /var/www/html/lib/private/Route/Router.php line 309
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
14. /var/www/html/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/enable")
15. /var/www/html/index.php line 37
    OC::handleRequest()

POST /index.php/settings/apps/enable
from 172.19.0.1 by admin at 2021-06-28T07:41:55+00:00
```

**Comment by paulijar** [comment]
Thanks for the report.

Did you get that exact same error message also before dropping the oc_music_* tables? Because it's likely that you will get something like shown above if you drop the tables after half-way successful installation; NC may already have marked in its internal book keeping that the database tables for Music v1.2.1 have been created, and it will not do that again for the same version. Then, you will get an error about missing table on the later installation steps.

But getting that kind of error is highly unexpected if updating over a working previous installation of Music. The message states that the table `oc_music_albums` was not found but this table has existed from the very first version of the app.

Which version of the Music app did you have installed before attempting to update to v1.2.1?

**Comment by mrzapp** [comment]
Dang, I don't know. I should have taken note of that before removing the app.

In any case, I have now uninstalled the app and removed all relevant tables from my database, but I'm still getting that error when trying to install from scratch. Do I need to weed out anything else to get a completely clean slate?

**Comment by paulijar** [comment]
This would probably help:
`delete from oc_migrations where app='music';`
With that, the database tables should get recreated on the next app installation attempt.

Also this might be useful on some installation problems:
`delete from oc_appconfig where appid='music';`
Among other thing, the `oc_appconfig` table stores the information about the currently installed app versions. But my best guess is that this is not actually necessary in your case.

**Comment by mrzapp** [comment]
Yeah, removing the migration rows was enough to allow me to reinstall the app.

Good enough for me. My NextCloud instance is about 5 years old, so I'm not surprised stuff like this would happen sooner or later.

I'm probably a fringe case, so I'll just close the issue. Thanks for the tip!
