### ISSUE TITLE
Play playlist from android/IOS app

### ISSUE THREAD

**Issue by adosix** [owncloud/music#870]
Would be great to be able to play exported playlists from IOS/Android app,. Anyway GREAT app, thanks for developing it :1st_place_medal: :heart:  .

**Comment by paulijar** [comment]
Sorry, I didn't quite understand the request. Which iOS/Android app are you talking about? If you set up the Ampache/Subsonic connection, then you can select from many Android apps (and probably one or a few iOS apps) which can play your playlists.

**Comment by adosix** [comment]
> Sorry, I didn't quite understand the request. Which iOS/Android app are you talking about? If you set up the Ampache/Subsonic connection, then you can select from many Android apps (and probably one or a few iOS apps) which can play your playlists.

I meant from nextcloud app.

**Comment by paulijar** [comment]
Okay, that's reasonable, but out-of-scope for the Music app. What the Nextcloud app can or cannot do with the files, depends solely on the capabilities of the Nextcloud app. The Music app has no way to augment those capabilities. So you should probably request in the [Nextcloud Android app github](https://github.com/nextcloud/android) that they would add support for playing the m3u8 playlist files.
