### ISSUE TITLE
api/scanstate returns Error 500 when scanning a big collection

### ISSUE THREAD

**Issue by msartiano** [owncloud/music#871]
Hello All,

**Overview:**
OS: Ubuntu 20.04 on Windows WSL
Software: Nextcloud 22
Music version: latest as of today
Setup: I have my music mounted in an external drive and it is accessible via files correctly.

**Problem:**
When adding an external drive folder with few songs, I can see a "Start scan" button in the Music App.
When adding an external drive folder with many songs, i.e. 10-50k, I don't see any "Start scan" button in the Music App.
With a big collection, I also get the following in the console.log:

```
XHRGET http://mydomain.com/index.php/apps/music/api/scanstate [HTTP/1.0 500 Internal Server Error 611ms]
```
```
Possibly unhandled rejection: {"data":"","status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","headers":{"requesttoken":"HBg7qPXxAUzndVgj3N/CA0XdDWY81rTX23jSRkfLbSw=:TWBJ+N6AeH2mDQoM5J6POxGvfiF0moy8iR3mPBOPOk0=","Accept":"application/json, text/plain, */*"},"url":"/index.php/apps/music/api/scanstate"},"statusText":"Internal Server Error","xhrStatus":"complete"} webpack.app.4edf41907fd4207c4fe7.js:102:79517
    s webpack.app.4edf41907fd4207c4fe7.js:102
    get webpack.app.4edf41907fd4207c4fe7.js:102
    c webpack.app.4edf41907fd4207c4fe7.js:102
    $digest webpack.app.4edf41907fd4207c4fe7.js:102
    $apply webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    A webpack.app.4edf41907fd4207c4fe7.js:102
    onload webpack.app.4edf41907fd4207c4fe7.js:102
    (Asinc.: EventHandlerNonNull)
    get webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    $digest webpack.app.4edf41907fd4207c4fe7.js:102
    $apply webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    A webpack.app.4edf41907fd4207c4fe7.js:102
    onload webpack.app.4edf41907fd4207c4fe7.js:102
    (Asinc.: EventHandlerNonNull)
    get webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    $digest webpack.app.4edf41907fd4207c4fe7.js:102
    $apply webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    A webpack.app.4edf41907fd4207c4fe7.js:102
    onload webpack.app.4edf41907fd4207c4fe7.js:102
    (Asinc.: EventHandlerNonNull)
    get webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    $digest webpack.app.4edf41907fd4207c4fe7.js:102
    $apply webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    A webpack.app.4edf41907fd4207c4fe7.js:102
    onload webpack.app.4edf41907fd4207c4fe7.js:102
    (Asinc.: EventHandlerNonNull)
    get webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    k webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    $digest webpack.app.4edf41907fd4207c4fe7.js:102
    evalAsync webpack.app.4edf41907fd4207c4fe7.js:102
    completeTask webpack.app.4edf41907fd4207c4fe7.js:102
    r webpack.app.4edf41907fd4207c4fe7.js:102
    (Asinc.: setTimeout handler)
    defer webpack.app.4edf41907fd4207c4fe7.js:102
    $evalAsync webpack.app.4edf41907fd4207c4fe7.js:102
    get webpack.app.4edf41907fd4207c4fe7.js:102
    d webpack.app.4edf41907fd4207c4fe7.js:102
    then webpack.app.4edf41907fd4207c4fe7.js:102
    b webpack.app.4edf41907fd4207c4fe7.js:102
    o webpack.app.4edf41907fd4207c4fe7.js:120
    I webpack.app.4edf41907fd4207c4fe7.js:120
    t webpack.app.4edf41907fd4207c4fe7.js:1
    D webpack.app.4edf41907fd4207c4fe7.js:120
    rt webpack.app.4edf41907fd4207c4fe7.js:1
    t webpack.app.4edf41907fd4207c4fe7.js:1
    selectPath webpack.app.4edf41907fd4207c4fe7.js:96
    _ dialogs.js:475
    click dialogs.js:481
    jQuery 15
```

Please let me know if you require further information.
Do you know what could be the cause and how to start scanning my music collection, or a possible workaround?

Alternatively, is there a way to manually scan the music via ssh? I am using Ubuntu on WSL and I can't find where the music scan executables are, maybe you can help?

Thank you!

**Comment by paulijar** [comment]
Thanks for the report. Can you find any more details from the nextcloud.log on your server? My best guess is that you are hitting the PHP `memory_limit` as set in php.ini. I have scanned 60k+ libraries without increasing the limit from the default 128M, but using the external storage may be different. Also, total number of files the user has on the cloud may increase the amount of memory needed, and there is also variation between the different Nextcloud and ownCloud versions.

Scanning from the command line is possible using the `occ` tool found from the Nextcloud root folder. If your web server uses the username "www-data", then the command given in the nextcloud root folder will be something like
`sudo -u www-data ./occ music:scan your_user_name`.
But if `memory_limit` is the problem, then you will likely run into the same problem also from the command line.

Note that if you are using PHP-FPM, then the instance of php.ini used by the web server is distinct from the one used by the command line.

**Comment by msartiano** [comment]
Alright, I have added a <?php phpinfo( ); ?> directly in the directory where nextcloud is, and here's what I get: `memory_limit | 128M | 128M`.

I have then modified the memory limit in `/etc/php/7.4/apache2/php.ini` and restarted the service, and now 20k songs are being scanned, that's great!
I will update if it won't work or if anything interesting is found.

In any case, what happens if I add 10 more songs tomorrow, do I need to apply a rescan, and how? Will it auto rescan on a cron job basis?

Thanks for your time and support, that really helped @paulijar .

**Comment by paulijar** [comment]
>In any case, what happens if I add 10 more songs tomorrow, do I need to apply a rescan, and how? Will it auto rescan on a cron job basis?

After the initial scan, the music library should be kept up-to-date automatically. The Music app should get an event from the Nextcloud server whenever a new file is added, and if that is an audio file, then it will be scanned in the background. This is the theory, in practice this may not work so smoothly in case you are using the external storage feature of Nextcloud. It depends also on the type of the external storage and how it has been set up, but on many external storages, Nextcloud does not automatically detect changes. It detects those only once you navigate to the folder or run `occ files:scan`. But once the server detects the change, then it should get scanned by Music, too.

If, for some reason, the server would not notify Music when a new file is detected, then you will get a prompt about unscanned files the next time you open the Music app. That's actually what the `music/api/scanstate` is all about: It compares the set of scanned files to the set of all existing audio files under you library path. If the diff of these sets is not empty, then you will be prompted to scan the files belonging to the diff.

**Comment by msartiano** [comment]
Thanks, I have one more question, ./occ gives me `sudo: ./occ: command not found` - would you be able to suggest what is the default location, as I can't seem to find it inside the `apps/music` folder of Nextcloud?

Just for curiosity and if it may help, the 'external drive' in Nextcloud is a local NTFS hard drive in my machine, that is internal and will never change unless upgraded or malfunctioning.

**Comment by paulijar** [comment]
The `occ` tool should be found from the root directory of nextcloud, not under the music app folder. That is, the tool itself is part of the nextcloud default installation, and the Music app just augments it with some new commands. You probably need to manually give the file the execution right bit before running it.

If your 'external drive' is actually a local directory on your server, then you should not have the problems I mentioned earlier. Those should happen only when the storage is truly external like some SMB share on another server or an Amazon S3 storage.

**Comment by msartiano** [comment]
Thanks, I confirm for the future people in similar WSL situations, that `/var/www/nextcloud/occ` is one plausible location.
Agree completely with you, I'd expect Samba drives not to have sync, but given that it is an internal drive, I would expect these events to bubble naturally, and that' why I specified.
Perfect, all sorted from my side, thank you @paulijar for the interesting discussion and proactive help and long life.
I will close this as I believe there's no more to specify, thanks.

**Comment by msartiano** [comment]
The issue above is sorted by increasing the PHP Memory limit.
To find where your php installation is, place a `info.php` file with the content `<?php phpinfo( ); ?>` and have a look.
Then modify the `php.ini` file, in my case stored in `/etc/php/7.4/apache2/php.ini` by increasing it, I did from `128M` to `512M` and it works.
