### ISSUE TITLE
m3u8 radio stations don't work

### ISSUE THREAD

**Issue by msartiano** [owncloud/music#872]
Hello,

the following stream works: https://ice08.fluidstream.net/KKItalia.aac
the following doesn't: https://radiouno1-lh.akamaihd.net/i/radiouno1_1@586814/index_128000_a-p.m3u8

Most of the streams I find online are in m3u8 format, VLC reads both of the above formats.
I wonder if Music reads only the first format, and what are the compatible streams, thank you.

**Comment by paulijar** [comment]
The streams with the m3u8 extension are what is known as HLS type stream. The following section under the Settings > Admin is relevant here:
![image](https://user-images.githubusercontent.com/8565946/126076630-a3393c96-a638-4826-92b9-c4fb87b318ca.png)

That is, you need to specifically make holes to the content-security-policy to allow streaming such stations on the web browser. On your example station, you can achieve this by adding the following line to the file `nextcloud/config/config.php`:
`'music.allowed_radio_hls_src' => ['https://radiouno1-lh.akamaihd.net'],`

To define multiple allowed sources, the syntax would be like
`'music.allowed_radio_hls_src' => ['source1', 'source2', 'source3'],`

If you want to, you can also allow any source by specifying
`'music.allowed_radio_hls_src' => ['http://*:*', 'https://*:*'],`

As the CSP is just the last line of defense, you would probably be fine even when allowing all the sources. But frankly, I don't understand the whole CSP business well enough to say anything definitive. That's also why I opted for safety on the default settings: If there is even a theoretical chance that loosening the CSP will undermine security, then that should not happen automatically but only on the full consent of each individual server administrator.

**Comment by msartiano** [comment]
That was exactly what I was looking for, thank you for the help!
Interesting point also regarding the defense line, something to investigate.

**Comment by paulijar** [comment]
Okay, great! I believe this issue can be closed then.
