### ISSUE TITLE
Compatibilty with compilations.

### ISSUE THREAD

**Issue by helloha82** [owncloud/music#874]
Love the development and freedom from online streaming services!

One feature I could digg is compatibility with albums containing compilations from different artists/composers.

Right now they show up as different albums for each track individually.

Thx for the good work!

**Comment by paulijar** [comment]
The multi-artist albums can already be handled gracefully, but that requires that the tracks of the album have the tag *Album artist* set. You can set it as "Various artists" or whatever you like, as long as all the tracks of the album have the same value. Then, the *Album artist* will be used as ordering criterion in the Albums view while the actual performing artist, as saved in the *Artist* tag (*), is still shown next to the track name. 

(*) The *Artist* tag may be called also *Artist name* or *Track artist* or *Contributing artist* or something similar, depending on the software used.
