### ISSUE TITLE
[FR] predefine the exclude path when setting it

### ISSUE THREAD

**Issue by mmattel** [owncloud/music#876]
When you set the path to your music collection, you define the root path for the audio files.
When defining an exclude path, you get again the full list of mounts.

This FR is about that an exclude path must be inside the collection path and therefore the list of possible selectable paths must not show all mounts but only all folders inside the collection path defined before.

**Comment by paulijar** [comment]
The excluded folder picker UI component has now been set to be opened with the configured music library path as the initial path. This change will be included in the Music v1.3.0 once that's published.

The limitation is that this is possible only on Nextcloud and only with versions 16 and later. On ownCloud and older versions of Nextcloud, the filepicker dialog provided by the core does not support setting the initial path. On those environments, the excluded folder picking will work just like before.

**Comment by mmattel** [comment]
Thanks for the fix 😄 , but unhappy regarding ownCloud 😢

**Comment by paulijar** [comment]
The newly released Music v1.3.1 now contains the change mentioned above.

**Comment by etyrnal** [comment]
this change feels like it forces Music to be stuck in the paradigm of only having a single source folder for music files.  With External Storages enabled, there can be multiple source folders of music, but the Music app makes it impossible to address multiple sources.  But for some reason we can exclude any number of folders -- yet we cannot address multiple music sources.

**Comment by paulijar** [comment]
@etyrnal No, not really. If we at some point add the support for defining multiple library folders, then the feature implemented here just needs a minor modification: In case the user actually has configured multiple paths, then open the exclude folder from the user root folder (like before).

As of today, the application already *can* handle library consisting of multiple source folders, some of which may be external storages or shared folders: Just select the root folder as the library path, and exclude anything you don't want to be included. Of course this may be cumbersome and awkward in some cases, but not impossible.
