### ISSUE TITLE
Ampache API stream type podcast incorrect response

### ISSUE THREAD

**Issue by memen45** [owncloud/music#891]
At the Ampache API endpoint with action=stream and type=podcast, the response is as if type=song. When the id of a podcast is used (which is coincidentally larger than the total number of songs/ids on the server), the response has the following message as well as 404 NOT FOUND status code:

```
{
    "message": "Did expect one result but found none when executing: query \"SELECT `*PREFIX*music_tracks`.*, `file`.`name` AS `filename`, `file`.`size`,\n\t\t\t\t\t\t`album`.`name` AS `album_name`, `artist`.`name` AS `artist_name`, `genre`.`name` AS `genre_name`\n\t\t\t\tFROM `*PREFIX*music_tracks`\n\t\t\t\tINNER JOIN `*PREFIX*filecache` `file`\n\t\t\t\tON `*PREFIX*music_tracks`.`file_id` = `file`.`fileid`\n\t\t\t\tINNER JOIN `*PREFIX*music_albums` `album`\n\t\t\t\tON `*PREFIX*music_tracks`.`album_id` = `album`.`id`\n\t\t\t\tINNER JOIN `*PREFIX*music_artists` `artist`\n\t\t\t\tON `*PREFIX*music_tracks`.`artist_id` = `artist`.`id`\n\t\t\t\tLEFT JOIN `*PREFIX*music_genres` `genre`\n\t\t\t\tON `*PREFIX*music_tracks`.`genre_id` = `genre`.`id`\n\t\t\t\tWHERE `*PREFIX*music_tracks`.`user_id` = ? AND `*PREFIX*music_tracks`.`id` = ? \"; parameters Array\n(\n    [0] => <username>\n    [1] => 600\n)\n; limit \"\"; offset \"\""
}
```

I would expect to receive a stream to the requested podcast (or a redirect, since the file contents will not be served from the server I guess. I also noticed that the ids after first adding the new podcast were simply 1-300, but now a new episode has been added and it got id 600. Is this expected? I have not added any songs or podcasts to the server in the mean time.

Note that I assumed Ampache API 4 is used as reference for the most part, for Ampache API 5 type=podcast_episode would be more accurate.

**Comment by paulijar** [comment]
Thanks for the report. The argument `type` was considered on the action `download` but it had been forgotten from the action `stream`.

Actually, the Ampache API 5 specification https://ampache.org/api/api-xml-methods#stream seems to still define the `type` option of the action `stream` as `podcast` even though on the action `download` it is `podcast_episode`. I wonder if this is just a mistake in the spec. Would @lachlan-00 have any comments on this?

Anyway, I guess that we could allow both types `podcast` and `podcast_episode` to be forward and backward compatible. And in both cases, we should assume that the given `id` refers to the episode.

**Comment by paulijar** [comment]
This issue is now fixed in Music v1.3.2

**Comment by lachlan-00** [comment]
that is very much a mistake i'll make it backcompat but it should be podcast_episode.

**Comment by lachlan-00** [comment]
added episode in with https://github.com/ampache/ampache/commit/3c00e0ea7dc9fe7fd84f38e5f2f0ddd6e6a03418

podcast will stay and will be removed when Ampache 6 comes out (which is probably a long way away now)

**Comment by memen45** [comment]
Thanks a lot both @lachlan-00 and @paulijar for fixing so quickly! This allows me to implement Podcast support over at memen45/SubMusic soon!
