### ISSUE TITLE
Cannot upgrade to Music 1.3.2 from 1.3.1 in Nextcloud

### ISSUE THREAD

**Issue by JoshuaPettus** [owncloud/music#892]
Hi,

When I tried to do the update I got 

> Preparing update
> 
> Set log level to debug
> 
> Turned on maintenance mode
> 
> Repair step: Repair MySQL collation
> 
> Repair info: All tables already have the correct collation -> nothing to do
> 
> Repair step: Repair SQLite autoincrement
> 
> Repair step: Copy data from accounts table when migrating from ownCloud
> 
> Repair step: Drop account terms table when migrating from ownCloud
> 
> Updating database schema
> 
> Updated database
> 
> Repair step: Drop any incompatible music database entries
> 
> Exception: Database error when running migration latest for app music

I'm using Nextcloud 22 with PHP 8.0.10

As of yet I haven't found anything in the log as to why...

**Comment by JoshuaPettus** [comment]
I was forced to disable the app via comandline, I then tried to enable the app and got 

An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'joshuapettus-0' for key 'music_bookmarks_user_track'


Seems the update borked something in the sql database.

**Comment by paulijar** [comment]
Thanks for the report. I just released a quick fix v1.3.3. I hope I got the migration logic right this time.

**Comment by raimund-schluessler** [comment]
I just updated to v1.3.3 from v1.3.1 on Nextcloud 22.1.1 and it worked fine without errors.

**Comment by poltrian** [comment]
Same here, with Nextcloud 21.04 and PHP 7.4

How can i cancel the update and install 1.3.3

**Comment by JoshuaPettus** [comment]
Thank you!  1.3.3 worked!

@poltrian, to get your nextcloud back you first have to disable music via the commandline

navigate to your nextcloud folder then 
sudo -u www-data php occ app:disable music

then take it out of maintenance mode. I know there is a command for it but all I can ever remember is to edit the config.php.  Then you are good to update the app and enable it again.

**Comment by raimund-schluessler** [comment]
> then take it out of maintenance mode. I know there is a command for it but all I can ever remember is to edit the config.php.

```sh
sudo -u www-data php occ maintenance:mode --off
```
