### ISSUE TITLE
Importing playlists always adds two invalid tracks on beginning

### ISSUE THREAD

**Issue by jerome-pouiller** [owncloud/music#895]
When I import a playlist, two invalid tracks always appears:
![Screenshot_20210911_175513](https://user-images.githubusercontent.com/1568726/132953804-7bd51615-19f0-45d7-a3df-a17d0c7ae189.png)

This issue can be easily reproduced by exporting a playlist and then import it again.

**Comment by paulijar** [comment]
Thanks for the report. I tested this export+import on Music v1.3.3 but couldn't reproduce the issue. Could you share a minimal playlist file which causes this issue for you?

**Comment by jerome-pouiller** [comment]
All my playlists start with:
```
#EXTM3U
#EXTENC: UTF-8
```
I think that the two invalid tracks matches these two first lines.

**Comment by jerome-pouiller** [comment]
I am able to produce the problem with an empty playlist (with only the two lines above). The notifications says that 0 songs has been imported, but two invalid entries are there.

**Comment by paulijar** [comment]
The lines starting with `#` shouldn't really create any entries to the playlist as they are comment lines. Can you attach the empty playlist file, so I can check if there's anything out of ordinary in it, like some invisible characters or weird kind of line breaks? So at least we would then know if the problem happens during the export or the import.

Also, which version of PHP and ownCloud or Nextcloud are you using?

**Comment by jerome-pouiller** [comment]
I use php 7.3 (from Debian buster) with Nextcloud 21.0.4.
[empty.m3u.zip](https://github.com/owncloud/music/files/7152935/empty.m3u.zip)

One interesting fact: It seems the problem appears only if I import the .m3u file to a newly created (empty) playlist.

**Comment by paulijar** [comment]
There seems to be nothing out of ordinary on that list file. And I still couldn't reproduce the issue, now using Nextcloud 21.0.2 and PHP 7.4 which is as close as I can get to your setup with my currently available test environments.

You were suspecting that the comment lines in the beginning of the file cause the issue. Can you confirm this by removing those lines, and then importing the list again?

**Comment by jerome-pouiller** [comment]
You're right, I also produce the problem with an empty file (not even a "\n", 0 bytes).

**Comment by jerome-pouiller** [comment]
I have checked the log, but I didn't see anything.

**Comment by paulijar** [comment]
Well, then we at least know that the problem is likely not in parsing of the file. Might be some database related issue then. Which DB are you using?

**Comment by jerome-pouiller** [comment]
SQLite

**Comment by jerome-pouiller** [comment]
I think it does not help, but:
```
$ sudo -u www-data sqlite3 owncloud.db "select * from oc_music_playlists where name IS \"empty\""
26|jezz|empty|2021-09-13 12:06:03.660||2021-09-13 12:06:22.075||0|0|
```

**Comment by paulijar** [comment]
Could you also show the results of the sqlite3 command `.schema oc_music_playlists`? I just noticed, that SQLite has different order of columns between my NC21 and NC22 installations, so this `select *` cannot be really interpreted without knowing the order of the columns.

**Comment by paulijar** [comment]
Also, I assume that the DB row shown above has those two ghost tracks? What does the row look like, if you just create a new playlist and don't import anything?

**Comment by jerome-pouiller** [comment]
The playlist named `empty` contains the two invalid tracks. I have created another playlist (`empty2`) that I didn't touch:
```
$ sudo -u www-data sqlite3 owncloud.db "select * from oc_music_playlists where name IS \"empty2\""
27|jezz|empty2|2021-09-13 13:04:10.781||2021-09-13 13:04:10.781|NULL --|-delimited list of track IDs
```

Then the schema:
```
$ sudo -u www-data sqlite3 owncloud.db ".schema oc_music_playlists"
CREATE TABLE oc_music_playlists (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id VARCHAR(64) NOT NULL COLLATE BINARY, name VARCHAR(256) DEFAULT NULL COLLATE BINARY, created DATETIME DEFAULT NULL, comment VARCHAR(256) DEFAULT NULL COLLATE BINARY, updated DATETIME DEFAULT NULL, track_ids CLOB DEFAULT 'NULL --|-delimited list of track IDs' COLLATE BINARY --|-delimited list of track IDs' COLLATE BINARY --|-delimited list of track IDs' COLLATE BINARY --|-delimited list of track IDs
);
```

I don't really remember, but I think that I have created this DB when I used NC20 and it has been migrated several times.

**Comment by paulijar** [comment]
That schema is now clearly screwed up. For the column `track_ids`, the default is supposed to be `NULL` but it is now a string `'NULL --|-delimited list of track IDs'`. That is, somehow the comment of the column has got merged into to the default value.

So whenever you create an empty playlist, the list will be populated with some crap which subsequently gets interpreted as two tracks IDs `0`. Based on this, the problem should be reproducible also without importing anything from a file. If you just create a new playlist and reload the web UI, I bet that you will still see those two ghost tracks.

**Comment by jerome-pouiller** [comment]
> If you just create a new playlist and reload the web UI, I bet that you will still see those two ghost tracks.
Indeed.

**Comment by jerome-pouiller** [comment]
I am not  a SQL wizard. Do you know how to repair my SQL database? I don't care on the content of `oc_music_*`. Can I simply drop these tables?

**Comment by paulijar** [comment]
If you can afford to wipe everything clean, then it's okay to drop those tables. In addition, you need to remove references to music from the migrations table: `DELETE FROM oc_migrations WHERE app LIKE 'music';`.

After this, when you disable and and then enable Music, the database tables should get recreated.

**Comment by jerome-pouiller** [comment]
Great! Thank you @paulijar for your time.
