### ISSUE TITLE
Embedded art in flac files is not shown

### ISSUE THREAD

**Issue by Cknight70** [owncloud/music#897]
I have a few albums which consist only of flac files with embedded art and no cover.jpg file, which the music app does not show in the web interface or to some Subsonic apps like Ultrasonic, but does in others like Strawberry or Audinaught although, I do not know if this is automatic fetching of album art at work with those apps.

I converted one of my flac files to mp3 to ensure this was a specific to flac issue 
![image](https://user-images.githubusercontent.com/28763729/133141682-4733aa71-f1ca-4e22-b724-7cde9cc11a1f.png)

I am using Music version 1.3.3 with Nextcloud version 22.1.1.

**Comment by paulijar** [comment]
Could you share one of those flac files with me? You can find my email from my github profile.

**Comment by paulijar** [comment]
Thanks for the file. But for me, the embedded art is visible on that file within Music. The art is not shown in Files but that is expected: the Files app uses the ID3Parser library to extract cover images from audio files while the Music app uses the getID3 library. The ID3Parser is a stripped-down fork of getID3, and it can handle only ID3v2 tags while the getID3 can handle many more tag types.

Are you using some storage back-end other than the internal storage within the Nextcloud server?

![image](https://user-images.githubusercontent.com/8565946/133214102-131e8f63-5179-4469-83f3-709694c61e50.png)

**Comment by paulijar** [comment]
Also, when you view at the track details like in my screenshot above, the do you see all the other details except for the album art?

**Comment by Cknight70** [comment]
Yes I am using a samba share for external storage, but I could trivially switch my music folder to local external storage and see if that fixes the issue.

I do not see any details, not even the album art Since the album has no cover 
![image](https://user-images.githubusercontent.com/28763729/133228675-e588dfda-c26a-4c31-aaa4-e4c9eadbe21f.png)

**Comment by paulijar** [comment]
Okay, the SMB storages have proven to be problematic for metadata extraction, see https://github.com/owncloud/music/issues/670 for one such problem. Installing `libsmbclient-php` may be a solution.

**Comment by Cknight70** [comment]
Thank you much, I have switched to using local storage and this problem is gone.
