### ISSUE TITLE
zh_cn is not fully translated.

### ISSUE THREAD

**Issue by RuofengX** [owncloud/music#898]
![图片](https://user-images.githubusercontent.com/40327863/134794410-5f6ffa07-6aaf-47bf-9bbb-b636a890834c.png)
As we can see in this image, this project is not fully translated. If I want to make some translation, what should I do? I notice there's a i10n folder, could someone gives me a tip?

**Comment by paulijar** [comment]
Yes, the same is true for the most of the languages. See https://github.com/owncloud/music/issues/671#issuecomment-782746463 for instructions on how to contribute translations.

**Comment by paulijar** [comment]
This has been resolved by https://github.com/owncloud/music/pull/899.
