### ISSUE TITLE
Unusable for large collections

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/music#90]
I know, the app is still in a preview state, but I wanted to give it a try; here's my report that alas, with a big music collection, the app is unusable at the moment.

On first access to the app, the page loading takes forever (actually it never finishes). I heard the hard drive being accessed so I thought I'd let it run. Then the access to the hard drive stopped suddenly. The server log then showed a segmentation fault in some child process; the apache and mysql process still showed high CPU usage. Only a restart of apache helped restore the ownCloud interface. And when trying to go again to the music app, the page loads forever, this time without any hard drive access, again locking up apache and mysql.

Please realize that people will have more than a few songs, and that therefore
1. Progress report during scan is crucial
2. The whole scan possibly cannot fit into one script run, or might be aborted in the middle, so there has to be a way to (ideally automatically) resume the scan
3. The scan not finishing should not break the music app; and even more importantly, should not prevent any other ownCloud access by leaving apache/mysql running at high CPU cycles...

Environment:
Ubuntu Server 12.04
ownCloud 5.0.10
music: tried with latest master (65f4678) and "various-fixes" branch (d75a4ff)
Client: Firefox 23.0 running on Ubuntu 13.04

**Comment by HLFH** [comment]
@MorrisJobke @butonic Is there a way to merge https://github.com/libasys/audios and ownCloud Music? ownCloud Music has a working Ampache backend but is unusable for large collections, Audios ownCloud plugin is usable for large collections.

**Comment by MorrisJobke** [comment]
We plan to join forces.

**Comment by pellaeon** [comment]
@MorrisJobke Any updates? How do you plan to solve problems with large collection? It's really a pain for me, so I want to help.
Currently I find 2 bottlenecks, one is `/api/collection` and another `/api/scan?dry=0`, both seems to be caused by slow database queries. Perhaps it could be solved by memcache?

**Comment by arpee** [comment]
Would also like to *bump* on this issue.

I get unresponsive pages since the application finished scanning my collection. 
(Stuck with a loading gif.)

**Comment by tetzlav** [comment]
+1 
unusable slow with 10000+ songs... :(

**Comment by HLFH** [comment]
@tetzlav You should use [Plex](https://plex.tv/) or [Emby](http://emby.media/) for multimedia (movies, tv shows, music) as @MorrisJobke [does](https://forums.plex.tv/discussion/108399/random-crashes-double-free-or-corruption-restart-fixes-this). For this moment, it's the better way.

**Comment by tenleftfingers** [comment]
You do not need 10k songs to slow down this. I have 3k and it's unusable. Press play on a song and wait minutes to play. UI takes minutes to complete scanning (which it does too often). Gap of several minutes between songs. No way to browse by album. Would love to see this app spread it's wings.

**Comment by bee272** [comment]
Great app but....
+1 
unusable with 10000+ songs... :(

**Comment by paulijar** [comment]
The PR #564 improving the performance especially with large collections was merged yesterday. If you are willing to test with development version, I would be interested to hear how it works now with large real-life music collections and what is the practical collection size limit for usability. I would recommend using Chrome browser with large music collections.

**Comment by paulijar** [comment]
The Music app version 0.4.1 containing #564 has been released to ownCloud marketplace and Nextcloud app store. There's always room for improvement on performance, but IMHO, the app is now quite usable at least with several thousands of tracks. Obviously, it will still probably become unusable if you add e.g. 100k tracks. I'm closing now this very old issue. Feel free to report a new issue if you still find it unusable with your music collection.
