### ISSUE TITLE
When importing, characters other than English will be recognized as garbled and cannot be imported

### ISSUE THREAD

**Issue by even0306** [owncloud/music#902]
>In nextcloud, create an m3u playlist. When importing, characters other than English will be recognized as garbled and cannot be imported

The display is normal with m3u8, it seems to be a problem with m3u format support

**Comment by paulijar** [comment]
For .m3u files, we assume ISO-8859-1 encoding unless there is a `#EXTENC` tag in the file defining another encoding. For .m3u8 files, we assume UTF-8 encoding unless there is the `#EXTENC` tag.
