### ISSUE TITLE
Error log related to Music app in Nextcloud 

### ISSUE THREAD

**Issue by elhananjair** [owncloud/music#907]
Hello there am having this non-stop error log in Nextcloud, I just wanted to mention it here may be if there is something to be updated. 
Here is the log:
_0,"time":"2021-10-19T04:58:40+00:00","remoteAddr":"192.168.22.105","user":"administrator","app":"music","method":"PROPFIND","url":"/remote.php/dav/files/administrator/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.3.5stable-Win64 (build 20210930) (Nextcloud, windows-10.0.22000 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"21.0.5.1"}_

**Comment by D3V1LC0D3R** [comment]
@paulijar is this a wontfix or just low priority? this might be a problem in the future (couldn't find out when this will stop working but it seems that it will happen at some point)

**Comment by paulijar** [comment]
Currently it's low priority. If the deprecated functionality is actually removed, then it will become a high priority.

**Comment by paulijar** [comment]
This issue is now finally solved in Music v2.0.0.
