### ISSUE TITLE
Stop button

### ISSUE THREAD

**Issue by pidlug** [owncloud/music#911]
Is it possible to stop listening in addition to pause?
With internet radio I would like to just stop listening to later start from current position, so e.g. news are fresh. Currently the player has only pause button, after pausing and later clicking play it countinues from the place it was paused. Some streams even break when trying to play after pause.
Currently the workaround I use is switching stations to fix the stream or just leaving the Music app.

**Comment by paulijar** [comment]
The stop functionality is there but finding it may not be quite obvious. There are three ways to trigger it:
1. The media control key "stop" in case your keyboard has one
2. Keyboard shortcut shift+space
3. If you are using Chrome, there is the media control popup. Pressing close button ("X") on the panel stops the playback.
![image](https://user-images.githubusercontent.com/8565946/139678546-2745572b-e2aa-4c2a-a64c-271b8749ec7b.png)

**Comment by pidlug** [comment]
Thanks! I'm on ungoogled-chromium - not sure if media control popup is available.
Other solutions wouldn't work because it is a tablet, without keyboard attached. Could be my use case is not very common...

**Comment by paulijar** [comment]
Okay. Much of the Music web UI is primarily designed for desktop use. Tablet or phone may be used, too, but the UX will be sub-optimal at best. This is especially because many things on the UI are shown only when hoovering with a mouse cursor. For tablet use, I would recommend using some Subsonic client.

On Chrome for Android, you can achieve the stop functionality by first pausing the playback, and then swiping off the player control from the system notification center (the "curtain"). I don't know if this works with Chromium, though.

**Comment by pidlug** [comment]
Heh, this "hovering" is more and more used - e.g in Gnome which tries to advertise itself as touchscreen friendly :-(
I agree that it helps to keep user interface clean. Anyway, it would be nice to have a stop button, simple because it does something different than pause and there is enough space to put it - at least on the internet radio player.

**Comment by paulijar** [comment]
While there usually is free space in the controls pane on PC screen and on landscape tablet, the view can be quite crowded already on portrait tablet.  Especially while the details pane is shown. And on mobile phone screens, we are chronically low on screen space. For these reasons, I'm not too excited about adding another button to the pane. But maybe there could be context menu shown with a long press on the pause button which would offer the stop option.

**Comment by pidlug** [comment]
I think that long press or double click could be a solution. Thanks.

**Comment by paulijar** [comment]
The new Music app release v1.5.0 now shows the stop button by long press of the play/pause button. This has been tested to work on the modern PC browsers, on Chorme for Android, and on Firefox for Android. However, handling the long press on touch devices is a bit tricky, and there is a good chance that this doesn't work perfectly or at all on some devices or browsers.

**Comment by edmundlaugasson** [comment]
Why not show stop button right away? It is small button and does not take too much space. Please allow it right away without doing anything extra and unlogical. Such pressing and holding is not intuitive. I could not figure out until I found current issue....

**Comment by paulijar** [comment]
@edmundlaugasson Well, this is basically already answered above: https://github.com/owncloud/music/issues/911#issuecomment-956654799

So even if there is plenty of free space when using a full screen window on some 1920p or 4K display, we need to support also many other screen/window sizes. So if we add any new buttons, then those need to be dynamic in the sense that they may need to be hidden on narrower screens. A lot of effort has been put to make these dynamics work fluently with the current controls, and adding any new buttons would require revisiting all this. It would probably be a lot more work than you would imagine, and there are many other features in the queue before this one.
