### ISSUE TITLE
Missing artist image when artist name has illegal character

### ISSUE THREAD

**Issue by samkottler** [owncloud/music#913]
In particular, AC/DC has the slash in it which means I cannot save the artist image as AC/DC.* Is there a way to either manually select the image to use or an alternative character that the scanner will recognize?

**Comment by paulijar** [comment]
Good point. There's currently no way around this, but I'll try to figure out something for the next version.

**Comment by paulijar** [comment]
In Music v1.5.0, you can now supply image called "AC_DC.*" to overcome the problem. Also all the characters `<>:"\|?*` may now be replaced with underscores `_` in the image filename (but you don't have to, as the slash `/` is the only actually forbidden character on Linux file names).
