### ISSUE TITLE
No album/directory/music covers

### ISSUE THREAD

**Issue by christophe195** [owncloud/music#917]
Hy,

I have let owncloud music scan my music directory where every artist has it's own directory but now i have no images (broken on substreamer).

Do i need to follow a specific folder structure?

i use nextcloud.
Mvg. Christophe VD

**Comment by paulijar** [comment]
Do you mean that you can see the album covers on the Music web UI but not on Substreamer? Or that the images are not visible on the web UI either? I have seen that Substreamer is quite quirky on showing the cover art; at first, it might not show album covers at all, but after a while, it may show some of them but never all. No other Subsonic client has issues like this, so I assume it's a client-side bug.

If you are experiencing the problem only on Substreamer, then can you test with any other Subsonic client? Or if you have the problem on the web UI, too, then can you describe your setup a bit more:
- Are the files located in the internal storage of Nextcloud or on some external storage (which one)?
- Do you have the album art embedded in the files or is there separate image files to be used as covers? What are the file types?

**Comment by christophe195** [comment]
The album cover's are not on the UI and on Substreamer.

Do i need to place them somewhere or can the app search for them on last.fm?

i did have the other music app of nextcloud.

**Comment by paulijar** [comment]
The app cannot grab the art automatically from Last.fm. You have two choices:
- Embed the album art in the tags of the audio files
- Store a separate image file (e.g. in jpg or png format) in the same folder with the tracks. For this to work correctly, you should have one folder per album. If there are more than one image files in the same folder with the tracks, the image file to be used is selected according the file name in order `cover*` > `albumart*` > `album*` > `front*` > `folder*` > `(any other name)`. But once the image file has got selected, it is not changed even if a new image file with more high-priority name later becomes available.

**Comment by paulijar** [comment]
So I assume that there was no bug here but just a misunderstood feature. Please reopen with more explanation if this was not the case.
