### ISSUE TITLE
Feature Request: Auto start playback/partymode by GET parameter

### ISSUE THREAD

**Issue by gsantner** [owncloud/music#922]
Hello!

Depending on the internet connection (& size music library size), Music app takes a while to load (i.e. 10 seconds).  
I 99% do the same steps when I just want to listen some music: Open own/nextcloud, wait long time, press shuffle button, start some track.

Guess this is rather small change but rather big use improvement for usage: Start playback automatically after Music app loaded by adding some URL parameter.

I.e. so the user can add the URL `https://example.org/nextcloud/index.php/apps/music?autoplay=1&shuffle=1` or `https://example.org/nextcloud/index.php/apps/music?partymode=1` to favourites, click it once and get some music played as soon OC/NC is ready for it.

Thanks for considering, this would be a very cool & time-saving addition.

**Comment by paulijar** [comment]
Music v1.5.0 now added handling for the URL query arguments `autoplay`, `shuffle`, and `repeat`. See the commit message linked above for details. In addition to autoplaying over your whole library, the `autoplay` argument can be used to automatically play a selected playlist (or any other view).

**Comment by gsantner** [comment]
Cool, thank you for working on a solution that fast (and generally working on the project).

I check it out when it's available in nextcloud updater

**Comment by gsantner** [comment]
@paulijar  
 I tried it and it's quite a improvement, thanks!

What I found is that however playback is not starting automatically (a track is loaded, but you need to press the "play button" manually then). This is some webbrowser feature I guess, which disallows automatic starts without at least one manual interaction?

Result of `https://DOMAIN/nextcloud/index.php/apps/music#/?shuffle=1&repeat=1&autoplay=1`

![grafik](https://user-images.githubusercontent.com/6735650/145392736-f7fe036c-79e1-462d-b941-b9bae22cb80a.png)

Result of `https://DOMAIN/nextcloud/index.php/apps/music#/alltracks?shuffle=1&repeat=1&autoplay=1`

![grafik](https://user-images.githubusercontent.com/6735650/145392875-8d29c987-b71e-4cdc-9ac6-8a658c66e2ca.png)

(not sure what the playback progressbar state/value means btw)

**Comment by gsantner** [comment]
I also recently added a better distinction between browser and controls using NextClouds Custom CSS addon:

```
#content.app-music #controls { background-color: darkgray;  filter: invert(100%); }
#content.app-music #controls .albumart { filter: invert(100%); }
```

![grafik](https://user-images.githubusercontent.com/6735650/145396600-3078cd29-f3de-439a-8d6e-eda502d9ac5e.png)

Is there some place in this project to add such user ideas and hints?

**Comment by paulijar** [comment]
> What I found is that however playback is not starting automatically 

Firefox, at least, has this per-site setting to (dis)allow the automatic playback. Other browsers may have something similar.
![image](https://user-images.githubusercontent.com/8565946/145474737-33527629-6bf5-4401-b37d-4ea7ec36aca3.png)

> Is there some place in this project to add such user ideas and hints?

No, not really. But if you want to create one, then maybe https://help.nextcloud.com/c/apps/music/111 would be a suitable platform.
