### ISSUE TITLE
Empty Spaces in Album Panel.

### ISSUE THREAD

**Issue by worksmarter** [owncloud/music#923]
Nextcloud version 22.2.1 or 22.2.2 update caused albums to be displayed with big spaces between some of them, particularly ones that have six songs in them push the lower albums out of the way and leave blank space in the albums panel. Also, the lack of tracks on an album seems to do the same thing. This occurred with an update to Nextcloud.

![albums_one](https://user-images.githubusercontent.com/8888460/143494052-2b42a10c-4241-4fae-9ebf-63b61a4cb6f1.png)
![album_two](https://user-images.githubusercontent.com/8888460/143494067-1b0e6079-50a8-44f6-92ad-c2683156ab78.png)

.

**Comment by paulijar** [comment]
Thanks for the report. There seems to now be awfully much margin between the track names. Probably NC has changed some shared style definition and we now need to override it to get back to the intended layout.

**Comment by worksmarter** [comment]
Thanks for the quick response. I would have to agree - those Nextcloud guys, not the music app - but the fix may have to be in the music app to override Nextclouds changes.

**Comment by paulijar** [comment]
This is now fixed in Music v1.5.0.
