### ISSUE TITLE
Playback Pauses at 5:11

### ISSUE THREAD

**Issue by runhard48-6** [owncloud/music#928]
I've been having a nagging problem across NC21-23 and multiple versions of the Music app, where playback pauses at 5:11 (and again around 10 minutes for longer songs) when using a desktop browser (Brave). Playback is fine using the Subsonic app on Android. Clicking the playback progress bar to skip ahead a few seconds resumes playback.

It seems like the problem is possibly being caused by "OC.requestToken changed", reported in the web console. There is no error in the Nextcloud web log.

Any guidance on if this is the cause of the problem, and/or how to solve it?

I'm running the standard version of Nextcloud 23 on a Raspberry Pi, Ubuntu 20.04, Apache and PHP 8.

Thanks!

**Comment by runhard48-6** [comment]
After more monitoring, it does not look like the "OC.requestToken changed" flag occurs every time playback stops at ~5:11. So, I am not sure at all what is the cause.

**Comment by paulijar** [comment]
Could you test this on any other browser so we could rule out or confirm this being a Brave-specific issue? Also, is the same problem present when you are playing the file from the Files app? In that case, the front-end code playing the file is mostly the same as within the Music app, but the back-end API used is different.

**Comment by runhard48-6** [comment]
My apologies, I should have tested playback in another browser. It appears that playback progresses normally using Firefox. However, playback does not progress past 5:11 in Chrome. As Brave is a chromium base, it seems like a chromium-specific issue?

I did check playback from the Files app, in Brave and Chrome, and playback does not progress correctly from there, either.

**Comment by paulijar** [comment]
Okay, thanks for the info, sounds like Chromium-specific indeed. Are all the tested files in the same file format or have you seen this on multiple types?

**Comment by runhard48-6** [comment]
All of the tested files are .mp3. To my knowledge, I do not have any other formats.

**Comment by paulijar** [comment]
I just tested that this problem doesn't happen on my setup of NC23 + PHP7.4 + Nginx on RaspberryPi3 using the Brave browser on Win10.

**Comment by runhard48-6** [comment]
Interesting! Could it be an apache issue? Seems unlikely that PHP7.4 vs 8 would be to blame.

Or, is there any sort of config setting within the various NC setting files that would limit how long a service could run for?

**Comment by paulijar** [comment]
I don't have any good theory on what would be the root cause here. But as you are the first one to ever report such issue, it's likely that most cloud setups are not suffering from this problem.

The way the audio streaming is handled by all modern browsers (well, at least Firefox and Chrome) is that they first request the whole file from the server and start downloading it. But once the browser thinks it has got enough for now, it pauses the download. Then, when the playback progresses near the boundary of the already buffered data, the browser resumes the paused download. If the original request has timed out before this, then the browser should be smart enough to make a new *partial* download request starting from the offset where the download was previously paused.

You could maybe try too observe these requests on the Network tab of the browser developer tools. That *might* give some clue about what is different between Firefox and the Chromium-based browsers.

**Comment by runhard48-6** [comment]
That makes sense.  I have not looked at the Network activity side-by-side yet, but I did have Firefox randomly pause at 5:11 the other day. I think that is the second time it has happened on FF.

So, currently, Brave and Chrome pause consistently at 5:11, and Firefox randomly/rarely pauses at 5:11.

As soon as I can I'll play the same track side-by-side in Brave and FF while watching the Network tab and report back.

**Comment by runhard48-6** [comment]
OK, I finally tried testing them side-by-side, with various levels of success. Firefox did freeze playback, but at random times. I couldn't seem to get much helpful information from the Network/Dev tools.

With Brave, playback paused at 5:10 and I did track down this.

![brave download stalled](https://user-images.githubusercontent.com/49246610/149708346-0eb0706b-0d02-4ed0-a700-49eefa4cb153.jpg)

Not sure where that leaves us?

**Comment by runhard48-6** [comment]
Quick thought; could this issue be related to Nextcloud's cron settings, which happen to be 5 minutes by default? Is there any reason not to try changing that to 4 minutes to see what happens? Obviously it will fire more frequently, but I'm not too worried about system load, if that is the only reason not to schedule NC's cron more frequently.

**Comment by paulijar** [comment]
There should be no reason not to alter the cron job frequency. In my installation, it fires only once per 15 minutes; I guess that was the default years ago, and has never got changed when I have just updated my installation to newer versions.

**Comment by runhard48-6** [comment]
Quick update: this seems to have resolved itself, though I don't know why. Possibly an update to Brave/Chromium? Regardless, playback is proceeding normally, regardless of how long the track is.
