### ISSUE TITLE
Folder Tree View Folder image

### ISSUE THREAD

**Issue by FadeFx** [owncloud/music#929]
Hi, first of all thanx to @paulijar for the tree layout in folder view, it even behaves as i would like it when the folder end is reachend... however, there is always something to make it better ;-) 
could we have the folder icons slightly bigger (maybe double the current size) and if available display a folder.[image file] or cover.[image file] front.[image file] instead if available?

**Comment by paulijar** [comment]
I realize that it's not exactly what was requested here, but Music v2.0.0 added the album cover images to all kinds of track lists, including the folder tree view. IMO the new design supersedes this request here.

**Comment by FadeFx** [comment]
Going to check ;-)

**Comment by FadeFx** [comment]
Not sure where you take the cover image from, but it doesn't show up in folder view. However, this might be related to my instance not displaying folder images in files app as well...
![Screenshot_20240630-123429~2](https://github.com/owncloud/music/assets/41125748/aba8952c-1d43-4dc1-b14f-d5a9c551d367)
![Screenshot_20240630-123439](https://github.com/owncloud/music/assets/41125748/2e06b72d-678f-4270-ac97-b88f7cbec5c0)

**Comment by paulijar** [comment]
There's no images on the folders per-se, just in front of each track. That's what I meant with the "not exactly what was requested here".

**Comment by FadeFx** [comment]
I C... :-( however, thank you for your work, really appreciated...
