### ISSUE TITLE
Strawberry Subsonic: Could not determine type of stream

### ISSUE THREAD

**Issue by JoshuaPettus** [owncloud/music#930]
I have been meaning to put this issue in for a while, but never get around to it.
This very well could really be an issue with the Strawberry Music Player and not Music itself but I thought I'd try here first, since it used to work.  I suspect it stopped working around the 1.4.0 update, although that's just a guess.

I can connect to my music server via the subsonic interface just fine.  The music lists just fine, but whenever I attempt to play anything, it just says "Could not determine type of stream"  

It use to play normally, but something changed with the last few music app versions, and it stopped working.   (Or some setting in strawberry changed but I can't seem to find it).  Ive tried it on multiple installations of Strawberry, linux and windows, all same result now.

All my other subsonic apps work fine.

I'm currently using NC23, Music 1.5.0 on an Ubuntu 20.04 server, PHP 8.0.

**Comment by paulijar** [comment]
Thanks for the report. I haven't tested Strawberry for a while. I shall test it once I have a chance.

**Comment by paulijar** [comment]
I now had time to test this but couldn't reproduce the issue. The songs were playing just fine on the Strawberry Music Player using the Subsonic API both with NC23+PHP7.4 and NC17+PHP7.1. Music app version was 1.5.0 and the Strawberry was v1.0.0 on Windows 10 (64-bit).

**Comment by JoshuaPettus** [comment]
Sorry it took me a while to take another look.  It's been busy this time of year.   Anyway, It was definitely some weirdness in the strawberry app. I uninstalled strawberry entirely and deleted everything in /home/user/AppData/Local/Strawberry.   After I reinstalled, only then did it properly scan the server.  Thank you for taking a look.  I'll close this.
