### ISSUE TITLE
Scan of all folders

### ISSUE THREAD

**Issue by bacinet02** [owncloud/music#931]
Hello,
I'm using nextcloud 23.0.0
I have a share folder for my music (nfs mount on my server)
I have launched the command: ./occ music:scan --all

But it seems to scan only the folders I have visited in next cloud files.
This scan finds approx 10% of my music only!

Thanks for help and congratulation for work!

**Comment by paulijar** [comment]
Hi,
From the point-of-view of the Music app, a file exists only if it has been indexed by the host cloud (Nextcloud in your case). All the files uploaded via the web UI or Android/Windows apps of Nextcloud should be automatically indexed. In case you have mounted an external (NFS) storage full of files and folders to Nextcloud, those are *not* indexed before you navigate to each sub-folder.

The good news is that you can force the whole storage to be indexed using `./occ files:scan`. You probably want to check the finer details of this command with `./occ files:scan --help` before starting. After that is done (may take a long while, depending on the size and other details of your external storage), you should be able to use `./occ music:scan` to find all your files.

**Comment by bacinet02** [comment]
Thanks! 
Now, it works :-)
