### ISSUE TITLE
Auto scan music

### ISSUE THREAD

**Issue by Seb3thehacker** [owncloud/music#938]
Is there a way to auto automatically scan for new music? It already detects when a new file is added so it seems like it would be easy to implement.

**Comment by elif1789** [comment]
not from settings interface, but inside crontab, you can put  [owncloud occ path]/occ music:scan
useful options  are username,  --rescan and --rescan-modified, see [](https://github.com/owncloud/music/issues/843)

**Comment by Seb3thehacker** [comment]
@elif1789 Awesome. Thank you!

**Comment by paulijar** [comment]
The question has been answered above and in the linked issue => closing
