### ISSUE TITLE
Add support for PHP 8.1

### ISSUE THREAD

**Issue by nextcloud486153** [owncloud/music#939]
There are some rolling-release distributions that already have support for PHP 8.1 (such as Arch Linux), and [info.xml](appinfo/info.xml#L32) limits it to 8.0.

Is there a reason for this, or could it be bumped? I tried bumping it manually, but I haven't thoroughly tested it against PHP 8.1

**Comment by paulijar** [comment]
There's no reason, other than that it has not been tested and I haven't even studied what are the differences between PHP 8.0 and 8.1. But if I had to guess, I would say that probably it works just fine on PHP 8.1. This is based on the fact that there were hardly any issues when moving from PHP 7.2 to 7.3 and 7.4. On the other hand, moving from 7.4 to 8.0 introduced many subtle bugs and I wouldn't be surprised if there are some such still left in the latest Music version. But I guess this is what the change in the major number signifies.

If you are now running your instance with PHP 8.1, then feel free to report any issues found and also if everything seems to work fine in the longer run. Maybe I'll then increase the version range supported in info.xml for the next release.

**Comment by JoshuaPettus** [comment]
I don't think NC 23 supports php 8.1, so it's a little moot at this point

**Comment by paulijar** [comment]
@nextcloud486153 So have you been running the app with PHP8.1 for the past months without issues? I need to publish a new app version soon with support for NC24, and I was thinking that maybe PHP8.1 should be added at the same time.

**Comment by OliveiraHermogenes** [comment]
@paulijar  I have a current setup with NC24+PHP8.1 with the music app disabled. How would I go about testing it? Enabling it with `occ app:enable --force music` throws an error about PHP version requirements.

**Comment by OliveiraHermogenes** [comment]
@paulijar I just enabled it and it seems to be working fine. NC24+PHP8.1 (Debian sid). I will keep testing and report in case of any issues.

**Comment by nextcloud486153** [comment]
@paulijar I've been running the app since my last comment with no apparent issues.

**Comment by paulijar** [comment]
Okay great, thanks for you both.

**Comment by paulijar** [comment]
Newly released Music v1.5.2 now declares support for PHP 8.1.
