### ISSUE TITLE
Cyrillic is not recognized in the app.

### ISSUE THREAD

**Issue by skorpions2000** [owncloud/music#941]
Cyrillic is not recognized in the app. Is there a way to enable Cyrillic support?

![image](https://user-images.githubusercontent.com/11683786/152644834-f54c17bf-570e-4230-aeb0-2fd894265c3b.png)

**Comment by paulijar** [comment]
The chances are that you have an incorrectly tagged mp3 file. This can happen at least two ways:
1. The file contains only ID3v1 tags. According to the spec, this kind of tags should always use Latin-1 encoding which would make it impossible to fill in any Cyrillic characters. But it's still possible that someone has filled in KOI8-R or Windows-1251 encoded Cyrillic data, but it's now impossible to detect this automatically to do the decoding as the original filler wanted.
2. The file contains ID3v2 tags which can legally use many kinds of encodings. However, the file doesn't define the used encoding correctly, and again, it can't be decoded as intended.

So now the first question is, can you find any other application which could actually decode the metadata of those files correctly?

In both of the cases 1 and 2, the best solution would be to retag those files using ID3v2.4 tags and UTF-8 encoding. In the case 1, you could also try to experiment with the settings of the GetID3 library which we use for the metadata extraction. There's no planned way in the Music app to do this but you could rather easily monkey patch your installation by adding lines after this line of code: https://github.com/owncloud/music/blob/3f5ca983c3bd1ca66d4c3cda43abd29868cca0b5/lib/Utility/ExtractorGetID3.php#L42

You could try to add there
`$this->getID3->encoding_id3v1_autodetect = true;`
or
`$this->getID3->encoding_id3v1 = 'KOI8-R';`
or
`$this->getID3->encoding_id3v1 = 'Windows-1251';`.

There are also a few other encodings containing Cyrillic characters but, as I have understood, those two are the most common, and also the only which *may* be detected by that `encoding_id3v1_autodetect`. However, the autodetect is heuristic and may produce wrong results, too.

If you make the code changes seen above, you should see any effects immediately in the song details pane but only upon rescan in the application main view.

**Comment by paulijar** [comment]
Closing as inactive. Presumably the root cause was in the audio file used and it's not clear if there is anything which Music could have done differently.
