### ISSUE TITLE
Gapless Play

### ISSUE THREAD

**Issue by ScoobyAS** [owncloud/music#942]
Would you please integrate gapless playback into this beautiful app. That would be highly appreciated for playback of some albums. Maybe it is also useful to have an option to choose if an album should be played in gapless mode or not (not=standard).

**Comment by paulijar** [comment]
There is already an open issue https://github.com/owncloud/music/issues/685 about this feature request. Also the issue https://github.com/owncloud/music/issues/776 is somewhat related.

That being said, this is a feature I have been thinking about lately. This might very well be on the agenda when I again have some time for the development of this app later this year. I don't know yet, how gapless I can make it but probably I can at least shorten the gap between the tracks.

I'm not so certain about the usefulness of the user option for this. Isn't "gapless" how any album has been intended to play by the artist, not adding any artificial gaps between the tracks? If the artist has wanted to have a gap there, it should be part of the track. So does anyone actually want to have the extra gaps between the tracks?

**Comment by paulijar** [comment]
Closing as a duplicate
