### ISSUE TITLE
error with notifications

### ISSUE THREAD

**Issue by R7JANV1** [owncloud/music#943]
If a public link is shared to an audio file, it will be displayed as downloaded in the notification bar each time the audio file is played with the music player.

**Comment by paulijar** [comment]
Could you show a screenshot of this, to help me understand the case? Which version of ownCloud or Nextcloud are you using?

**Comment by R7JANV1** [comment]
If audio files are shared individually, this does not happen, but the file is played in the browser's old HTML player. However, when a folder with audio files is shared, the problem with notifications appears.
![grafik](https://user-images.githubusercontent.com/90777102/153083246-6c68b070-5571-4d8d-a0a1-fa41474624d6.png)

**Comment by paulijar** [comment]
You still didn't mention the version of Nextcloud used. For me, there are no notifications shown when a file is played or even downloaded from a public share. I tested Nextcloud versions 17 and 23.0.0 RC3.

What I do see, is a line on the Activity tab of the file details pane:
![image](https://user-images.githubusercontent.com/8565946/153286661-6aaddcb8-3e71-4779-b10b-f34a33c01394.png)
But such "Downloaded" line appears both when I listen the track from the folder share and when I listen to an individually shared file.

You could also try to listen tracks from the publicly shared folder using the "View" option and see, if that makes any difference compared to using the Music app player.
![image](https://user-images.githubusercontent.com/8565946/153287429-d191637b-e31c-4366-a301-d7ed0ce3100f.png)

**Comment by R7JANV1** [comment]
Probably you have not enabled the notification. (Public or email shared file / folder was downloaded).

Nextcloud 23

**Comment by R7JANV1** [comment]
Sorry you are right it's Nextcloud and not the great music app.
