### ISSUE TITLE
It would be great to have Like button in the player buttons

### ISSUE THREAD

**Issue by rstefko** [owncloud/music#946]
The button would add / remove current song into the "Liked" playlist.

Or at least allow to drag currently played song to the playlist.

**Comment by paulijar** [comment]
This is closely related to the earlier request https://github.com/owncloud/music/issues/779 although adding the like/favorite button to the player bar is a new idea.

Allowing the dragging of the currently playing song is also a good idea, and should be much simpler to implement than the dedicated "liked" view and mechanisms.

**Comment by paulijar** [comment]
Music v1.5.2 was just released with the ability to drag the playing song from the player bar to any playlist.

**Comment by paulijar** [comment]
Music v2.0.0 added the set/unset favorite option to the details pane. There's still no dedicated "Favorite" or "Liked" view, but the other issue https://github.com/owncloud/music/issues/779 covers that and I think this issue can be closed. As of today, the selected favorites may be listed using either the Smart list view or the Advanced search.
