### ISSUE TITLE
Edit song metadata

### ISSUE THREAD

**Issue by 2br-2b** [owncloud/music#952]
It would be nice if there were an easy option to edit a song's metadata from the music player.

**Comment by paulijar** [comment]
Yep, closing as a duplicate.

For what it's worth, a major reason this has not been implemented so far is that I'm a bit hesitant to accept the risks involved. There are so many supported file types with so many supported metadata types and with weird edge-cases that comprehensive testing of such feature would be nigh impossible. Hence, there's a good chance that sooner or later some user would corrupt their files with the feature. And I wouldn't be quite comfortable being responsible of that.
