### ISSUE TITLE
[Feature Request] add current track to a playlist via drag&drop

### ISSUE THREAD

**Issue by martingabelmann** [owncloud/music#956]
I have a huge music library (O(4k) tracks)  and often I'm playing the whole thing in the folder-view in shuffle-mode.
Every now and then I'd like to be able to add the currently played track to a playlist (sort-of organizing the music library while playing).
However, it seems like I'm not able to jump to the currently played track in neither of the tree-/flat-/all-tracks-layouts, am I?

Therefore, I propose a feature which enable the ability to drag&drop the title from the player into a playlist.

I think this is a quite basic feature which may be used very frequently by many new users...

probably related to #877 #835

**Comment by paulijar** [comment]
Actually, this feature has already been implemented in response to https://github.com/owncloud/music/issues/946 but it just hasn't been released yet. So it will be there in then next release, when ever that may happen.

I see that this feature could be useful for many people but I'm somewhat worried that people will not find it, as it is not advertised in any way.

**Comment by martingabelmann** [comment]
Oh, uhm, sorry for the (delayed) dup. Thanks a lot for your work!
  
Imho this feature does not really require advertisement - I felt the need for it and just tried whether it would work. And assuming my intuition regarding GUIs is not that different from the average user...

**Comment by paulijar** [comment]
Music v1.5.2 was just released with the ability to drag the playing song from the player bar to any playlist.

**Comment by martingabelmann** [comment]
Works like a charm! Thank you so much :)
