### ISSUE TITLE
when converting owncloud db, crash on music date conversion

### ISSUE THREAD

**Issue by mybuntu-git2** [owncloud/music#963]
I am converting sqlite to Mariadb in owncloud, and get this error while running `db:convert-type --all-apps mysql`

```
An exception occurred while executing 'INSERT INTO `oc_music_tracks` (`id`,  
   `user_id`, `title`, `number`, `disk`, `year`, `artist_id`, `album_id`, `le  
  ngth`, `file_id`, `bitrate`, `mimetype`, `mbid`, `starred`, `genre_id`, `pl  
  ay_count`, `last_played`, `created`, `updated`) VALUES(?, ?, ?, ?, ?, ?, ?,  
   ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["10", "cloudadmin", "Sev  
  enth Star", "5", "1", "1986", "9", "10", "320", "5025", "1817631", "audio\/  
  flac", null, null, "1", "1", "54151-01-05 01:53:20.000", "2022-03-04 19:45:  
  52.923", "2022-03-04 19:45:52.923"]:                                         
                                                                               
  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '5  
  4151-01-05 01:53:20.000' for column `owncloud`.`oc_music_tracks`.`last_play  
  ed` at row 1     
```

I am following standard guidelines for [db conversion](https://doc.owncloud.com/server/next/admin_manual/configuration/database/db_conversion.html#preparation
)
...suggestions?

**Comment by mybuntu-git2** [comment]
workaround is to remove music and reinstall. overall since buildup of music library is always self-consistent, this is not a big deal.

**Comment by paulijar** [comment]
I don't know what's going on there, but the year 54151 on the datetime "54151-01-05 01:53:20.000" doesn't sound quite right. Since this is just the "last played" timestamp, it's not very critical and you could probably just substitute it with `null`.
