### ISSUE TITLE
PodcastEpisodeBusinessLayer fails to parse MM:SS duration format

### ISSUE THREAD

**Issue by ksmolder** [owncloud/music#967]
When importing a particular podcast (), I noticed that Music didn't extract the duration of the episodes. Looking at the `PodcastEpisodeBusinessLayer` code, Music currently supports two duration formats:

- Total number of seconds
- HH:MM:SS

The episodes that failed to have their duration extracted, had the hours part omitted from the HH:MM:SS representation, so only the minutes and seconds were included.

The following regular expression would be more flexible and support also the MM:SS format:
 `^(?:(?:(?<hours>\d+):)?(?<minutes>[0-5]?\d):)?(?<seconds>[0-5]\d)(?:\.\d*)?$`

The downside is that it looks frightening ;-), so that's why I included the named references.

Recognized duration formats:

- 12:45:56 → 12 hours + 45 minutes + 56 seconds
- 12:45:78 → Not recognized as the number of seconds is higher than 59
- 12:45 → 12 minutes + 45 seconds
- 12 → 12 seconds
- 12.9 → 12 seconds
- 12:45.67 → 12 minutes + 45 seconds

So basically, subseconds are still discarded.

The inclusion of named groupings might make the actual calculation more readable (to counteract the more difficult regex). The `parseDuration` method would read:

    private static function parseDuration(string $data) :?int {
        $matches = null;
    
        if (\ctype_digit($data)) {
            return (int)$data; // plain seconds
        } elseif (\preg_match('/^(?:(?:(?<hours>\d+):)?(?<minutes>[0-5]?\d):)?(?<seconds>[0-5]\d)(?:\.\d*)?$/', $data, $matches) === 1) {
            return (int)$matches['hours'] * 3600 + (int)$matches['minutes'] * 60 + (int)$matches['seconds']; // HH:MM:SS
        } else {
            return null; // no value or unsupported format
        }
    }

An alternative approach could be to add an additional `elseif` block to the check, especially checking for the MM:SS format. The downside of this approach is that if a podcasts includes the duration as SS.mmm, none of the checks would succeed.

    private static function parseDuration(string $data) :?int {
        $matches = null;
    
        if (\ctype_digit($data)) {
            return (int)$data; // plain seconds
        } elseif (\preg_match('/^(\d\d):(\d\d).*/', $data, $matches) === 1) {
            return (int)$matches[2] * 60 + (int)$matches[3]; // MM:SS
        } elseif (\preg_match('/^(\d\d):(\d\d):(\d\d).*/', $data, $matches) === 1) {
            return (int)$matches[1] * 3600 + (int)$matches[2] * 60 + (int)$matches[3]; // HH:MM:SS
        } else {
            return null; // no value or unsupported format
        }
    }

I can prepare a PR if that would be helpful. It would be nice to know which approach you prefer the most.

Thanks!

**Comment by paulijar** [comment]
Thanks for your effort. A pull request would be welcome. I could accept either one of your proposed solutions. The regex sure looks frightening but after careful deciphering, I could figure out how it works. So it's not that bad in the end.

But actually, I have one question about the regex solution as I haven't used the named groupings much: Is it safe to refer to `$matches['hours']` also in those cases when the hours group is not present in the data? Or would this generate e.g. a warning to the logs?

**Comment by ksmolder** [comment]
The regex won't result in any warnings. PHP always creates the placeholders for the matched values in `$matches`, regardless of whether it found a match or not. If it doesn't detect the pattern , PHP will fill the corresponding placeholder with an empty string (by default) or `null` (if you pass the `PREG_UNMATCHED_AS_NULL` flag to `preg_match`).

When you cast an empty string to an integer, it results in the value `0`. So the line converting the hours - minutes - seconds groups to the total number of seconds, should also be safe, even if the episode didn't include the hours and/ or minutes section.

I'll prepare the PR later this week.
