### ISSUE TITLE
Podcast Playback Speed

### ISSUE THREAD

**Issue by mikeholler** [owncloud/music#972]
I listen to a lot of podcasts, and I would like to use this app to do so. The biggest feature that is stopping me from switching over is that playback speed is currently locked to 1x. I would love to see a range from 0.5 to 3x added to the player. This would also be a nice step along the road to an audiobook feature.

**Comment by paulijar** [comment]
The just released Music v1.6.0 now includes this feature. It can be found by long pressing the play/pause button on the controls pane.
