### ISSUE TITLE
Update version to support Nextcloud v24

### ISSUE THREAD

**Issue by cravas** [owncloud/music#973]
Hello all

I'm running NC on docker and it's showing an update to v24.
Unfortunately, the only app that has no v24 support is Music.

Is this still mantained?

I really like this app and prefer it over Audio Player since I can have Radio Stations on it.

Thank you for the support and app.

**Comment by paulijar** [comment]
Yes, this app is maintained, although I haven't had much time for this project lately. The app has been tested to work also on NC24 (see https://github.com/owncloud/music/pull/957) but I would need to release a new version which would claim this support. I'll try to do it during this weekend.

**Comment by cravas** [comment]
@paulijar
Thank you for the fast reply.
I'll close this since you're already aware of it and I believe it's a simple update.

Cheers
