### ISSUE TITLE
[Feature request] Libre.FM scrobbling

### ISSUE THREAD

**Issue by janilowski** [owncloud/music#978]
Currently, owncloud/music only supports scrobbling to the proprietary Last.FM service. I think it would be great to support a freedom-respecting alternative - LibreFM

**Comment by paulijar** [comment]
Actually, we don't support scrobbling to Last.fm, either. But there is an open feature request https://github.com/owncloud/music/issues/339 about it. The only thing, the Music app can currently do with Last.fm, is to obtain the artist bio and album descriptions.

**Comment by janilowski** [comment]
Duplicate, sorry, didn't show up in search results for some reason :P
[#339](https://github.com/owncloud/music/issues/339)
