### ISSUE TITLE
Build requirements

### ISSUE THREAD

**Issue by medismail** [owncloud/music#982]
Hi,

I try to build the music app to my nextcloud server, I have install npm, download the repo, change directory to music/build and run make build after successful running, i just have two small js files in dist directory, did I miss something? 
Server: Debian 11
npm version: 8

**Comment by paulijar** [comment]
No, I don't see anything obviously wrong in your attempt. But you should get two rather large .js files an even larger .map files, along with two .css files tot the `dist` folder.

What kind of output do you get to the console when you run `make build`?

**Comment by medismail** [comment]
This is the output message:
npm install --deps

up to date, audited 537 packages in 4s

81 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 moderate, 4 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm run build

> music@1.5.2 build
> webpack

(node:185092) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:185092) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
asset webpack.app.6f263f8bffab4b3fdc4f.js 997 bytes [emitted] [immutable] [minimized] (name: app) 1 related asset
asset webpack.files_music_player.f9da5911f5254da252e4.js 520 bytes [emitted] [immutable] [minimized] (name: files_music_player) 1 related asset
asset manifest.json 134 bytes [emitted]
../js/index.app.js 1.59 KiB [built] [code generated]
../js/index.embedded.js 1.05 KiB [built] [code generated]
webpack 5.72.0 compiled successfully in 1645 ms

**Comment by paulijar** [comment]
That's weird. For me, the output begins just the same, but there's much more of it.
```
npm install --deps

up to date, audited 536 packages in 5s

81 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm run build

> music@1.5.2 build
> webpack

(node:19804) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(node:19804) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
assets by path img/*.svg 38.3 KiB
  assets by chunk 4.32 KiB (auxiliary name: files_music_player)
    asset img/0870be038f536fc670da5db9131d0040.svg 918 bytes [emitted] (auxiliary name: app, files_music_player)
    asset img/3002b85934190d593f9f8e3d9c29c540.svg 881 bytes [emitted] (auxiliary name: app, files_music_player)
    asset img/5347a8f54eb01e2ae5be536a2b86ef4d.svg 685 bytes [emitted] (auxiliary name: app, files_music_player)
    + 6 assets
  + 30 assets
assets by info 1.75 MiB [immutable]
  assets by status 1.71 MiB [big]
    asset webpack.app.acd2e3ec99207eb31c65.js 1.18 MiB [emitted] [immutable] [minimized] [big] (name: app) 2 related assets
    asset webpack.files_music_player.2048df180cef917d417f.js 537 KiB [emitted] [immutable] [minimized] [big] (name: files_music_player) 2 related assets
  assets by path *.css 44.9 KiB
    asset webpack.app.cf3d7053fff72210a07a.css 37.6 KiB [emitted] [immutable] (name: app) 1 related asset
    asset webpack.files_music_player.361a5d8ccce9f2d0904e.css 7.32 KiB [emitted] [immutable] (name: files_music_player) 1 related asset
asset manifest.json 2.85 KiB [emitted]
Entrypoint app [big] 1.22 MiB (5.36 MiB) = webpack.app.cf3d7053fff72210a07a.css 37.6 KiB webpack.app.acd2e3ec99207eb31c65.js 1.18 MiB 41 auxiliary assets
Entrypoint files_music_player [big] 544 KiB (2.59 MiB) = webpack.files_music_player.361a5d8ccce9f2d0904e.css 7.32 KiB webpack.files_music_player.2048df180cef917d417f.js 537 KiB 11 auxiliary assets
runtime modules 4.32 KiB 14 modules
modules by path ./node_modules/ 2.9 MiB 231 modules
modules by path ../ 1.06 MiB (javascript) 44.8 KiB (css/mini-extract)
  optional modules 665 KiB [optional] 95 modules
  css modules 44.8 KiB 16 modules
  modules by path ../js/vendor/ 410 KiB
    modules by path ../js/vendor/aurora/*.js 389 KiB 3 modules
    + 3 modules
  modules by path ../js/*.js 2.64 KiB
    ../js/index.app.js 1.59 KiB [built] [code generated]
    ../js/index.embedded.js 1.05 KiB [built] [code generated]
  + 14 modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  webpack.app.acd2e3ec99207eb31c65.js (1.18 MiB)
  webpack.files_music_player.2048df180cef917d417f.js (537 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.22 MiB)
      webpack.app.cf3d7053fff72210a07a.css
      webpack.app.acd2e3ec99207eb31c65.js
  files_music_player (544 KiB)
      webpack.files_music_player.361a5d8ccce9f2d0904e.css
      webpack.files_music_player.2048df180cef917d417f.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.72.0 compiled with 3 warnings in 30969 ms
```

**Comment by medismail** [comment]
This is running from build folder?

**Comment by paulijar** [comment]
Yes. The difference is that I'm running this on a Windows workstation. But there should be no good reason why this wouldn't work on Linux.

**Comment by medismail** [comment]
I succeed to build v1.3.3 the problem start from version 1.4.0

**Comment by paulijar** [comment]
In the Music version 1.4.0, we updated the webpack version used from 4,x to 5.x. It's likely that your problem is somehow related to this.

**Comment by medismail** [comment]
Yes exactly i change webpack to 4.x in the master branch and  it is build the files.

**Comment by paulijar** [comment]
So did you ever find a way to make the webpack 5.x build work on your system?

**Comment by medismail** [comment]
No, I didn't try to find solution, if no one have the same bug, I think is related somehow to my system, my goal is to just develop a feature of radio stream title. I will install new system later and check if it will works. You can close the bug as is not confirmed.
