### ISSUE TITLE
import playlist character set issues

### ISSUE THREAD

**Issue by mepreston** [owncloud/music#983]
Music v1.5.2
When i'm importing playlists (m3u format) and there are characters in international character sets it fails to import the line.
when scanning media there doesn't seem to be any issues as it loads all my files.  this only occurs when importing a playlist.
the error log start out with:
{"reqId":"YqCuuMvT0Iu3P1Fq2NCi1wAAygc","level":2,"time":"June 08, 2022 10:14:27","remoteAddr":"192.168.xxx.xxx","user":"xxxxxxxxxxxxx","app":"music","method":"POST","url":"/nextcloud/index.phpc/api/playlists/61/import","message":"Some files were not found from the user's music library: 

Examples of what is in the play list and the error in the nextcloud log:

music/music library/Pop/Carole King/Her Greatest Hits/11 - Corazón.flac
\"music\\/music library\\/Pop\\/Carole King\\/Her Greatest Hits\\/11 - Coraz\\u00c3\\u00b3n.flac\"

music/music library/Pop/Dionne Warwick/Definitive Collection/12 - Déjà Vu.flac
\"music\\/music library\\/Pop\\/Dionne Warwick\\/Definitive Collection\\/12 - D\\u00c3\\u00a9j\\u00c3\\u00a0 Vu.flac\"

music/music library/Pop/Gloria Estefan/Alma Caribeña/01 - Por Un Beso.flac
\"music\\/music library\\/Pop\\/Gloria Estefan\\/Alma Caribe\\u00c3\\u00b1a\\/01 - Por Un Beso.flac\

**Comment by mepreston** [comment]
sorry about that, i'm very late to create your own playlist of any kind .   changing the file extension fixed all but one set of files:

"music\\/music library\\/Rock\\/Queen + Adam Lambert\\/Live Around The World\\/01 - Tear It Up.flac\"

It seems the plugin doesn't like the plus sign in this filename.  I'm guessing it needs to be escaped.

**Comment by paulijar** [comment]
The `+` character shouldn't be a problem. And I just renamed one of my files to `01 - Tear It Up.flac` and moved it to folder `.../Queen + Adam Lambert/Live Around The World` and I couldn't see any problems with it: I created a playlist on Music with this track, then exported the playlist to a file, and was able to import the file back to Music. Looking at the file contents, there is nothing special there, like any kind of escaping.

**Comment by mepreston** [comment]
Sorry about that i completely forgot that had moved that to another folder after i had created that play list.
so yes it all works great. thanks for helping out on this non-issue.   might there be a setting in the future of the plugin to set what character set should be used?
