### ISSUE TITLE
Possibility of ignoring "The" in artistname

### ISSUE THREAD

**Issue by trvrcr** [owncloud/music#984]
Hello,

Foremost, I love the app!!!

Would it be possible to add an option of ignoring "the" in the artist name if it's at the front?

So basically have "The XX" under the X mark or "The smashing pumpkins" under S mark

**Comment by FadeFx** [comment]
Done in Music 1.6.0

**Comment by paulijar** [comment]
Yes, Music v1.6.0 now contains this feature. By default, the articles "The", "El", "La", "Los", "Las", "Le", "Les" are ignored on alphabetization but you can configure this in the Music app settings.
