### ISSUE TITLE
How to make a default tab when opening an application...

### ISSUE THREAD

**Issue by Vishin44** [owncloud/music#986]
***Greetings!*** Dear developer, could you tell me how to configure the application so that when you click on the Music application, it opens not ***"Albums"***, but ***"Genres"***.
*P.S. I apologize for the spelling, I used a translator)))*

**Comment by paulijar** [comment]
Sorry, there's no such feature. But if you are all the time navigating to the *Genres* view, then you could consider bookmarking that page on your web browser.

**Comment by paulijar** [comment]
Closing in favor of https://github.com/owncloud/music/issues/1034.
