### ISSUE TITLE
Nextcloud Music - Subsonic access with TOTP enabled

### ISSUE THREAD

**Issue by WarpinWolf** [owncloud/music#993]
Hi,

not sure if this is the right place. 

Nextcloud 24.0.2. Apache. Mobile with Ultrasonic app.

Everything did work nicely until I did enable TOTP in Nextcloud.

Ultrasonic lost access.

Tried with app password in Nextcloud-> settings -> Security as well as with new app password in Music settings.

Doesn't work (access denied).

Am I dumb or is it clear that it won't work?

Thanks
Wolf

**Comment by paulijar** [comment]
There's no good reason, why the two-factor authentication would have any effect on the Subsonic API of the Music app. This API bypasses any authentication requirements of Nextcloud and implements its own scheme instead.

I just tested enabling the [Two-Factor TOTP Provider](https://apps.nextcloud.com/apps/twofactor_totp) on NC23, and for me, Ultrasonic worked just fine afterwards.

Can you find anything from nextcloud.log after the failed attempts to connect Ultrasonic to your cloud?
