### ISSUE TITLE
Problems after upgrading to 1.6.0

### ISSUE THREAD

**Issue by JoshuaPettus** [owncloud/music#998]
Hi,
I am using NC 24.0.4
PostgreSQL 14.5
Ubuntu 22.04
nginx 1.23.1
PHP 8.1.8

I suspect It may be a postgres issue.  Since upgrading to 1.6.0 now the web interface for Album, Folders,  Genres, All Tracks, and Internet Radio just spins rather than renders.  Interestingly, Podcast section works just fine.

Also the settings menu will not come up.  I tried dumping and re-scaning my database on the command line but that didn't work. 

Subsonic works just fine though.  This is only affecting the nextcloud web interface

Here are some errors I'm getting in the log if that helps

`[index] Error: Exception: Call to undefined method OCA\Music\Utility\LibrarySettings::getIgnoredArticles() in file '/var/www/nextcloud/apps/music/lib/Controller/SettingController.php' line 110 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1023
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /apps/music/api/settings
from IP by joshuapettus at 2022-08-14T00:44:32+00:00`

`[index] Error: TypeError: OCA\Music\Controller\RadioApiController::__construct(): Argument #3 ($config) must be of type OCP\IConfig, OCA\Music\BusinessLayer\RadioStationBusinessLayer given, called in /var/www/nextcloud/apps/music/lib/App/Music.php on line 188 at <<closure>>

 0. /var/www/nextcloud/apps/music/lib/App/Music.php line 188
    OCA\Music\Controller\RadioApiController->__construct()
 1. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 162
    OCA\Music\App\Music->OCA\Music\App\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 122
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
 3. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 129
    Pimple\Container->offsetGet()
 4. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 459
    OC\AppFramework\Utility\SimpleContainer->query()
 5. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 437
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
 6. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 57
    OC\AppFramework\DependencyInjection\DIContainer->query()
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 145
    OC\AppFramework\Utility\SimpleContainer->get()
 8. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
 9. /var/www/nextcloud/lib/base.php line 1023
    OC\Route\Router->match()
10. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

GET /apps/music/api/radio
from IP by jadmin at 2022-08-14T00:43:37+00:00`

**Comment by paulijar** [comment]
Those errors look like your installation had got only partially updated. For example, LibrarySettings::getIgnoredArticles() is a new function introduced in v1.6.0, so apparently, the class SettingController calling it has got updated but the class LibrarySettings hasn't.

You could try to completely remove the Music app from the disk and then reinstall it from scratch.

**Comment by JoshuaPettus** [comment]
Weird,   I tried that before hoping that is what it might have been. (Hate it when that happens)

This time I made sure the music folder wasn't listed under apps.  Ran uninstall again from occ to be sure.  Then I installed it again (this time from occ)  and same thing happens...

**Comment by paulijar** [comment]
That is indeed the correct hash for the updated version of LibrarySettings. And you still get the same error message in the log? Now I wonder, is it possible that some PHP caching system is serving you the old version of the file?

**Comment by JoshuaPettus** [comment]
That was it!   First I flushed redis, then I flushed opcache with service php-fpm restart..

Sorry I'll have to remember that.  Thank you!
