### ISSUE TITLE
Android - can not use drag'n drop for playlists

### ISSUE THREAD

**Issue by FadeFx** [owncloud/music#999]
Hi, 
Just figured out that filling playlists on Android is not possible, at least on phone layout, as the sidebar containing the playlist auto hides when you touch outside it. It should be possible to hover the burger button to unhide the sidebar.

**Comment by paulijar** [comment]
Yes, this is a valid point. Another thing is that the dragging is often not possible at all on touch devices. Maybe we would need to have also some alternative way to add songs to playlists. But on Chrome for Android, the dragging in general seems to work, so your proposal would make sense.

**Comment by paulijar** [comment]
Music v1.8.0 is now released and there, the navigation pane is opened when a track is dragged on top of the "burger" button.

**Comment by FadeFx** [comment]
Tester and working as intended ;-)
